# -*- coding: utf-8 -*-
import json, sys
T={}
def a(en,es,fr,de,ru,ar,nl,pl,no,sv): T[en]={'es':es,'fr':fr,'de':de,'ru':ru,'ar':ar,'nl':nl,'pl':pl,'no':no,'sv':sv}

a("Developer visual of the planted balconies above the lawn",
 "Imagen del promotor de las terrazas ajardinadas sobre el césped",
 "Visuel du promoteur des balcons plantés au-dessus de la pelouse",
 "Bauträger-Visualisierung der bepflanzten Balkone über dem Rasen",
 "Визуализация застройщика: озеленённые балконы над газоном",
 "تصور من المطور للشرفات المزروعة فوق المسطح الأخضر",
 "Beeld van de ontwikkelaar van de beplante balkons boven het gazon",
 "Wizualizacja dewelopera przedstawiająca obsadzone zielenią balkony nad trawnikiem",
 "Visualisering fra utbygger av de beplantede balkongene over plenen",
 "Visualisering från utvecklaren av de planterade balkongerna ovanför gräsmattan")
a("The planted facade","La fachada ajardinada","La façade plantée","Die bepflanzte Fassade",
 "Озеленённый фасад","الواجهة المزروعة","De beplante gevel","Obsadzona zielenią elewacja","Den beplantede fasaden","Den planterade fasaden")
a("Developer visual of a block seen from the access road, with the planted slope beside it",
 "Imagen del promotor de un bloque visto desde el vial de acceso, con la ladera ajardinada al lado",
 "Visuel du promoteur d'un immeuble vu depuis la voie d'accès, le talus planté à côté",
 "Bauträger-Visualisierung eines Gebäudes von der Zufahrt aus, mit dem bepflanzten Hang daneben",
 "Визуализация застройщика: корпус со стороны подъездной дороги и озеленённый склон рядом",
 "تصور من المطور لأحد المباني من طريق الدخول، مع المنحدر المزروع بجانبه",
 "Beeld van de ontwikkelaar van een gebouw gezien vanaf de toegangsweg, met de beplante helling ernaast",
 "Wizualizacja dewelopera przedstawiająca budynek od strony drogi dojazdowej, z obsadzoną zielenią skarpą obok",
 "Visualisering fra utbygger av et bygg sett fra adkomstveien, med den beplantede skråningen ved siden",
 "Visualisering från utvecklaren av ett hus sett från tillfartsvägen, med den planterade slänten bredvid")
a("Developer visual looking out over the wooded hills to the coast and the sea",
 "Imagen del promotor con vistas sobre las colinas arboladas hacia la costa y el mar",
 "Visuel du promoteur avec vue sur les collines boisées vers la côte et la mer",
 "Bauträger-Visualisierung mit Blick über die bewaldeten Hügel zur Küste und zum Meer",
 "Визуализация застройщика: вид через лесистые холмы на побережье и море",
 "تصور من المطور بإطلالة فوق التلال المشجّرة نحو الساحل والبحر",
 "Beeld van de ontwikkelaar met uitzicht over de beboste heuvels naar de kust en de zee",
 "Wizualizacja dewelopera z widokiem przez zalesione wzgórza na wybrzeże i morze",
 "Visualisering fra utbygger med utsikt over de skogkledde åsene mot kysten og havet",
 "Visualisering från utvecklaren med utsikt över de skogbevuxna kullarna mot kusten och havet")
a("The setting","El entorno","Le cadre","Die Lage","Окружение","المحيط","De omgeving","Otoczenie","Omgivelsene","Omgivningarna")
a("Developer visual of the living and dining room open to the terrace and the sea",
 "Imagen del promotor del salón comedor abierto a la terraza y al mar",
 "Visuel du promoteur du séjour et de la salle à manger ouverts sur la terrasse et la mer",
 "Bauträger-Visualisierung des Wohn- und Esszimmers, offen zur Terrasse und zum Meer",
 "Визуализация застройщика: гостиная-столовая, открытая на террасу и к морю",
 "تصور من المطور لغرفة المعيشة والطعام المفتوحة على التراس والبحر",
 "Beeld van de ontwikkelaar van de woon- en eetkamer, open naar het terras en de zee",
 "Wizualizacja dewelopera przedstawiająca salon z jadalnią otwarty na taras i morze",
 "Visualisering fra utbygger av stuen og spisestuen, åpen mot terrassen og havet",
 "Visualisering från utvecklaren av vardagsrummet och matplatsen, öppna mot terrassen och havet")
a("Developer visual of the living room with the kitchen and dining table behind it",
 "Imagen del promotor del salón con la cocina y la mesa de comedor al fondo",
 "Visuel du promoteur du séjour avec la cuisine et la table à manger derrière",
 "Bauträger-Visualisierung des Wohnzimmers mit Küche und Esstisch dahinter",
 "Визуализация застройщика: гостиная, за ней кухня и обеденный стол",
 "تصور من المطور لغرفة المعيشة مع المطبخ وطاولة الطعام خلفها",
 "Beeld van de ontwikkelaar van de woonkamer met de keuken en de eettafel erachter",
 "Wizualizacja dewelopera przedstawiająca salon z kuchnią i stołem jadalnym w głębi",
 "Visualisering fra utbygger av stuen med kjøkkenet og spisebordet bak",
 "Visualisering från utvecklaren av vardagsrummet med köket och matbordet bakom")
a("Developer visual of the living room with the open kitchen along the back wall",
 "Imagen del promotor del salón con la cocina abierta a lo largo de la pared del fondo",
 "Visuel du promoteur du séjour avec la cuisine ouverte le long du mur du fond",
 "Bauträger-Visualisierung des Wohnzimmers mit der offenen Küche an der Rückwand",
 "Визуализация застройщика: гостиная с открытой кухней вдоль дальней стены",
 "تصور من المطور لغرفة المعيشة مع المطبخ المفتوح على طول الجدار الخلفي",
 "Beeld van de ontwikkelaar van de woonkamer met de open keuken langs de achterwand",
 "Wizualizacja dewelopera przedstawiająca salon z otwartą kuchnią wzdłuż tylnej ściany",
 "Visualisering fra utbygger av stuen med det åpne kjøkkenet langs bakveggen",
 "Visualisering från utvecklaren av vardagsrummet med det öppna köket längs bortre väggen")
a("Developer visual of the kitchen and dining table beside the terrace door",
 "Imagen del promotor de la cocina y la mesa de comedor junto a la puerta de la terraza",
 "Visuel du promoteur de la cuisine et de la table à manger près de la porte de la terrasse",
 "Bauträger-Visualisierung der Küche und des Esstischs neben der Terrassentür",
 "Визуализация застройщика: кухня и обеденный стол у двери на террасу",
 "تصور من المطور للمطبخ وطاولة الطعام بجوار باب التراس",
 "Beeld van de ontwikkelaar van de keuken en de eettafel naast de terrasdeur",
 "Wizualizacja dewelopera przedstawiająca kuchnię i stół jadalny przy drzwiach na taras",
 "Visualisering fra utbygger av kjøkkenet og spisebordet ved terrassedøren",
 "Visualisering från utvecklaren av köket och matbordet vid terrassdörren")
a("Developer visual of a bedroom with fitted wardrobes and a window onto the greenery",
 "Imagen del promotor de un dormitorio con armarios empotrados y una ventana al verde",
 "Visuel du promoteur d'une chambre avec placards intégrés et une fenêtre sur la verdure",
 "Bauträger-Visualisierung eines Schlafzimmers mit Einbauschränken und Fenster ins Grüne",
 "Визуализация застройщика: спальня со встроенными шкафами и окном в зелень",
 "تصور من المطور لغرفة نوم بخزائن مدمجة ونافذة تطل على الخضرة",
 "Beeld van de ontwikkelaar van een slaapkamer met inbouwkasten en een raam op het groen",
 "Wizualizacja dewelopera przedstawiająca sypialnię z zabudowanymi szafami i oknem na zieleń",
 "Visualisering fra utbygger av et soverom med innebygde skap og vindu mot det grønne",
 "Visualisering från utvecklaren av ett sovrum med inbyggda garderober och fönster mot grönskan")
a("Developer visual of a bathroom with a walk-in shower and an oak vanity",
 "Imagen del promotor de un baño con ducha de obra y mueble de roble",
 "Visuel du promoteur d'une salle de bains avec douche à l'italienne et meuble en chêne",
 "Bauträger-Visualisierung eines Badezimmers mit bodengleicher Dusche und Eichenwaschtisch",
 "Визуализация застройщика: ванная комната с душевой без поддона и дубовой тумбой",
 "تصور من المطور لحمام بدش مفتوح ووحدة خزانة من خشب البلوط",
 "Beeld van de ontwikkelaar van een badkamer met inloopdouche en een eiken wastafelmeubel",
 "Wizualizacja dewelopera przedstawiająca łazienkę z prysznicem walk-in i dębową szafką",
 "Visualisering fra utbygger av et bad med dusjnisje uten kant og en eikeservant",
 "Visualisering från utvecklaren av ett badrum med golvbrunnsdusch och ekkommod")
a("A bathroom","Un baño","Une salle de bains","Ein Badezimmer","Ванная комната","حمّام","Een badkamer","Łazienka","Et bad","Ett badrum")
a("Developer visual of a terrace corner with a sofa, planters and the sea beyond",
 "Imagen del promotor de un rincón de terraza con sofá, jardineras y el mar al fondo",
 "Visuel du promoteur d'un coin de terrasse avec canapé, jardinières et la mer au fond",
 "Bauträger-Visualisierung einer Terrassenecke mit Sofa, Pflanzkübeln und dem Meer dahinter",
 "Визуализация застройщика: уголок террасы с диваном, кашпо и морем вдали",
 "تصور من المطور لركن من التراس بأريكة وأحواض نباتات والبحر في الخلفية",
 "Beeld van de ontwikkelaar van een terrashoek met bank, plantenbakken en de zee erachter",
 "Wizualizacja dewelopera przedstawiająca narożnik tarasu z sofą, donicami i morzem w tle",
 "Visualisering fra utbygger av et terrassehjørne med sofa, plantekasser og havet bak",
 "Visualisering från utvecklaren av ett terrasshörn med soffa, planteringskärl och havet bakom")
a("Developer visual of a ground-floor terrace under bougainvillea, looking to the sea",
 "Imagen del promotor de una terraza en planta baja bajo la buganvilla, mirando al mar",
 "Visuel du promoteur d'une terrasse en rez-de-chaussée sous le bougainvillier, face à la mer",
 "Bauträger-Visualisierung einer Erdgeschossterrasse unter Bougainvillea mit Blick aufs Meer",
 "Визуализация застройщика: терраса первого этажа под бугенвиллеей с видом на море",
 "تصور من المطور لتراس في الطابق الأرضي تحت الجهنمية بإطلالة على البحر",
 "Beeld van de ontwikkelaar van een terras op de begane grond onder bougainville, met zicht op zee",
 "Wizualizacja dewelopera przedstawiająca taras na parterze pod bugenwillą, z widokiem na morze",
 "Visualisering fra utbygger av en terrasse i første etasje under bougainvillea, med utsikt mot havet",
 "Visualisering från utvecklaren av en terrass på bottenvåningen under bougainvillea, med utsikt mot havet")
json.dump(T, open(sys.argv[1],'w'), ensure_ascii=False, indent=1); print(len(T))
