# -*- coding: utf-8 -*-
import json, sys
T={}
def a(en,es,fr,de,ru,ar,nl,pl,no,sv): T[en]={'es':es,'fr':fr,'de':de,'ru':ru,'ar':ar,'nl':nl,'pl':pl,'no':no,'sv':sv}

a("Ten homes available on a <em>wooded hillside</em>","Diez viviendas disponibles en una <em>ladera arbolada</em>",
 "Dix logements disponibles sur un <em>coteau boisé</em>","Zehn verfügbare Wohnungen an einem <em>bewaldeten Hang</em>",
 "Десять квартир на <em>лесистом склоне</em>","عشرة منازل متاحة على <em>منحدر مشجّر</em>",
 "Tien beschikbare woningen op een <em>beboste helling</em>","Dziesięć mieszkań na <em>zalesionym zboczu</em>",
 "Ti tilgjengelige boliger i en <em>skogkledd skråning</em>","Tio tillgängliga bostäder på en <em>skogbevuxen sluttning</em>")
a("Three blocks stepped into the slope in Mijas, between La Cala de Mijas and Fuengirola, with the A-7 and AP-7 a few minutes away.",
 "Tres bloques escalonados en la ladera en Mijas, entre La Cala de Mijas y Fuengirola, con la A-7 y la AP-7 a pocos minutos.",
 "Trois immeubles étagés sur la pente à Mijas, entre La Cala de Mijas et Fuengirola, à quelques minutes de l'A-7 et de l'AP-7.",
 "Drei gestaffelt in den Hang gesetzte Gebäude in Mijas, zwischen La Cala de Mijas und Fuengirola, wenige Minuten von der A-7 und der AP-7.",
 "Три корпуса уступами на склоне в Михасе, между Ла-Кала-де-Михас и Фуэнхиролой, в нескольких минутах от A-7 и AP-7.",
 "ثلاثة مبانٍ متدرجة على المنحدر في ميخاس، بين لا كالا دي ميخاس وفوينخيرولا، على بعد دقائق من A-7 وAP-7.",
 "Drie getrapt in de helling geplaatste gebouwen in Mijas, tussen La Cala de Mijas en Fuengirola, op enkele minuten van de A-7 en de AP-7.",
 "Trzy budynki ustawione tarasowo na zboczu w Mijas, między La Cala de Mijas a Fuengirolą, kilka minut od A-7 i AP-7.",
 "Tre bygg satt trinnvis inn i skråningen i Mijas, mellom La Cala de Mijas og Fuengirola, noen minutter fra A-7 og AP-7.",
 "Tre hus insatta i sluttningen i Mijas, mellan La Cala de Mijas och Fuengirola, några minuter från A-7 och AP-7.")
a("Two and three bedrooms, from 92.81 to 136.53 sqm built among the homes available now, each with a garage space and a storeroom.",
 "Dos y tres dormitorios, de 92,81 a 136,53 m² construidos entre las viviendas disponibles ahora, cada una con plaza de garaje y trastero.",
 "Deux et trois chambres, de 92,81 à 136,53 m² construits parmi les logements disponibles, chacun avec une place de garage et un débarras.",
 "Zwei und drei Schlafzimmer, von 92,81 bis 136,53 m² Wohnfläche bei den derzeit verfügbaren Wohnungen, jede mit Garagenstellplatz und Abstellraum.",
 "Две и три спальни, от 92,81 до 136,53 м² построенной площади среди доступных сейчас квартир, у каждой место в гараже и кладовая.",
 "غرفتان وثلاث غرف نوم، من 92.81 إلى 136.53 م² مبنية بين المنازل المتاحة حالياً، ولكل منها موقف في المرآب ومخزن.",
 "Twee en drie slaapkamers, van 92,81 tot 136,53 m² bouwoppervlak bij de nu beschikbare woningen, elk met een garageplaats en een berging.",
 "Dwie i trzy sypialnie, od 92,81 do 136,53 m² powierzchni zabudowanej wśród dostępnych obecnie mieszkań, każde z miejscem w garażu i komórką lokatorską.",
 "To og tre soverom, fra 92,81 til 136,53 m² bygget blant boligene som er tilgjengelige nå, hver med garasjeplass og bod.",
 "Två och tre sovrum, från 92,81 till 136,53 m² byggyta bland de bostäder som är tillgängliga nu, var och en med garageplats och förråd.")
a("Two and three bedrooms, with terraces from 15 sqm.","Dos y tres dormitorios, con terrazas desde 15 m².",
 "Deux et trois chambres, avec des terrasses à partir de 15 m².","Zwei und drei Schlafzimmer, mit Terrassen ab 15 m².",
 "Две и три спальни, с террасами от 15 м².","غرفتان وثلاث غرف نوم، مع شرفات تبدأ من 15 م².",
 "Twee en drie slaapkamers, met terrassen vanaf 15 m².","Dwie i trzy sypialnie, z tarasami od 15 m².",
 "To og tre soverom, med terrasser fra 15 m².","Två och tre sovrum, med terrasser från 15 m².")
a("Ground-floor homes have a private garden; the penthouses have terraces of up to 78 sqm.",
 "Las viviendas en planta baja tienen jardín privado; los áticos, terrazas de hasta 78 m².",
 "Les logements en rez-de-chaussée ont un jardin privatif ; les penthouses, des terrasses jusqu'à 78 m².",
 "Die Erdgeschosswohnungen haben einen privaten Garten, die Penthäuser Terrassen von bis zu 78 m².",
 "У квартир на первом этаже собственный сад, у пентхаусов — террасы до 78 м².",
 "منازل الطابق الأرضي لها حديقة خاصة، والبنتهاوس شرفات تصل إلى 78 م².",
 "De woningen op de begane grond hebben een privétuin; de penthouses terrassen tot 78 m².",
 "Mieszkania na parterze mają prywatny ogród, a penthouse'y tarasy do 78 m².",
 "Boligene i første etasje har egen hage, og toppleilighetene terrasser på opptil 78 m².",
 "Bostäderna på bottenvåningen har egen trädgård, och takvåningarna terrasser på upp till 78 m².")
a("A garage space and a storeroom with every home.","Plaza de garaje y trastero con cada vivienda.",
 "Une place de garage et un débarras avec chaque logement.","Garagenstellplatz und Abstellraum zu jeder Wohnung.",
 "Место в гараже и кладовая к каждой квартире.","موقف في المرآب ومخزن مع كل منزل.",
 "Een garageplaats en een berging bij elke woning.","Miejsce w garażu i komórka lokatorska do każdego mieszkania.",
 "Garasjeplass og bod til hver bolig.","Garageplats och förråd till varje bostad.")
a("A fitted kitchen with oven, induction hob, extractor, microwave, fridge and dishwasher.",
 "Cocina amueblada con horno, placa de inducción, campana, microondas, frigorífico y lavavajillas.",
 "Cuisine équipée avec four, plaque à induction, hotte, micro-ondes, réfrigérateur et lave-vaisselle.",
 "Einbauküche mit Backofen, Induktionskochfeld, Dunstabzug, Mikrowelle, Kühlschrank und Geschirrspüler.",
 "Кухня с техникой: духовой шкаф, индукционная плита, вытяжка, микроволновая печь, холодильник и посудомоечная машина.",
 "مطبخ مجهّز بفرن وموقد حثّي وشفاط وميكروويف وثلاجة وغسالة صحون.",
 "Een ingerichte keuken met oven, inductiekookplaat, afzuigkap, magnetron, koelkast en vaatwasser.",
 "Kuchnia w zabudowie z piekarnikiem, płytą indukcyjną, okapem, mikrofalówką, lodówką i zmywarką.",
 "Innredet kjøkken med stekeovn, induksjonstopp, ventilator, mikrobølgeovn, kjøleskap og oppvaskmaskin.",
 "Inrett kök med ugn, induktionshäll, fläkt, mikrovågsugn, kyl och diskmaskin.")
a("Ducted heating and cooling in the living room and the bedrooms.",
 "Climatización frío/calor por conductos en el salón y los dormitorios.",
 "Climatisation chaud/froid gainable dans le séjour et les chambres.",
 "Kanalgeführte Heizung und Kühlung im Wohnzimmer und in den Schlafzimmern.",
 "Канальное отопление и охлаждение в гостиной и спальнях.",
 "تدفئة وتبريد بالمجاري في غرفة المعيشة وغرف النوم.",
 "Kanaalgebonden verwarming en koeling in de woonkamer en de slaapkamers.",
 "Kanałowe ogrzewanie i chłodzenie w salonie i sypialniach.",
 "Kanalbasert varme og kjøling i stuen og soverommene.",
 "Kanalbaserad värme och kyla i vardagsrummet och sovrummen.")
a("Individual aerothermal hot water for each home.","Agua caliente sanitaria por aerotermia individual en cada vivienda.",
 "Eau chaude sanitaire par aérothermie individuelle pour chaque logement.",
 "Individuelle Aerothermie für das Warmwasser jeder Wohnung.",
 "Индивидуальная аэротермальная система горячего водоснабжения в каждой квартире.",
 "ماء ساخن بنظام حراري هوائي مستقل لكل منزل.",
 "Individuele aerothermie voor warm water in elke woning.",
 "Indywidualna pompa ciepła powietrzna do ciepłej wody w każdym mieszkaniu.",
 "Individuell luft-til-vann-varmepumpe for varmtvann i hver bolig.",
 "Individuell luftvärmepump för varmvatten i varje bostad.")
a("Exterior joinery with a thermal break and double glazing.",
 "Carpintería exterior con rotura de puente térmico y doble acristalamiento.",
 "Menuiseries extérieures à rupture de pont thermique et double vitrage.",
 "Außenfenster mit thermischer Trennung und Doppelverglasung.",
 "Наружные оконные конструкции с терморазрывом и двойным остеклением.",
 "نجارة خارجية بفاصل حراري وزجاج مزدوج.",
 "Buitenschrijnwerk met thermische onderbreking en dubbele beglazing.",
 "Stolarka zewnętrzna z przekładką termiczną i podwójnymi szybami.",
 "Utvendige vinduer med kuldebrudd og todelt glass.",
 "Utvändiga fönster med köldbrygga och tvåglas.")
a("Photovoltaic panels supplying the communal services.","Placas fotovoltaicas para los servicios comunes.",
 "Panneaux photovoltaïques alimentant les services communs.","Photovoltaikmodule für die Gemeinschaftsanlagen.",
 "Фотоэлектрические панели для общедомовых нужд.","ألواح كهروضوئية لتغذية الخدمات المشتركة.",
 "Zonnepanelen voor de gemeenschappelijke voorzieningen.","Panele fotowoltaiczne zasilające części wspólne.",
 "Solcellepaneler til fellesanleggene.","Solceller för de gemensamma anläggningarna.")
a("10 homes <em>available</em>","10 viviendas <em>disponibles</em>","10 logements <em>disponibles</em>",
 "10 Wohnungen <em>verfügbar</em>","10 квартир <em>в продаже</em>","10 منازل <em>متاحة</em>",
 "10 woningen <em>beschikbaar</em>","10 mieszkań <em>dostępnych</em>","10 boliger <em>tilgjengelig</em>","10 bostäder <em>tillgängliga</em>")
a("Ten apartments are available, two of them on the ground floor. Nueva Living reconfirms price and availability before any viewing or reservation.",
 "Hay diez apartamentos disponibles, dos de ellos en planta baja. Nueva Living reconfirma precio y disponibilidad antes de cualquier visita o reserva.",
 "Dix appartements sont disponibles, dont deux en rez-de-chaussée. Nueva Living reconfirme le prix et la disponibilité avant toute visite ou réservation.",
 "Zehn Wohnungen sind verfügbar, zwei davon im Erdgeschoss. Nueva Living bestätigt Preis und Verfügbarkeit vor jeder Besichtigung oder Reservierung erneut.",
 "Доступны десять квартир, две из них на первом этаже. Nueva Living заново подтверждает цену и наличие перед любым просмотром или бронированием.",
 "تتوفر عشر شقق، اثنتان منها في الطابق الأرضي. تؤكد Nueva Living السعر والتوافر مجدداً قبل أي معاينة أو حجز.",
 "Er zijn tien appartementen beschikbaar, twee daarvan op de begane grond. Nueva Living bevestigt prijs en beschikbaarheid opnieuw vóór elke bezichtiging of reservering.",
 "Dostępnych jest dziesięć apartamentów, dwa z nich na parterze. Nueva Living ponownie potwierdza cenę i dostępność przed każdą wizytą lub rezerwacją.",
 "Ti leiligheter er tilgjengelige, to av dem i første etasje. Nueva Living bekrefter pris og tilgjengelighet på nytt før enhver visning eller reservasjon.",
 "Tio lägenheter är tillgängliga, två av dem på bottenvåningen. Nueva Living bekräftar pris och tillgänglighet på nytt före varje visning eller reservation.")
json.dump(T, open(sys.argv[1],'w'), ensure_ascii=False, indent=1); print(len(T))
