# -*- coding: utf-8 -*-
import json, sys
T={}
def a(en,es,fr,de,ru,ar,nl,pl,no,sv): T[en]={'es':es,'fr':fr,'de':de,'ru':ru,'ar':ar,'nl':nl,'pl':pl,'no':no,'sv':sv}

a("Developer visual of a terrace laid for dinner, with a sofa and the coast beyond",
 "Imagen del promotor de una terraza preparada para cenar, con un sofá y la costa al fondo",
 "Visuel du promoteur d'une terrasse dressée pour le dîner, avec un canapé et la côte au fond",
 "Bauträger-Visualisierung einer für das Abendessen gedeckten Terrasse, mit Sofa und der Küste dahinter",
 "Визуализация застройщика: терраса, накрытая к ужину, диван и побережье вдали",
 "تصور من المطور لتراس مُجهّز للعشاء مع أريكة والساحل في الخلفية",
 "Beeld van de ontwikkelaar van een terras gedekt voor het diner, met een bank en de kust erachter",
 "Wizualizacja dewelopera przedstawiająca taras nakryty do kolacji, z sofą i wybrzeżem w tle",
 "Visualisering fra utbygger av en terrasse dekket til middag, med sofa og kysten bak",
 "Visualisering från utvecklaren av en terrass dukad till middag, med soffa och kusten bakom")
a("Developer visual of the living room, its terrace door open to the sea view",
 "Imagen del promotor del salón, con la puerta de la terraza abierta a las vistas al mar",
 "Visuel du promoteur du séjour, sa porte de terrasse ouverte sur la vue mer",
 "Bauträger-Visualisierung des Wohnzimmers, die Terrassentür offen zum Meerblick",
 "Визуализация застройщика: гостиная с открытой дверью на террасу и видом на море",
 "تصور من المطور لغرفة المعيشة وبابها المفتوح على التراس والإطلالة البحرية",
 "Beeld van de ontwikkelaar van de woonkamer, met de terrasdeur open naar het zeezicht",
 "Wizualizacja dewelopera przedstawiająca salon z otwartymi drzwiami na taras i widokiem na morze",
 "Visualisering fra utbygger av stuen, med terrassedøren åpen mot havutsikten",
 "Visualisering från utvecklaren av vardagsrummet, med terrassdörren öppen mot havsutsikten")
a("Developer visual of the fitted kitchen in white with a timber worktop",
 "Imagen del promotor de la cocina amueblada en blanco con encimera de madera",
 "Visuel du promoteur de la cuisine équipée blanche avec plan de travail en bois",
 "Bauträger-Visualisierung der weißen Einbauküche mit Holzarbeitsplatte",
 "Визуализация застройщика: белая кухня с деревянной столешницей",
 "تصور من المطور للمطبخ المجهّز باللون الأبيض بسطح عمل خشبي",
 "Beeld van de ontwikkelaar van de witte inbouwkeuken met houten werkblad",
 "Wizualizacja dewelopera przedstawiająca białą kuchnię w zabudowie z drewnianym blatem",
 "Visualisering fra utbygger av det hvite innredede kjøkkenet med trebenkeplate",
 "Visualisering från utvecklaren av det vita inredda köket med träbänkskiva")
a("Developer visual of the main bedroom with a timber headboard and fitted wardrobes",
 "Imagen del promotor del dormitorio principal con cabecero de madera y armarios empotrados",
 "Visuel du promoteur de la chambre principale avec tête de lit en bois et placards intégrés",
 "Bauträger-Visualisierung des Hauptschlafzimmers mit Holzkopfteil und Einbauschränken",
 "Визуализация застройщика: главная спальня с деревянным изголовьем и встроенными шкафами",
 "تصور من المطور لغرفة النوم الرئيسية بلوح رأس خشبي وخزائن مدمجة",
 "Beeld van de ontwikkelaar van de hoofdslaapkamer met houten hoofdbord en inbouwkasten",
 "Wizualizacja dewelopera przedstawiająca główną sypialnię z drewnianym zagłówkiem i zabudowanymi szafami",
 "Visualisering fra utbygger av hovedsoverommet med tregavl og innebygde skap",
 "Visualisering från utvecklaren av huvudsovrummet med trägavel och inbyggda garderober")
a("Developer visual of a bedroom with open shelving and a patterned wall",
 "Imagen del promotor de un dormitorio con estanterías abiertas y una pared estampada",
 "Visuel du promoteur d'une chambre avec étagères ouvertes et un mur à motifs",
 "Bauträger-Visualisierung eines Schlafzimmers mit offenen Regalen und gemusterter Wand",
 "Визуализация застройщика: спальня с открытыми полками и стеной с узором",
 "تصور من المطور لغرفة نوم برفوف مفتوحة وجدار مزخرف",
 "Beeld van de ontwikkelaar van een slaapkamer met open planken en een gedessineerde wand",
 "Wizualizacja dewelopera przedstawiająca sypialnię z otwartymi półkami i wzorzystą ścianą",
 "Visualisering fra utbygger av et soverom med åpne hyller og en mønstret vegg",
 "Visualisering från utvecklaren av ett sovrum med öppna hyllor och en mönstrad vägg")
a("Developer visual of a bedroom set up as a study, a desk beneath the shelves",
 "Imagen del promotor de un dormitorio habilitado como estudio, con un escritorio bajo las estanterías",
 "Visuel du promoteur d'une chambre aménagée en bureau, un plan de travail sous les étagères",
 "Bauträger-Visualisierung eines als Arbeitszimmer eingerichteten Schlafzimmers, ein Schreibtisch unter den Regalen",
 "Визуализация застройщика: спальня, обустроенная как кабинет, письменный стол под полками",
 "تصور من المطور لغرفة نوم مهيّأة كمكتب، بمكتب أسفل الرفوف",
 "Beeld van de ontwikkelaar van een slaapkamer ingericht als werkkamer, een bureau onder de planken",
 "Wizualizacja dewelopera przedstawiająca sypialnię urządzoną jako gabinet, z biurkiem pod półkami",
 "Visualisering fra utbygger av et soverom innredet som arbeidsrom, med skrivebord under hyllene",
 "Visualisering från utvecklaren av ett sovrum inrett som arbetsrum, med skrivbord under hyllorna")
a("A bedroom as a study","Un dormitorio como estudio","Une chambre en bureau","Ein Schlafzimmer als Arbeitszimmer",
 "Спальня как кабинет","غرفة نوم كمكتب","Een slaapkamer als werkkamer","Sypialnia jako gabinet","Et soverom som arbeidsrom","Ett sovrum som arbetsrum")
a("Developer visual of the en-suite bathroom with a walk-in shower and a wide vanity",
 "Imagen del promotor del baño en suite con ducha de obra y un mueble amplio",
 "Visuel du promoteur de la salle de bains attenante avec douche à l'italienne et un large meuble",
 "Bauträger-Visualisierung des En-suite-Bads mit bodengleicher Dusche und breitem Waschtisch",
 "Визуализация застройщика: ванная при спальне с душевой без поддона и широкой тумбой",
 "تصور من المطور للحمام الداخلي بدش مفتوح ووحدة خزانة عريضة",
 "Beeld van de ontwikkelaar van de en-suite badkamer met inloopdouche en een breed wastafelmeubel",
 "Wizualizacja dewelopera przedstawiająca łazienkę przy sypialni z prysznicem walk-in i szeroką szafką",
 "Visualisering fra utbygger av badet ved soverommet med dusjnisje uten kant og en bred servant",
 "Visualisering från utvecklaren av badrummet vid sovrummet med golvbrunnsdusch och ett brett kommod")
a("The en-suite","El baño en suite","La salle de bains attenante","Das En-suite-Bad","Ванная при спальне",
 "الحمام الداخلي","De en-suite badkamer","Łazienka przy sypialni","Badet ved soverommet","Badrummet vid sovrummet")
a("Developer visual of the second bathroom with a bath and a washbasin",
 "Imagen del promotor del segundo baño con bañera y lavabo",
 "Visuel du promoteur de la seconde salle de bains avec baignoire et lavabo",
 "Bauträger-Visualisierung des zweiten Badezimmers mit Badewanne und Waschbecken",
 "Визуализация застройщика: вторая ванная комната с ванной и раковиной",
 "تصور من المطور للحمام الثاني بحوض استحمام ومغسلة",
 "Beeld van de ontwikkelaar van de tweede badkamer met bad en wastafel",
 "Wizualizacja dewelopera przedstawiająca drugą łazienkę z wanną i umywalką",
 "Visualisering fra utbygger av det andre badet med badekar og servant",
 "Visualisering från utvecklaren av det andra badrummet med badkar och tvättställ")
a("Forty-six homes, <em>eight available</em>","Cuarenta y seis viviendas, <em>ocho disponibles</em>",
 "Quarante-six logements, <em>huit disponibles</em>","Sechsundvierzig Wohnungen, <em>acht verfügbar</em>",
 "Сорок шесть квартир, <em>восемь доступны</em>","ستة وأربعون منزلاً، <em>ثمانية متاحة</em>",
 "Zesenveertig woningen, <em>acht beschikbaar</em>","Czterdzieści sześć mieszkań, <em>osiem dostępnych</em>",
 "Førtiseks boliger, <em>åtte tilgjengelige</em>","Fyrtiosex bostäder, <em>åtta tillgängliga</em>")
a("Two blocks in a gated scheme above Mijas Costa, a short drive from the beaches and the A-7.",
 "Dos bloques en una promoción cerrada sobre Mijas Costa, a poca distancia en coche de las playas y de la A-7.",
 "Deux immeubles dans une résidence fermée au-dessus de Mijas Costa, à quelques minutes en voiture des plages et de l'A-7.",
 "Zwei Gebäude in einer geschlossenen Anlage oberhalb von Mijas Costa, wenige Autominuten von den Stränden und der A-7.",
 "Два корпуса в закрытом комплексе над Михас-Костой, в нескольких минутах езды от пляжей и A-7.",
 "مبنيان في مجمع مغلق فوق ميخاس كوستا، على مسافة قصيرة بالسيارة من الشواطئ وطريق A-7.",
 "Twee blokken in een besloten project boven Mijas Costa, op korte rijafstand van de stranden en de A-7.",
 "Dwa budynki w zamkniętej inwestycji nad Mijas Costa, w krótkim dojeździe od plaż i A-7.",
 "To bygg i et lukket prosjekt over Mijas Costa, en kort kjøretur fra strendene og A-7.",
 "Två hus i ett slutet projekt ovanför Mijas Costa, en kort bilresa från stränderna och A-7.")
a("Two and three bedrooms, 97 to 137 sqm built, with gardens of up to 81.80 sqm on the ground floor and sea views from the upper homes.",
 "Dos y tres dormitorios, de 97 a 137 m² construidos, con jardines de hasta 81,80 m² en planta baja y vistas al mar desde las viviendas superiores.",
 "Deux et trois chambres, de 97 à 137 m² construits, avec des jardins jusqu'à 81,80 m² en rez-de-chaussée et vue mer depuis les logements des étages.",
 "Zwei und drei Schlafzimmer, 97 bis 137 m² Wohnfläche, mit Gärten bis 81,80 m² im Erdgeschoss und Meerblick aus den oberen Wohnungen.",
 "Две и три спальни, от 97 до 137 м² построенной площади, с садами до 81,80 м² на первом этаже и видом на море из верхних квартир.",
 "غرفتان وثلاث غرف نوم، من 97 إلى 137 م² مبنية، مع حدائق حتى 81.80 م² في الطابق الأرضي وإطلالات بحرية من المنازل العلوية.",
 "Twee en drie slaapkamers, 97 tot 137 m² bouwoppervlak, met tuinen tot 81,80 m² op de begane grond en zeezicht vanuit de hoger gelegen woningen.",
 "Dwie i trzy sypialnie, od 97 do 137 m² powierzchni zabudowanej, z ogrodami do 81,80 m² na parterze i widokiem na morze z wyższych mieszkań.",
 "To og tre soverom, 97 til 137 m² bygget, med hager opptil 81,80 m² i første etasje og havutsikt fra boligene høyere opp.",
 "Två och tre sovrum, 97 till 137 m² byggyta, med trädgårdar upp till 81,80 m² på bottenvåningen och havsutsikt från bostäderna högre upp.")
a("Two and three bedrooms across two blocks.","Dos y tres dormitorios repartidos en dos bloques.",
 "Deux et trois chambres réparties sur deux immeubles.","Zwei und drei Schlafzimmer, verteilt auf zwei Gebäude.",
 "Две и три спальни в двух корпусах.","غرفتان وثلاث غرف نوم موزعة على مبنيين.",
 "Twee en drie slaapkamers verdeeld over twee blokken.","Dwie i trzy sypialnie w dwóch budynkach.",
 "To og tre soverom fordelt på to bygg.","Två och tre sovrum fördelade på två hus.")
a("Ground-floor homes have gardens of up to 81.80 sqm; the upper homes have sea views.",
 "Las viviendas en planta baja tienen jardines de hasta 81,80 m²; las superiores, vistas al mar.",
 "Les logements en rez-de-chaussée disposent de jardins jusqu'à 81,80 m² ; ceux des étages, de la vue mer.",
 "Die Erdgeschosswohnungen haben Gärten bis 81,80 m², die oberen Wohnungen Meerblick.",
 "У квартир на первом этаже сады до 81,80 м², у верхних — вид на море.",
 "منازل الطابق الأرضي لها حدائق تصل إلى 81.80 م²، والمنازل العلوية لها إطلالات بحرية.",
 "De woningen op de begane grond hebben tuinen tot 81,80 m²; de hoger gelegen woningen hebben zeezicht.",
 "Mieszkania na parterze mają ogrody do 81,80 m², a wyższe – widok na morze.",
 "Boligene i første etasje har hager på opptil 81,80 m², og boligene høyere opp har havutsikt.",
 "Bostäderna på bottenvåningen har trädgårdar upp till 81,80 m², och de högre upp har havsutsikt.")
a("A parking space and a storeroom with every home.","Plaza de aparcamiento y trastero con cada vivienda.",
 "Une place de parking et un débarras avec chaque logement.","Stellplatz und Abstellraum zu jeder Wohnung.",
 "Парковочное место и кладовая к каждой квартире.","موقف سيارة ومخزن مع كل منزل.",
 "Een parkeerplaats en een berging bij elke woning.","Miejsce postojowe i komórka lokatorska do każdego mieszkania.",
 "Parkeringsplass og bod til hver bolig.","Parkeringsplats och förråd till varje bostad.")
a("A communal pool, landscaped gardens and a chill-out area.","Piscina comunitaria, jardines y zona chill-out.",
 "Piscine commune, jardins paysagers et espace chill-out.","Gemeinschaftspool, angelegte Gärten und Chill-out-Bereich.",
 "Общий бассейн, ландшафтные сады и зона chill-out.","مسبح مشترك وحدائق منسقة ومنطقة استرخاء.",
 "Een gemeenschappelijk zwembad, aangelegde tuinen en een chill-outzone.","Basen wspólny, urządzone ogrody i strefa chill-out.",
 "Fellesbasseng, opparbeidede hager og et chill-out-område.","Gemensam pool, anlagda trädgårdar och en chill out-yta.")
a("A gated, private urbanisation.","Una urbanización privada y cerrada.","Une résidence privée et fermée.",
 "Eine geschlossene, private Wohnanlage.","Закрытый частный жилой комплекс.","مجمع سكني خاص ومغلق.",
 "Een besloten, private urbanisatie.","Zamknięte, prywatne osiedle.","Et lukket, privat boligområde.","Ett slutet, privat bostadsområde.")
a("8 of 46 homes <em>available</em>","8 de 46 viviendas <em>disponibles</em>","8 des 46 logements <em>disponibles</em>",
 "8 von 46 Wohnungen <em>verfügbar</em>","8 из 46 квартир <em>в продаже</em>","8 من 46 منزلاً <em>متاحة</em>",
 "8 van de 46 woningen <em>beschikbaar</em>","8 z 46 mieszkań <em>dostępnych</em>","8 av 46 boliger <em>tilgjengelig</em>","8 av 46 bostäder <em>tillgängliga</em>")
json.dump(T, open(sys.argv[1],'w'), ensure_ascii=False, indent=1); print(len(T))
