# -*- coding: utf-8 -*-
import json, sys
T={}
def a(en,es,fr,de,ru,ar,nl,pl,no,sv): T[en]={'es':es,'fr':fr,'de':de,'ru':ru,'ar':ar,'nl':nl,'pl':pl,'no':no,'sv':sv}

a("Eight apartments are available, four of them on the ground floor with a garden. Nueva Living reconfirms price and availability before any viewing or reservation.",
 "Hay ocho apartamentos disponibles, cuatro de ellos en planta baja con jardín. Nueva Living reconfirma precio y disponibilidad antes de cualquier visita o reserva.",
 "Huit appartements sont disponibles, dont quatre en rez-de-chaussée avec jardin. Nueva Living reconfirme le prix et la disponibilité avant toute visite ou réservation.",
 "Acht Wohnungen sind verfügbar, vier davon im Erdgeschoss mit Garten. Nueva Living bestätigt Preis und Verfügbarkeit vor jeder Besichtigung oder Reservierung erneut.",
 "Доступны восемь квартир, четыре из них на первом этаже с садом. Nueva Living заново подтверждает цену и наличие перед любым просмотром или бронированием.",
 "تتوفر ثماني شقق، أربع منها في الطابق الأرضي مع حديقة. تؤكد Nueva Living السعر والتوافر مجدداً قبل أي معاينة أو حجز.",
 "Er zijn acht appartementen beschikbaar, vier daarvan op de begane grond met tuin. Nueva Living bevestigt prijs en beschikbaarheid opnieuw vóór elke bezichtiging of reservering.",
 "Dostępnych jest osiem apartamentów, cztery z nich na parterze z ogrodem. Nueva Living ponownie potwierdza cenę i dostępność przed każdą wizytą lub rezerwacją.",
 "Åtte leiligheter er tilgjengelige, fire av dem i første etasje med hage. Nueva Living bekrefter pris og tilgjengelighet på nytt før enhver visning eller reservasjon.",
 "Åtta lägenheter är tillgängliga, fyra av dem på bottenvåningen med trädgård. Nueva Living bekräftar pris och tillgänglighet på nytt före varje visning eller reservation.")
a("Floors, areas and prices are transcribed from the seller's own availability list, read on 28 September 2026. Built areas are the developer's constructed figure and include a share of the common parts; the useful area of each home is smaller and is on its floorplan. Prices exclude VAT and the other purchase costs, which are set out in the buying guides.",
 "Plantas, superficies y precios están transcritos de la propia lista de disponibilidad del vendedor, consultada el 28 de septiembre de 2026. Las superficies son la construida del promotor e incluyen una parte proporcional de elementos comunes; la superficie útil de cada vivienda es menor y figura en su plano. Los precios no incluyen el IVA ni los demás gastos de compra, detallados en las guías de compra.",
 "Étages, surfaces et prix sont transcrits de la liste de disponibilité du vendeur, consultée le 28 septembre 2026. Les surfaces sont la surface construite du promoteur et incluent une quote-part des parties communes ; la surface utile de chaque logement est inférieure et figure sur son plan. Les prix s'entendent hors TVA et hors autres frais d'acquisition, détaillés dans les guides d'achat.",
 "Geschosse, Flächen und Preise sind aus der Verfügbarkeitsliste des Verkäufers übernommen, eingesehen am 28. September 2026. Die Flächen sind die Bauträger-Bruttofläche und enthalten einen Anteil am Gemeinschaftseigentum; die Nutzfläche jeder Wohnung ist kleiner und steht im Grundriss. Die Preise verstehen sich ohne Mehrwertsteuer und ohne die übrigen Kaufnebenkosten, die in den Kaufratgebern aufgeführt sind.",
 "Этажи, площади и цены перенесены из собственного списка наличия продавца, просмотренного 28 сентября 2026 года. Площади — построенная площадь застройщика и включают долю мест общего пользования; полезная площадь каждой квартиры меньше и указана на её плане. Цены не включают НДС и прочие расходы на покупку, которые описаны в руководствах покупателя.",
 "الطوابق والمساحات والأسعار منقولة عن قائمة التوافر الخاصة بالبائع، اطُّلع عليها في 28 سبتمبر 2026. المساحات هي المساحة المبنية للمطور وتشمل حصة من الأجزاء المشتركة، والمساحة المفيدة لكل منزل أقل وتظهر في مخططه. الأسعار لا تشمل ضريبة القيمة المضافة ولا باقي تكاليف الشراء الموضحة في أدلة الشراء.",
 "Verdiepingen, oppervlakten en prijzen zijn overgenomen uit de eigen beschikbaarheidslijst van de verkoper, geraadpleegd op 28 september 2026. De oppervlakten zijn de bouwoppervlakte van de ontwikkelaar en omvatten een aandeel in de gemeenschappelijke delen; de nuttige oppervlakte van elke woning is kleiner en staat op de plattegrond. Prijzen zijn exclusief btw en de overige aankoopkosten, die in de koopgidsen staan.",
 "Kondygnacje, powierzchnie i ceny przepisano z własnej listy dostępności sprzedającego, sprawdzonej 28 września 2026 roku. Powierzchnie to powierzchnia zabudowana dewelopera i obejmują udział w częściach wspólnych; powierzchnia użytkowa każdego mieszkania jest mniejsza i podana jest na jego rzucie. Ceny nie zawierają VAT ani pozostałych kosztów zakupu, opisanych w przewodnikach zakupowych.",
 "Etasjer, arealer og priser er hentet fra selgerens egen tilgjengelighetsliste, lest 28. september 2026. Arealene er utbyggerens bruttoareal og inkluderer en andel av fellesarealene; det nyttbare arealet i hver bolig er mindre og står på plantegningen. Prisene er uten merverdiavgift og de øvrige kjøpsomkostningene, som står i kjøpsguidene.",
 "Våningar, ytor och priser är hämtade från säljarens egen tillgänglighetslista, läst den 28 september 2026. Ytorna är utvecklarens byggyta och inkluderar en andel av de gemensamma delarna; varje bostads nyttiga yta är mindre och står på dess planritning. Priserna är exklusive moms och övriga köpkostnader, som beskrivs i köpguiderna.")
a("Currently off-plan, with completion given as the third quarter of 2027. Nueva Living asks for the delivery date in writing and puts it in the contract.",
 "Actualmente sobre plano, con entrega indicada para el tercer trimestre de 2027. Nueva Living pide la fecha de entrega por escrito y la lleva al contrato.",
 "Actuellement sur plan, avec une livraison annoncée au troisième trimestre 2027. Nueva Living demande la date de livraison par écrit et l'inscrit au contrat.",
 "Derzeit im Bauträgerverkauf, die Fertigstellung ist für das dritte Quartal 2027 angegeben. Nueva Living lässt sich den Übergabetermin schriftlich geben und nimmt ihn in den Vertrag auf.",
 "Сейчас на стадии проекта, срок сдачи указан как третий квартал 2027 года. Nueva Living запрашивает дату передачи письменно и вносит её в договор.",
 "المشروع حالياً على المخطط، والإنجاز مذكور في الربع الثالث من عام 2027. تطلب Nueva Living تاريخ التسليم كتابةً وتدرجه في العقد.",
 "Momenteel op plan, met oplevering opgegeven voor het derde kwartaal van 2027. Nueva Living vraagt de opleverdatum schriftelijk op en neemt die in het contract op.",
 "Obecnie na etapie przedsprzedaży, z terminem zakończenia podanym na trzeci kwartał 2027 roku. Nueva Living prosi o datę odbioru na piśmie i wpisuje ją do umowy.",
 "For tiden på tegnebrettet, med ferdigstillelse oppgitt til tredje kvartal 2027. Nueva Living ber om overtakelsesdatoen skriftlig og tar den inn i kontrakten.",
 "För närvarande på ritning, med färdigställande angivet till tredje kvartalet 2027. Nueva Living begär tillträdesdatumet skriftligt och för in det i avtalet.")
a("This project suits buyers who want a straightforward apartment near the Mijas Costa beaches without a resort-scale service charge.",
 "Este proyecto encaja con quienes buscan un apartamento sencillo cerca de las playas de Mijas Costa sin una cuota propia de un resort.",
 "Ce programme convient aux acquéreurs qui cherchent un appartement simple près des plages de Mijas Costa sans charges dignes d'un resort.",
 "Das Projekt passt zu Käufern, die eine unkomplizierte Wohnung nahe den Stränden von Mijas Costa wollen, ohne Hausgeld in Resort-Größe.",
 "Проект подходит покупателям, которым нужна простая квартира рядом с пляжами Михас-Косты без взносов уровня курорта.",
 "يناسب هذا المشروع من يريد شقة بسيطة قرب شواطئ ميخاس كوستا دون رسوم خدمات بحجم المنتجعات.",
 "Dit project past bij kopers die een eenvoudig appartement bij de stranden van Mijas Costa willen zonder servicekosten op resortniveau.",
 "Ta inwestycja odpowiada osobom szukającym prostego apartamentu blisko plaż Mijas Costa bez opłat rodem z resortu.",
 "Prosjektet passer kjøpere som vil ha en enkel leilighet nær strendene i Mijas Costa uten fellesutgifter i resort-skala.",
 "Projektet passar köpare som vill ha en enkel lägenhet nära stränderna i Mijas Costa utan avgifter i resortklass.")
a("Buyers who want a simple, well-built apartment rather than a scheme full of facilities.",
 "Compradores que buscan un apartamento sencillo y bien construido más que una promoción llena de instalaciones.",
 "Des acquéreurs qui veulent un appartement simple et bien construit plutôt qu'un programme rempli d'équipements.",
 "Käufer, die eine einfache, gut gebaute Wohnung wollen statt einer Anlage voller Einrichtungen.",
 "Покупателям, которым нужна простая, добротная квартира, а не комплекс, набитый инфраструктурой.",
 "من يريد شقة بسيطة ومبنية جيداً بدل مشروع مليء بالمرافق.",
 "Kopers die een eenvoudig, degelijk gebouwd appartement willen in plaats van een project vol voorzieningen.",
 "Kupującym, którzy wolą proste, solidnie zbudowane mieszkanie niż inwestycję pełną udogodnień.",
 "Kjøpere som vil ha en enkel, godt bygget leilighet framfor et prosjekt fullt av fasiliteter.",
 "Köpare som vill ha en enkel, välbyggd lägenhet snarare än ett projekt fullt av faciliteter.")
a("Forty-six homes in two blocks, with one pool and gardens rather than a long amenity list, which keeps the community fee down.",
 "Cuarenta y seis viviendas en dos bloques, con una piscina y jardines en lugar de una larga lista de instalaciones, lo que mantiene baja la cuota de comunidad.",
 "Quarante-six logements dans deux immeubles, avec une piscine et des jardins plutôt qu'une longue liste d'équipements, ce qui maintient les charges basses.",
 "Sechsundvierzig Wohnungen in zwei Gebäuden, mit einem Pool und Gärten statt einer langen Liste an Einrichtungen, was das Hausgeld niedrig hält.",
 "Сорок шесть квартир в двух корпусах, с одним бассейном и садами вместо длинного списка удобств, что удерживает взнос на содержание низким.",
 "ستة وأربعون منزلاً في مبنيين، بمسبح واحد وحدائق بدل قائمة طويلة من المرافق، ما يبقي رسوم الخدمات منخفضة.",
 "Zesenveertig woningen in twee blokken, met één zwembad en tuinen in plaats van een lange lijst voorzieningen, wat de servicekosten laag houdt.",
 "Czterdzieści sześć mieszkań w dwóch budynkach, z jednym basenem i ogrodami zamiast długiej listy udogodnień, co utrzymuje niski czynsz wspólnoty.",
 "Førtiseks boliger i to bygg, med ett basseng og hager i stedet for en lang liste med fasiliteter, noe som holder fellesutgiftene nede.",
 "Fyrtiosex bostäder i två hus, med en pool och trädgårdar i stället för en lång lista faciliteter, vilket håller nere samfällighetsavgiften.")
a("Mijas Costa puts the beaches, Fuengirola and the A-7 within a short drive.",
 "Mijas Costa deja las playas, Fuengirola y la A-7 a poca distancia en coche.",
 "Mijas Costa place les plages, Fuengirola et l'A-7 à quelques minutes en voiture.",
 "Mijas Costa bringt Strände, Fuengirola und die A-7 in kurze Fahrdistanz.",
 "Михас-Коста оставляет пляжи, Фуэнхиролу и A-7 в нескольких минутах езды.",
 "تضع ميخاس كوستا الشواطئ وفوينخيرولا وطريق A-7 على مسافة قصيرة بالسيارة.",
 "Mijas Costa brengt de stranden, Fuengirola en de A-7 op korte rijafstand.",
 "Mijas Costa stawia plaże, Fuengirolę i A-7 w krótkim zasięgu jazdy.",
 "Mijas Costa gir kort kjøretur til strendene, Fuengirola og A-7.",
 "Mijas Costa ger kort bilresa till stränderna, Fuengirola och A-7.")
a("Eight of the 46 remain and the seller's list changes, so it is worth confirming before you shortlist.",
 "Quedan ocho de las 46 y la lista del vendedor cambia, así que conviene confirmarla antes de preseleccionar.",
 "Huit des 46 restent et la liste du vendeur évolue : mieux vaut la confirmer avant de présélectionner.",
 "Acht der 46 sind noch frei, und die Liste des Verkäufers ändert sich, daher lohnt sich eine Bestätigung vor der Auswahl.",
 "Из 46 остаётся восемь, а список продавца меняется, поэтому стоит уточнить его перед отбором.",
 "تبقى ثماني من أصل 46 وقائمة البائع تتغير، لذا يُستحسن تأكيدها قبل الاختيار.",
 "Acht van de 46 resteren en de lijst van de verkoper verandert, dus het loont die te bevestigen voordat u selecteert.",
 "Zostało osiem z 46, a lista sprzedającego się zmienia, więc warto ją potwierdzić przed wyborem.",
 "Åtte av de 46 gjenstår, og selgerens liste endrer seg, så det lønner seg å bekrefte før du velger ut.",
 "Åtta av de 46 återstår och säljarens lista ändras, så det är värt att bekräfta innan urvalet görs.")
a("Completion in 2027","Entrega en 2027","Livraison en 2027","Fertigstellung 2027","Сдача в 2027 году",
 "الإنجاز في 2027","Oplevering in 2027","Zakończenie w 2027","Ferdigstilling i 2027","Färdigställande 2027")
a("Closer than most off-plan on this coast. The date belongs in the contract.",
 "Más cerca que la mayoría de la obra nueva de esta costa. La fecha debe estar en el contrato.",
 "Plus proche que la plupart des programmes neufs de cette côte. La date a sa place dans le contrat.",
 "Näher als die meisten Neubauten an dieser Küste. Der Termin gehört in den Vertrag.",
 "Ближе, чем у большинства строящихся проектов на этом побережье. Дата должна быть в договоре.",
 "أقرب من معظم مشاريع البناء على هذا الساحل. التاريخ مكانه العقد.",
 "Dichterbij dan de meeste nieuwbouw aan deze kust. De datum hoort in het contract.",
 "Bliżej niż większość inwestycji w budowie na tym wybrzeżu. Data powinna znaleźć się w umowie.",
 "Nærmere enn de fleste prosjekter under bygging på denne kysten. Datoen hører hjemme i kontrakten.",
 "Närmare än de flesta nyproduktioner på den här kusten. Datumet hör hemma i avtalet.")
a("A modest amenity list","Una lista de instalaciones contenida","Une liste d'équipements mesurée",
 "Eine überschaubare Ausstattungsliste","Скромный набор удобств","قائمة مرافق متواضعة",
 "Een bescheiden voorzieningenlijst","Skromna lista udogodnień","En beskjeden fasilitetsliste","En måttlig lista faciliteter")
a("One pool and gardens rather than a sports club. Lower fees, and fewer things to maintain.",
 "Una piscina y jardines en lugar de un club deportivo. Cuotas más bajas y menos cosas que mantener.",
 "Une piscine et des jardins plutôt qu'un club sportif. Des charges plus faibles et moins d'entretien.",
 "Ein Pool und Gärten statt eines Sportclubs. Niedrigere Kosten und weniger Instandhaltung.",
 "Один бассейн и сады вместо спортклуба. Ниже взносы и меньше того, что надо содержать.",
 "مسبح واحد وحدائق بدل نادٍ رياضي. رسوم أقل وصيانة أقل.",
 "Eén zwembad en tuinen in plaats van een sportclub. Lagere kosten en minder onderhoud.",
 "Jeden basen i ogrody zamiast klubu sportowego. Niższe opłaty i mniej rzeczy do utrzymania.",
 "Ett basseng og hager i stedet for en sportsklubb. Lavere utgifter og mindre å vedlikeholde.",
 "En pool och trädgårdar i stället för en sportklubb. Lägre avgifter och mindre att underhålla.")
a("Ground floor or upper","Planta baja o plantas superiores","Rez-de-chaussée ou étages","Erdgeschoss oder obere Geschosse",
 "Первый этаж или выше","الطابق الأرضي أم العلوي","Begane grond of hoger","Parter czy wyżej","Første etasje eller høyere","Bottenvåning eller högre upp")
a("The gardens are on the ground floor and the sea views are above. They are different products.",
 "Los jardines están en planta baja y las vistas al mar, arriba. Son productos distintos.",
 "Les jardins sont en rez-de-chaussée et la vue mer aux étages. Ce sont deux produits différents.",
 "Die Gärten liegen im Erdgeschoss, der Meerblick darüber. Das sind zwei verschiedene Produkte.",
 "Сады на первом этаже, а вид на море выше. Это разные продукты.",
 "الحدائق في الطابق الأرضي والإطلالات البحرية في الأعلى. إنهما منتجان مختلفان.",
 "De tuinen liggen op de begane grond en het zeezicht hoger. Dat zijn verschillende producten.",
 "Ogrody są na parterze, a widok na morze wyżej. To dwa różne produkty.",
 "Hagene ligger i første etasje og havutsikten høyere opp. Det er to ulike produkter.",
 "Trädgårdarna finns på bottenvåningen och havsutsikten högre upp. Det är två olika produkter.")
json.dump(T, open(sys.argv[1],'w'), ensure_ascii=False, indent=1); print(len(T))
