# -*- coding: utf-8 -*-
import json, sys
T={}
def a(en,es,fr,de,ru,ar,nl,pl,no,sv): T[en]={'es':es,'fr':fr,'de':de,'ru':ru,'ar':ar,'nl':nl,'pl':pl,'no':no,'sv':sv}

a("Two blocks on <em>a quiet slope</em>","Dos bloques en <em>una ladera tranquila</em>","Deux immeubles sur <em>un coteau tranquille</em>",
 "Zwei Gebäude an <em>einem ruhigen Hang</em>","Два корпуса на <em>тихом склоне</em>","مبنيان على <em>منحدر هادئ</em>",
 "Twee blokken op <em>een rustige helling</em>","Dwa budynki na <em>spokojnym zboczu</em>","To bygg i <em>en rolig skråning</em>","Två hus i <em>en lugn sluttning</em>")
a("Two low blocks set above the road, with the pool and gardens between them.",
 "Dos bloques de baja altura situados sobre la carretera, con la piscina y los jardines entre ellos.",
 "Deux immeubles bas placés au-dessus de la route, avec la piscine et les jardins entre eux.",
 "Zwei niedrige Gebäude oberhalb der Straße, mit Pool und Gärten dazwischen.",
 "Два невысоких корпуса над дорогой, между ними бассейн и сады.",
 "مبنيان منخفضان فوق الطريق، بينهما المسبح والحدائق.",
 "Twee lage blokken boven de weg, met het zwembad en de tuinen ertussen.",
 "Dwa niskie budynki nad drogą, z basenem i ogrodami pomiędzy nimi.",
 "To lave bygg over veien, med bassenget og hagene mellom seg.",
 "Två låga hus ovanför vägen, med poolen och trädgårdarna emellan.")
a("White volumes and planted balconies, in a scheme whose upper homes look over the coastal plain to the sea.",
 "Volúmenes blancos y terrazas ajardinadas, en una promoción cuyas viviendas superiores miran sobre la llanura costera hacia el mar.",
 "Des volumes blancs et des balcons plantés, dans un programme dont les logements des étages regardent la plaine côtière jusqu'à la mer.",
 "Weiße Baukörper und bepflanzte Balkone, in einer Anlage, deren obere Wohnungen über die Küstenebene zum Meer blicken.",
 "Белые объёмы и озеленённые балконы в комплексе, верхние квартиры которого смотрят через прибрежную равнину на море.",
 "كتل بيضاء وشرفات مزروعة، في مشروع تطل منازله العلوية فوق السهل الساحلي إلى البحر.",
 "Witte volumes en beplante balkons, in een project waarvan de hoger gelegen woningen over de kustvlakte naar de zee kijken.",
 "Białe bryły i obsadzone zielenią balkony, w inwestycji, której wyższe mieszkania patrzą ponad nadmorską równiną na morze.",
 "Hvite volumer og beplantede balkonger, i et prosjekt der boligene høyere opp ser over kystsletten mot havet.",
 "Vita volymer och planterade balkonger, i ett projekt vars bostäder högre upp ser över kustslätten mot havet.")
a("Upper homes look over the plain to the sea.","Las viviendas superiores miran sobre la llanura hacia el mar.",
 "Les logements des étages regardent la plaine jusqu'à la mer.","Die oberen Wohnungen blicken über die Ebene zum Meer.",
 "Верхние квартиры смотрят через равнину на море.","تطل المنازل العلوية فوق السهل إلى البحر.",
 "De hoger gelegen woningen kijken over de vlakte naar de zee.","Wyższe mieszkania patrzą ponad równiną na morze.",
 "Boligene høyere opp ser over sletten mot havet.","Bostäderna högre upp ser över slätten mot havet.")
a("Terraces from 9.30 sqm, ground-floor gardens to 81.80 sqm.","Terrazas desde 9,30 m² y jardines en planta baja hasta 81,80 m².",
 "Terrasses à partir de 9,30 m², jardins en rez-de-chaussée jusqu'à 81,80 m².",
 "Terrassen ab 9,30 m², Erdgeschossgärten bis 81,80 m².","Террасы от 9,30 м², сады на первом этаже до 81,80 м².",
 "شرفات من 9.30 م²، وحدائق الطابق الأرضي حتى 81.80 م².","Terrassen vanaf 9,30 m², tuinen op de begane grond tot 81,80 m².",
 "Tarasy od 9,30 m², ogrody na parterze do 81,80 m².","Terrasser fra 9,30 m², hager i første etasje opptil 81,80 m².",
 "Terrasser från 9,30 m², trädgårdar på bottenvåningen upp till 81,80 m².")
a("Shared space","Zonas comunes","Espaces partagés","Gemeinschaftsflächen","Общие зоны","المساحات المشتركة",
 "Gedeelde ruimte","Przestrzeń wspólna","Fellesarealer","Gemensamma ytor")
a("Simple living <em>near the beach</em>","Vivir sencillo <em>cerca de la playa</em>","Vivre simplement <em>près de la plage</em>",
 "Einfach wohnen <em>nahe dem Strand</em>","Простая жизнь <em>рядом с пляжем</em>","حياة بسيطة <em>قرب الشاطئ</em>",
 "Eenvoudig wonen <em>vlak bij het strand</em>","Proste życie <em>blisko plaży</em>","Enkelt liv <em>nær stranden</em>","Enkelt boende <em>nära stranden</em>")
a("A gated scheme built around one pool and its gardens rather than a long list of facilities.",
 "Una promoción cerrada construida en torno a una piscina y sus jardines, no a una larga lista de instalaciones.",
 "Une résidence fermée construite autour d'une piscine et de ses jardins plutôt que d'une longue liste d'équipements.",
 "Eine geschlossene Anlage, die um einen Pool und seine Gärten herum gebaut ist statt um eine lange Liste an Einrichtungen.",
 "Закрытый комплекс, выстроенный вокруг одного бассейна и его садов, а не вокруг длинного списка удобств.",
 "مجمع مغلق بُني حول مسبح واحد وحدائقه بدل قائمة طويلة من المرافق.",
 "Een besloten project gebouwd rond één zwembad en zijn tuinen in plaats van een lange lijst voorzieningen.",
 "Zamknięta inwestycja zbudowana wokół jednego basenu i jego ogrodów, a nie długiej listy udogodnień.",
 "Et lukket prosjekt bygget rundt ett basseng og hagene, ikke rundt en lang liste med fasiliteter.",
 "Ett slutet projekt byggt kring en pool och dess trädgårdar i stället för en lång lista faciliteter.")
a("A communal pool with loungers and planting, lit in the evening.",
 "Una piscina comunitaria con tumbonas y vegetación, iluminada por la noche.",
 "Une piscine commune avec transats et plantations, éclairée le soir.",
 "Ein Gemeinschaftspool mit Liegen und Bepflanzung, abends beleuchtet.",
 "Общий бассейн с шезлонгами и озеленением, с вечерней подсветкой.",
 "مسبح مشترك بكراسي تشمس ونباتات، مضاء في المساء.",
 "Een gemeenschappelijk zwembad met ligbedden en beplanting, 's avonds verlicht.",
 "Basen wspólny z leżakami i zielenią, oświetlony wieczorem.",
 "Et fellesbasseng med solsenger og beplantning, opplyst om kvelden.",
 "En gemensam pool med solsängar och planteringar, upplyst på kvällen.")
a("Landscaped green areas and a chill-out terrace between the blocks.",
 "Zonas verdes ajardinadas y una terraza chill-out entre los bloques.",
 "Des espaces verts paysagers et une terrasse chill-out entre les immeubles.",
 "Angelegte Grünflächen und eine Chill-out-Terrasse zwischen den Gebäuden.",
 "Озеленённые зоны и терраса chill-out между корпусами.",
 "مساحات خضراء منسقة وتراس استرخاء بين المبنيين.",
 "Aangelegde groenzones en een chill-outterras tussen de blokken.",
 "Urządzone tereny zielone i taras chill-out między budynkami.",
 "Opparbeidede grøntarealer og en chill-out-terrasse mellom byggene.",
 "Anlagda grönytor och en chill out-terrass mellan husen.")
a("The Mijas Costa beaches and Fuengirola are a short drive down the hill.",
 "Las playas de Mijas Costa y Fuengirola quedan a poca distancia en coche ladera abajo.",
 "Les plages de Mijas Costa et Fuengirola sont à quelques minutes en voiture en descendant.",
 "Die Strände von Mijas Costa und Fuengirola sind eine kurze Fahrt den Hang hinunter entfernt.",
 "Пляжи Михас-Косты и Фуэнхирола — в нескольких минутах езды вниз по склону.",
 "شواطئ ميخاس كوستا وفوينخيرولا على مسافة قصيرة بالسيارة نزولاً من التل.",
 "De stranden van Mijas Costa en Fuengirola liggen op korte rijafstand de heuvel af.",
 "Plaże Mijas Costa i Fuengirola są w krótkim dojeździe w dół zbocza.",
 "Strendene i Mijas Costa og Fuengirola er en kort kjøretur ned bakken.",
 "Stränderna i Mijas Costa och Fuengirola nås med en kort bilresa nedför backen.")
a("Which homes keep the sea view and which look inland.","Qué viviendas conservan las vistas al mar y cuáles miran al interior.",
 "Quels logements conservent la vue mer et lesquels donnent vers l'intérieur.",
 "Welche Wohnungen den Meerblick behalten und welche ins Landesinnere schauen.",
 "Какие квартиры сохраняют вид на море, а какие смотрят вглубь суши.",
 "أي المنازل تحتفظ بالإطلالة البحرية وأيها تطل نحو الداخل.",
 "Welke woningen het zeezicht houden en welke landinwaarts kijken.",
 "Które mieszkania zachowują widok na morze, a które patrzą w głąb lądu.",
 "Hvilke boliger beholder havutsikten og hvilke vender innover.",
 "Vilka bostäder behåller havsutsikten och vilka vetter inåt land.")
a("What the gardens actually give you against a terrace upstairs.",
 "Qué aportan realmente los jardines frente a una terraza en planta alta.",
 "Ce qu'apportent réellement les jardins par rapport à une terrasse à l'étage.",
 "Was die Gärten tatsächlich bringen im Vergleich zu einer Terrasse weiter oben.",
 "Что на деле дают сады по сравнению с террасой этажом выше.",
 "ما تقدمه الحدائق فعلياً مقابل تراس في الأعلى.",
 "Wat de tuinen werkelijk opleveren tegenover een terras hogerop.",
 "Co naprawdę dają ogrody w porównaniu z tarasem wyżej.",
 "Hva hagene faktisk gir sammenlignet med en terrasse lenger opp.",
 "Vad trädgårdarna faktiskt ger jämfört med en terrass högre upp.")
a("The community fee for a scheme of this size.","La cuota de comunidad de una promoción de este tamaño.",
 "Les charges de copropriété pour un programme de cette taille.","Das Hausgeld für eine Anlage dieser Größe.",
 "Взнос на содержание комплекса такого размера.","رسوم الخدمات لمشروع بهذا الحجم.",
 "De servicekosten voor een project van deze omvang.","Czynsz wspólnoty przy inwestycji tej wielkości.",
 "Fellesutgiftene for et prosjekt av denne størrelsen.","Samfällighetsavgiften för ett projekt av den här storleken.")
a("Mijas Costa, <em>above the beaches</em>","Mijas Costa, <em>sobre las playas</em>","Mijas Costa, <em>au-dessus des plages</em>",
 "Mijas Costa, <em>oberhalb der Strände</em>","Михас-Коста, <em>над пляжами</em>","ميخاس كوستا، <em>فوق الشواطئ</em>",
 "Mijas Costa, <em>boven de stranden</em>","Mijas Costa, <em>nad plażami</em>","Mijas Costa, <em>over strendene</em>","Mijas Costa, <em>ovanför stränderna</em>")
a("A gated scheme of 46 homes above Mijas Costa, a short drive from the beaches, Fuengirola and the A-7.",
 "Una promoción cerrada de 46 viviendas sobre Mijas Costa, a poca distancia en coche de las playas, Fuengirola y la A-7.",
 "Une résidence fermée de 46 logements au-dessus de Mijas Costa, à quelques minutes en voiture des plages, de Fuengirola et de l'A-7.",
 "Eine geschlossene Anlage mit 46 Wohnungen oberhalb von Mijas Costa, wenige Autominuten von den Stränden, Fuengirola und der A-7.",
 "Закрытый комплекс из 46 квартир над Михас-Костой, в нескольких минутах езды от пляжей, Фуэнхиролы и A-7.",
 "مجمع مغلق من 46 منزلاً فوق ميخاس كوستا، على مسافة قصيرة بالسيارة من الشواطئ وفوينخيرولا وطريق A-7.",
 "Een besloten project van 46 woningen boven Mijas Costa, op korte rijafstand van de stranden, Fuengirola en de A-7.",
 "Zamknięta inwestycja 46 mieszkań nad Mijas Costa, w krótkim dojeździe od plaż, Fuengiroli i A-7.",
 "Et lukket prosjekt med 46 boliger over Mijas Costa, en kort kjøretur fra strendene, Fuengirola og A-7.",
 "Ett slutet projekt med 46 bostäder ovanför Mijas Costa, en kort bilresa från stränderna, Fuengirola och A-7.")
a("Mijas Costa, <em>Costa del Sol</em>","Mijas Costa, <em>Costa del Sol</em>","Mijas Costa, <em>Costa del Sol</em>",
 "Mijas Costa, <em>Costa del Sol</em>","Михас-Коста, <em>Коста-дель-Соль</em>","ميخاس كوستا، <em>كوستا ديل سول</em>",
 "Mijas Costa, <em>Costa del Sol</em>","Mijas Costa, <em>Costa del Sol</em>","Mijas Costa, <em>Costa del Sol</em>","Mijas Costa, <em>Costa del Sol</em>")
a("Mijas Costa, Costa del Sol","Mijas Costa, Costa del Sol","Mijas Costa, Costa del Sol","Mijas Costa, Costa del Sol",
 "Михас-Коста, Коста-дель-Соль","ميخاس كوستا، كوستا ديل سول","Mijas Costa, Costa del Sol","Mijas Costa, Costa del Sol",
 "Mijas Costa, Costa del Sol","Mijas Costa, Costa del Sol")
a("Eight of the 46 apartments: three with two bedrooms and five with three.",
 "Ocho de los 46 apartamentos: tres de dos dormitorios y cinco de tres.",
 "Huit des 46 appartements : trois de deux chambres et cinq de trois.",
 "Acht der 46 Wohnungen: drei mit zwei und fünf mit drei Schlafzimmern.",
 "Восемь из 46 квартир: три с двумя спальнями и пять с тремя.",
 "ثماني من أصل 46 شقة: ثلاث بغرفتي نوم وخمس بثلاث غرف.",
 "Acht van de 46 appartementen: drie met twee slaapkamers en vijf met drie.",
 "Osiem z 46 apartamentów: trzy z dwiema sypialniami i pięć z trzema.",
 "Åtte av de 46 leilighetene: tre med to soverom og fem med tre.",
 "Åtta av de 46 lägenheterna: tre med två sovrum och fem med tre.")
a("From EUR 421,600 to EUR 550,100, excluding VAT and the other purchase costs.",
 "De 421.600 € a 550.100 €, sin incluir el IVA ni los demás gastos de compra.",
 "De 421 600 € à 550 100 €, hors TVA et autres frais d'acquisition.",
 "Von 421.600 € bis 550.100 €, ohne Mehrwertsteuer und die übrigen Kaufnebenkosten.",
 "От 421 600 € до 550 100 €, без НДС и прочих расходов на покупку.",
 "من 421,600 € إلى 550,100 €، دون ضريبة القيمة المضافة وباقي تكاليف الشراء.",
 "Van € 421.600 tot € 550.100, exclusief btw en de overige aankoopkosten.",
 "Od 421 600 € do 550 100 €, bez VAT i pozostałych kosztów zakupu.",
 "Fra 421 600 € til 550 100 €, uten merverdiavgift og de øvrige kjøpsomkostningene.",
 "Från 421 600 € till 550 100 €, exklusive moms och övriga köpkostnader.")
a("From 97 to 137 sqm built, with terraces from 9.30 to 53 sqm.","De 97 a 137 m² construidos, con terrazas de 9,30 a 53 m².",
 "De 97 à 137 m² construits, avec des terrasses de 9,30 à 53 m².","Von 97 bis 137 m² Wohnfläche, mit Terrassen von 9,30 bis 53 m².",
 "От 97 до 137 м² построенной площади, с террасами от 9,30 до 53 м².","من 97 إلى 137 م² مبنية، مع شرفات من 9.30 إلى 53 م².",
 "Van 97 tot 137 m² bouwoppervlak, met terrassen van 9,30 tot 53 m².","Od 97 do 137 m² powierzchni zabudowanej, z tarasami od 9,30 do 53 m².",
 "Fra 97 til 137 m² bygget, med terrasser fra 9,30 til 53 m².","Från 97 till 137 m² byggyta, med terrasser från 9,30 till 53 m².")
a("Completion is given as the third quarter of 2027.","La entrega está indicada para el tercer trimestre de 2027.",
 "La livraison est annoncée pour le troisième trimestre 2027.","Die Fertigstellung ist für das dritte Quartal 2027 angegeben.",
 "Срок сдачи указан как третий квартал 2027 года.","الإنجاز مذكور في الربع الثالث من عام 2027.",
 "De oplevering is opgegeven voor het derde kwartaal van 2027.","Zakończenie podano na trzeci kwartał 2027 roku.",
 "Ferdigstillelse er oppgitt til tredje kvartal 2027.","Färdigställandet anges till tredje kvartalet 2027.")
a("Yes. Every home comes with a parking space and a storeroom.","Sí. Cada vivienda incluye plaza de aparcamiento y trastero.",
 "Oui. Chaque logement comprend une place de parking et un débarras.","Ja. Zu jeder Wohnung gehören ein Stellplatz und ein Abstellraum.",
 "Да. К каждой квартире прилагаются парковочное место и кладовая.","نعم. كل منزل يشمل موقف سيارة ومخزناً.",
 "Ja. Bij elke woning horen een parkeerplaats en een berging.","Tak. Do każdego mieszkania należy miejsce postojowe i komórka lokatorska.",
 "Ja. Hver bolig har parkeringsplass og bod.","Ja. Varje bostad har parkeringsplats och förråd.")
a("A communal pool, landscaped gardens and a chill-out area, in a gated urbanisation.",
 "Piscina comunitaria, jardines y zona chill-out, en una urbanización cerrada.",
 "Une piscine commune, des jardins paysagers et un espace chill-out, dans une résidence fermée.",
 "Ein Gemeinschaftspool, angelegte Gärten und ein Chill-out-Bereich, in einer geschlossenen Wohnanlage.",
 "Общий бассейн, ландшафтные сады и зона chill-out в закрытом комплексе.",
 "مسبح مشترك وحدائق منسقة ومنطقة استرخاء، في مجمع سكني مغلق.",
 "Een gemeenschappelijk zwembad, aangelegde tuinen en een chill-outzone, in een besloten urbanisatie.",
 "Basen wspólny, urządzone ogrody i strefa chill-out na zamkniętym osiedlu.",
 "Et fellesbasseng, opparbeidede hager og et chill-out-område, i et lukket boligområde.",
 "En gemensam pool, anlagda trädgårdar och en chill out-yta, i ett slutet bostadsområde.")
a("I would like the current availability and prices for the Mijas Costa Bay Residences.",
 "Me gustaría recibir la disponibilidad y los precios actuales de Mijas Costa Bay Residences.",
 "Je souhaite recevoir la disponibilité et les prix actuels de Mijas Costa Bay Residences.",
 "Ich hätte gern die aktuelle Verfügbarkeit und die Preise für Mijas Costa Bay Residences.",
 "Хочу получить актуальное наличие и цены по Mijas Costa Bay Residences.",
 "أرغب في معرفة التوافر والأسعار الحالية لمشروع Mijas Costa Bay Residences.",
 "Ik ontvang graag de actuele beschikbaarheid en prijzen van Mijas Costa Bay Residences.",
 "Chciałbym otrzymać aktualną dostępność i ceny dla Mijas Costa Bay Residences.",
 "Jeg vil gjerne ha oppdatert tilgjengelighet og priser for Mijas Costa Bay Residences.",
 "Jag vill gärna ha aktuell tillgänglighet och priser för Mijas Costa Bay Residences.")
json.dump(T, open(sys.argv[1],'w'), ensure_ascii=False, indent=1); print(len(T))
