# -*- coding: utf-8 -*-
import json, sys
T={}
def a(en,es,fr,de,ru,ar,nl,pl,no,sv): T[en]={'es':es,'fr':fr,'de':de,'ru':ru,'ar':ar,'nl':nl,'pl':pl,'no':no,'sv':sv}

a("Prices are transcribed from the seller's own price list dated February 2026; which four homes remain was reconfirmed with the seller on 29 September 2026. Interior areas are the developer's figure from the floorplan of each home. Two entries are left blank rather than estimated: the seller has not issued a floorplan for apartment 30B, and the villa's floorplan states no areas. Prices exclude VAT at 10 per cent, stamp duty at 1.5 per cent, and notary and land registry fees.",
 "Los precios están transcritos de la lista del propio vendedor con fecha de febrero de 2026; qué cuatro viviendas quedan se volvió a confirmar con el vendedor el 29 de septiembre de 2026. Las superficies interiores son la cifra de la promotora que figura en el plano de cada vivienda. Dos casillas se dejan en blanco en lugar de estimarse: el vendedor no ha emitido plano del apartamento 30B y el plano de la villa no indica superficies. Los precios no incluyen el IVA del 10 %, el AJD del 1,5 % ni los gastos de notaría y registro.",
 "Les prix sont transcrits de la liste du vendeur datée de février 2026 ; les quatre logements restants ont été reconfirmés auprès du vendeur le 29 septembre 2026. Les surfaces intérieures sont le chiffre du promoteur figurant sur le plan de chaque logement. Deux cases sont laissées vides plutôt qu'estimées : le vendeur n'a pas émis de plan pour l'appartement 30B et le plan de la villa n'indique aucune surface. Les prix s'entendent hors TVA de 10 %, droits d'enregistrement de 1,5 % et frais de notaire et de publicité foncière.",
 "Die Preise sind der Preisliste des Verkäufers vom Februar 2026 entnommen; welche vier Wohnungen noch frei sind, wurde am 29. September 2026 mit dem Verkäufer erneut bestätigt. Die Innenflächen sind die Angabe des Bauträgers aus dem Grundriss der jeweiligen Wohnung. Zwei Felder bleiben leer statt geschätzt: Für Wohnung 30B hat der Verkäufer keinen Grundriss herausgegeben, und der Grundriss der Villa nennt keine Flächen. Die Preise verstehen sich ohne 10 % MwSt., 1,5 % Stempelsteuer sowie Notar- und Grundbuchkosten.",
 "Цены перенесены из прайс-листа продавца от февраля 2026 года; какие четыре дома остались, подтверждено у продавца 29 сентября 2026 года. Внутренние площади — цифра застройщика из плана каждой квартиры. Два поля оставлены пустыми, а не оценены: план квартиры 30B продавец не выпускал, а в плане виллы площади не указаны. Цены без НДС 10 %, гербового сбора 1,5 % и расходов на нотариуса и регистрацию.",
 "الأسعار منقولة عن قائمة أسعار البائع المؤرخة في فبراير 2026؛ وأُعيد تأكيد المساكن الأربعة المتبقية مع البائع في 29 سبتمبر 2026. المساحات الداخلية هي رقم المطور الوارد في مخطط كل مسكن. تُركت خانتان فارغتين بدل تقديرهما: لم يصدر البائع مخططاً للشقة 30B، ومخطط الفيلا لا يذكر أي مساحات. الأسعار لا تشمل ضريبة القيمة المضافة بنسبة 10 بالمائة ولا رسم الدمغة بنسبة 1.5 بالمائة ولا أتعاب التوثيق والسجل العقاري.",
 "De prijzen zijn overgenomen uit de eigen prijslijst van de verkoper van februari 2026; welke vier woningen resteren is op 29 september 2026 opnieuw bij de verkoper bevestigd. De binnenoppervlakken zijn het cijfer van de ontwikkelaar uit de plattegrond van elke woning. Twee velden blijven leeg in plaats van geschat: de verkoper heeft geen plattegrond uitgegeven voor appartement 30B, en de plattegrond van de villa vermeldt geen oppervlakken. De prijzen zijn exclusief 10 % btw, 1,5 % overdrachtsbelasting en notaris- en kadasterkosten.",
 "Ceny przepisano z listy cenowej sprzedającego z lutego 2026 roku; to, które cztery domy pozostały, potwierdzono u sprzedającego 29 września 2026 roku. Powierzchnie wewnętrzne to liczba dewelopera z rzutu każdego mieszkania. Dwa pola pozostawiono puste zamiast szacować: sprzedający nie wydał rzutu mieszkania 30B, a rzut willi nie podaje żadnych powierzchni. Ceny nie obejmują 10 % VAT, 1,5 % podatku od czynności ani opłat notarialnych i wieczystoksięgowych.",
 "Prisene er hentet fra selgerens egen prisliste datert februar 2026; hvilke fire boliger som er igjen, ble bekreftet på nytt med selgeren 29. september 2026. Innvendige arealer er utviklerens tall fra plantegningen til hver bolig. To felt står tomme i stedet for å bli anslått: selgeren har ikke utstedt plantegning for leilighet 30B, og villaens plantegning oppgir ingen arealer. Prisene er uten 10 % mva, 1,5 % dokumentavgift og notar- og tinglysingsgebyrer.",
 "Priserna är avskrivna från säljarens egen prislista daterad februari 2026; vilka fyra bostäder som återstår bekräftades på nytt med säljaren den 29 september 2026. Invändiga ytor är byggherrens siffra från respektive bostads planlösning. Två fält lämnas tomma i stället för att uppskattas: säljaren har inte utfärdat någon planlösning för lägenhet 30B, och villans planlösning anger inga ytor. Priserna är exklusive 10 % moms, 1,5 % stämpelskatt samt notarie- och registreringsavgifter.")

a("The building licence has been granted by Estepona council, which the developer confirmed in September 2026. Completion is given as the last quarter of 2027 into the first quarter of 2028. Nueva Living asks for the delivery date in writing and puts it in the contract.",
 "El Ayuntamiento de Estepona ha concedido la licencia de obra, según confirmó la promotora en septiembre de 2026. La entrega se indica entre el último trimestre de 2027 y el primero de 2028. Nueva Living pide la fecha de entrega por escrito y la incorpora al contrato.",
 "La mairie d'Estepona a accordé le permis de construire, ce que le promoteur a confirmé en septembre 2026. La livraison est annoncée du dernier trimestre 2027 au premier trimestre 2028. Nueva Living demande la date de livraison par écrit et la fait inscrire au contrat.",
 "Die Stadt Estepona hat die Baugenehmigung erteilt, was der Bauträger im September 2026 bestätigt hat. Die Fertigstellung wird vom letzten Quartal 2027 bis ins erste Quartal 2028 angegeben. Nueva Living verlangt den Liefertermin schriftlich und nimmt ihn in den Vertrag auf.",
 "Муниципалитет Эстепоны выдал разрешение на строительство, что застройщик подтвердил в сентябре 2026 года. Сдача указана с последнего квартала 2027 года по первый квартал 2028 года. Nueva Living запрашивает срок сдачи в письменном виде и вносит его в договор.",
 "منحت بلدية إستيبونا رخصة البناء، وهو ما أكده المطور في سبتمبر 2026. والتسليم محدد من الربع الأخير من 2027 إلى الربع الأول من 2028. تطلب Nueva Living تاريخ التسليم كتابةً وتدرجه في العقد.",
 "De gemeente Estepona heeft de bouwvergunning verleend, wat de ontwikkelaar in september 2026 bevestigde. De oplevering is opgegeven van het laatste kwartaal van 2027 tot in het eerste kwartaal van 2028. Nueva Living vraagt de opleverdatum schriftelijk op en laat die in het contract opnemen.",
 "Urząd miasta Estepona wydał pozwolenie na budowę, co deweloper potwierdził we wrześniu 2026 roku. Odbiór podano od ostatniego kwartału 2027 do pierwszego kwartału 2028 roku. Nueva Living prosi o datę odbioru na piśmie i wpisuje ją do umowy.",
 "Estepona kommune har gitt byggetillatelsen, noe utvikleren bekreftet i september 2026. Ferdigstilling er oppgitt fra siste kvartal 2027 inn i første kvartal 2028. Nueva Living ber om overleveringsdatoen skriftlig og fører den inn i kontrakten.",
 "Esteponas kommun har beviljat bygglovet, vilket byggherren bekräftade i september 2026. Färdigställandet anges från sista kvartalet 2027 in i första kvartalet 2028. Nueva Living begär överlämningsdatumet skriftligt och för in det i avtalet.")

a("Balance of the first stage","Resto de la primera fase","Solde de la première étape","Restbetrag der ersten Stufe","Остаток первого этапа","رصيد المرحلة الأولى","Restant van de eerste fase","Reszta pierwszego etapu","Resten av første trinn","Resten av första steget")
a("After 10 Months","A los 10 meses","Au bout de 10 mois","Nach 10 Monaten","Через 10 месяцев","بعد 10 أشهر","Na 10 maanden","Po 10 miesiącach","Etter 10 måneder","Efter 10 månader")
a("After 14 Months","A los 14 meses","Au bout de 14 mois","Nach 14 Monaten","Через 14 месяцев","بعد 14 شهراً","Na 14 maanden","Po 14 miesiącach","Etter 14 måneder","Efter 14 månader")
a("Fixed date, not a build milestone","Fecha fija, no un hito de obra","Date fixe, et non une étape de chantier","Fester Termin, kein Bauabschnitt","Фиксированная дата, а не этап строительства","تاريخ ثابت، وليس مرحلة بناء","Vaste datum, geen bouwmijlpaal","Stała data, a nie etap budowy","Fast dato, ikke en byggemilepæl","Fast datum, inte en byggetapp")

a("This is the developer's own schedule for this development, not a typical one: the two middle instalments fall on fixed dates rather than on build milestones. Nueva Living confirms it in the reservation agreement before you commit.",
 "Este es el calendario propio de la promotora para esta promoción, y no el habitual: los dos pagos intermedios vencen en fechas fijas y no según hitos de obra. Nueva Living lo confirma en el contrato de reserva antes de asumir compromiso alguno.",
 "Il s'agit de l'échéancier propre au promoteur pour ce programme, et non d'un échéancier habituel : les deux versements intermédiaires tombent à dates fixes et non selon l'avancement du chantier. Nueva Living le confirme dans le contrat de réservation avant tout engagement.",
 "Dies ist der eigene Zahlungsplan des Bauträgers für dieses Projekt, kein üblicher: Die beiden mittleren Raten fallen auf feste Termine und nicht auf Bauabschnitte. Nueva Living bestätigt ihn im Reservierungsvertrag vor jeder Bindung.",
 "Это собственный график застройщика для данного комплекса, а не типовой: два промежуточных платежа привязаны к фиксированным датам, а не к этапам строительства. Nueva Living подтверждает его в договоре бронирования до принятия обязательств.",
 "هذا جدول المطور الخاص بهذا المشروع، وليس جدولاً معتاداً: القسطان الأوسطان يستحقان في تواريخ ثابتة لا وفق مراحل البناء. تؤكده Nueva Living في اتفاقية الحجز قبل أي التزام.",
 "Dit is het eigen betalingsschema van de ontwikkelaar voor dit project, geen gebruikelijk schema: de twee middelste termijnen vallen op vaste data en niet op bouwmijlpalen. Nueva Living bevestigt het in de reserveringsovereenkomst voordat er verplichtingen ontstaan.",
 "To własny harmonogram dewelopera dla tej inwestycji, a nie typowy: dwie środkowe raty przypadają na stałe daty, a nie na etapy budowy. Nueva Living potwierdza go w umowie rezerwacyjnej przed podjęciem zobowiązań.",
 "Dette er utviklerens egen betalingsplan for dette prosjektet, ikke en vanlig en: de to midterste avdragene forfaller på faste datoer og ikke etter byggemilepæler. Nueva Living bekrefter den i reservasjonsavtalen før noen binding.",
 "Detta är byggherrens egen betalningsplan för det här projektet, inte en sedvanlig: de två mellersta delbetalningarna förfaller på fasta datum och inte efter byggetapper. Nueva Living bekräftar den i reservationsavtalet innan något åtagande.")

a("Genuine beachfront on this coast is close to finished, and this is one of the last schemes being built on it.",
 "La primera línea de playa auténtica en esta costa está prácticamente agotada, y esta es una de las últimas promociones que se construyen sobre ella.",
 "Le véritable front de mer sur cette côte est presque épuisé, et ce programme est l'un des derniers à y être construit.",
 "Echte erste Strandlinie ist an dieser Küste nahezu erschöpft, und dies ist eines der letzten Projekte, die darauf gebaut werden.",
 "Настоящая первая линия на этом побережье практически исчерпана, и это один из последних комплексов, которые на ней строятся.",
 "الواجهة البحرية الحقيقية على هذا الساحل شارفت على النفاد، وهذا من آخر المشاريع التي تُبنى عليها.",
 "Echte eerstelijns strandgrond aan deze kust is bijna op, en dit is een van de laatste projecten die erop worden gebouwd.",
 "Prawdziwa pierwsza linia brzegowa na tym wybrzeżu jest niemal wyczerpana, a to jedna z ostatnich inwestycji, które na niej powstają.",
 "Ekte strandlinje på denne kysten er nesten oppbrukt, og dette er et av de siste prosjektene som bygges på den.",
 "Äkta strandlinje på den här kusten är nästan slut, och det här är ett av de sista projekten som byggs på den.")

a("Buyers who want to step from the house onto the sand, and will not compromise on it.","Compradores que quieren salir de casa directamente a la arena y no transigen en ello.","Des acheteurs qui veulent passer de la maison au sable et n'y transigent pas.","Käufer, die vom Haus direkt in den Sand treten wollen und dabei keine Kompromisse machen.","Покупатели, которые хотят выходить из дома прямо на песок и не идут на компромисс.","مشترون يريدون الخروج من المنزل إلى الرمل مباشرة ولا يساومون على ذلك.","Kopers die vanuit huis zo het zand op willen stappen en daar niet op inleveren.","Nabywcy, którzy chcą wyjść z domu prosto na piasek i nie idą w tym na kompromis.","Kjøpere som vil gå rett fra huset ut på sanden, og ikke gir slipp på det.","Köpare som vill kliva från huset rakt ut på sanden och inte ger avkall på det.")
a("A true seafront plot of 33,346 sqm. Most of what is marketed as beachfront here is a road away from it.","Una parcela de 33.346 m² en primera línea real. Casi todo lo que aquí se comercializa como primera línea tiene una carretera de por medio.","Une parcelle de 33 346 m² véritablement en front de mer. La plupart de ce qui est commercialisé ici comme front de mer en est séparé par une route.","Ein echtes Strandgrundstück von 33.346 m². Das meiste, was hier als erste Strandlinie vermarktet wird, ist durch eine Straße davon getrennt.","Настоящий участок первой линии в 33 346 м². Большинство того, что здесь продаётся как первая линия, отделено дорогой.","قطعة أرض حقيقية على الواجهة البحرية بمساحة 33,346 م². معظم ما يُسوَّق هنا على أنه واجهة بحرية يفصله طريق عنها.","Een echt strandperceel van 33.346 m². Het meeste wat hier als eerstelijns wordt aangeboden, ligt een weg ervandaan.","Prawdziwa działka w pierwszej linii o powierzchni 33 346 m². Większość tego, co sprzedaje się tu jako pierwsza linia, oddziela droga.","En ekte strandtomt på 33 346 m². Det meste som markedsføres som strandlinje her, ligger en vei unna.","En äkta strandtomt om 33 346 m². Det mesta som marknadsförs som strandlinje här ligger en väg bort.")
a("Playa del Ángel sits between Estepona town and the New Golden Mile, with a sculpture park and the coastal path beside it.","Playa del Ángel se sitúa entre el casco de Estepona y la Nueva Milla de Oro, con un parque de esculturas y la senda litoral al lado.","Playa del Ángel se trouve entre le centre d'Estepona et la Nouvelle Mille d'Or, avec un parc de sculptures et le sentier littoral à côté.","Die Playa del Ángel liegt zwischen dem Ortskern von Estepona und der Neuen Goldenen Meile, mit einem Skulpturenpark und dem Küstenweg daneben.","Плая-дель-Анхель расположен между центром Эстепоны и Новой Золотой милей, рядом парк скульптур и прибрежная тропа.","تقع بلايا ديل أنخيل بين بلدة إستيبونا والميل الذهبي الجديد، وبجوارها حديقة منحوتات والممشى الساحلي.","Playa del Ángel ligt tussen het centrum van Estepona en de Nieuwe Gouden Mijl, met een beeldenpark en het kustpad ernaast.","Playa del Ángel leży między miastem Estepona a Nową Złotą Milą, obok park rzeźb i ścieżka nadmorska.","Playa del Ángel ligger mellom Estepona sentrum og Den nye gylne mil, med en skulpturpark og kyststien ved siden av.","Playa del Ángel ligger mellan Esteponas stadskärna och Nya Golden Mile, med en skulpturpark och kuststigen intill.")
a("Four of the 48 remain, and the last homes in a scheme move quickly.","Quedan cuatro de las 48, y las últimas viviendas de una promoción se venden rápido.","Il en reste quatre sur 48, et les derniers logements d'un programme partent vite.","Vier der 48 sind noch da, und die letzten Wohnungen einer Anlage gehen schnell.","Осталось четыре из 48, а последние дома в комплексе уходят быстро.","بقيت أربعة من أصل 48، وآخر المساكن في أي مشروع تُباع سريعاً.","Vier van de 48 zijn over, en de laatste woningen in een project gaan snel.","Zostały cztery z 48, a ostatnie domy w inwestycji schodzą szybko.","Fire av de 48 står igjen, og de siste boligene i et prosjekt går raskt.","Fyra av de 48 återstår, och de sista bostäderna i ett projekt går snabbt.")

a("The licence is granted","La licencia está concedida","Le permis est accordé","Die Baugenehmigung liegt vor","Разрешение получено","الرخصة ممنوحة","De vergunning is verleend","Pozwolenie jest wydane","Tillatelsen er gitt","Bygglovet är beviljat")
a("Building can proceed, and your payments sit behind a bank guarantee. Not every scheme at this price has reached that point.","Las obras pueden avanzar y los pagos quedan respaldados por un aval bancario. No todas las promociones de este precio han llegado a ese punto.","Les travaux peuvent avancer et les versements sont couverts par une garantie bancaire. Tous les programmes à ce prix n'en sont pas là.","Der Bau kann fortschreiten, und die Zahlungen sind durch eine Bankbürgschaft gesichert. Nicht jedes Projekt dieser Preisklasse ist so weit.","Строительство может идти, а платежи обеспечены банковской гарантией. Не каждый комплекс в этой цене дошёл до этой точки.","يمكن أن يمضي البناء، ومدفوعاتك مغطاة بضمان مصرفي. ليست كل المشاريع في هذا السعر بلغت هذه المرحلة.","De bouw kan doorgaan en de betalingen zijn gedekt door een bankgarantie. Niet elk project in deze prijsklasse is zover.","Budowa może postępować, a wpłaty są zabezpieczone gwarancją bankową. Nie każda inwestycja w tej cenie doszła do tego etapu.","Byggingen kan fortsette, og innbetalingene er dekket av en bankgaranti. Ikke alle prosjekter i denne prisklassen er kommet dit.","Bygget kan fortsätta och betalningarna täcks av en bankgaranti. Alla projekt i den här prisklassen har inte kommit dit.")
a("The land is the asset","El activo es el suelo","Le terrain est l'actif","Der Wert liegt im Grundstück","Актив — это земля","الأرض هي الأصل","De grond is het bezit","Aktywem jest grunt","Tomten er verdien","Marken är tillgången")
a("Beachfront plots of this size are not being released again on this stretch. The building can be improved; the position cannot.","En este tramo no van a salir más parcelas de este tamaño en primera línea. El edificio se puede mejorar; la ubicación no.","Des parcelles de cette taille en front de mer ne reviendront pas sur ce tronçon. Le bâtiment peut être amélioré ; l'emplacement non.","Strandgrundstücke dieser Größe werden auf diesem Abschnitt nicht wieder frei. Das Gebäude lässt sich verbessern, die Lage nicht.","Участков такого размера на первой линии на этом отрезке больше не появится. Здание можно улучшить, положение — нет.","لن تُطرح قطع أرض بهذا الحجم على الواجهة البحرية في هذا الامتداد مجدداً. المبنى يمكن تحسينه؛ الموقع لا.","Strandpercelen van deze omvang komen op dit stuk niet opnieuw vrij. Het gebouw kan beter worden gemaakt; de ligging niet.","Działki tej wielkości w pierwszej linii nie pojawią się już na tym odcinku. Budynek można ulepszyć; położenia nie.","Strandtomter av denne størrelsen slippes ikke igjen på denne strekningen. Bygget kan forbedres; beliggenheten kan ikke.","Strandtomter av den här storleken släpps inte igen på den här sträckan. Byggnaden går att förbättra; läget gör det inte.")
a("The payment dates are fixed","Las fechas de pago son fijas","Les dates de paiement sont fixes","Die Zahlungstermine sind fest","Даты платежей фиксированы","تواريخ الدفع ثابتة","De betaaldata liggen vast","Terminy płatności są stałe","Betalingsdatoene er faste","Betalningsdatumen är fasta")
a("Two instalments fall at 10 and 14 months whatever the site has done by then. Worth planning cash around.","Dos pagos vencen a los 10 y 14 meses con independencia de cómo vaya la obra. Conviene planificar la liquidez en consecuencia.","Deux versements tombent à 10 et 14 mois quel que soit l'état du chantier. À intégrer dans votre plan de trésorerie.","Zwei Raten werden nach 10 und 14 Monaten fällig, unabhängig vom Baufortschritt. Das gehört in die Liquiditätsplanung.","Два платежа приходятся на 10-й и 14-й месяц независимо от хода стройки. Это стоит учесть в планировании средств.","قسطان يستحقان عند 10 و14 شهراً مهما بلغ تقدم الموقع. يستحسن التخطيط للسيولة على هذا الأساس.","Twee termijnen vervallen na 10 en 14 maanden, ongeacht hoever de bouw dan is. Verstandig om de liquiditeit daarop af te stemmen.","Dwie raty przypadają po 10 i 14 miesiącach niezależnie od postępu budowy. Warto zaplanować pod to płynność.","To avdrag forfaller etter 10 og 14 måneder uansett hvor langt byggingen er kommet. Verdt å planlegge likviditeten etter.","Två delbetalningar förfaller vid 10 och 14 månader oavsett hur långt bygget har kommit. Värt att planera likviditeten efter.")
a("Add the purchase costs","Suma los gastos de compra","Ajoutez les frais d'acquisition","Kaufnebenkosten hinzurechnen","Прибавьте расходы на покупку","أضف تكاليف الشراء","Tel de aankoopkosten erbij","Doliczyć koszty zakupu","Legg til kjøpsomkostningene","Lägg till köpkostnaderna")
a("VAT at 10 per cent and stamp duty at 1.5 per cent sit on top, which on the villa is over EUR 1.4 million.","El IVA del 10 % y el AJD del 1,5 % se suman aparte, lo que en la villa supone más de 1,4 millones de euros.","La TVA de 10 % et les droits d'enregistrement de 1,5 % s'ajoutent, soit plus de 1,4 million d'euros pour la villa.","Hinzu kommen 10 Prozent MwSt. und 1,5 Prozent Stempelsteuer, bei der Villa also über 1,4 Millionen Euro.","Сверху идут НДС 10 процентов и гербовый сбор 1,5 процента — на вилле это более 1,4 миллиона евро.","تُضاف ضريبة القيمة المضافة بنسبة 10 بالمائة ورسم الدمغة بنسبة 1.5 بالمائة، وهو ما يتجاوز 1.4 مليون يورو على الفيلا.","Daarbovenop komen 10 procent btw en 1,5 procent overdrachtsbelasting, wat op de villa meer dan 1,4 miljoen euro is.","Do tego dochodzi 10 procent VAT i 1,5 procent podatku, co przy willi daje ponad 1,4 miliona euro.","I tillegg kommer 10 prosent mva og 1,5 prosent dokumentavgift, som på villaen er over 1,4 millioner euro.","Utöver det tillkommer 10 procent moms och 1,5 procent stämpelskatt, vilket på villan är över 1,4 miljoner euro.")

a("That the building licence is granted before any money moves. For this scheme it is.","Que la licencia de obra esté concedida antes de que se mueva un euro. En esta promoción lo está.","Que le permis de construire soit accordé avant tout versement. Pour ce programme, il l'est.","Dass die Baugenehmigung vorliegt, bevor Geld fließt. Bei dieser Anlage liegt sie vor.","Что разрешение на строительство получено до любых платежей. У этого комплекса оно есть.","أن تكون رخصة البناء ممنوحة قبل تحريك أي أموال. وهي كذلك في هذا المشروع.","Dat de bouwvergunning is verleend voordat er geld wordt overgemaakt. Bij dit project is dat zo.","Że pozwolenie na budowę jest wydane, zanim ruszą pieniądze. W tej inwestycji jest.","At byggetillatelsen er gitt før penger flyttes. For dette prosjektet er den det.","Att bygglovet är beviljat innan några pengar rör sig. För det här projektet är det beviljat.")

a("Low white volumes on <em>the shoreline</em>","Volúmenes blancos y bajos en <em>la orilla</em>","Des volumes blancs et bas sur <em>le rivage</em>","Niedrige weiße Baukörper an <em>der Uferlinie</em>","Низкие белые объёмы на <em>берегу</em>","أحجام بيضاء منخفضة على <em>خط الشاطئ</em>","Lage witte volumes aan <em>de waterlijn</em>","Niskie białe bryły na <em>linii brzegowej</em>","Lave hvite volumer i <em>strandkanten</em>","Låga vita volymer i <em>strandkanten</em>")
a("Six villas along the sand, then five three-storey buildings set back behind a central plaza and its gardens.","Seis villas junto a la arena y, detrás, cinco edificios de tres plantas retranqueados tras una plaza central y sus jardines.","Six villas le long du sable, puis cinq immeubles de trois étages en retrait derrière une place centrale et ses jardins.","Sechs Villen am Sand, dahinter fünf dreigeschossige Gebäude, zurückgesetzt hinter einem zentralen Platz und seinen Gärten.","Шесть вилл у самого песка, а за ними пять трёхэтажных зданий, отступивших за центральную площадь с садами.","ست فيلات على امتداد الرمل، ثم خمسة مبانٍ من ثلاثة طوابق متراجعة خلف ساحة مركزية وحدائقها.","Zes villa's langs het zand, daarachter vijf gebouwen van drie lagen, terugliggend achter een centraal plein en zijn tuinen.","Sześć willi wzdłuż piasku, a za nimi pięć trzykondygnacyjnych budynków cofniętych za centralny plac i jego ogrody.","Seks villaer langs sanden, deretter fem bygninger i tre etasjer trukket tilbake bak en sentral plass og hagene.","Sex villor längs sanden, och bakom dem fem trevåningshus indragna bakom ett centralt torg och dess trädgårdar.")
a("The blocks are raised enough to see over the villas, so the sea is in view from every home.","Los bloques se elevan lo suficiente para ver por encima de las villas, de modo que hay vistas al mar desde todas las viviendas.","Les immeubles sont suffisamment surélevés pour voir par-dessus les villas, si bien que la mer est visible de chaque logement.","Die Baukörper sind hoch genug, um über die Villen hinwegzusehen, sodass von jeder Wohnung das Meer zu sehen ist.","Корпуса подняты настолько, чтобы видеть поверх вилл, поэтому море видно из каждой квартиры.","المباني مرتفعة بما يكفي للرؤية فوق الفيلات، فيظهر البحر من كل مسكن.","De blokken zijn hoog genoeg om over de villa's heen te kijken, zodat de zee vanuit elke woning zichtbaar is.","Budynki są na tyle wyniesione, by patrzeć ponad willami, więc morze widać z każdego mieszkania.","Bygningene er hevet nok til å se over villaene, slik at sjøen er synlig fra hver bolig.","Huskropparna är tillräckligt höjda för att se över villorna, så havet syns från varje bostad.")
a("33,346 sqm of genuine beachfront.","33.346 m² de primera línea de playa auténtica.","33 346 m² de véritable front de mer.","33.346 m² echte erste Strandlinie.","33 346 м² настоящей первой линии.","33,346 م² من واجهة بحرية حقيقية.","33.346 m² echte eerstelijns strandgrond.","33 346 m² prawdziwej pierwszej linii brzegowej.","33 346 m² ekte strandlinje.","33 346 m² äkta strandlinje.")
a("Every home turned to the Mediterranean.","Todas las viviendas orientadas al Mediterráneo.","Chaque logement tourné vers la Méditerranée.","Jede Wohnung zum Mittelmeer ausgerichtet.","Каждая квартира обращена к Средиземному морю.","كل مسكن موجّه نحو البحر المتوسط.","Elke woning gericht op de Middellandse Zee.","Każde mieszkanie zwrócone ku Morzu Śródziemnemu.","Hver bolig vendt mot Middelhavet.","Varje bostad vänd mot Medelhavet.")
a("All vehicle circulation underground.","Toda la circulación de vehículos, subterránea.","Toute la circulation des véhicules en sous-sol.","Der gesamte Fahrzeugverkehr unterirdisch.","Всё движение автомобилей под землёй.","حركة السيارات كلها تحت الأرض.","Al het autoverkeer ondergronds.","Cały ruch samochodowy pod ziemią.","All bilkjøring under bakken.","All biltrafik under mark.")
a("Bioclimatic, with native planting through the gardens.","Diseño bioclimático, con vegetación autóctona en los jardines.","Conception bioclimatique, avec une végétation indigène dans les jardins.","Bioklimatisch, mit heimischer Bepflanzung in den Gärten.","Биоклиматический подход и местная растительность в садах.","تصميم مناخي حيوي، بنباتات محلية في الحدائق.","Bioklimatisch, met inheemse beplanting in de tuinen.","Bioklimatyczny, z rodzimą roślinnością w ogrodach.","Bioklimatisk, med stedegen beplantning i hagene.","Bioklimatisk, med inhemsk växtlighet i trädgårdarna.")

a("The sea, <em>and everything behind it</em>","El mar, <em>y todo lo que hay detrás</em>","La mer, <em>et tout ce qui se trouve derrière</em>","Das Meer, <em>und alles dahinter</em>","Море, <em>и всё, что за ним</em>","البحر، <em>وكل ما وراءه</em>","De zee, <em>en alles daarachter</em>","Morze <em>i wszystko za nim</em>","Sjøen, <em>og alt bak den</em>","Havet, <em>och allt bakom det</em>")
a("A spa, a gym and a padel court around the central plaza, with the coastal path and a beach club at the gate.","Spa, gimnasio y pista de pádel alrededor de la plaza central, con la senda litoral y un beach club en la puerta.","Un spa, une salle de sport et un terrain de padel autour de la place centrale, avec le sentier littoral et un beach club à la porte.","Spa, Fitnessraum und Padelplatz rund um den zentralen Platz, mit dem Küstenweg und einem Beach Club vor dem Tor.","Спа, спортзал и падел-корт вокруг центральной площади, у ворот — прибрежная тропа и бич-клуб.","سبا وصالة رياضة وملعب بادل حول الساحة المركزية، والممشى الساحلي ونادٍ شاطئي عند البوابة.","Een spa, een fitnessruimte en een padelbaan rond het centrale plein, met het kustpad en een beachclub voor de poort.","Spa, siłownia i kort do padla wokół centralnego placu, a przy bramie ścieżka nadmorska i beach club.","Spa, treningsrom og padelbane rundt den sentrale plassen, med kyststien og en strandklubb ved porten.","Spa, gym och padelbana kring det centrala torget, med kuststigen och en strandklubb vid grinden.")
a("A heated 155 sqm pool under a skylight, with sauna, hammam, jacuzzi and treatment rooms.","Una piscina climatizada de 155 m² bajo un lucernario, con sauna, hammam, jacuzzi y cabinas de tratamiento.","Une piscine chauffée de 155 m² sous une verrière, avec sauna, hammam, jacuzzi et cabines de soins.","Ein beheiztes 155-m²-Becken unter einem Oberlicht, mit Sauna, Hammam, Whirlpool und Behandlungsräumen.","Подогреваемый бассейн 155 м² под световым фонарём, с сауной, хаммамом, джакузи и процедурными кабинетами.","مسبح مُدفأ بمساحة 155 م² تحت كوّة سقفية، مع ساونا وحمّام وجاكوزي وغرف علاج.","Een verwarmd bad van 155 m² onder een daklicht, met sauna, hammam, jacuzzi en behandelruimtes.","Podgrzewany basen o powierzchni 155 m² pod świetlikiem, z sauną, hammamem, jacuzzi i gabinetami zabiegowymi.","Et oppvarmet basseng på 155 m² under et takvindu, med badstue, hammam, boblebad og behandlingsrom.","En uppvärmd pool om 155 m² under ett takfönster, med bastu, hammam, jacuzzi och behandlingsrum.")
a("The pools","Las piscinas","Les piscines","Die Pools","Бассейны","المسابح","De zwembaden","Baseny","Bassengene","Poolerna")
a("An outdoor pool for adults and a separate children's pool in the seaside gardens.","Una piscina exterior para adultos y una piscina infantil aparte en los jardines junto al mar.","Une piscine extérieure pour adultes et une pataugeoire séparée dans les jardins en bord de mer.","Ein Außenpool für Erwachsene und ein separates Kinderbecken in den Gärten am Meer.","Открытый бассейн для взрослых и отдельный детский бассейн в приморских садах.","مسبح خارجي للبالغين ومسبح منفصل للأطفال في الحدائق المطلّة على البحر.","Een buitenzwembad voor volwassenen en een apart kinderbad in de tuinen aan zee.","Basen zewnętrzny dla dorosłych i osobny basen dla dzieci w ogrodach nad morzem.","Et utendørsbasseng for voksne og et eget barnebasseng i hagene ved sjøen.","En utomhuspool för vuxna och en separat barnpool i trädgårdarna vid havet.")
a("A padel court and a fully equipped gym looking onto the gardens.","Una pista de pádel y un gimnasio totalmente equipado con vistas a los jardines.","Un terrain de padel et une salle de sport entièrement équipée donnant sur les jardins.","Ein Padelplatz und ein voll ausgestatteter Fitnessraum mit Blick in die Gärten.","Падел-корт и полностью оснащённый спортзал с видом на сады.","ملعب بادل وصالة رياضة كاملة التجهيز تطلّ على الحدائق.","Een padelbaan en een volledig uitgeruste fitnessruimte met zicht op de tuinen.","Kort do padla i w pełni wyposażona siłownia z widokiem na ogrody.","En padelbane og et fullt utstyrt treningsrom med utsikt mot hagene.","En padelbana och ett fullt utrustat gym med utsikt mot trädgårdarna.")

a("The seller's own list, with the homes that remain.","La lista del propio vendedor, con las viviendas que quedan.","La liste du vendeur lui-même, avec les logements restants.","Die Liste des Verkäufers selbst, mit den noch freien Wohnungen.","Собственный список продавца с оставшимися домами.","قائمة البائع نفسه، بالمساكن المتبقية.","De eigen lijst van de verkoper, met de resterende woningen.","Własna lista sprzedającego z pozostałymi domami.","Selgerens egen liste, med boligene som er igjen.","Säljarens egen lista, med de bostäder som återstår.")
a("Per home, where the seller has issued one.","Por vivienda, cuando el vendedor ha emitido uno.","Par logement, lorsque le vendeur en a émis un.","Je Wohnung, sofern der Verkäufer einen herausgegeben hat.","По каждой квартире, если продавец его выпустил.","لكل مسكن، حيثما أصدر البائع مخططاً.","Per woning, waar de verkoper er een heeft uitgegeven.","Dla każdego mieszkania, o ile sprzedający go wydał.","Per bolig, der selgeren har utstedt en.","Per bostad, där säljaren har utfärdat en.")
a("The developer's instalment plan in full.","El plan de pagos completo de la promotora.","L'échéancier complet du promoteur.","Der vollständige Zahlungsplan des Bauträgers.","Полный график платежей застройщика.","خطة أقساط المطور كاملةً.","Het volledige betalingsschema van de ontwikkelaar.","Pełny harmonogram płatności dewelopera.","Utviklerens fullstendige betalingsplan.","Byggherrens fullständiga betalningsplan.")

a("The two unpriced figures","Las dos cifras que faltan","Les deux chiffres manquants","Die beiden fehlenden Angaben","Две недостающие цифры","الرقمان الناقصان","De twee ontbrekende cijfers","Dwie brakujące liczby","De to manglende tallene","De två saknade siffrorna")
a("The areas for apartment 30B and the villa, which the seller has not put in writing.","Las superficies del apartamento 30B y de la villa, que el vendedor no ha puesto por escrito.","Les surfaces de l'appartement 30B et de la villa, que le vendeur n'a pas mises par écrit.","Die Flächen von Wohnung 30B und der Villa, die der Verkäufer nicht schriftlich angegeben hat.","Площади квартиры 30B и виллы, которые продавец не указал письменно.","مساحات الشقة 30B والفيلا، التي لم يوثقها البائع كتابةً.","De oppervlakken van appartement 30B en de villa, die de verkoper niet op schrift heeft gesteld.","Powierzchnie mieszkania 30B i willi, których sprzedający nie podał na piśmie.","Arealene for leilighet 30B og villaen, som selgeren ikke har gitt skriftlig.","Ytorna för lägenhet 30B och villan, som säljaren inte har lämnat skriftligt.")
a("The beach itself","La playa misma","La plage elle-même","Der Strand selbst","Сам пляж","الشاطئ نفسه","Het strand zelf","Sama plaża","Selve stranden","Själva stranden")
a("How the plot meets the sand, and what sits either side of it.","Cómo llega la parcela a la arena y qué hay a uno y otro lado.","Comment la parcelle rejoint le sable, et ce qui se trouve de part et d'autre.","Wie das Grundstück an den Sand grenzt und was zu beiden Seiten liegt.","Как участок выходит к песку и что находится по обе стороны.","كيف تلتقي قطعة الأرض بالرمل، وما الذي يقع على جانبيها.","Hoe het perceel aan het zand grenst, en wat er aan weerszijden ligt.","Jak działka styka się z piaskiem i co znajduje się po obu jej stronach.","Hvordan tomten møter sanden, og hva som ligger på hver side.","Hur tomten möter sanden, och vad som ligger på var sida.")
a("The community fee on a scheme with a spa, a gym and a padel court to run.","La cuota de comunidad en una promoción que tiene que mantener spa, gimnasio y pista de pádel.","Les charges de copropriété dans un programme qui doit faire fonctionner un spa, une salle de sport et un terrain de padel.","Das Hausgeld in einer Anlage, die Spa, Fitnessraum und Padelplatz unterhalten muss.","Взносы в сообщество в комплексе, которому нужно содержать спа, спортзал и падел-корт.","رسم المجمّع في مشروع عليه تشغيل سبا وصالة رياضة وملعب بادل.","De servicekosten in een project dat een spa, een fitnessruimte en een padelbaan moet onderhouden.","Opłata wspólnotowa w inwestycji, która musi utrzymać spa, siłownię i kort do padla.","Fellesutgiftene i et prosjekt som skal drifte spa, treningsrom og padelbane.","Samfällighetsavgiften i ett projekt som ska driva spa, gym och padelbana.")

a("Playa del Ángel, <em>on the sand</em>","Playa del Ángel, <em>sobre la arena</em>","Playa del Ángel, <em>sur le sable</em>","Playa del Ángel, <em>am Sand</em>","Плая-дель-Анхель, <em>на песке</em>","بلايا ديل أنخيل، <em>على الرمل</em>","Playa del Ángel, <em>op het zand</em>","Playa del Ángel, <em>na piasku</em>","Playa del Ángel, <em>på sanden</em>","Playa del Ángel, <em>på sanden</em>")
a("A gated beachfront scheme between Estepona town and the New Golden Mile, with the coastal path and a sculpture park alongside it.","Una promoción cerrada en primera línea de playa entre el casco de Estepona y la Nueva Milla de Oro, con la senda litoral y un parque de esculturas al lado.","Un programme fermé en front de mer entre le centre d'Estepona et la Nouvelle Mille d'Or, avec le sentier littoral et un parc de sculptures à côté.","Eine geschlossene Anlage in erster Strandlinie zwischen dem Ortskern von Estepona und der Neuen Goldenen Meile, mit dem Küstenweg und einem Skulpturenpark daneben.","Закрытый комплекс на первой линии между центром Эстепоны и Новой Золотой милей, рядом прибрежная тропа и парк скульптур.","مجمّع مغلق على الواجهة البحرية بين بلدة إستيبونا والميل الذهبي الجديد، وبجواره الممشى الساحلي وحديقة منحوتات.","Een gesloten project aan het strand tussen het centrum van Estepona en de Nieuwe Gouden Mijl, met het kustpad en een beeldenpark ernaast.","Zamknięta inwestycja w pierwszej linii brzegowej między miastem Estepona a Nową Złotą Milą, obok ścieżka nadmorska i park rzeźb.","Et portert prosjekt i strandkanten mellom Estepona sentrum og Den nye gylne mil, med kyststien og en skulpturpark ved siden av.","Ett grindat projekt i strandkanten mellan Esteponas stadskärna och Nya Golden Mile, med kuststigen och en skulpturpark intill.")

a("Four of the 48 homes: three apartments and one of the six seafront villas.","Cuatro de las 48 viviendas: tres apartamentos y una de las seis villas frente al mar.","Quatre des 48 logements : trois appartements et l'une des six villas face à la mer.","Vier der 48 Wohnungen: drei Wohnungen und eine der sechs Villen am Meer.","Четыре из 48 домов: три квартиры и одна из шести вилл у моря.","أربعة من أصل 48 مسكناً: ثلاث شقق وواحدة من الفيلات الست المطلّة على البحر.","Vier van de 48 woningen: drie appartementen en een van de zes villa's aan zee.","Cztery z 48 domów: trzy mieszkania i jedna z sześciu willi nad morzem.","Fire av de 48 boligene: tre leiligheter og en av de seks villaene ved sjøen.","Fyra av de 48 bostäderna: tre lägenheter och en av de sex villorna vid havet.")
a("From EUR 3,500,000 for an apartment to EUR 12,750,000 for the villa, excluding VAT and the other purchase costs.","Desde 3.500.000 € un apartamento hasta 12.750.000 € la villa, sin incluir el IVA ni los demás gastos de compra.","De 3 500 000 € pour un appartement à 12 750 000 € pour la villa, hors TVA et autres frais d'acquisition.","Von 3.500.000 € für eine Wohnung bis 12.750.000 € für die Villa, ohne MwSt. und die übrigen Kaufnebenkosten.","От 3 500 000 € за квартиру до 12 750 000 € за виллу, без НДС и прочих расходов на покупку.","من 3,500,000 € للشقة إلى 12,750,000 € للفيلا، دون ضريبة القيمة المضافة وسائر تكاليف الشراء.","Van € 3.500.000 voor een appartement tot € 12.750.000 voor de villa, exclusief btw en de overige aankoopkosten.","Od 3 500 000 € za mieszkanie do 12 750 000 € za willę, bez VAT i pozostałych kosztów zakupu.","Fra 3 500 000 € for en leilighet til 12 750 000 € for villaen, uten mva og de øvrige kjøpsomkostningene.","Från 3 500 000 € för en lägenhet till 12 750 000 € för villan, exklusive moms och övriga köpkostnader.")
a("The two apartments with published floorplans are 211.46 and 295.00 sqm of interior area. The seller has not issued figures for the other two homes.","Los dos apartamentos con plano publicado tienen 211,46 y 295,00 m² de superficie interior. El vendedor no ha facilitado cifras de las otras dos viviendas.","Les deux appartements dont le plan est publié font 211,46 et 295,00 m² de surface intérieure. Le vendeur n'a pas communiqué de chiffres pour les deux autres logements.","Die beiden Wohnungen mit veröffentlichtem Grundriss haben 211,46 und 295,00 m² Innenfläche. Für die anderen beiden Wohnungen hat der Verkäufer keine Angaben gemacht.","Две квартиры с опубликованными планами имеют 211,46 и 295,00 м² внутренней площади. По двум другим домам продавец цифр не предоставил.","الشقتان اللتان نُشر مخططهما تبلغان 211.46 و295.00 م² من المساحة الداخلية. ولم يصدر البائع أرقاماً للمسكنين الآخرين.","De twee appartementen met gepubliceerde plattegrond meten 211,46 en 295,00 m² binnenoppervlak. Voor de andere twee woningen heeft de verkoper geen cijfers verstrekt.","Dwa mieszkania z opublikowanymi rzutami mają 211,46 i 295,00 m² powierzchni wewnętrznej. Dla pozostałych dwóch domów sprzedający nie podał danych.","De to leilighetene med publisert plantegning er på 211,46 og 295,00 m² innvendig areal. For de to andre boligene har selgeren ikke oppgitt tall.","De två lägenheterna med publicerad planlösning är 211,46 och 295,00 m² invändig yta. För de två andra bostäderna har säljaren inte lämnat några siffror.")
a("Completion is given as the last quarter of 2027 into the first quarter of 2028.","La entrega se indica entre el último trimestre de 2027 y el primero de 2028.","La livraison est annoncée du dernier trimestre 2027 au premier trimestre 2028.","Die Fertigstellung wird vom letzten Quartal 2027 bis ins erste Quartal 2028 angegeben.","Сдача указана с последнего квартала 2027 года по первый квартал 2028 года.","التسليم محدد من الربع الأخير من 2027 إلى الربع الأول من 2028.","De oplevering is opgegeven van het laatste kwartaal van 2027 tot in het eerste kwartaal van 2028.","Odbiór podano od ostatniego kwartału 2027 do pierwszego kwartału 2028 roku.","Ferdigstilling er oppgitt fra siste kvartal 2027 inn i første kvartal 2028.","Färdigställandet anges från sista kvartalet 2027 in i första kvartalet 2028.")
a("Has the licence been granted?","¿Está concedida la licencia?","Le permis a-t-il été accordé ?","Liegt die Baugenehmigung vor?","Получено ли разрешение на строительство?","هل مُنحت الرخصة؟","Is de vergunning verleend?","Czy pozwolenie zostało wydane?","Er byggetillatelsen gitt?","Är bygglovet beviljat?")
a("Yes. The developer confirmed in September 2026 that Estepona council has granted the building licence.","Sí. La promotora confirmó en septiembre de 2026 que el Ayuntamiento de Estepona ha concedido la licencia de obra.","Oui. Le promoteur a confirmé en septembre 2026 que la mairie d'Estepona a accordé le permis de construire.","Ja. Der Bauträger hat im September 2026 bestätigt, dass die Stadt Estepona die Baugenehmigung erteilt hat.","Да. Застройщик подтвердил в сентябре 2026 года, что муниципалитет Эстепоны выдал разрешение на строительство.","نعم. أكد المطور في سبتمبر 2026 أن بلدية إستيبونا منحت رخصة البناء.","Ja. De ontwikkelaar bevestigde in september 2026 dat de gemeente Estepona de bouwvergunning heeft verleend.","Tak. Deweloper potwierdził we wrześniu 2026 roku, że urząd miasta Estepona wydał pozwolenie na budowę.","Ja. Utvikleren bekreftet i september 2026 at Estepona kommune har gitt byggetillatelsen.","Ja. Byggherren bekräftade i september 2026 att Esteponas kommun har beviljat bygglovet.")
a("How are payments staged?","¿Cómo se escalonan los pagos?","Comment les paiements sont-ils échelonnés ?","Wie sind die Zahlungen gestaffelt?","Как распределены платежи?","كيف تُوزَّع الدفعات؟","Hoe zijn de betalingen gespreid?","Jak rozłożone są płatności?","Hvordan er betalingene fordelt?","Hur är betalningarna fördelade?")
a("EUR 100,000 on reservation, 25 per cent on contract, 12.5 per cent at 10 months, 12.5 per cent at 14 months and 50 per cent on completion.","100.000 € en la reserva, 25 % en el contrato, 12,5 % a los 10 meses, 12,5 % a los 14 meses y 50 % en la entrega.","100 000 € à la réservation, 25 % au contrat, 12,5 % à 10 mois, 12,5 % à 14 mois et 50 % à la livraison.","100.000 € bei Reservierung, 25 % bei Vertragsschluss, 12,5 % nach 10 Monaten, 12,5 % nach 14 Monaten und 50 % bei Übergabe.","100 000 € при бронировании, 25 % при подписании договора, 12,5 % через 10 месяцев, 12,5 % через 14 месяцев и 50 % при передаче.","100,000 € عند الحجز، و25 بالمائة عند التعاقد، و12.5 بالمائة عند 10 أشهر، و12.5 بالمائة عند 14 شهراً، و50 بالمائة عند التسليم.","€ 100.000 bij reservering, 25 % bij contract, 12,5 % na 10 maanden, 12,5 % na 14 maanden en 50 % bij oplevering.","100 000 € przy rezerwacji, 25 % przy umowie, 12,5 % po 10 miesiącach, 12,5 % po 14 miesiącach i 50 % przy odbiorze.","100 000 € ved reservasjon, 25 % ved kontrakt, 12,5 % etter 10 måneder, 12,5 % etter 14 måneder og 50 % ved overlevering.","100 000 € vid reservation, 25 % vid avtal, 12,5 % efter 10 månader, 12,5 % efter 14 månader och 50 % vid tillträde.")
a("A spa with a heated pool, sauna and hammam, an outdoor pool, a children's pool, a gym, a padel court and a children's play area.","Un spa con piscina climatizada, sauna y hammam, una piscina exterior, una piscina infantil, un gimnasio, una pista de pádel y una zona de juegos infantil.","Un spa avec piscine chauffée, sauna et hammam, une piscine extérieure, une pataugeoire, une salle de sport, un terrain de padel et une aire de jeux.","Ein Spa mit beheiztem Pool, Sauna und Hammam, ein Außenpool, ein Kinderbecken, ein Fitnessraum, ein Padelplatz und ein Kinderspielplatz.","Спа с подогреваемым бассейном, сауной и хаммамом, открытый бассейн, детский бассейн, спортзал, падел-корт и детская площадка.","سبا بمسبح مُدفأ وساونا وحمّام، ومسبح خارجي، ومسبح للأطفال، وصالة رياضة، وملعب بادل، وملعب أطفال.","Een spa met verwarmd zwembad, sauna en hammam, een buitenzwembad, een kinderbad, een fitnessruimte, een padelbaan en een speeltuin.","Spa z podgrzewanym basenem, sauną i hammamem, basen zewnętrzny, basen dla dzieci, siłownia, kort do padla i plac zabaw.","Et spa med oppvarmet basseng, badstue og hammam, et utendørsbasseng, et barnebasseng, et treningsrom, en padelbane og en lekeplass.","Ett spa med uppvärmd pool, bastu och hammam, en utomhuspool, en barnpool, ett gym, en padelbana och en lekplats.")
a("The price list, the floorplans and the payment schedule.","La lista de precios, los planos y el calendario de pagos.","La liste de prix, les plans et l'échéancier de paiement.","Die Preisliste, die Grundrisse und der Zahlungsplan.","Прайс-лист, планировки и график платежей.","قائمة الأسعار والمخططات وجدول الدفعات.","De prijslijst, de plattegronden en het betalingsschema.","Cennik, rzuty i harmonogram płatności.","Prislisten, plantegningene og betalingsplanen.","Prislistan, planlösningarna och betalningsplanen.")
a("I would like the current availability and prices for the Playa del Angel Residences.","Me gustaría recibir la disponibilidad y los precios actuales de Playa del Angel Residences.","Je souhaite recevoir les disponibilités et les prix actuels de Playa del Angel Residences.","Ich möchte die aktuelle Verfügbarkeit und die Preise von Playa del Angel Residences erhalten.","Хотелось бы получить текущее наличие и цены по Playa del Angel Residences.","أودّ الحصول على التوافر والأسعار الحالية لمشروع Playa del Angel Residences.","Ik ontvang graag de actuele beschikbaarheid en prijzen van Playa del Angel Residences.","Chciałbym otrzymać aktualną dostępność i ceny dla Playa del Angel Residences.","Jeg ønsker gjeldende tilgjengelighet og priser for Playa del Angel Residences.","Jag vill gärna få aktuell tillgänglighet och priser för Playa del Angel Residences.")
a("Final Release","Última fase","Dernière phase","Letzte Phase","Финальная очередь","المرحلة الأخيرة","Laatste fase","Ostatni etap","Siste salgstrinn","Sista etappen")
json.dump(T, open(sys.argv[1],'w'), ensure_ascii=False, indent=1); print(len(T))
