// Translations for the two hand-authored ("bespoke") cinematic-viewer
// scene sets embedded directly in nueva-living-home.html:
// MARBELLA_WEST_GARDEN_VIEWING_SCENES and CANCELADA_PARK_VIEWING_SCENES.
//
// These sit OUTSIDE the NUEVA GENERATED VIEWING SCENES markers, and the
// viewer resolves BESPOKE_VIEWING_SCENES *before* PROJECT_VIEWING_SCENE_SETS
// -- so for these two projects the bespoke English text wins over the
// generated, already-translated scene data. Without these entries the
// cinematic viewer silently shows English on every locale homepage for
// Marbella West Garden Residences and Cancelada Park.
//
// Applied as literal find/replace (longest-first) alongside
// HOMEPAGE_CONTENT_ENTRIES in build_homepage_locales.mjs.
//
// Note: DEFAULT_VIEWING_SCENES in the same file is deliberately NOT
// translated -- it is unreachable in practice, since all 13 projects have
// generated scene sets, so the `|| DEFAULT_VIEWING_SCENES` fallback never
// resolves. Translating it would be dead weight.
export const BESPOKE_SCENE_ENTRIES = [
  // ===== Marbella West Garden Residences (20 scenes)
  { find: '01 — Marbella West', es: '01 — Marbella West', fr: '01 — Marbella West', de: '01 — Marbella West', ru: '01 — Марбелья-Уэст', ar: '01 — ماربيا الغربية' },
  { find: 'A new residential address<br>between coast and city.', es: 'Una nueva dirección residencial<br>entre la costa y la ciudad.', fr: 'Une nouvelle adresse résidentielle<br>entre la côte et la ville.', de: 'Eine neue Wohnadresse<br>zwischen Küste und Stadt.', ru: 'Новый жилой адрес<br>между побережьем и городом.', ar: 'عنوان سكني جديد<br>بين الساحل والمدينة.' },
  { find: 'The opening view introduces the curved, planted architecture of this 139-home community near San Pedro and Puerto Banus.', es: 'La vista inicial presenta la arquitectura curva y ajardinada de esta comunidad de 139 viviendas cerca de San Pedro y Puerto Banús.', fr: 'La vue d’ouverture présente l’architecture courbe et végétalisée de cette communauté de 139 logements près de San Pedro et Puerto Banús.', de: 'Die Eröffnungsansicht zeigt die geschwungene, begrünte Architektur dieser Wohnanlage mit 139 Einheiten nahe San Pedro und Puerto Banús.', ru: 'Первый кадр знакомит с изогнутой озеленённой архитектурой этого комплекса на 139 резиденций рядом с Сан-Педро и Пуэрто-Банусом.', ar: 'يقدّم المشهد الافتتاحي العمارة المنحنية المكسوة بالنباتات لهذا المجتمع المكوّن من 139 مسكنًا قرب سان بيدرو وبويرتو بانوس.' },

  { find: '02 — Architecture', es: '02 — Arquitectura', fr: '02 — Architecture', de: '02 — Architektur', ru: '02 — Архитектура', ar: '02 — العمارة' },
  { find: 'Rounded terraces,<br>softened by planting.', es: 'Terrazas redondeadas,<br>suavizadas por la vegetación.', fr: 'Terrasses arrondies,<br>adoucies par la végétation.', de: 'Abgerundete Terrassen,<br>aufgelockert durch Bepflanzung.', ru: 'Скруглённые террасы,<br>смягчённые озеленением.', ar: 'تراسات منحنية<br>تلطّفها المساحات الخضراء.' },
  { find: 'Huete Arquitectos combines broad glazing, layered terraces and integrated greenery in a warm Mediterranean material palette.', es: 'Huete Arquitectos combina amplios acristalamientos, terrazas escalonadas y vegetación integrada en una cálida paleta de materiales mediterránea.', fr: 'Huete Arquitectos associe de larges baies vitrées, des terrasses étagées et une végétation intégrée dans une palette de matériaux méditerranéenne chaleureuse.', de: 'Huete Arquitectos verbindet großflächige Verglasung, gestaffelte Terrassen und integriertes Grün in einer warmen mediterranen Materialpalette.', ru: 'Huete Arquitectos сочетает панорамное остекление, ярусные террасы и встроенное озеленение в тёплой средиземноморской палитре материалов.', ar: 'يجمع مكتب Huete Arquitectos بين الزجاج الواسع والتراسات المتدرجة والمساحات الخضراء المدمجة ضمن لوحة مواد متوسطية دافئة.' },

  { find: '03 — Garden Courtyard', es: '03 — Patio Ajardinado', fr: '03 — Cour-Jardin', de: '03 — Gartenhof', ru: '03 — Внутренний Сад', ar: '03 — فناء الحديقة' },
  { find: 'The community turns<br>towards its gardens.', es: 'La comunidad se vuelca<br>hacia sus jardines.', fr: 'La résidence s’oriente<br>vers ses jardins.', de: 'Die Anlage öffnet sich<br>zu ihren Gärten.', ru: 'Комплекс обращён<br>к своим садам.', ar: 'يتوجه المجمع<br>نحو حدائقه.' },
  { find: 'Landscaped courtyards, water and private outdoor areas sit at the centre of the residential plan.', es: 'Los patios ajardinados, el agua y las zonas exteriores privadas ocupan el centro del plan residencial.', fr: 'Les cours paysagées, l’eau et les espaces extérieurs privés occupent le cœur du plan résidentiel.', de: 'Begrünte Innenhöfe, Wasserflächen und private Außenbereiche bilden das Zentrum des Wohnkonzepts.', ru: 'Озеленённые дворы, водные элементы и частные внешние зоны образуют центр жилого плана.', ar: 'تتوسط الأفنية المنسقة والمسطحات المائية والمساحات الخارجية الخاصة المخطط السكني.' },

  { find: '04 — Terrace Living', es: '04 — Vida en la Terraza', fr: '04 — Vivre sur la Terrasse', de: '04 — Terrassenwohnen', ru: '04 — Жизнь на Террасе', ar: '04 — المعيشة على التراس' },
  { find: 'Outdoor space made<br>for everyday use.', es: 'Espacio exterior pensado<br>para el uso diario.', fr: 'Un extérieur conçu<br>pour le quotidien.', de: 'Außenraum, gemacht<br>für den täglichen Gebrauch.', ru: 'Открытое пространство<br>для повседневной жизни.', ar: 'مساحة خارجية مصممة<br>للاستخدام اليومي.' },
  { find: 'Generous terraces extend the living areas with room for dining, shade and evening time outdoors.', es: 'Las amplias terrazas prolongan las zonas de estar con espacio para comer, sombra y veladas al aire libre.', fr: 'De généreuses terrasses prolongent les pièces de vie avec de la place pour les repas, l’ombre et les soirées en extérieur.', de: 'Großzügige Terrassen erweitern die Wohnbereiche um Platz zum Essen, Schatten und Abende im Freien.', ru: 'Просторные террасы продолжают жилые зоны, оставляя место для обедов, тени и вечеров на воздухе.', ar: 'تمتد التراسات الواسعة من مساحات المعيشة لتتيح مجالًا لتناول الطعام والظل والأمسيات في الهواء الطلق.' },

  { find: '05 — Indoor–Outdoor Flow', es: '05 — Continuidad Interior-Exterior', fr: '05 — Continuité Intérieur-Extérieur', de: '05 — Innen-Außen-Übergang', ru: '05 — Связь Внутри и Снаружи', ar: '05 — الانسياب بين الداخل والخارج' },
  { find: 'Living space opens<br>directly to the terrace.', es: 'El salón se abre<br>directamente a la terraza.', fr: 'Le séjour s’ouvre<br>directement sur la terrasse.', de: 'Der Wohnbereich öffnet sich<br>direkt zur Terrasse.', ru: 'Гостиная выходит<br>прямо на террасу.', ar: 'تنفتح مساحة المعيشة<br>مباشرة على التراس.' },
  { find: 'Wide glazed openings make the exterior feel like a continuation of the main room rather than a separate balcony.', es: 'Los amplios huecos acristalados hacen que el exterior se perciba como una continuación del salón y no como un balcón independiente.', fr: 'De larges ouvertures vitrées font percevoir l’extérieur comme le prolongement de la pièce principale plutôt que comme un balcon séparé.', de: 'Breite Glasöffnungen lassen den Außenbereich als Fortsetzung des Hauptraums erscheinen statt als separaten Balkon.', ru: 'Широкие остеклённые проёмы превращают внешнюю зону в продолжение гостиной, а не в отдельный балкон.', ar: 'تجعل الفتحات الزجاجية الواسعة المساحة الخارجية امتدادًا للغرفة الرئيسية بدلًا من كونها شرفة منفصلة.' },

  { find: '06 — Signature Residences', es: '06 — Residencias Signature', fr: '06 — Résidences Signature', de: '06 — Signature-Residenzen', ru: '06 — Резиденции Signature', ar: '06 — مساكن Signature' },
  { find: 'Efficient homes<br>with a calm social core.', es: 'Viviendas eficientes<br>con un sereno núcleo social.', fr: 'Des logements efficients<br>au cœur convivial et apaisé.', de: 'Effiziente Wohnungen<br>mit ruhigem sozialem Kern.', ru: 'Функциональные резиденции<br>со спокойным общим центром.', ar: 'مساكن عملية<br>بقلب اجتماعي هادئ.' },
  { find: 'The Signature collection includes one-, two- and three-bedroom homes with open living areas and generous terraces.', es: 'La colección Signature incluye viviendas de uno, dos y tres dormitorios con salones diáfanos y amplias terrazas.', fr: 'La collection Signature comprend des logements d’une, deux et trois chambres avec séjours ouverts et généreuses terrasses.', de: 'Die Signature-Kollektion umfasst Wohnungen mit einem, zwei und drei Schlafzimmern, offenen Wohnbereichen und großzügigen Terrassen.', ru: 'Коллекция Signature включает резиденции с одной, двумя и тремя спальнями, гостиными открытой планировки и просторными террасами.', ar: 'تضم مجموعة Signature مساكن بغرفة وغرفتين وثلاث غرف نوم مع مساحات معيشة مفتوحة وتراسات واسعة.' },

  { find: '07 — Signature Plan', es: '07 — Plano Signature', fr: '07 — Plan Signature', de: '07 — Signature-Grundriss', ru: '07 — Планировка Signature', ar: '07 — مخطط Signature' },
  { find: 'A supplied two-bedroom<br>layout example.', es: 'Un ejemplo de distribución<br>de dos dormitorios facilitado por el promotor.', fr: 'Un exemple de plan<br>de deux chambres fourni par le promoteur.', de: 'Ein vom Bauträger bereitgestelltes<br>Beispiel für einen Zweizimmer-Grundriss.', ru: 'Пример планировки<br>с двумя спальнями от застройщика.', ar: 'مثال لمخطط<br>بغرفتي نوم مقدَّم من المطور.' },
  { find: 'The drawing shows the open living–kitchen area, two bedrooms and a covered terrace. Exact areas and orientation vary by home.', es: 'El plano muestra el salón-cocina diáfano, dos dormitorios y una terraza cubierta. Las superficies exactas y la orientación varían según la vivienda.', fr: 'Le plan montre l’espace séjour-cuisine ouvert, deux chambres et une terrasse couverte. Les surfaces exactes et l’orientation varient selon le logement.', de: 'Die Zeichnung zeigt den offenen Wohn-Koch-Bereich, zwei Schlafzimmer und eine überdachte Terrasse. Genaue Flächen und Ausrichtung variieren je nach Wohnung.', ru: 'На чертеже показаны объединённая кухня-гостиная, две спальни и крытая терраса. Точные площади и ориентация различаются в зависимости от резиденции.', ar: 'يوضح الرسم مساحة المعيشة والمطبخ المفتوحة وغرفتَي نوم وتراسًا مغطى. تختلف المساحات الدقيقة والاتجاه حسب المسكن.' },

  { find: '08 — Iconic Residences', es: '08 — Residencias Iconic', fr: '08 — Résidences Iconic', de: '08 — Iconic-Residenzen', ru: '08 — Резиденции Iconic', ar: '08 — مساكن Iconic' },
  { find: 'Corner homes with<br>larger private exteriors.', es: 'Viviendas en esquina con<br>mayores exteriores privados.', fr: 'Des logements d’angle aux<br>extérieurs privés plus vastes.', de: 'Eckwohnungen mit<br>größeren privaten Außenbereichen.', ru: 'Угловые резиденции<br>с большими приватными террасами.', ar: 'مساكن ركنية بمساحات<br>خارجية خاصة أوسع.' },
  { find: 'Iconic Residences are single-level corner homes with extra-large terraces and an integrated private pool.', es: 'Las Iconic Residences son viviendas en esquina de una sola planta con terrazas de gran tamaño y piscina privada integrada.', fr: 'Les Iconic Residences sont des logements d’angle de plain-pied avec de très grandes terrasses et une piscine privée intégrée.', de: 'Die Iconic Residences sind eingeschossige Eckwohnungen mit besonders großen Terrassen und integriertem Privatpool.', ru: 'Iconic Residences — одноуровневые угловые резиденции с очень большими террасами и встроенным частным бассейном.', ar: 'مساكن Iconic هي وحدات ركنية بمستوى واحد مع تراسات كبيرة للغاية ومسبح خاص مدمج.' },

  { find: '09 — Iconic Plan', es: '09 — Plano Iconic', fr: '09 — Plan Iconic', de: '09 — Iconic-Grundriss', ru: '09 — Планировка Iconic', ar: '09 — مخطط Iconic' },
  { find: 'An illustrative corner home<br>with its own pool.', es: 'Una vivienda en esquina de ejemplo<br>con piscina propia.', fr: 'Un logement d’angle à titre indicatif<br>avec sa propre piscine.', de: 'Eine beispielhafte Eckwohnung<br>mit eigenem Pool.', ru: 'Пример угловой резиденции<br>с собственным бассейном.', ar: 'مسكن ركني توضيحي<br>بمسبح خاص به.' },
  { find: 'The supplied plan shows two bedrooms, an open living–kitchen area and a wraparound terrace. Unit-specific details must be confirmed.', es: 'El plano facilitado muestra dos dormitorios, un salón-cocina diáfano y una terraza envolvente. Los detalles concretos de cada vivienda deben confirmarse.', fr: 'Le plan fourni montre deux chambres, un espace séjour-cuisine ouvert et une terrasse enveloppante. Les détails propres à chaque logement doivent être confirmés.', de: 'Der bereitgestellte Grundriss zeigt zwei Schlafzimmer, einen offenen Wohn-Koch-Bereich und eine umlaufende Terrasse. Wohnungsspezifische Details sind zu bestätigen.', ru: 'Предоставленный план показывает две спальни, объединённую кухню-гостиную и опоясывающую террасу. Детали по конкретной резиденции требуют подтверждения.', ar: 'يوضح المخطط المقدَّم غرفتَي نوم ومساحة معيشة ومطبخ مفتوحة وتراسًا محيطًا. يجب تأكيد التفاصيل الخاصة بكل وحدة.' },

  { find: '10 — Sky Villas', es: '10 — Sky Villas', fr: '10 — Sky Villas', de: '10 — Sky Villas', ru: '10 — Sky Villas', ar: '10 — Sky Villas' },
  { find: 'Duplex penthouses<br>with private rooftops.', es: 'Áticos dúplex<br>con azoteas privadas.', fr: 'Penthouses duplex<br>avec toits-terrasses privés.', de: 'Duplex-Penthouses<br>mit privaten Dachterrassen.', ru: 'Двухуровневые пентхаусы<br>с частными крышами.', ar: 'بنتهاوس دوبلكس<br>بأسطح خاصة.' },
  { find: 'Sky Villas add expansive terraces, a solarium and a private pool, with open outlooks towards the Mediterranean and La Concha.', es: 'Las Sky Villas suman terrazas de gran amplitud, solárium y piscina privada, con vistas despejadas al Mediterráneo y a La Concha.', fr: 'Les Sky Villas ajoutent de vastes terrasses, un solarium et une piscine privée, avec des vues dégagées sur la Méditerranée et La Concha.', de: 'Die Sky Villas bieten zusätzlich weitläufige Terrassen, ein Solarium und einen Privatpool mit freiem Blick auf das Mittelmeer und La Concha.', ru: 'Sky Villas добавляют просторные террасы, солярий и частный бассейн с открытыми видами на Средиземное море и Ла-Кончу.', ar: 'تضيف Sky Villas تراسات فسيحة وسطحًا شمسيًا ومسبحًا خاصًا مع إطلالات مفتوحة على البحر المتوسط وجبل لا كونتشا.' },

  { find: '11 — Sky Villa Plan', es: '11 — Plano de Sky Villa', fr: '11 — Plan de Sky Villa', de: '11 — Sky-Villa-Grundriss', ru: '11 — Планировка Sky Villa', ar: '11 — مخطط Sky Villa' },
  { find: 'Two levels,<br>four bedrooms and a pool.', es: 'Dos plantas,<br>cuatro dormitorios y piscina.', fr: 'Deux niveaux,<br>quatre chambres et une piscine.', de: 'Zwei Ebenen,<br>vier Schlafzimmer und ein Pool.', ru: 'Два уровня,<br>четыре спальни и бассейн.', ar: 'مستويان<br>وأربع غرف نوم ومسبح.' },
  { find: 'This supplied example places the bedrooms on the lower level and the living space, terraces and pool above. Exact layouts vary.', es: 'Este ejemplo facilitado sitúa los dormitorios en la planta inferior y el salón, las terrazas y la piscina en la superior. Las distribuciones exactas varían.', fr: 'Cet exemple fourni place les chambres au niveau inférieur et le séjour, les terrasses et la piscine à l’étage. Les plans exacts varient.', de: 'Dieses bereitgestellte Beispiel platziert die Schlafzimmer auf der unteren Ebene und Wohnbereich, Terrassen und Pool darüber. Die genauen Grundrisse variieren.', ru: 'В этом примере спальни расположены на нижнем уровне, а гостиная, террасы и бассейн — на верхнем. Точные планировки различаются.', ar: 'يضع هذا المثال المقدَّم غرف النوم في المستوى السفلي ومساحة المعيشة والتراسات والمسبح في الأعلى. تختلف المخططات الدقيقة.' },

  { find: '12 — Masterplan', es: '12 — Plan General', fr: '12 — Plan d’Ensemble', de: '12 — Masterplan', ru: '12 — Генеральный План', ar: '12 — المخطط العام' },
  { find: 'Shared life arranged<br>across the community.', es: 'La vida en común,<br>distribuida por toda la comunidad.', fr: 'La vie collective,<br>répartie dans toute la résidence.', de: 'Gemeinschaftsleben,<br>über die Anlage verteilt.', ru: 'Общественная жизнь,<br>распределённая по комплексу.', ar: 'حياة مشتركة<br>موزعة عبر المجمع.' },
  { find: 'The supplied masterplan locates the courtyard pool, rooftop sky pool and yoga area, gym and spa, and ground-floor business hub.', es: 'El plan general facilitado sitúa la piscina del patio, la piscina y la zona de yoga en la azotea, el gimnasio y el spa, y el centro de negocios en planta baja.', fr: 'Le plan d’ensemble fourni situe la piscine de la cour, la piscine et l’espace yoga en toiture, la salle de sport et le spa, ainsi que l’espace de travail en rez-de-chaussée.', de: 'Der bereitgestellte Masterplan verortet den Innenhofpool, den Dachpool mit Yogabereich, Fitnessstudio und Spa sowie den Business-Hub im Erdgeschoss.', ru: 'Предоставленный генеральный план показывает бассейн во дворе, бассейн и зону йоги на крыше, тренажёрный зал и спа, а также бизнес-хаб на первом этаже.', ar: 'يحدد المخطط العام المقدَّم موقع مسبح الفناء ومسبح السطح ومنطقة اليوغا وصالة الرياضة والسبا ومركز الأعمال في الطابق الأرضي.' },

  { find: '13 — Outdoor Pool', es: '13 — Piscina Exterior', fr: '13 — Piscine Extérieure', de: '13 — Außenpool', ru: '13 — Открытый Бассейн', ar: '13 — المسبح الخارجي' },
  { find: 'A landscaped pool<br>at the heart of the site.', es: 'Una piscina ajardinada<br>en el corazón del conjunto.', fr: 'Une piscine paysagée<br>au cœur du site.', de: 'Ein begrünter Pool<br>im Herzen der Anlage.', ru: 'Озеленённый бассейн<br>в сердце комплекса.', ar: 'مسبح منسق<br>في قلب الموقع.' },
  { find: 'The central pool sits inside the planted courtyard, creating a protected shared space between the residences.', es: 'La piscina central se sitúa dentro del patio ajardinado, creando un espacio común protegido entre las viviendas.', fr: 'La piscine centrale s’installe dans la cour végétalisée, créant un espace partagé protégé entre les résidences.', de: 'Der zentrale Pool liegt im bepflanzten Innenhof und schafft einen geschützten Gemeinschaftsbereich zwischen den Residenzen.', ru: 'Центральный бассейн расположен в озеленённом дворе, образуя защищённое общее пространство между резиденциями.', ar: 'يقع المسبح المركزي داخل الفناء المزروع، مكوّنًا مساحة مشتركة محمية بين المساكن.' },

  { find: '14 — Rooftop Lounge', es: '14 — Salón en la Azotea', fr: '14 — Salon sur le Toit', de: '14 — Dach-Lounge', ru: '14 — Лаундж на Крыше', ar: '14 — صالة السطح' },
  { find: 'An adults-only rooftop<br>above the gardens.', es: 'Una azotea solo para adultos<br>sobre los jardines.', fr: 'Un toit réservé aux adultes<br>au-dessus des jardins.', de: 'Eine Dachebene nur für Erwachsene<br>über den Gärten.', ru: 'Крыша только для взрослых<br>над садами.', ar: 'سطح مخصص للبالغين<br>يعلو الحدائق.' },
  { find: 'The rooftop layer includes an infinity pool and lounge area, designed around long coastal views.', es: 'El nivel de azotea incluye una piscina infinita y una zona de estar, diseñadas en torno a amplias vistas al litoral.', fr: 'Le niveau en toiture comprend une piscine à débordement et un espace salon, conçus autour de larges vues sur le littoral.', de: 'Die Dachebene umfasst einen Infinity-Pool und einen Loungebereich, ausgerichtet auf weite Küstenblicke.', ru: 'Уровень крыши включает бассейн-инфинити и лаундж-зону, спроектированные вокруг протяжённых видов на побережье.', ar: 'يضم مستوى السطح مسبحًا لامتناهيًا ومنطقة صالة، مصمَّمين حول إطلالات ساحلية ممتدة.' },

  { find: '15 — Rooftop Yoga', es: '15 — Yoga en la Azotea', fr: '15 — Yoga sur le Toit', de: '15 — Dach-Yoga', ru: '15 — Йога на Крыше', ar: '15 — يوغا على السطح' },
  { find: 'Morning movement<br>with La Concha beyond.', es: 'Movimiento matinal<br>con La Concha al fondo.', fr: 'Mouvement matinal<br>avec La Concha en toile de fond.', de: 'Morgendliche Bewegung<br>mit La Concha im Hintergrund.', ru: 'Утренняя практика<br>с Ла-Кончей на горизонте.', ar: 'حركة صباحية<br>وجبل لا كونتشا في الأفق.' },
  { find: 'A dedicated rooftop yoga deck adds a quieter wellness space above the wider amenity programme.', es: 'Una plataforma de yoga en la azotea añade un espacio de bienestar más tranquilo por encima del resto de zonas comunes.', fr: 'Une plateforme de yoga dédiée en toiture ajoute un espace bien-être plus calme au-dessus de l’ensemble des prestations.', de: 'Ein eigenes Yoga-Deck auf dem Dach ergänzt das Angebot um einen ruhigeren Wellnessbereich.', ru: 'Отдельная площадка для йоги на крыше добавляет более тихое велнес-пространство над остальной инфраструктурой.', ar: 'تضيف منصة يوغا مخصصة على السطح مساحة عافية أكثر هدوءًا فوق باقي المرافق.' },

  { find: '16 — Indoor Lap Pool', es: '16 — Piscina Interior de Natación', fr: '16 — Bassin de Nage Intérieur', de: '16 — Innen-Schwimmbecken', ru: '16 — Крытый Бассейн для Плавания', ar: '16 — مسبح سباحة داخلي' },
  { find: 'Training and recovery<br>throughout the year.', es: 'Entrenamiento y recuperación<br>durante todo el año.', fr: 'Entraînement et récupération<br>tout au long de l’année.', de: 'Training und Regeneration<br>das ganze Jahr über.', ru: 'Тренировки и восстановление<br>круглый год.', ar: 'تدريب واستشفاء<br>على مدار العام.' },
  { find: 'The indoor lap pool forms part of a broader wellness hub rather than a single-purpose gym area.', es: 'La piscina interior de natación forma parte de un centro de bienestar más amplio, no de una simple zona de gimnasio.', fr: 'Le bassin de nage intérieur s’inscrit dans un pôle bien-être plus large plutôt que dans une simple salle de sport.', de: 'Das Innen-Schwimmbecken ist Teil eines umfassenderen Wellnessbereichs und nicht nur eine Fitnesszone.', ru: 'Крытый бассейн для плавания — часть более широкого велнес-центра, а не просто тренажёрной зоны.', ar: 'يشكل مسبح السباحة الداخلي جزءًا من مركز عافية أوسع وليس مجرد منطقة رياضية.' },

  { find: '17 — Wellness Hub', es: '17 — Centro de Bienestar', fr: '17 — Pôle Bien-Être', de: '17 — Wellness-Hub', ru: '17 — Велнес-Центр', ar: '17 — مركز العافية' },
  { find: 'Heat, water and<br>purposeful recovery.', es: 'Calor, agua y<br>recuperación con propósito.', fr: 'Chaleur, eau et<br>récupération ciblée.', de: 'Wärme, Wasser und<br>gezielte Regeneration.', ru: 'Тепло, вода<br>и осознанное восстановление.', ar: 'حرارة وماء<br>واستشفاء هادف.' },
  { find: 'The supplied programme includes sauna, steam bath, hydromassage, contrast pool and red-light therapy alongside fitness facilities.', es: 'El programa facilitado incluye sauna, baño de vapor, hidromasaje, piscina de contrastes y terapia de luz roja junto a las instalaciones de fitness.', fr: 'Le programme fourni comprend sauna, hammam, hydromassage, bassin de contraste et luminothérapie rouge, en complément des installations de fitness.', de: 'Das bereitgestellte Programm umfasst Sauna, Dampfbad, Hydromassage, Kontrastbecken und Rotlichttherapie neben den Fitnessanlagen.', ru: 'Заявленная программа включает сауну, паровую баню, гидромассаж, контрастный бассейн и терапию красным светом наряду с фитнес-зонами.', ar: 'يشمل البرنامج المقدَّم ساونا وحمام بخار وتدليكًا مائيًا وحوض تباين حراري وعلاجًا بالضوء الأحمر إلى جانب مرافق اللياقة.' },

  { find: '18 — Business Hub', es: '18 — Centro de Negocios', fr: '18 — Espace de Travail', de: '18 — Business-Hub', ru: '18 — Бизнес-Хаб', ar: '18 — مركز الأعمال' },
  { find: 'A practical layer<br>for longer stays.', es: 'Un recurso práctico<br>para estancias largas.', fr: 'Un espace pratique<br>pour les séjours prolongés.', de: 'Eine praktische Ebene<br>für längere Aufenthalte.', ru: 'Практичное решение<br>для длительного пребывания.', ar: 'مساحة عملية<br>للإقامات الطويلة.' },
  { find: 'Dedicated work space supports buyers using the property as a primary home or for extended periods on the coast.', es: 'El espacio de trabajo específico da soporte a los compradores que usan la vivienda como residencia principal o para estancias prolongadas en la costa.', fr: 'Un espace de travail dédié accompagne les acquéreurs utilisant le bien comme résidence principale ou pour de longues périodes sur la côte.', de: 'Ein eigener Arbeitsbereich unterstützt Käufer, die die Immobilie als Hauptwohnsitz oder für längere Zeiträume an der Küste nutzen.', ru: 'Отдельная рабочая зона рассчитана на покупателей, использующих жильё как основное или для длительного пребывания на побережье.', ar: 'تدعم مساحة العمل المخصصة المشترين الذين يستخدمون العقار كمسكن رئيسي أو لفترات طويلة على الساحل.' },

  { find: '19 — Social Life', es: '19 — Vida Social', fr: '19 — Vie Sociale', de: '19 — Gemeinschaftsleben', ru: '19 — Общественная Жизнь', ar: '19 — الحياة الاجتماعية' },
  { find: 'Shared rooms for<br>family and downtime.', es: 'Salas comunes para<br>la familia y el ocio.', fr: 'Des espaces partagés pour<br>la famille et la détente.', de: 'Gemeinschaftsräume für<br>Familie und Freizeit.', ru: 'Общие залы для<br>семьи и отдыха.', ar: 'غرف مشتركة<br>للعائلة وأوقات الاسترخاء.' },
  { find: 'The project adds social areas, a cinema, sports corner and children’s room to the residential and wellness spaces.', es: 'El proyecto añade zonas sociales, cine, rincón deportivo y sala infantil a los espacios residenciales y de bienestar.', fr: 'Le projet ajoute des espaces conviviaux, un cinéma, un coin sport et une salle pour enfants aux espaces résidentiels et bien-être.', de: 'Das Projekt ergänzt die Wohn- und Wellnessbereiche um Gemeinschaftsflächen, ein Kino, eine Sportecke und einen Kinderraum.', ru: 'Проект дополняет жилые и велнес-зоны общественными пространствами, кинозалом, спортивным уголком и детской комнатой.', ar: 'يضيف المشروع مناطق اجتماعية وصالة سينما وركنًا رياضيًا وغرفة للأطفال إلى المساحات السكنية ومرافق العافية.' },

  { find: '20 — Current Release', es: '20 — Fase Actual', fr: '20 — Phase Actuelle', de: '20 — Aktuelle Phase', ru: '20 — Текущая Очередь', ar: '20 — المرحلة الحالية' },
  { find: 'Marbella West Gardens,<br>details available by request.', es: 'Marbella West Gardens,<br>información disponible bajo petición.', fr: 'Marbella West Gardens,<br>informations disponibles sur demande.', de: 'Marbella West Gardens,<br>Details auf Anfrage erhältlich.', ru: 'Marbella West Gardens,<br>подробности по запросу.', ar: 'Marbella West Gardens،<br>التفاصيل متاحة عند الطلب.' },
  { find: 'Ask for the latest price list, unit availability, floorplans, payment terms and a private presentation before choosing a residence.', es: 'Solicita la lista de precios actualizada, la disponibilidad de viviendas, los planos, las condiciones de pago y una presentación privada antes de elegir una residencia.', fr: 'Demandez la dernière liste de prix, la disponibilité des logements, les plans, les conditions de paiement et une présentation privée avant de choisir une résidence.', de: 'Fordern Sie die aktuelle Preisliste, die Verfügbarkeit, Grundrisse, Zahlungsbedingungen und eine private Präsentation an, bevor Sie sich für eine Residenz entscheiden.', ru: 'Запросите актуальный прайс-лист, наличие резиденций, планировки, условия оплаты и частную презентацию, прежде чем сделать выбор.', ar: 'اطلب أحدث قائمة أسعار وتوافر الوحدات والمخططات وشروط الدفع وعرضًا خاصًا قبل اختيار المسكن.' },

  // ===== Cancelada Park (12 scenes)
  { find: '01 — Cancelada Park', es: '01 — Cancelada Park', fr: '01 — Cancelada Park', de: '01 — Cancelada Park', ru: '01 — Cancelada Park', ar: '01 — Cancelada Park' },
  { find: 'Low-rise residences<br>on the New Golden Mile.', es: 'Viviendas de baja altura<br>en la Nueva Milla de Oro.', fr: 'Des résidences de faible hauteur<br>sur la New Golden Mile.', de: 'Niedriggeschossige Residenzen<br>an der New Golden Mile.', ru: 'Малоэтажные резиденции<br>на Новой Золотой миле.', ar: 'مساكن منخفضة الارتفاع<br>على الميل الذهبي الجديد.' },
  { find: 'The opening view shows the residential phase, landscaped pool gardens and its position within a wider resort setting.', es: 'La vista inicial muestra la fase residencial, los jardines ajardinados con piscina y su posición dentro de un entorno de resort más amplio.', fr: 'La vue d’ouverture montre la phase résidentielle, les jardins paysagers avec piscine et sa position au sein d’un ensemble resort plus vaste.', de: 'Die Eröffnungsansicht zeigt die Wohnphase, die angelegten Poolgärten und ihre Lage innerhalb einer größeren Resortanlage.', ru: 'Первый кадр показывает жилую очередь, озеленённые сады с бассейном и её расположение в составе более крупного курортного комплекса.', ar: 'يُظهر المشهد الافتتاحي المرحلة السكنية وحدائق المسبح المنسقة وموقعها ضمن منتجع أوسع.' },

  { find: 'Clean white volumes,<br>warmed by timber.', es: 'Volúmenes blancos y puros,<br>templados por la madera.', fr: 'Des volumes blancs épurés,<br>réchauffés par le bois.', de: 'Klare weiße Baukörper,<br>erwärmt durch Holz.', ru: 'Чистые белые объёмы,<br>согретые деревом.', ar: 'كتل بيضاء نقية<br>يدفئها الخشب.' },
  { find: 'Pablo Villarroel shapes the buildings around broad glazing, planted terraces and a contemporary Mediterranean material palette.', es: 'Pablo Villarroel configura los edificios en torno a amplios acristalamientos, terrazas ajardinadas y una paleta de materiales mediterránea contemporánea.', fr: 'Pablo Villarroel façonne les bâtiments autour de larges baies vitrées, de terrasses végétalisées et d’une palette de matériaux méditerranéenne contemporaine.', de: 'Pablo Villarroel formt die Gebäude um großflächige Verglasung, bepflanzte Terrassen und eine zeitgenössische mediterrane Materialpalette.', ru: 'Пабло Вильярроэль формирует здания вокруг панорамного остекления, озеленённых террас и современной средиземноморской палитры материалов.', ar: 'يصوغ بابلو فيلارويل المباني حول الزجاج الواسع والتراسات المزروعة ولوحة مواد متوسطية معاصرة.' },

  { find: '03 — Pool Gardens', es: '03 — Jardines con Piscina', fr: '03 — Jardins-Piscine', de: '03 — Poolgärten', ru: '03 — Сады с Бассейном', ar: '03 — حدائق المسبح' },
  { find: 'A protected garden<br>at the centre of the phase.', es: 'Un jardín protegido<br>en el centro de la fase.', fr: 'Un jardin protégé<br>au centre de la phase.', de: 'Ein geschützter Garten<br>im Zentrum der Phase.', ru: 'Защищённый сад<br>в центре очереди.', ar: 'حديقة محمية<br>في قلب المرحلة.' },
  { find: 'The outdoor pool and relaxation area sit between the low-rise buildings, with planting softening the shared residential setting.', es: 'La piscina exterior y la zona de relax se sitúan entre los edificios de baja altura, con vegetación que suaviza el entorno residencial común.', fr: 'La piscine extérieure et l’espace détente s’installent entre les bâtiments bas, la végétation adoucissant le cadre résidentiel partagé.', de: 'Außenpool und Ruhebereich liegen zwischen den niedrigen Gebäuden, wobei Bepflanzung das gemeinschaftliche Wohnumfeld auflockert.', ru: 'Открытый бассейн и зона отдыха расположены между малоэтажными корпусами, а озеленение смягчает общее жилое пространство.', ar: 'يقع المسبح الخارجي ومنطقة الاسترخاء بين المباني المنخفضة، مع نباتات تلطّف البيئة السكنية المشتركة.' },

  { find: '04 — Garden Residences', es: '04 — Viviendas con Jardín', fr: '04 — Résidences avec Jardin', de: '04 — Gartenresidenzen', ru: '04 — Резиденции с Садом', ar: '04 — مساكن الحدائق' },
  { find: 'Private outdoor space<br>that works as a real room.', es: 'Un exterior privado<br>que funciona como una estancia más.', fr: 'Un extérieur privé<br>qui fonctionne comme une vraie pièce.', de: 'Privater Außenraum,<br>der als echtes Zimmer funktioniert.', ru: 'Приватное открытое пространство,<br>работающее как полноценная комната.', ar: 'مساحة خارجية خاصة<br>تعمل كغرفة حقيقية.' },
  { find: 'Selected ground-floor homes pair large terraces with private gardens, creating a practical option for longer stays and family use.', es: 'Determinadas viviendas en planta baja combinan amplias terrazas con jardines privados, creando una opción práctica para estancias largas y uso familiar.', fr: 'Certains logements en rez-de-chaussée associent de grandes terrasses à des jardins privés, offrant une option pratique pour les longs séjours et un usage familial.', de: 'Ausgewählte Erdgeschosswohnungen verbinden große Terrassen mit privaten Gärten und bieten eine praktische Option für längere Aufenthalte und Familien.', ru: 'Отдельные резиденции на первом этаже сочетают большие террасы с частными садами — практичный вариант для длительного пребывания и семей.', ar: 'تجمع مساكن مختارة في الطابق الأرضي بين تراسات واسعة وحدائق خاصة، ما يوفر خيارًا عمليًا للإقامات الطويلة والاستخدام العائلي.' },

  { find: '05 — Penthouses', es: '05 — Áticos', fr: '05 — Penthouses', de: '05 — Penthouses', ru: '05 — Пентхаусы', ar: '05 — بنتهاوس' },
  { find: 'Upper-floor homes<br>with broad terraces.', es: 'Viviendas en planta alta<br>con amplias terrazas.', fr: 'Des logements aux étages supérieurs<br>avec de larges terrasses.', de: 'Wohnungen in den Obergeschossen<br>mit weiten Terrassen.', ru: 'Резиденции верхних этажей<br>с просторными террасами.', ar: 'مساكن في الطوابق العليا<br>بتراسات واسعة.' },
  { find: 'The penthouse release adds generous exterior areas and selected rooftop solariums, with three- and four-bedroom layouts.', es: 'La fase de áticos añade generosas zonas exteriores y solariums en azotea en determinadas viviendas, con distribuciones de tres y cuatro dormitorios.', fr: 'La phase penthouse ajoute de généreux espaces extérieurs et, pour certains logements, des solariums en toiture, avec des plans de trois et quatre chambres.', de: 'Die Penthouse-Phase bietet großzügige Außenflächen und bei ausgewählten Einheiten Dachsolarien, mit Grundrissen für drei und vier Schlafzimmer.', ru: 'Очередь пентхаусов добавляет просторные внешние зоны и солярии на крыше в отдельных резиденциях, с планировками на три и четыре спальни.', ar: 'تضيف مرحلة البنتهاوس مساحات خارجية سخية وأسطحًا شمسية في وحدات مختارة، بمخططات من ثلاث وأربع غرف نوم.' },

  { find: '06 — Residence Choice', es: '06 — Elección de Vivienda', fr: '06 — Choix de la Résidence', de: '06 — Wahl der Residenz', ru: '06 — Выбор Резиденции', ar: '06 — اختيار المسكن' },
  { find: 'Compare the outdoor space,<br>not only the bedroom count.', es: 'Compara el espacio exterior,<br>no solo el número de dormitorios.', fr: 'Comparez l’espace extérieur,<br>pas seulement le nombre de chambres.', de: 'Vergleichen Sie den Außenraum,<br>nicht nur die Zimmerzahl.', ru: 'Сравнивайте открытое пространство,<br>а не только число спален.', ar: 'قارن المساحة الخارجية<br>لا عدد غرف النوم فقط.' },
  { find: 'The strongest choice depends on orientation, privacy and usable garden, terrace or solarium area as much as the internal layout.', es: 'La mejor elección depende tanto de la orientación, la privacidad y la superficie útil de jardín, terraza o solárium como de la distribución interior.', fr: 'Le meilleur choix dépend autant de l’orientation, de l’intimité et de la surface utile de jardin, terrasse ou solarium que du plan intérieur.', de: 'Die beste Wahl hängt ebenso von Ausrichtung, Privatsphäre und nutzbarer Garten-, Terrassen- oder Solariumfläche ab wie vom Innengrundriss.', ru: 'Лучший выбор зависит от ориентации, приватности и полезной площади сада, террасы или солярия не меньше, чем от внутренней планировки.', ar: 'يعتمد الخيار الأفضل على الاتجاه والخصوصية والمساحة المفيدة للحديقة أو التراس أو السطح الشمسي بقدر اعتماده على التوزيع الداخلي.' },

  { find: '07 — Wider Setting', es: '07 — Entorno Más Amplio', fr: '07 — Cadre Élargi', de: '07 — Weiteres Umfeld', ru: '07 — Более Широкое Окружение', ar: '07 — المحيط الأوسع' },
  { find: 'The residences form part<br>of a broader resort plan.', es: 'Las viviendas forman parte<br>de un plan de resort más amplio.', fr: 'Les résidences s’inscrivent<br>dans un plan resort plus large.', de: 'Die Residenzen sind Teil<br>eines größeren Resortkonzepts.', ru: 'Резиденции — часть<br>более широкого курортного плана.', ar: 'تشكل المساكن جزءًا<br>من مخطط منتجع أوسع.' },
  { find: 'The supplied overview places the residential plots alongside sport, wellness, dining, work and leisure facilities. Timing and access should be confirmed.', es: 'La visión general facilitada sitúa las parcelas residenciales junto a instalaciones deportivas, de bienestar, restauración, trabajo y ocio. Los plazos y el acceso deben confirmarse.', fr: 'La vue d’ensemble fournie place les parcelles résidentielles aux côtés des installations de sport, bien-être, restauration, travail et loisirs. Le calendrier et l’accès sont à confirmer.', de: 'Die bereitgestellte Übersicht ordnet die Wohngrundstücke neben Sport-, Wellness-, Gastronomie-, Arbeits- und Freizeiteinrichtungen an. Zeitplan und Zugang sind zu bestätigen.', ru: 'Предоставленный обзор размещает жилые участки рядом со спортивными, велнес-, ресторанными, рабочими и досуговыми объектами. Сроки и доступ требуют подтверждения.', ar: 'تضع النظرة العامة المقدَّمة القطع السكنية إلى جانب مرافق الرياضة والعافية والمطاعم والعمل والترفيه. ينبغي تأكيد التوقيت وإمكانية الوصول.' },

  { find: '08 — New Golden Mile', es: '08 — Nueva Milla de Oro', fr: '08 — New Golden Mile', de: '08 — New Golden Mile', ru: '08 — Новая Золотая Миля', ar: '08 — الميل الذهبي الجديد' },
  { find: 'Cancelada between<br>Estepona and Marbella.', es: 'Cancelada, entre<br>Estepona y Marbella.', fr: 'Cancelada, entre<br>Estepona et Marbella.', de: 'Cancelada zwischen<br>Estepona und Marbella.', ru: 'Канселада между<br>Эстепоной и Марбельей.', ar: 'كانسيلادا بين<br>إستيبونا وماربيا.' },
  { find: 'The beach is described as an approximate ten-minute walk, with Estepona and Puerto Banus both about twelve kilometres away.', es: 'La playa se describe a unos diez minutos a pie, con Estepona y Puerto Banús a unos doce kilómetros cada uno.', fr: 'La plage est indiquée à environ dix minutes à pied, Estepona et Puerto Banús se situant chacun à une douzaine de kilomètres.', de: 'Der Strand wird mit etwa zehn Gehminuten angegeben, Estepona und Puerto Banús liegen jeweils rund zwölf Kilometer entfernt.', ru: 'Пляж указан примерно в десяти минутах ходьбы, а Эстепона и Пуэрто-Банус — примерно в двенадцати километрах каждый.', ar: 'يُذكر أن الشاطئ على بُعد نحو عشر دقائق سيرًا، بينما تبعد إستيبونا وبويرتو بانوس نحو اثني عشر كيلومترًا لكل منهما.' },

  { find: '09 — Wider Resort Wellness', es: '09 — Bienestar del Resort', fr: '09 — Bien-Être du Resort', de: '09 — Wellness im Resort', ru: '09 — Велнес Курорта', ar: '09 — عافية المنتجع' },
  { find: 'Wellness planned<br>beyond the residence.', es: 'Bienestar previsto<br>más allá de la vivienda.', fr: 'Un bien-être prévu<br>au-delà de la résidence.', de: 'Wellness, geplant<br>über die Residenz hinaus.', ru: 'Велнес, предусмотренный<br>за пределами резиденции.', ar: 'عافية مخطط لها<br>خارج حدود المسكن.' },
  { find: 'The wider resort concept includes spa and wellness facilities. Confirm what is included, where it sits and when it is expected to open.', es: 'El concepto de resort más amplio incluye instalaciones de spa y bienestar. Conviene confirmar qué se incluye, dónde se ubica y cuándo está prevista su apertura.', fr: 'Le concept resort élargi comprend des installations de spa et de bien-être. Confirmez ce qui est inclus, son emplacement et sa date d’ouverture prévue.', de: 'Das erweiterte Resortkonzept umfasst Spa- und Wellnesseinrichtungen. Klären Sie, was enthalten ist, wo es liegt und wann die Eröffnung erwartet wird.', ru: 'Более широкая концепция курорта включает спа- и велнес-объекты. Уточните, что входит, где расположено и когда ожидается открытие.', ar: 'يشمل مفهوم المنتجع الأوسع مرافق سبا وعافية. تأكد مما هو مشمول وأين يقع ومتى يُتوقع افتتاحه.' },

  { find: '10 — Wider Resort Sport', es: '10 — Deporte del Resort', fr: '10 — Sport du Resort', de: '10 — Sport im Resort', ru: '10 — Спорт Курорта', ar: '10 — رياضة المنتجع' },
  { find: 'Padel, tennis and fitness<br>within the wider plan.', es: 'Pádel, tenis y fitness<br>dentro del plan más amplio.', fr: 'Padel, tennis et fitness<br>dans le plan élargi.', de: 'Padel, Tennis und Fitness<br>im erweiterten Konzept.', ru: 'Падел, теннис и фитнес<br>в рамках общего плана.', ar: 'بادل وتنس ولياقة<br>ضمن المخطط الأوسع.' },
  { find: 'Sport facilities add practical lifestyle value for longer stays, subject to final delivery, access terms and any separate fees.', es: 'Las instalaciones deportivas aportan valor práctico para estancias largas, sujetas a la entrega final, las condiciones de acceso y posibles cuotas independientes.', fr: 'Les installations sportives apportent une valeur pratique pour les longs séjours, sous réserve de la livraison finale, des conditions d’accès et d’éventuels frais séparés.', de: 'Sportanlagen bieten praktischen Mehrwert für längere Aufenthalte, vorbehaltlich endgültiger Fertigstellung, Zugangsbedingungen und etwaiger gesonderter Gebühren.', ru: 'Спортивные объекты добавляют практическую ценность для длительного пребывания — при условии окончательной сдачи, условий доступа и возможных отдельных сборов.', ar: 'تضيف المرافق الرياضية قيمة عملية للإقامات الطويلة، رهنًا بالتسليم النهائي وشروط الدخول وأي رسوم منفصلة.' },

  { find: '11 — Wider Resort Services', es: '11 — Servicios del Resort', fr: '11 — Services du Resort', de: '11 — Services im Resort', ru: '11 — Услуги Курорта', ar: '11 — خدمات المنتجع' },
  { find: 'Dining, work and daily life<br>considered together.', es: 'Restauración, trabajo y vida diaria<br>pensados en conjunto.', fr: 'Restauration, travail et vie quotidienne<br>pensés ensemble.', de: 'Gastronomie, Arbeit und Alltag<br>zusammen gedacht.', ru: 'Питание, работа и повседневность<br>продуманы вместе.', ar: 'المطاعم والعمل والحياة اليومية<br>مدروسة معًا.' },
  { find: 'Restaurant, retail, coworking and family facilities are shown as part of the wider concept rather than the immediate residential phase.', es: 'El restaurante, la zona comercial, el coworking y las instalaciones familiares se muestran como parte del concepto más amplio, no de la fase residencial inmediata.', fr: 'Restaurant, commerces, coworking et équipements familiaux sont présentés comme faisant partie du concept élargi et non de la phase résidentielle immédiate.', de: 'Restaurant, Einzelhandel, Coworking und Familieneinrichtungen werden als Teil des Gesamtkonzepts gezeigt, nicht der unmittelbaren Wohnphase.', ru: 'Ресторан, магазины, коворкинг и семейные объекты показаны как часть более широкой концепции, а не текущей жилой очереди.', ar: 'يُعرض المطعم والمتاجر ومساحة العمل المشترك والمرافق العائلية كجزء من المفهوم الأوسع لا من المرحلة السكنية الحالية.' },

  { find: '12 — Current Release', es: '12 — Fase Actual', fr: '12 — Phase Actuelle', de: '12 — Aktuelle Phase', ru: '12 — Текущая Очередь', ar: '12 — المرحلة الحالية' },
  { find: 'Cancelada Park,<br>the details come next.', es: 'Cancelada Park,<br>los detalles vienen a continuación.', fr: 'Cancelada Park,<br>les détails arrivent ensuite.', de: 'Cancelada Park,<br>die Details folgen.', ru: 'Cancelada Park,<br>далее — детали.', ar: 'Cancelada Park،<br>والتفاصيل تأتي تاليًا.' },
  { find: 'Ask for the latest residence plans, availability, guide prices, payment terms and confirmed delivery information before choosing a home.', es: 'Solicita los planos actualizados, la disponibilidad, los precios orientativos, las condiciones de pago y la información de entrega confirmada antes de elegir una vivienda.', fr: 'Demandez les derniers plans, la disponibilité, les prix indicatifs, les conditions de paiement et les informations de livraison confirmées avant de choisir un logement.', de: 'Fordern Sie aktuelle Grundrisse, Verfügbarkeit, Richtpreise, Zahlungsbedingungen und bestätigte Übergabeinformationen an, bevor Sie sich für eine Wohnung entscheiden.', ru: 'Запросите актуальные планировки, наличие, ориентировочные цены, условия оплаты и подтверждённые сроки сдачи, прежде чем выбрать резиденцию.', ar: 'اطلب أحدث مخططات المساكن والتوافر والأسعار الاسترشادية وشروط الدفع ومعلومات التسليم المؤكدة قبل اختيار المسكن.' }
];
