// Translations for the two hand-authored ("bespoke") cinematic-viewer
// scene sets embedded directly in nueva-living-home.html:
// MARBELLA_WEST_GARDEN_VIEWING_SCENES and CANCELADA_PARK_VIEWING_SCENES.
//
// These sit OUTSIDE the NUEVA GENERATED VIEWING SCENES markers, and the
// viewer resolves BESPOKE_VIEWING_SCENES *before* PROJECT_VIEWING_SCENE_SETS
// -- so for these two projects the bespoke English text wins over the
// generated, already-translated scene data. Without these entries the
// cinematic viewer silently shows English on every locale homepage for
// Marbella West Garden Residences and Cancelada Park.
//
// Applied as literal find/replace (longest-first) alongside
// HOMEPAGE_CONTENT_ENTRIES in build_homepage_locales.mjs.
//
// Note: DEFAULT_VIEWING_SCENES in the same file is deliberately NOT
// translated -- it is unreachable in practice, since all 13 projects have
// generated scene sets, so the `|| DEFAULT_VIEWING_SCENES` fallback never
// resolves. Translating it would be dead weight.
export const BESPOKE_SCENE_ENTRIES = [
  // ===== Marbella West Garden Residences (20 scenes)
  { find: '01 — Marbella West', es: '01 — Marbella West', fr: '01 — Marbella West', de: '01 — Marbella West', ru: '01 — Марбелья-Уэст', ar: '01 — ماربيا الغربية', nl: '01 — Marbella West', pl: '01 — Marbella West', sv: '01 — Marbella West', no: '01 — Marbella West' },
  { find: 'A new residential address<br>between coast and city.', es: 'Una nueva dirección residencial<br>entre la costa y la ciudad.', fr: 'Une nouvelle adresse résidentielle<br>entre la côte et la ville.', de: 'Eine neue Wohnadresse<br>zwischen Küste und Stadt.', ru: 'Новый жилой адрес<br>между побережьем и городом.', ar: 'عنوان سكني جديد<br>بين الساحل والمدينة.', nl: 'Een nieuw woonadres<br>tussen kust en stad.', pl: 'Nowy adres mieszkalny<br>między wybrzeżem a miastem.', sv: 'En ny bostadsadress<br>mellan kust och stad.', no: 'En ny boligadresse<br>mellom kyst og by.' },
  { find: 'The opening view introduces the curved, planted architecture of this 139-home community near San Pedro and Puerto Banús.', es: 'La vista inicial presenta la arquitectura curva y ajardinada de esta comunidad de 139 viviendas cerca de San Pedro y Puerto Banús.', fr: 'La vue d’ouverture présente l’architecture courbe et végétalisée de cette communauté de 139 logements près de San Pedro et Puerto Banús.', de: 'Die Eröffnungsansicht zeigt die geschwungene, begrünte Architektur dieser Wohnanlage mit 139 Einheiten nahe San Pedro und Puerto Banús.', ru: 'Первый кадр знакомит с изогнутой озеленённой архитектурой этого комплекса на 139 резиденций рядом с Сан-Педро и Пуэрто-Банусом.', ar: 'يقدّم المشهد الافتتاحي العمارة المنحنية المكسوة بالنباتات لهذا المجتمع المكوّن من 139 مسكنًا قرب سان بيدرو وبويرتو بانوس.', nl: 'Het openingsbeeld toont de gebogen, groene architectuur van deze gemeenschap met 139 woningen nabij San Pedro en Puerto Banús.', pl: 'Pierwszy widok przedstawia łukowatą, obsadzoną zielenią architekturę tego osiedla liczącego 139 domów w pobliżu San Pedro i Puerto Banús.', sv: 'Den inledande vyn presenterar den böjda, planterade arkitekturen i detta bostadsområde med 139 hem nära San Pedro och Puerto Banús.', no: 'Åpningsbildet viser den buede, beplantede arkitekturen i dette boligområdet med 139 hjem nær San Pedro og Puerto Banús.' },

  { find: '02 — Architecture', es: '02 — Arquitectura', fr: '02 — Architecture', de: '02 — Architektur', ru: '02 — Архитектура', ar: '02 — العمارة', nl: '02 — Architectuur', pl: '02 — Architektura', sv: '02 — Arkitektur', no: '02 — Arkitektur' },
  { find: 'Rounded terraces,<br>softened by planting.', es: 'Terrazas redondeadas,<br>suavizadas por la vegetación.', fr: 'Terrasses arrondies,<br>adoucies par la végétation.', de: 'Abgerundete Terrassen,<br>aufgelockert durch Bepflanzung.', ru: 'Скруглённые террасы,<br>смягчённые озеленением.', ar: 'تراسات منحنية<br>تلطّفها المساحات الخضراء.', nl: 'Ronde terrassen,<br>verzacht door beplanting.', pl: 'Zaokrąglone tarasy,<br>złagodzone zielenią.', sv: 'Rundade terrasser,<br>mjukade upp av växtlighet.', no: 'Avrundede terrasser,<br>mildnet av beplantning.' },
  { find: 'Huete Arquitectos combines broad glazing, layered terraces and integrated greenery in a warm Mediterranean material palette.', es: 'Huete Arquitectos combina amplios acristalamientos, terrazas escalonadas y vegetación integrada en una cálida paleta de materiales mediterránea.', fr: 'Huete Arquitectos associe de larges baies vitrées, des terrasses étagées et une végétation intégrée dans une palette de matériaux méditerranéenne chaleureuse.', de: 'Huete Arquitectos verbindet großflächige Verglasung, gestaffelte Terrassen und integriertes Grün in einer warmen mediterranen Materialpalette.', ru: 'Huete Arquitectos сочетает панорамное остекление, ярусные террасы и встроенное озеленение в тёплой средиземноморской палитре материалов.', ar: 'يجمع مكتب Huete Arquitectos بين الزجاج الواسع والتراسات المتدرجة والمساحات الخضراء المدمجة ضمن لوحة مواد متوسطية دافئة.', nl: 'Huete Arquitectos combineert brede beglazing, gelaagde terrassen en geïntegreerd groen in een warm mediterraan materialenpalet.', pl: 'Huete Arquitectos łączy rozległe przeszklenia, wielopoziomowe tarasy i wkomponowaną zieleń w ciepłej, śródziemnomorskiej palecie materiałów.', sv: 'Huete Arquitectos kombinerar breda glaspartier, terrasserade nivåer och integrerad grönska i en varm medelhavsinspirerad materialpalett.', no: 'Huete Arquitectos kombinerer store glassflater, trinnvise terrasser og integrert grønt i en varm middelhavsinspirert materialpalett.' },

  { find: '03 — Garden Courtyard', es: '03 — Patio Ajardinado', fr: '03 — Cour-Jardin', de: '03 — Gartenhof', ru: '03 — Внутренний Сад', ar: '03 — فناء الحديقة', nl: '03 — Tuinbinnenplaats', pl: '03 — Dziedziniec Ogrodowy', sv: '03 — Trädgårdsgård', no: '03 — Hagegård' },
  { find: 'The community turns<br>towards its gardens.', es: 'La comunidad se vuelca<br>hacia sus jardines.', fr: 'La résidence s’oriente<br>vers ses jardins.', de: 'Die Anlage öffnet sich<br>zu ihren Gärten.', ru: 'Комплекс обращён<br>к своим садам.', ar: 'يتوجه المجمع<br>نحو حدائقه.', nl: 'De gemeenschap keert zich<br>naar haar tuinen.', pl: 'Osiedle zwraca się<br>ku swoim ogrodom.', sv: 'Boendet vänder sig<br>mot sina trädgårdar.', no: 'Boligområdet vender seg<br>mot sine hager.' },
  { find: 'Landscaped courtyards, water and private outdoor areas sit at the centre of the residential plan.', es: 'Los patios ajardinados, el agua y las zonas exteriores privadas ocupan el centro del plan residencial.', fr: 'Les cours paysagées, l’eau et les espaces extérieurs privés occupent le cœur du plan résidentiel.', de: 'Begrünte Innenhöfe, Wasserflächen und private Außenbereiche bilden das Zentrum des Wohnkonzepts.', ru: 'Озеленённые дворы, водные элементы и частные внешние зоны образуют центр жилого плана.', ar: 'تتوسط الأفنية المنسقة والمسطحات المائية والمساحات الخارجية الخاصة المخطط السكني.', nl: 'Aangelegde binnenplaatsen, water en privé buitenruimtes vormen het middelpunt van het woonplan.', pl: 'Zagospodarowane dziedzińce, woda i prywatne strefy zewnętrzne znajdują się w centrum planu osiedla.', sv: 'Iordningställda innergårdar, vatten och privata uteplatser utgör mittpunkten i bostadsplanen.', no: 'Opparbeidede gårdsrom, vann og private uteområder danner sentrum i boligplanen.' },

  { find: '04 — Terrace Living', es: '04 — Vida en la Terraza', fr: '04 — Vivre sur la Terrasse', de: '04 — Terrassenwohnen', ru: '04 — Жизнь на Террасе', ar: '04 — المعيشة على التراس', nl: '04 — Terrasleven', pl: '04 — Życie na Tarasie', sv: '04 — Livet på Terrassen', no: '04 — Livet på Terrassen' },
  { find: 'Outdoor space made<br>for everyday use.', es: 'Espacio exterior pensado<br>para el uso diario.', fr: 'Un extérieur conçu<br>pour le quotidien.', de: 'Außenraum, gemacht<br>für den täglichen Gebrauch.', ru: 'Открытое пространство<br>для повседневной жизни.', ar: 'مساحة خارجية مصممة<br>للاستخدام اليومي.', nl: 'Buitenruimte gemaakt<br>voor dagelijks gebruik.', pl: 'Przestrzeń zewnętrzna stworzona<br>do codziennego użytku.', sv: 'Utrymme utomhus skapat<br>för vardagligt bruk.', no: 'Uteareal skapt<br>for daglig bruk.' },
  { find: 'Generous terraces extend the living areas with room for dining, shade and evening time outdoors.', es: 'Las amplias terrazas prolongan las zonas de estar con espacio para comer, sombra y veladas al aire libre.', fr: 'De généreuses terrasses prolongent les pièces de vie avec de la place pour les repas, l’ombre et les soirées en extérieur.', de: 'Großzügige Terrassen erweitern die Wohnbereiche um Platz zum Essen, Schatten und Abende im Freien.', ru: 'Просторные террасы продолжают жилые зоны, оставляя место для обедов, тени и вечеров на воздухе.', ar: 'تمتد التراسات الواسعة من مساحات المعيشة لتتيح مجالًا لتناول الطعام والظل والأمسيات في الهواء الطلق.', nl: 'Ruime terrassen verlengen de woonruimtes met plek om te dineren, schaduw te vinden en avonden buiten door te brengen.', pl: 'Obszerne tarasy przedłużają strefy dzienne, dając miejsce na posiłki, cień i wieczory na świeżym powietrzu.', sv: 'Generösa terrasser förlänger vardagsrummen med plats för middagar, skugga och kvällar utomhus.', no: 'Romslige terrasser forlenger oppholdsrommene med plass til middager, skygge og kveldstid utendørs.' },

  { find: '05 — Indoor–Outdoor Flow', es: '05 — Continuidad Interior-Exterior', fr: '05 — Continuité Intérieur-Extérieur', de: '05 — Innen-Außen-Übergang', ru: '05 — Связь Внутри и Снаружи', ar: '05 — الانسياب بين الداخل والخارج', nl: '05 — Vloeiende Overgang Binnen-Buiten', pl: '05 — Płynne Przejście Wnętrze-Zewnętrze', sv: '05 — Flöde Mellan Inne och Ute', no: '05 — Flyt Mellom Inne og Ute' },
  { find: 'Living space opens<br>directly to the terrace.', es: 'El salón se abre<br>directamente a la terraza.', fr: 'Le séjour s’ouvre<br>directement sur la terrasse.', de: 'Der Wohnbereich öffnet sich<br>direkt zur Terrasse.', ru: 'Гостиная выходит<br>прямо на террасу.', ar: 'تنفتح مساحة المعيشة<br>مباشرة على التراس.', nl: 'De woonruimte opent zich<br>direct naar het terras.', pl: 'Przestrzeń dzienna otwiera się<br>bezpośrednio na taras.', sv: 'Vardagsrummet öppnar sig<br>direkt mot terrassen.', no: 'Stuen åpner seg<br>direkte mot terrassen.' },
  { find: 'Wide glazed openings make the exterior feel like a continuation of the main room rather than a separate balcony.', es: 'Los amplios huecos acristalados hacen que el exterior se perciba como una continuación del salón y no como un balcón independiente.', fr: 'De larges ouvertures vitrées font percevoir l’extérieur comme le prolongement de la pièce principale plutôt que comme un balcon séparé.', de: 'Breite Glasöffnungen lassen den Außenbereich als Fortsetzung des Hauptraums erscheinen statt als separaten Balkon.', ru: 'Широкие остеклённые проёмы превращают внешнюю зону в продолжение гостиной, а не в отдельный балкон.', ar: 'تجعل الفتحات الزجاجية الواسعة المساحة الخارجية امتدادًا للغرفة الرئيسية بدلًا من كونها شرفة منفصلة.', nl: 'Brede glazen openingen laten het exterieur aanvoelen als een verlengstuk van de hoofdruimte in plaats van een aparte balkon.', pl: 'Szerokie przeszklone otwory sprawiają, że przestrzeń zewnętrzna odczuwana jest jako przedłużenie głównego pomieszczenia, a nie osobny balkon.', sv: 'Breda glasöppningar får utomhusdelen att kännas som en fortsättning på huvudrummet snarare än en separat balkong.', no: 'Brede glassåpninger gjør at uteområdet oppleves som en forlengelse av hovedrommet snarere enn en separat balkong.' },

  { find: '06 — Signature Residences', es: '06 — Residencias Signature', fr: '06 — Résidences Signature', de: '06 — Signature-Residenzen', ru: '06 — Резиденции Signature', ar: '06 — مساكن Signature', nl: '06 — Signature-Residenties', pl: '06 — Rezydencje Signature', sv: '06 — Signature-Residens', no: '06 — Signature-Residenser' },
  { find: 'Efficient homes<br>with a calm social core.', es: 'Viviendas eficientes<br>con un sereno núcleo social.', fr: 'Des logements efficients<br>au cœur convivial et apaisé.', de: 'Effiziente Wohnungen<br>mit ruhigem sozialem Kern.', ru: 'Функциональные резиденции<br>со спокойным общим центром.', ar: 'مساكن عملية<br>بقلب اجتماعي هادئ.', nl: 'Efficiënte woningen<br>met een rustige sociale kern.', pl: 'Funkcjonalne domy<br>ze spokojnym, wspólnym centrum.', sv: 'Effektiva bostäder<br>med en lugn social kärna.', no: 'Effektive boliger<br>med en rolig sosial kjerne.' },
  { find: 'The Signature collection includes one-, two- and three-bedroom homes with open living areas and generous terraces.', es: 'La colección Signature incluye viviendas de uno, dos y tres dormitorios con salones diáfanos y amplias terrazas.', fr: 'La collection Signature comprend des logements d’une, deux et trois chambres avec séjours ouverts et généreuses terrasses.', de: 'Die Signature-Kollektion umfasst Wohnungen mit einem, zwei und drei Schlafzimmern, offenen Wohnbereichen und großzügigen Terrassen.', ru: 'Коллекция Signature включает резиденции с одной, двумя и тремя спальнями, гостиными открытой планировки и просторными террасами.', ar: 'تضم مجموعة Signature مساكن بغرفة وغرفتين وثلاث غرف نوم مع مساحات معيشة مفتوحة وتراسات واسعة.', nl: 'De Signature-collectie omvat woningen met één, twee en drie slaapkamers, met open woonruimtes en ruime terrassen.', pl: 'Kolekcja Signature obejmuje domy z jedną, dwiema i trzema sypialniami, z otwartymi strefami dziennymi i obszernymi tarasami.', sv: 'Signature-kollektionen omfattar bostäder med en, två och tre sovrum, med öppna vardagsrum och generösa terrasser.', no: 'Signature-kolleksjonen omfatter boliger med étt, to og tre soverom, med åpne stuer og romslige terrasser.' },

  { find: '07 — Signature Plan', es: '07 — Plano Signature', fr: '07 — Plan Signature', de: '07 — Signature-Grundriss', ru: '07 — Планировка Signature', ar: '07 — مخطط Signature', nl: '07 — Signature-Plattegrond', pl: '07 — Plan Signature', sv: '07 — Signature-Planlösning', no: '07 — Signature-Plantegning' },
  { find: 'A supplied two-bedroom<br>layout example.', es: 'Un ejemplo de distribución<br>de dos dormitorios facilitado por el promotor.', fr: 'Un exemple de plan<br>de deux chambres fourni par le promoteur.', de: 'Ein vom Bauträger bereitgestelltes<br>Beispiel für einen Zweizimmer-Grundriss.', ru: 'Пример планировки<br>с двумя спальнями от застройщика.', ar: 'مثال لمخطط<br>بغرفتي نوم مقدَّم من المطور.', nl: 'Een door de ontwikkelaar aangeleverd<br>voorbeeld van een indeling met twee slaapkamers.', pl: 'Przykładowy układ<br>z dwiema sypialniami dostarczony przez dewelopera.', sv: 'Ett exempel på planlösning<br>med två sovrum, tillhandahållet av utvecklaren.', no: 'Et eksempel på en planløsning<br>med to soverom, levert av utbygger.' },
  { find: 'The drawing shows the open living–kitchen area, two bedrooms and a covered terrace. Exact areas and orientation vary by home.', es: 'El plano muestra el salón-cocina diáfano, dos dormitorios y una terraza cubierta. Las superficies exactas y la orientación varían según la vivienda.', fr: 'Le plan montre l’espace séjour-cuisine ouvert, deux chambres et une terrasse couverte. Les surfaces exactes et l’orientation varient selon le logement.', de: 'Die Zeichnung zeigt den offenen Wohn-Koch-Bereich, zwei Schlafzimmer und eine überdachte Terrasse. Genaue Flächen und Ausrichtung variieren je nach Wohnung.', ru: 'На чертеже показаны объединённая кухня-гостиная, две спальни и крытая терраса. Точные площади и ориентация различаются в зависимости от резиденции.', ar: 'يوضح الرسم مساحة المعيشة والمطبخ المفتوحة وغرفتَي نوم وتراسًا مغطى. تختلف المساحات الدقيقة والاتجاه حسب المسكن.', nl: 'De tekening toont de open woonkamer-keuken, twee slaapkamers en een overdekt terras. De exacte oppervlaktes en oriëntatie variëren per woning.', pl: 'Rysunek przedstawia otwartą strefę dzienną z kuchnią, dwie sypialnie i zadaszony taras. Dokładne metraże i orientacja różnią się w zależności od domu.', sv: 'Ritningen visar den öppna vardagsrums- och köksdelen, två sovrum och en täckt terrass. Exakta ytor och orientering varierar mellan bostäderna.', no: 'Tegningen viser den åpne stue- og kjøkkenløsningen, to soverom og en overbygd terrasse. Nøyaktige arealer og orientering varierer fra bolig til bolig.' },

  { find: '08 — Iconic Residences', es: '08 — Residencias Iconic', fr: '08 — Résidences Iconic', de: '08 — Iconic-Residenzen', ru: '08 — Резиденции Iconic', ar: '08 — مساكن Iconic', nl: '08 — Iconic-Residenties', pl: '08 — Rezydencje Iconic', sv: '08 — Iconic-Residens', no: '08 — Iconic-Residenser' },
  { find: 'Corner homes with<br>larger private exteriors.', es: 'Viviendas en esquina con<br>mayores exteriores privados.', fr: 'Des logements d’angle aux<br>extérieurs privés plus vastes.', de: 'Eckwohnungen mit<br>größeren privaten Außenbereichen.', ru: 'Угловые резиденции<br>с большими приватными террасами.', ar: 'مساكن ركنية بمساحات<br>خارجية خاصة أوسع.', nl: 'Hoekwoningen met<br>grotere privé buitenruimtes.', pl: 'Domy narożne z<br>większymi prywatnymi przestrzeniami zewnętrznymi.', sv: 'Hörnbostäder med<br>större privata uteytor.', no: 'Hjørneboliger med<br>større private uteområder.' },
  { find: 'Iconic Residences are single-level corner homes with extra-large terraces and an integrated private pool.', es: 'Las Iconic Residences son viviendas en esquina de una sola planta con terrazas de gran tamaño y piscina privada integrada.', fr: 'Les Iconic Residences sont des logements d’angle de plain-pied avec de très grandes terrasses et une piscine privée intégrée.', de: 'Die Iconic Residences sind eingeschossige Eckwohnungen mit besonders großen Terrassen und integriertem Privatpool.', ru: 'Iconic Residences — одноуровневые угловые резиденции с очень большими террасами и встроенным частным бассейном.', ar: 'مساكن Iconic هي وحدات ركنية بمستوى واحد مع تراسات كبيرة للغاية ومسبح خاص مدمج.', nl: 'Iconic Residences zijn eenlaagse hoekwoningen met extra grote terrassen en een geïntegreerd privézwembad.', pl: 'Iconic Residences to jednopoziomowe domy narożne z wyjątkowo dużymi tarasami i wbudowanym prywatnym basenem.', sv: 'Iconic Residences är enplans hörnbostäder med extra stora terrasser och en integrerad privat pool.', no: 'Iconic Residences er enetasjes hjørneboliger med ekstra store terrasser og et integrert privat basseng.' },

  { find: '09 — Iconic Plan', es: '09 — Plano Iconic', fr: '09 — Plan Iconic', de: '09 — Iconic-Grundriss', ru: '09 — Планировка Iconic', ar: '09 — مخطط Iconic', nl: '09 — Iconic-Plattegrond', pl: '09 — Plan Iconic', sv: '09 — Iconic-Planlösning', no: '09 — Iconic-Plantegning' },
  { find: 'An illustrative corner home<br>with its own pool.', es: 'Una vivienda en esquina de ejemplo<br>con piscina propia.', fr: 'Un logement d’angle à titre indicatif<br>avec sa propre piscine.', de: 'Eine beispielhafte Eckwohnung<br>mit eigenem Pool.', ru: 'Пример угловой резиденции<br>с собственным бассейном.', ar: 'مسكن ركني توضيحي<br>بمسبح خاص به.', nl: 'Een illustratieve hoekwoning<br>met eigen zwembad.', pl: 'Poglądowy dom narożny<br>z własnym basenem.', sv: 'Ett illustrativt hörnhem<br>med egen pool.', no: 'En illustrerende hjørnebolig<br>med eget basseng.' },
  { find: 'The supplied plan shows two bedrooms, an open living–kitchen area and a wraparound terrace. Unit-specific details must be confirmed.', es: 'El plano facilitado muestra dos dormitorios, un salón-cocina diáfano y una terraza envolvente. Los detalles concretos de cada vivienda deben confirmarse.', fr: 'Le plan fourni montre deux chambres, un espace séjour-cuisine ouvert et une terrasse enveloppante. Les détails propres à chaque logement doivent être confirmés.', de: 'Der bereitgestellte Grundriss zeigt zwei Schlafzimmer, einen offenen Wohn-Koch-Bereich und eine umlaufende Terrasse. Wohnungsspezifische Details sind zu bestätigen.', ru: 'Предоставленный план показывает две спальни, объединённую кухню-гостиную и опоясывающую террасу. Детали по конкретной резиденции требуют подтверждения.', ar: 'يوضح المخطط المقدَّم غرفتَي نوم ومساحة معيشة ومطبخ مفتوحة وتراسًا محيطًا. يجب تأكيد التفاصيل الخاصة بكل وحدة.', nl: 'De aangeleverde plattegrond toont twee slaapkamers, een open woonkamer-keuken en een terras rondom. Unitspecifieke details moeten worden bevestigd.', pl: 'Dostarczony plan przedstawia dwie sypialnie, otwartą strefę dzienną z kuchnią i taras otaczający budynek. Szczegóły dotyczące konkretnego lokalu wymagają potwierdzenia.', sv: 'Den tillhandahållna planlösningen visar två sovrum, en öppen vardagsrums- och köksdel och en terrass som löper runt hörnet. Enhetsspecifika detaljer måste bekräftas.', no: 'Den leverte plantegningen viser to soverom, en åpen stue- og kjøkkenløsning og en terrasse som går rundt hjørnet. Enhetsspesifikke detaljer må bekreftes.' },

  { find: '10 — Sky Villas', es: '10 — Sky Villas', fr: '10 — Sky Villas', de: '10 — Sky Villas', ru: '10 — Sky Villas', ar: '10 — Sky Villas', nl: '10 — Sky Villas', pl: '10 — Sky Villas', sv: '10 — Sky Villas', no: '10 — Sky Villas' },
  { find: 'Duplex penthouses<br>with private rooftops.', es: 'Áticos dúplex<br>con azoteas privadas.', fr: 'Penthouses duplex<br>avec toits-terrasses privés.', de: 'Duplex-Penthäuser<br>mit privaten Dachterrassen.', ru: 'Двухуровневые пентхаусы<br>с частными крышами.', ar: 'بنتهاوس دوبلكس<br>بأسطح خاصة.', nl: 'Duplex penthouses<br>met privé dakterrassen.', pl: 'Dwupoziomowe penthouse\'y<br>z prywatnymi tarasami na dachu.', sv: 'Duplexpenthouse<br>med privata takterrasser.', no: 'Duplexpenthus<br>med private takterrasser.' },
  { find: 'Sky Villas add expansive terraces, a solarium and a private pool, with open outlooks towards the Mediterranean and La Concha.', es: 'Las Sky Villas suman terrazas de gran amplitud, solárium y piscina privada, con vistas despejadas al Mediterráneo y a La Concha.', fr: 'Les Sky Villas ajoutent de vastes terrasses, un solarium et une piscine privée, avec des vues dégagées sur la Méditerranée et La Concha.', de: 'Die Sky Villas bieten zusätzlich weitläufige Terrassen, ein Solarium und einen Privatpool mit freiem Blick auf das Mittelmeer und La Concha.', ru: 'Sky Villas добавляют просторные террасы, солярий и частный бассейн с открытыми видами на Средиземное море и Ла-Кончу.', ar: 'تضيف Sky Villas تراسات فسيحة وسطحًا شمسيًا ومسبحًا خاصًا مع إطلالات مفتوحة على البحر المتوسط وجبل لا كونتشا.', nl: 'Sky Villas bieden extra ruime terrassen, een solarium en een privézwembad, met open uitzicht op de Middellandse Zee en La Concha.', pl: 'Sky Villas oferują rozległe tarasy, solarium i prywatny basen, z otwartym widokiem na Morze Śródziemne i La Concha.', sv: 'Sky Villas tillför vidsträckta terrasser, ett solarium och en privat pool, med öppen utsikt mot Medelhavet och La Concha.', no: 'Sky Villas tilfører vidstrakte terrasser, et solarium og et privat basseng, med åpen utsikt mot Middelhavet og La Concha.' },

  { find: '11 — Sky Villa Plan', es: '11 — Plano de Sky Villa', fr: '11 — Plan de Sky Villa', de: '11 — Sky-Villa-Grundriss', ru: '11 — Планировка Sky Villa', ar: '11 — مخطط Sky Villa', nl: '11 — Sky Villa-Plattegrond', pl: '11 — Plan Sky Villa', sv: '11 — Sky Villa-Planlösning', no: '11 — Sky Villa-Plantegning' },
  { find: 'Two levels,<br>four bedrooms and a pool.', es: 'Dos plantas,<br>cuatro dormitorios y piscina.', fr: 'Deux niveaux,<br>quatre chambres et une piscine.', de: 'Zwei Ebenen,<br>vier Schlafzimmer und ein Pool.', ru: 'Два уровня,<br>четыре спальни и бассейн.', ar: 'مستويان<br>وأربع غرف نوم ومسبح.', nl: 'Twee verdiepingen,<br>vier slaapkamers en een zwembad.', pl: 'Dwa poziomy,<br>cztery sypialnie i basen.', sv: 'Två plan,<br>fyra sovrum och en pool.', no: 'To etasjer,<br>fire soverom og et basseng.' },
  { find: 'This supplied example places the bedrooms on the lower level and the living space, terraces and pool above. Exact layouts vary.', es: 'Este ejemplo facilitado sitúa los dormitorios en la planta inferior y el salón, las terrazas y la piscina en la superior. Las distribuciones exactas varían.', fr: 'Cet exemple fourni place les chambres au niveau inférieur et le séjour, les terrasses et la piscine à l’étage. Les plans exacts varient.', de: 'Dieses bereitgestellte Beispiel platziert die Schlafzimmer auf der unteren Ebene und Wohnbereich, Terrassen und Pool darüber. Die genauen Grundrisse variieren.', ru: 'В этом примере спальни расположены на нижнем уровне, а гостиная, террасы и бассейн — на верхнем. Точные планировки различаются.', ar: 'يضع هذا المثال المقدَّم غرف النوم في المستوى السفلي ومساحة المعيشة والتراسات والمسبح في الأعلى. تختلف المخططات الدقيقة.', nl: 'In dit aangeleverde voorbeeld bevinden de slaapkamers zich op het onderste niveau en de woonruimte, terrassen en het zwembad erboven. De exacte indelingen variëren.', pl: 'W tym przykładowym układzie sypialnie znajdują się na niższym poziomie, a strefa dzienna, tarasy i basen powyżej. Dokładne układy różnią się między sobą.', sv: 'I detta exempel ligger sovrummen på den nedre nivån och vardagsrummet, terrasserna och poolen ovanför. Exakta planlösningar varierar.', no: 'I dette eksempelet ligger soverommene på det nedre nivået, mens stue, terrasser og basseng befinner seg over. Nøyaktige planløsninger varierer.' },

  { find: '12 — Masterplan', es: '12 — Plan General', fr: '12 — Plan d’Ensemble', de: '12 — Masterplan', ru: '12 — Генеральный План', ar: '12 — المخطط العام', nl: '12 — Masterplan', pl: '12 — Plan Generalny', sv: '12 — Masterplan', no: '12 — Masterplan' },
  { find: 'Shared life arranged<br>across the community.', es: 'La vida en común,<br>distribuida por toda la comunidad.', fr: 'La vie collective,<br>répartie dans toute la résidence.', de: 'Gemeinschaftsleben,<br>über die Anlage verteilt.', ru: 'Общественная жизнь,<br>распределённая по комплексу.', ar: 'حياة مشتركة<br>موزعة عبر المجمع.', nl: 'Gedeeld leven verspreid<br>over de gemeenschap.', pl: 'Wspólne życie rozłożone<br>na terenie całego osiedla.', sv: 'Gemensamt liv fördelat<br>över hela boendet.', no: 'Fællesskap fordelt<br>utover hele bomiljøet.' },
  { find: 'The supplied masterplan locates the courtyard pool, rooftop sky pool and yoga area, gym and spa, and ground-floor business hub.', es: 'El plan general facilitado sitúa la piscina del patio, la piscina y la zona de yoga en la azotea, el gimnasio y el spa, y el centro de negocios en planta baja.', fr: 'Le plan d’ensemble fourni situe la piscine de la cour, la piscine et l’espace yoga en toiture, la salle de sport et le spa, ainsi que l’espace de travail en rez-de-chaussée.', de: 'Der bereitgestellte Masterplan verortet den Innenhofpool, den Dachpool mit Yogabereich, Fitnessstudio und Spa sowie den Business-Hub im Erdgeschoss.', ru: 'Предоставленный генеральный план показывает бассейн во дворе, бассейн и зону йоги на крыше, тренажёрный зал и спа, а также бизнес-хаб на первом этаже.', ar: 'يحدد المخطط العام المقدَّم موقع مسبح الفناء ومسبح السطح ومنطقة اليوغا وصالة الرياضة والسبا ومركز الأعمال في الطابق الأرضي.', nl: 'Het aangeleverde masterplan situeert het binnenzwembad, het dakzwembad met yogaruimte, de sportschool en spa, en het businesscentrum op de begane grond.', pl: 'Dostarczony plan generalny lokalizuje basen na dziedzińcu, basen na dachu wraz ze strefą jogi, siłownię i spa oraz centrum biznesowe na parterze.', sv: 'Den tillhandahållna masterplanen placerar gårdspoolen, takpoolen med yogaområde, gym och spa, samt affärshubben i bottenvåningen.', no: 'Den leverte masterplanen plasserer gårdsbassenget, takbassenget med yogaområde, treningssenter og spa, samt forretningshuben i første etasje.' },

  { find: '13 — Outdoor Pool', es: '13 — Piscina Exterior', fr: '13 — Piscine Extérieure', de: '13 — Außenpool', ru: '13 — Открытый Бассейн', ar: '13 — المسبح الخارجي', nl: '13 — Buitenzwembad', pl: '13 — Basen Zewnętrzny', sv: '13 — Utomhuspool', no: '13 — Utendørsbasseng' },
  { find: 'A landscaped pool<br>at the heart of the site.', es: 'Una piscina ajardinada<br>en el corazón del conjunto.', fr: 'Une piscine paysagée<br>au cœur du site.', de: 'Ein begrünter Pool<br>im Herzen der Anlage.', ru: 'Озеленённый бассейн<br>в сердце комплекса.', ar: 'مسبح منسق<br>في قلب الموقع.', nl: 'Een aangelegd zwembad<br>in het hart van het complex.', pl: 'Zagospodarowany basen<br>w sercu kompleksu.', sv: 'En iordningställd pool<br>i hjärtat av området.', no: 'Et opparbeidet basseng<br>i hjertet av området.' },
  { find: 'The central pool sits inside the planted courtyard, creating a protected shared space between the residences.', es: 'La piscina central se sitúa dentro del patio ajardinado, creando un espacio común protegido entre las viviendas.', fr: 'La piscine centrale s’installe dans la cour végétalisée, créant un espace partagé protégé entre les résidences.', de: 'Der zentrale Pool liegt im bepflanzten Innenhof und schafft einen geschützten Gemeinschaftsbereich zwischen den Residenzen.', ru: 'Центральный бассейн расположен в озеленённом дворе, образуя защищённое общее пространство между резиденциями.', ar: 'يقع المسبح المركزي داخل الفناء المزروع، مكوّنًا مساحة مشتركة محمية بين المساكن.', nl: 'Het centrale zwembad ligt binnen de beplante binnenplaats en creëert zo een beschutte gedeelde ruimte tussen de woningen.', pl: 'Centralny basen znajduje się w obsadzonym zielenią dziedzińcu, tworząc osłoniętą, wspólną przestrzeń pomiędzy budynkami.', sv: 'Den centrala poolen ligger inne i den planterade innergården och skapar ett skyddat gemensamt utrymme mellan bostäderna.', no: 'Det sentrale bassenget ligger inne i det beplantede gårdsrommet og skaper et skjermet fellesareal mellom boligene.' },

  { find: '14 — Rooftop Lounge', es: '14 — Salón en la Azotea', fr: '14 — Salon sur le Toit', de: '14 — Dach-Lounge', ru: '14 — Лаундж на Крыше', ar: '14 — صالة السطح', nl: '14 — Dakterras Lounge', pl: '14 — Lounge na Dachu', sv: '14 — Takloungen', no: '14 — Takloungen' },
  { find: 'An adults-only rooftop<br>above the gardens.', es: 'Una azotea solo para adultos<br>sobre los jardines.', fr: 'Un toit réservé aux adultes<br>au-dessus des jardins.', de: 'Eine Dachebene nur für Erwachsene<br>über den Gärten.', ru: 'Крыша только для взрослых<br>над садами.', ar: 'سطح مخصص للبالغين<br>يعلو الحدائق.', nl: 'Een dakterras alleen voor volwassenen<br>boven de tuinen.', pl: 'Dach tylko dla dorosłych<br>ponad ogrodami.', sv: 'En takterrass enbart för vuxna<br>ovanför trädgårdarna.', no: 'En takterrasse kun for voksne<br>over hagene.' },
  { find: 'The rooftop layer includes an infinity pool and lounge area, designed around long coastal views.', es: 'El nivel de azotea incluye una piscina infinita y una zona de estar, diseñadas en torno a amplias vistas al litoral.', fr: 'Le niveau en toiture comprend une piscine à débordement et un espace salon, conçus autour de larges vues sur le littoral.', de: 'Die Dachebene umfasst einen Infinity-Pool und einen Loungebereich, ausgerichtet auf weite Küstenblicke.', ru: 'Уровень крыши включает бассейн-инфинити и лаундж-зону, спроектированные вокруг протяжённых видов на побережье.', ar: 'يضم مستوى السطح مسبحًا لامتناهيًا ومنطقة صالة، مصمَّمين حول إطلالات ساحلية ممتدة.', nl: 'De daklaag omvat een infinity pool en loungeruimte, ontworpen rond weidse kustuitzichten.', pl: 'Poziom na dachu obejmuje basen typu infinity i strefę lounge, zaprojektowane wokół rozległych widoków na wybrzeże.', sv: 'Taknivån omfattar en infinitypool och en loungeyta, utformade kring vidsträckta havsutsikter.', no: 'Taknivået omfatter et infinitybasseng og en loungesone, utformet rundt vide utsikter mot kysten.' },

  { find: '15 — Rooftop Yoga', es: '15 — Yoga en la Azotea', fr: '15 — Yoga sur le Toit', de: '15 — Dach-Yoga', ru: '15 — Йога на Крыше', ar: '15 — يوغا على السطح', nl: '15 — Yoga op het Dak', pl: '15 — Joga na Dachu', sv: '15 — Yoga på Taket', no: '15 — Yoga på Taket' },
  { find: 'Morning movement<br>with La Concha beyond.', es: 'Movimiento matinal<br>con La Concha al fondo.', fr: 'Mouvement matinal<br>avec La Concha en toile de fond.', de: 'Morgendliche Bewegung<br>mit La Concha im Hintergrund.', ru: 'Утренняя практика<br>с Ла-Кончей на горизонте.', ar: 'حركة صباحية<br>وجبل لا كونتشا في الأفق.', nl: 'Ochtendbeweging<br>met La Concha op de achtergrond.', pl: 'Poranny ruch<br>z La Concha w tle.', sv: 'Morgonrörelse<br>med La Concha i bakgrunden.', no: 'Morgentrening<br>med La Concha i bakgrunnen.' },
  { find: 'A dedicated rooftop yoga deck adds a quieter wellness space above the wider amenity programme.', es: 'Una plataforma de yoga en la azotea añada un espacio de bienestar más tranquilo por encima del resto de zonas comunes.', fr: 'Une plateforme de yoga dédiée en toiture ajoute un espace bien-être plus calme au-dessus de l’ensemble des prestations.', de: 'Ein eigenes Yoga-Deck auf dem Dach ergänzt das Angebot um einen ruhigeren Wellnessbereich.', ru: 'Отдельная площадка для йоги на крыше добавляет более тихое велнес-пространство над остальной инфраструктурой.', ar: 'تضيف منصة يوغا مخصصة على السطح مساحة عافية أكثر هدوءًا فوق باقي المرافق.', nl: 'Een speciaal yogadek op het dak voegt een rustigere wellnessruimte toe boven het bredere voorzieningenaanbod.', pl: 'Dedykowany taras jogi na dachu wprowadza spokojniejszą przestrzeń wellness ponad szerszym programem udogodnień.', sv: 'Ett dedikerat yogadäck på taket tillför en lugnare wellnessyta ovanför det bredare utbudet av bekvämligheter.', no: 'Et eget yogadekk på taket gir en roligere velværesone over det bredere fasilitetstilbudet.' },

  { find: '16 — Indoor Lap Pool', es: '16 — Piscina Interior de Natación', fr: '16 — Bassin de Nage Intérieur', de: '16 — Innen-Schwimmbecken', ru: '16 — Крытый Бассейн для Плавания', ar: '16 — مسبح سباحة داخلي', nl: '16 — Binnenzwembad', pl: '16 — Kryty Basen', sv: '16 — Inomhusbassäng', no: '16 — Innendørs Svømmebasseng' },
  { find: 'Training and recovery<br>throughout the year.', es: 'Entrenamiento y recuperación<br>durante todo el año.', fr: 'Entraînement et récupération<br>tout au long de l’année.', de: 'Training und Regeneration<br>das ganze Jahr über.', ru: 'Тренировки и восстановление<br>круглый год.', ar: 'تدريب واستشفاء<br>على مدار العام.', nl: 'Trainen en herstellen<br>het hele jaar door.', pl: 'Trening i regeneracja<br>przez cały rok.', sv: 'Träning och återhämtning<br>året runt.', no: 'Trening og restitusjon<br>hele året.' },
  { find: 'The indoor lap pool forms part of a broader wellness hub rather than a single-purpose gym area.', es: 'La piscina interior de natación forma parte de un centro de bienestar más amplio, no de una simple zona de gimnasio.', fr: 'Le bassin de nage intérieur s’inscrit dans un pôle bien-être plus large plutôt que dans une simple salle de sport.', de: 'Das Innen-Schwimmbecken ist Teil eines umfassenderen Wellnessbereichs und nicht nur eine Fitnesszone.', ru: 'Крытый бассейн для плавания — часть более широкого велнес-центра, а не просто тренажёрной зоны.', ar: 'يشكل مسبح السباحة الداخلي جزءًا من مركز عافية أوسع وليس مجرد منطقة رياضية.', nl: 'Het binnenzwembad maakt deel uit van een breder wellnesscentrum in plaats van een op zichzelf staande fitnessruimte.', pl: 'Kryty basen stanowi część szerszego centrum wellness, a nie odrębnej strefy siłowni.', sv: 'Inomhusbassängen är en del av en bredare wellnesshubb snarare än en fristående gymyta.', no: 'Det innendørs svømmebassenget er en del av en bredere velværehub, ikke bare en treningssone.' },

  { find: '17 — Wellness Hub', es: '17 — Centro de Bienestar', fr: '17 — Pôle Bien-Être', de: '17 — Wellness-Hub', ru: '17 — Велнес-Центр', ar: '17 — مركز العافية', nl: '17 — Wellnesscentrum', pl: '17 — Centrum Wellness', sv: '17 — Wellnesshubb', no: '17 — Velværehub' },
  { find: 'Heat, water and<br>purposeful recovery.', es: 'Calor, agua y<br>recuperación con propósito.', fr: 'Chaleur, eau et<br>récupération ciblée.', de: 'Wärme, Wasser und<br>gezielte Regeneration.', ru: 'Тепло, вода<br>и осознанное восстановление.', ar: 'حرارة وماء<br>واستشفاء هادف.', nl: 'Warmte, water en<br>doelgericht herstel.', pl: 'Ciepło, woda i<br>ukierunkowana regeneracja.', sv: 'Värme, vatten och<br>målinriktad återhämtning.', no: 'Varme, vann og<br>målrettet restitusjon.' },
  { find: 'The supplied programme includes sauna, steam bath, hydromassage, contrast pool and red-light therapy alongside fitness facilities.', es: 'El programa facilitado incluye sauna, baño de vapor, hidromasaje, piscina de contrastes y terapia de luz roja junto a las instalaciones de fitness.', fr: 'Le programme fourni comprend sauna, hammam, hydromassage, bassin de contraste et luminothérapie rouge, en complément des installations de fitness.', de: 'Das bereitgestellte Programm umfasst Sauna, Dampfbad, Hydromassage, Kontrastbecken und Rotlichttherapie neben den Fitnessanlagen.', ru: 'Заявленная программа включает сауну, паровую баню, гидромассаж, контрастный бассейн и терапию красным светом наряду с фитнес-зонами.', ar: 'يشمل البرنامج المقدَّم ساونا وحمام بخار وتدليكًا مائيًا وحوض تباين حراري وعلاجًا بالضوء الأحمر إلى جانب مرافق اللياقة.', nl: 'Het aangeleverde programma omvat sauna, stoombad, hydromassage, contrastbad en rodelichttherapie naast fitnessfaciliteiten.', pl: 'Dostarczony program obejmuje saunę, łaźnię parową, hydromasaż, basen kontrastowy i terapię czerwonym światłem obok strefy fitness.', sv: 'Det tillhandahållna programmet omfattar bastu, ångbad, hydromassage, kontrastbad och rödljusterapi vid sidan av gymfaciliteter.', no: 'Det leverte programmet omfatter badstue, dampbad, hydromassasje, kontrastbasseng og rødlysterapi i tillegg til treningsfasiliteter.' },

  { find: '18 — Business Hub', es: '18 — Centro de Negocios', fr: '18 — Espace de Travail', de: '18 — Business-Hub', ru: '18 — Бизнес-Хаб', ar: '18 — مركز الأعمال', nl: '18 — Businesscentrum', pl: '18 — Centrum Biznesowe', sv: '18 — Affärshubb', no: '18 — Forretningshub' },
  { find: 'A practical layer<br>for longer stays.', es: 'Un recurso práctico<br>para estancias largas.', fr: 'Un espace pratique<br>pour les séjours prolongés.', de: 'Eine praktische Ebene<br>für längere Aufenthalte.', ru: 'Практичное решение<br>для длительного пребывания.', ar: 'مساحة عملية<br>للإقامات الطويلة.', nl: 'Een praktische laag<br>voor langere verblijven.', pl: 'Praktyczny element<br>dla dłuższych pobytów.', sv: 'En praktisk dimension<br>för längre vistelser.', no: 'Et praktisk tillegg<br>for lengre opphold.' },
  { find: 'Dedicated work space supports buyers using the property as a primary home or for extended periods on the coast.', es: 'El espacio de trabajo específico da soporte a los compradores que usan la vivienda como residencia principal o para estancias prolongadas en la costa.', fr: 'Un espace de travail dédié accompagne les acquéreurs utilisant le bien comme résidence principale ou pour de longues périodes sur la côte.', de: 'Ein eigener Arbeitsbereich unterstützt Käufer, die die Immobilie als Hauptwohnsitz oder für längere Zeiträume an der Küste nutzen.', ru: 'Отдельная рабочая зона рассчитана на покупателей, использующих жильё как основное или для длительного пребывания на побережье.', ar: 'تدعم مساحة العمل المخصصة المشترين الذين يستخدمون العقار كمسكن رئيسي أو لفترات طويلة على الساحل.', nl: 'Speciale werkruimte ondersteunt kopers die de woning als hoofdverblijf gebruiken of voor langere periodes aan de kust.', pl: 'Dedykowana przestrzeń do pracy wspiera nabywców korzystających z nieruchomości jako głównego domu lub podczas dłuższych pobytów na wybrzeżu.', sv: 'Dedikerat arbetsutrymme stödjer köpare som använder bostaden som permanentbostad eller för längre perioder på kusten.', no: 'Dedikert arbeidsplass støtter kjøpere som bruker boligen som hovedbolig eller for lengre opphold på kysten.' },

  { find: '19 — Social Life', es: '19 — Vida Social', fr: '19 — Vie Sociale', de: '19 — Gemeinschaftsleben', ru: '19 — Общественная Жизнь', ar: '19 — الحياة الاجتماعية', nl: '19 — Sociaal Leven', pl: '19 — Życie Towarzyskie', sv: '19 — Socialt Liv', no: '19 — Sosialt Liv' },
  { find: 'Shared rooms for<br>family and downtime.', es: 'Salas comunes para<br>la familia y el ocio.', fr: 'Des espaces partagés pour<br>la famille et la détente.', de: 'Gemeinschaftsräume für<br>Familie und Freizeit.', ru: 'Общие залы для<br>семьи и отдыха.', ar: 'غرف مشتركة<br>للعائلة وأوقات الاسترخاء.', nl: 'Gedeelde ruimtes voor<br>familie en ontspanning.', pl: 'Wspólne pomieszczenia dla<br>rodziny i chwil odpoczynku.', sv: 'Gemensamma rum för<br>familj och avkoppling.', no: 'Fellesrom for<br>familie og avslapning.' },
  { find: 'The project adds social areas, a cinema, sports corner and children’s room to the residential and wellness spaces.', es: 'El proyecto añada zonas sociales, cine, rincón deportivo y sala infantil a los espacios residenciales y de bienestar.', fr: 'Le projet ajoute des espaces conviviaux, un cinéma, un coin sport et une salle pour enfants aux espaces résidentiels et bien-être.', de: 'Das Projekt ergänzt die Wohn- und Wellnessbereiche um Gemeinschaftsflächen, ein Kino, eine Sportecke und einen Kinderraum.', ru: 'Проект дополняет жилые и велнес-зоны общественными пространствами, кинозалом, спортивным уголком и детской комнатой.', ar: 'يضيف المشروع مناطق اجتماعية وصالة سينما وركنًا رياضيًا وغرفة للأطفال إلى المساحات السكنية ومرافق العافية.', nl: 'Het project voegt sociale ruimtes, een bioscoopzaal, een sporthoek en een kinderkamer toe aan de woon- en wellnessruimtes.', pl: 'Projekt dodaje strefy towarzyskie, kino, kącik sportowy i pokój dla dzieci do przestrzeni mieszkalnych i wellness.', sv: 'Projektet tillför sociala ytor, en biosalong, ett sportshörn och ett barnrum till bostads- och wellnessutrymmena.', no: 'Prosjektet tilfører sosiale soner, en kinosal, et sportshjørne og et barnerom til bolig- og velværearealene.' },

  { find: '20 — Current Release', es: '20 — Fase Actual', fr: '20 — Phase Actuelle', de: '20 — Aktuelle Phase', ru: '20 — Текущая Очередь', ar: '20 — المرحلة الحالية', nl: '20 — Huidige Fase', pl: '20 — Aktualna Faza', sv: '20 — Nuvarande Fas', no: '20 — Nåværende Fase' },
  { find: 'Marbella West Gardens,<br>details available by request.', es: 'Marbella West Gardens,<br>información disponible bajo petición.', fr: 'Marbella West Gardens,<br>informations disponibles sur demande.', de: 'Marbella West Gardens,<br>Details auf Anfrage erhältlich.', ru: 'Marbella West Gardens,<br>подробности по запросу.', ar: 'Marbella West Gardens،<br>التفاصيل متاحة عند الطلب.', nl: 'Marbella West Gardens,<br>details beschikbaar op aanvraag.', pl: 'Marbella West Gardens,<br>szczegóły dostępne na życzenie.', sv: 'Marbella West Gardens,<br>detaljer tillgängliga på begäran.', no: 'Marbella West Gardens,<br>detaljer tilgjengelig på forespørsel.' },
  { find: 'Ask for the latest price list, unit availability, floorplans, payment terms and a private presentation before choosing a residence.', es: 'Solicite la lista de precios actualizada, la disponibilidad de viviendas, los planos, las condiciones de pago y una presentación privada antes de elegir una residencia.', fr: 'Demandez la dernière liste de prix, la disponibilité des logements, les plans, les conditions de paiement et une présentation privée avant de choisir une résidence.', de: 'Fordern Sie die aktuelle Preisliste, die Verfügbarkeit, Grundrisse, Zahlungsbedingungen und eine private Präsentation an, bevor Sie sich für eine Residenz entscheiden.', ru: 'Запросите актуальный прайс-лист, наличие резиденций, планировки, условия оплаты и частную презентацию, прежде чем сделать выбор.', ar: 'اطلب أحدث قائمة أسعار وتوافر الوحدات والمخططات وشروط الدفع وعرضًا خاصًا قبل اختيار المسكن.', nl: 'Vraag naar de meest recente prijslijst, beschikbaarheid, plattegronden, betalingsvoorwaarden en een privé presentatie voordat u een woning kiest.', pl: 'Poproś o aktualny cennik, dostępność lokali, rzuty, warunki płatności i prywatną prezentację przed wyborem rezydencji.', sv: 'Fråga efter den senaste prislistan, tillgänglighet, planritningar, betalningsvillkor och en privat presentation innan ni väljer bostad.', no: 'Be om den nyeste prislisten, tilgjengelighet, plantegninger, betalingsvilkår og en privat presentasjon før du velger bolig.' },

  // ===== Cancelada Park (12 scenes)
  { find: '01 — Cancelada Park', es: '01 — Cancelada Park', fr: '01 — Cancelada Park', de: '01 — Cancelada Park', ru: '01 — Cancelada Park', ar: '01 — Cancelada Park', nl: '01 — Cancelada Park', pl: '01 — Cancelada Park', sv: '01 — Cancelada Park', no: '01 — Cancelada Park' },
  { find: 'Low-rise residences<br>on the New Golden Mile.', es: 'Viviendas de baja altura<br>en la Nueva Milla de Oro.', fr: 'Des résidences de faible hauteur<br>sur la New Golden Mile.', de: 'Niedriggeschossige Residenzen<br>an der New Golden Mile.', ru: 'Малоэтажные резиденции<br>на Новой Золотой миле.', ar: 'مساكن منخفضة الارتفاع<br>على الميل الذهبي الجديد.', nl: 'Laagbouwwoningen<br>aan de New Golden Mile.', pl: 'Niskie zabudowania mieszkalne<br>przy New Golden Mile.', sv: 'Låghusbostäder<br>vid New Golden Mile.', no: 'Lavblokkboliger<br>ved New Golden Mile.' },
  { find: 'The opening view shows the residential phase, landscaped pool gardens and its position within a wider resort setting.', es: 'La vista inicial muestra la fase residencial, los jardines ajardinados con piscina y su posición dentro de un entorno de resort más amplio.', fr: 'La vue d’ouverture montre la phase résidentielle, les jardins paysagers avec piscine et sa position au sein d’un ensemble resort plus vaste.', de: 'Die Eröffnungsansicht zeigt die Wohnphase, die angelegten Poolgärten und ihre Lage innerhalb einer größeren Resortanlage.', ru: 'Первый кадр показывает жилую очередь, озеленённые сады с бассейном и её расположение в составе более крупного курортного комплекса.', ar: 'يُظهر المشهد الافتتاحي المرحلة السكنية وحدائق المسبح المنسقة وموقعها ضمن منتجع أوسع.', nl: 'Het openingsbeeld toont de woonfase, aangelegde zwembadtuinen en de ligging binnen een breder resortgeheel.', pl: 'Pierwszy widok pokazuje fazę mieszkalną, zagospodarowane ogrody z basenem oraz jej położenie w ramach szerszego kompleksu resortowego.', sv: 'Den inledande vyn visar bostadsetappen, iordningställda poolsträdgårdar och dess placering inom en större resortmiljö.', no: 'Åpningsbildet viser boligfasen, opparbeidede bassenghager og plasseringen innenfor en større resortsetting.' },

  { find: 'Clean white volumes,<br>warmed by timber.', es: 'Volúmenes blancos y puros,<br>templados por la madera.', fr: 'Des volumes blancs épurés,<br>réchauffés par le bois.', de: 'Klare weiße Baukörper,<br>erwärmt durch Holz.', ru: 'Чистые белые объёмы,<br>согретые деревом.', ar: 'كتل بيضاء نقية<br>يدفئها الخشب.', nl: 'Strakke witte volumes,<br>verwarmd door hout.', pl: 'Czyste, białe bryły,<br>ocieplone drewnem.', sv: 'Rena vita volymer,<br>värmda av trä.', no: 'Rene hvite volumer,<br>varmet opp av tre.' },
  { find: 'Pablo Villarroel shapes the buildings around broad glazing, planted terraces and a contemporary Mediterranean material palette.', es: 'Pablo Villarroel configura los edificios en torno a amplios acristalamientos, terrazas ajardinadas y una paleta de materiales mediterránea contemporánea.', fr: 'Pablo Villarroel façonne les bâtiments autour de larges baies vitrées, de terrasses végétalisées et d’une palette de matériaux méditerranéenne contemporaine.', de: 'Pablo Villarroel formt die Gebäude um großflächige Verglasung, bepflanzte Terrassen und eine zeitgenössische mediterrane Materialpalette.', ru: 'Пабло Вильярроэль формирует здания вокруг панорамного остекления, озеленённых террас и современной средиземноморской палитры материалов.', ar: 'يصوغ بابلو فيلارويل المباني حول الزجاج الواسع والتراسات المزروعة ولوحة مواد متوسطية معاصرة.', nl: 'Pablo Villarroel vormt de gebouwen rond brede beglazing, beplante terrassen en een eigentijds mediterraan materialenpalet.', pl: 'Pablo Villarroel kształtuje budynki wokół rozległych przeszkleń, obsadzonych zielenią tarasów i współczesnej, śródziemnomorskiej palety materiałów.', sv: 'Pablo Villarroel formar byggnaderna kring breda glaspartier, planterade terrasser och en samtida medelhavsinspirerad materialpalett.', no: 'Pablo Villarroel former bygningene rundt store glassflater, beplantede terrasser og en samtidig middelhavsinspirert materialpalett.' },

  { find: '03 — Pool Gardens', es: '03 — Jardines con Piscina', fr: '03 — Jardins-Piscine', de: '03 — Poolgärten', ru: '03 — Сады с Бассейном', ar: '03 — حدائق المسبح', nl: '03 — Zwembadtuinen', pl: '03 — Ogrody z Basenem', sv: '03 — Poolsträdgårdar', no: '03 — Bassenghager' },
  { find: 'A protected garden<br>at the centre of the phase.', es: 'Un jardín protegido<br>en el centro de la fase.', fr: 'Un jardin protégé<br>au centre de la phase.', de: 'Ein geschützter Garten<br>im Zentrum der Phase.', ru: 'Защищённый сад<br>в центре очереди.', ar: 'حديقة محمية<br>في قلب المرحلة.', nl: 'Een beschutte tuin<br>in het hart van de fase.', pl: 'Osłonięty ogród<br>w centrum fazy.', sv: 'En skyddad trädgård<br>i mitten av etappen.', no: 'En skjermet hage<br>i sentrum av fasen.' },
  { find: 'The outdoor pool and relaxation area sit between the low-rise buildings, with planting softening the shared residential setting.', es: 'La piscina exterior y la zona de relax se sitúan entre los edificios de baja altura, con vegetación que suaviza el entorno residencial común.', fr: 'La piscine extérieure et l’espace détente s’installent entre les bâtiments bas, la végétation adoucissant le cadre résidentiel partagé.', de: 'Außenpool und Ruhebereich liegen zwischen den niedrigen Gebäuden, wobei Bepflanzung das gemeinschaftliche Wohnumfeld auflockert.', ru: 'Открытый бассейн и зона отдыха расположены между малоэтажными корпусами, а озеленение смягчает общее жилое пространство.', ar: 'يقع المسبح الخارجي ومنطقة الاسترخاء بين المباني المنخفضة، مع نباتات تلطّف البيئة السكنية المشتركة.', nl: 'Het buitenzwembad en de ontspanningsruimte liggen tussen de laagbouwgebouwen, waarbij beplanting de gedeelde woonomgeving verzacht.', pl: 'Basen zewnętrzny i strefa relaksu znajdują się pomiędzy niskimi budynkami, a zieleń łagodzi wspólną przestrzeń mieszkalną.', sv: 'Utomhuspoolen och avkopplingsytan ligger mellan låghusen, med växtlighet som mjukar upp den gemensamma boendemiljön.', no: 'Utendørsbassenget og avslapningssonen ligger mellom lavblokkene, med beplantning som mildner det felles bomiljøet.' },

  { find: '04 — Garden Residences', es: '04 — Viviendas con Jardín', fr: '04 — Résidences avec Jardin', de: '04 — Gartenresidenzen', ru: '04 — Резиденции с Садом', ar: '04 — مساكن الحدائق', nl: '04 — Tuinresidenties', pl: '04 — Rezydencje z Ogrodem', sv: '04 — Trädgårdsresidens', no: '04 — Hageresidenser' },
  { find: 'Private outdoor space<br>that works as a real room.', es: 'Un exterior privado<br>que funciona como una estancia más.', fr: 'Un extérieur privé<br>qui fonctionne comme une vraie pièce.', de: 'Privater Außenraum,<br>der als echtes Zimmer funktioniert.', ru: 'Приватное открытое пространство,<br>работающее как полноценная комната.', ar: 'مساحة خارجية خاصة<br>تعمل كغرفة حقيقية.', nl: 'Privé buitenruimte<br>die functioneert als een echte kamer.', pl: 'Prywatna przestrzeń zewnętrzna,<br>która działa jak prawdziwe pomieszczenie.', sv: 'Privat utrymme utomhus<br>som fungerar som ett riktigt rum.', no: 'Privat uteareal<br>som fungerer som et ekte rom.' },
  { find: 'Selected ground-floor homes pair large terraces with private gardens, creating a practical option for longer stays and family use.', es: 'Determinadas viviendas en planta baja combinan amplias terrazas con jardines privados, creando una opción práctica para estancias largas y uso familiar.', fr: 'Certains logements en rez-de-chaussée associent de grandes terrasses à des jardins privés, offrant une option pratique pour les longs séjours et un usage familial.', de: 'Ausgewählte Erdgeschosswohnungen verbinden große Terrassen mit privaten Gärten und bieten eine praktische Option für längere Aufenthalte und Familien.', ru: 'Отдельные резиденции на первом этаже сочетают большие террасы с частными садами — практичный вариант для длительного пребывания и семей.', ar: 'تجمع مساكن مختارة في الطابق الأرضي بين تراسات واسعة وحدائق خاصة، ما يوفر خيارًا عمليًا للإقامات الطويلة والاستخدام العائلي.', nl: 'Bepaalde woningen op de begane grond combineren grote terrassen met privétuinen, wat een praktische optie biedt voor langere verblijven en gezinsgebruik.', pl: 'Wybrane domy na parterze łączą duże tarasy z prywatnymi ogrodami, tworząc praktyczną opcję na dłuższe pobyty i użytek rodzinny.', sv: 'Utvalda bottenvåningsbostäder kombinerar stora terrasser med privata trädgårdar, vilket skapar ett praktiskt alternativ för längre vistelser och familjebruk.', no: 'Utvalgte boliger i første etasje kombinerer store terrasser med private hager, noe som gir et praktisk alternativ for lengre opphold og familiebruk.' },

  { find: '05 — Penthouses', es: '05 — Áticos', fr: '05 — Penthouses', de: '05 — Penthäuser', ru: '05 — Пентхаусы', ar: '05 — بنتهاوس', nl: '05 — Penthouses', pl: '05 — Penthouse\'y', sv: '05 — Takvåningar', no: '05 — Toppleiligheter' },
  { find: 'Upper-floor homes<br>with broad terraces.', es: 'Viviendas en planta alta<br>con amplias terrazas.', fr: 'Des logements aux étages supérieurs<br>avec de larges terrasses.', de: 'Wohnungen in den Obergeschossen<br>mit weiten Terrassen.', ru: 'Резиденции верхних этажей<br>с просторными террасами.', ar: 'مساكن في الطوابق العليا<br>بتراسات واسعة.', nl: 'Woningen op de bovenverdieping<br>met brede terrassen.', pl: 'Mieszkania na wyższych piętrach<br>z szerokimi tarasami.', sv: 'Bostäder på övre våningarna<br>med breda terrasser.', no: 'Boliger i de øvre etasjene<br>med brede terrasser.' },
  { find: 'The penthouse release adds generous exterior areas and selected rooftop solariums, with three- and four-bedroom layouts.', es: 'La fase de áticos añada generosas zonas exteriores y solariums en azotea en determinadas viviendas, con distribuciones de tres y cuatro dormitorios.', fr: 'La phase penthouse ajoute de généreux espaces extérieurs et, pour certains logements, des solariums en toiture, avec des plans de trois et quatre chambres.', de: 'Die Penthouse-Phase bietet großzügige Außenflächen und bei ausgewählten Einheiten Dachsolarien, mit Grundrissen für drei und vier Schlafzimmer.', ru: 'Очередь пентхаусов добавляет просторные внешние зоны и солярии на крыше в отдельных резиденциях, с планировками на три и четыре спальни.', ar: 'تضيف مرحلة البنتهاوس مساحات خارجية سخية وأسطحًا شمسية في وحدات مختارة، بمخططات من ثلاث وأربع غرف نوم.', nl: 'De penthousefase voegt ruime buitenruimtes en geselecteerde dakterrassen met solarium toe, met indelingen van drie en vier slaapkamers.', pl: 'Faza penthouse\'ów wprowadza obszerne przestrzenie zewnętrzne oraz wybrane solaria na dachu, z układami trzy- i czterosypialnianymi.', sv: 'Takvåningsetappen tillför generösa uteytor och utvalda soldäck på taket, med planlösningar för tre och fyra sovrum.', no: 'Toppleilighetsfasen tilfører romslige uteområder og utvalgte soldekk på taket, med planløsninger for tre og fire soverom.' },

  { find: '06 — Residence Choice', es: '06 — Elección de Vivienda', fr: '06 — Choix de la Résidence', de: '06 — Wahl der Residenz', ru: '06 — Выбор Резиденции', ar: '06 — اختيار المسكن', nl: '06 — Keuze van Woning', pl: '06 — Wybór Rezydencji', sv: '06 — Val av Bostad', no: '06 — Valg av Bolig' },
  { find: 'Compare the outdoor space,<br>not only the bedroom count.', es: 'Compara el espacio exterior,<br>no solo el número de dormitorios.', fr: 'Comparez l’espace extérieur,<br>pas seulement le nombre de chambres.', de: 'Vergleichen Sie den Außenraum,<br>nicht nur die Zimmerzahl.', ru: 'Сравнивайте открытое пространство,<br>а не только число спален.', ar: 'قارن المساحة الخارجية<br>لا عدد غرف النوم فقط.', nl: 'Vergelijk de buitenruimte,<br>niet alleen het aantal slaapkamers.', pl: 'Porównaj przestrzeń zewnętrzną,<br>nie tylko liczbę sypialni.', sv: 'Jämför utrymmet utomhus,<br>inte bara antalet sovrum.', no: 'Sammenlign uteplassen,<br>ikke bare antall soverom.' },
  { find: 'The strongest choice depends on orientation, privacy and usable garden, terrace or solarium area as much as the internal layout.', es: 'La mejor elección depende tanto de la orientación, la privacidad y la superficie útil de jardín, terraza o solárium como de la distribución interior.', fr: 'Le meilleur choix dépend autant de l’orientation, de l’intimité et de la surface utile de jardin, terrasse ou solarium que du plan intérieur.', de: 'Die beste Wahl hängt ebenso von Ausrichtung, Privatsphäre und nutzbarer Garten-, Terrassen- oder Solariumfläche ab wie vom Innengrundriss.', ru: 'Лучший выбор зависит от ориентации, приватности и полезной площади сада, террасы или солярия не меньше, чем от внутренней планировки.', ar: 'يعتمد الخيار الأفضل على الاتجاه والخصوصية والمساحة المفيدة للحديقة أو التراس أو السطح الشمسي بقدر اعتماده على التوزيع الداخلي.', nl: 'De beste keuze hangt net zo goed af van oriëntatie, privacy en bruikbare tuin-, terras- of solariumruimte als van de interne indeling.', pl: 'Najlepszy wybór zależy w równym stopniu od orientacji, prywatności i użytkowej powierzchni ogrodu, tarasu lub solarium, co od układu wnętrza.', sv: 'Det bästa valet beror lika mycket på orientering, avskildhet och användbar trädgårds-, terrass- eller solariumyta som på den interna planlösningen.', no: 'Det beste valget avhenger like mye av retning, privatliv og brukbart hage-, terrasse- eller solariumsareal som av den interne planløsningen.' },

  { find: '07 — Wider Setting', es: '07 — Entorno Más Amplio', fr: '07 — Cadre Élargi', de: '07 — Weiteres Umfeld', ru: '07 — Более Широкое Окружение', ar: '07 — المحيط الأوسع', nl: '07 — Bredere Omgeving', pl: '07 — Szerszy Kontekst', sv: '07 — Vidare Sammanhang', no: '07 — Bredere Kontekst' },
  { find: 'The residences form part<br>of a broader resort plan.', es: 'Las viviendas forman parte<br>de un plan de resort más amplio.', fr: 'Les résidences s’inscrivent<br>dans un plan resort plus large.', de: 'Die Residenzen sind Teil<br>eines größeren Resortkonzepts.', ru: 'Резиденции — часть<br>более широкого курортного плана.', ar: 'تشكل المساكن جزءًا<br>من مخطط منتجع أوسع.', nl: 'De woningen maken deel uit<br>van een breder resortplan.', pl: 'Rezydencje stanowią część<br>szerszego planu resortu.', sv: 'Bostäderna utgör en del<br>av en större resortplan.', no: 'Boligene er en del<br>av en større resortplan.' },
  { find: 'The supplied overview places the residential plots alongside sport, wellness, dining, work and leisure facilities. Timing and access should be confirmed.', es: 'La visión general facilitada sitúa las parcelas residenciales junto a instalaciones deportivas, de bienestar, restauración, trabajo y ocio. Los plazos y el acceso deben confirmarse.', fr: 'La vue d’ensemble fournie place les parcelles résidentielles aux côtés des installations de sport, bien-être, restauration, travail et loisirs. Le calendrier et l’accès sont à confirmer.', de: 'Die bereitgestellte Übersicht ordnet die Wohngrundstücke neben Sport-, Wellness-, Gastronomie-, Arbeits- und Freizeiteinrichtungen an. Zeitplan und Zugang sind zu bestätigen.', ru: 'Предоставленный обзор размещает жилые участки рядом со спортивными, велнес-, ресторанными, рабочими и досуговыми объектами. Сроки и доступ требуют подтверждения.', ar: 'تضع النظرة العامة المقدَّمة القطع السكنية إلى جانب مرافق الرياضة والعافية والمطاعم والعمل والترفيه. ينبغي تأكيد التوقيت وإمكانية الوصول.', nl: 'Het aangeleverde overzicht plaatst de woonpercelen naast sport-, wellness-, eet-, werk- en vrijetijdsvoorzieningen. Timing en toegang dienen te worden bevestigd.', pl: 'Dostarczony przegląd umieszcza działki mieszkalne obok obiektów sportowych, wellness, gastronomicznych, biurowych i rekreacyjnych. Terminy i dostęp należy potwierdzić.', sv: 'Den tillhandahållna översikten placerar bostadstomterna intill sport-, wellness-, restaurang-, arbets- och fritidsanläggningar. Tidsplan och tillgång bör bekräftas.', no: 'Den leverte oversikten plasserer boligtomtene ved siden av sport-, velvære-, spise-, arbeids- og fritidsfasiliteter. Tidspunkt og tilgang bør bekreftes.' },

  { find: '08 — New Golden Mile', es: '08 — Nueva Milla de Oro', fr: '08 — New Golden Mile', de: '08 — New Golden Mile', ru: '08 — Новая Золотая Миля', ar: '08 — الميل الذهبي الجديد', nl: '08 — New Golden Mile', pl: '08 — New Golden Mile', sv: '08 — New Golden Mile', no: '08 — New Golden Mile' },
  { find: 'Cancelada between<br>Estepona and Marbella.', es: 'Cancelada, entre<br>Estepona y Marbella.', fr: 'Cancelada, entre<br>Estepona et Marbella.', de: 'Cancelada zwischen<br>Estepona und Marbella.', ru: 'Канселада между<br>Эстепоной и Марбельей.', ar: 'كانسيلادا بين<br>إستيبونا وماربيا.', nl: 'Cancelada tussen<br>Estepona en Marbella.', pl: 'Cancelada pomiędzy<br>Estepona a Marbellą.', sv: 'Cancelada mellan<br>Estepona och Marbella.', no: 'Cancelada mellom<br>Estepona og Marbella.' },
  { find: 'The beach is described as an approximate ten-minute walk, with Estepona and Puerto Banús both about twelve kilometres away.', es: 'La playa se describe a unos diez minutos a pie, con Estepona y Puerto Banús a unos doce kilómetros cada uno.', fr: 'La plage est indiquée à environ dix minutes à pied, Estepona et Puerto Banús se situant chacun à une douzaine de kilomètres.', de: 'Der Strand wird mit etwa zehn Gehminuten angegeben, Estepona und Puerto Banús liegen jeweils rund zwölf Kilometer entfernt.', ru: 'Пляж указан примерно в десяти минутах ходьбы, а Эстепона и Пуэрто-Банус — примерно в двенадцати километрах каждый.', ar: 'يُذكر أن الشاطئ على بُعد نحو عشر دقائق سيرًا، بينما تبعد إستيبونا وبويرتو بانوس نحو اثني عشر كيلومترًا لكل منهما.', nl: 'Het strand is op ongeveer tien minuten lopen, met Estepona en Puerto Banús allebei op circa twaalf kilometer afstand.', pl: 'Plaża znajduje się w odległości około dziesięciu minut spacerem, a Estepona i Puerto Banús leżą w odległości około dwunastu kilometrów każde.', sv: 'Stranden anges ligga på ungefär tio minuters promenadavstånd, med Estepona och Puerto Banús båda cirka tolv kilometer bort.', no: 'Stranden oppgis å ligge omtrent ti minutters gange unna, med Estepona og Puerto Banús begge rundt tolv kilometer unna.' },

  { find: '09 — Wider Resort Wellness', es: '09 — Bienestar del Resort', fr: '09 — Bien-Être du Resort', de: '09 — Wellness im Resort', ru: '09 — Велнес Курорта', ar: '09 — عافية المنتجع', nl: '09 — Wellness van het Resort', pl: '09 — Wellness Resortu', sv: '09 — Wellness i Resortet', no: '09 — Velvære i Resortet' },
  { find: 'Wellness planned<br>beyond the residence.', es: 'Bienestar previsto<br>más allá de la vivienda.', fr: 'Un bien-être prévu<br>au-delà de la résidence.', de: 'Wellness, geplant<br>über die Residenz hinaus.', ru: 'Велнес, предусмотренный<br>за пределами резиденции.', ar: 'عافية مخطط لها<br>خارج حدود المسكن.', nl: 'Wellness gepland<br>buiten de woning.', pl: 'Wellness zaplanowany<br>poza samą rezydencją.', sv: 'Wellness planerat<br>utanför bostaden.', no: 'Velvære planlagt<br>utenfor boligen.' },
  { find: 'The wider resort concept includes spa and wellness facilities. Confirm what is included, where it sits and when it is expected to open.', es: 'El concepto de resort más amplio incluye instalaciones de spa y bienestar. Conviene confirmar qué se incluye, dónde se ubica y cuándo está prevista su apertura.', fr: 'Le concept resort élargi comprend des installations de spa et de bien-être. Confirmez ce qui est inclus, son emplacement et sa date d’ouverture prévue.', de: 'Das erweiterte Resortkonzept umfasst Spa- und Wellnesseinrichtungen. Klären Sie, was enthalten ist, wo es liegt und wann die Eröffnung erwartet wird.', ru: 'Более широкая концепция курорта включает спа- и велнес-объекты. Уточните, что входит, где расположено и когда ожидается открытие.', ar: 'يشمل مفهوم المنتجع الأوسع مرافق سبا وعافية. تأكد مما هو مشمول وأين يقع ومتى يُتوقع افتتاحه.', nl: 'Het bredere resortconcept omvat spa- en wellnessfaciliteiten. Bevestig wat is inbegrepen, waar het zich bevindt en wanneer de opening wordt verwacht.', pl: 'Szerszy koncept resortu obejmuje obiekty spa i wellness. Należy potwierdzić, co jest wliczone, gdzie się znajduje i kiedy planowane jest otwarcie.', sv: 'Det större resortkonceptet omfattar spa- och wellnessanläggningar. Bekräfta vad som ingår, var det ligger och när öppningen förväntas.', no: 'Det bredere resortkonseptet omfatter spa- og velværefasiliteter. Bekreft hva som er inkludert, hvor det ligger og når åpning forventes.' },

  { find: '10 — Wider Resort Sport', es: '10 — Deporte del Resort', fr: '10 — Sport du Resort', de: '10 — Sport im Resort', ru: '10 — Спорт Курорта', ar: '10 — رياضة المنتجع', nl: '10 — Sport van het Resort', pl: '10 — Sport Resortu', sv: '10 — Sport i Resortet', no: '10 — Sport i Resortet' },
  { find: 'Padel, tennis and fitness<br>within the wider plan.', es: 'Pádel, tenis y fitness<br>dentro del plan más amplio.', fr: 'Padel, tennis et fitness<br>dans le plan élargi.', de: 'Padel, Tennis und Fitness<br>im erweiterten Konzept.', ru: 'Падел, теннис и фитнес<br>в рамках общего плана.', ar: 'بادل وتنس ولياقة<br>ضمن المخطط الأوسع.', nl: 'Padel, tennis en fitness<br>binnen het bredere plan.', pl: 'Padel, tenis i fitness<br>w ramach szerszego planu.', sv: 'Padel, tennis och gym<br>inom den större planen.', no: 'Padel, tennis og trening<br>innenfor den bredere planen.' },
  { find: 'Sport facilities add practical lifestyle value for longer stays, subject to final delivery, access terms and any separate fees.', es: 'Las instalaciones deportivas aportan valor práctico para estancias largas, sujetas a la entrega final, las condiciones de acceso y posibles cuotas independientes.', fr: 'Les installations sportives apportent une valeur pratique pour les longs séjours, sous réserve de la livraison finale, des conditions d’accès et d’éventuels frais séparés.', de: 'Sportanlagen bieten praktischen Mehrwert für längere Aufenthalte, vorbehaltlich endgültiger Fertigstellung, Zugangsbedingungen und etwaiger gesonderter Gebühren.', ru: 'Спортивные объекты добавляют практическую ценность для длительного пребывания — при условии окончательной сдачи, условий доступа и возможных отдельных сборов.', ar: 'تضيف المرافق الرياضية قيمة عملية للإقامات الطويلة، رهنًا بالتسليم النهائي وشروط الدخول وأي رسوم منفصلة.', nl: 'Sportfaciliteiten voegen praktische levensstijlwaarde toe voor langere verblijven, onder voorbehoud van definitieve oplevering, toegangsvoorwaarden en eventuele afzonderlijke kosten.', pl: 'Obiekty sportowe dodają praktyczną wartość dla dłuższych pobytów, z zastrzeżeniem ostatecznego terminu realizacji, warunków dostępu i ewentualnych odrębnych opłat.', sv: 'Sportanläggningarna tillför praktiskt livsstilsvärde för längre vistelser, med förbehåll för slutlig färdigställande, tillträdesvillkor och eventuella separata avgifter.', no: 'Sportsfasilitetene tilfører praktisk livsstilsverdi for lengre opphold, med forbehold om endelig ferdigstillelse, tilgangsvilkår og eventuelle separate avgifter.' },

  { find: '11 — Wider Resort Services', es: '11 — Servicios del Resort', fr: '11 — Services du Resort', de: '11 — Services im Resort', ru: '11 — Услуги Курорта', ar: '11 — خدمات المنتجع', nl: '11 — Diensten van het Resort', pl: '11 — Usługi Resortu', sv: '11 — Service i Resortet', no: '11 — Service i Resortet' },
  { find: 'Dining, work and daily life<br>considered together.', es: 'Restauración, trabajo y vida diaria<br>pensados en conjunto.', fr: 'Restauration, travail et vie quotidienne<br>pensés ensemble.', de: 'Gastronomie, Arbeit und Alltag<br>zusammen gedacht.', ru: 'Питание, работа и повседневность<br>продуманы вместе.', ar: 'المطاعم والعمل والحياة اليومية<br>مدروسة معًا.', nl: 'Eten, werken en het dagelijks leven<br>in samenhang bekeken.', pl: 'Gastronomia, praca i codzienne życie<br>rozpatrywane razem.', sv: 'Mat, arbete och vardagsliv<br>betraktade tillsammans.', no: 'Mat, arbeid og dagligliv<br>sett i sammenheng.' },
  { find: 'Restaurant, retail, coworking and family facilities are shown as part of the wider concept rather than the immediate residential phase.', es: 'El restaurante, la zona comercial, el coworking y las instalaciones familiares se muestran como parte del concepto más amplio, no de la fase residencial inmediata.', fr: 'Restaurant, commerces, coworking et équipements familiaux sont présentés comme faisant partie du concept élargi et non de la phase résidentielle immédiate.', de: 'Restaurant, Einzelhandel, Coworking und Familieneinrichtungen werden als Teil des Gesamtkonzepts gezeigt, nicht der unmittelbaren Wohnphase.', ru: 'Ресторан, магазины, коворкинг и семейные объекты показаны как часть более широкой концепции, а не текущей жилой очереди.', ar: 'يُعرض المطعم والمتاجر ومساحة العمل المشترك والمرافق العائلية كجزء من المفهوم الأوسع لا من المرحلة السكنية الحالية.', nl: 'Restaurant, winkels, coworking en familiefaciliteiten worden getoond als onderdeel van het bredere concept, niet van de directe woonfase.', pl: 'Restauracja, sklepy, coworking i udogodnienia rodzinne są przedstawione jako część szerszej koncepcji, a nie bezpośredniej fazy mieszkalnej.', sv: 'Restaurang, butiker, coworking och familjeanläggningar visas som en del av det större konceptet snarare än den omedelbara bostadsetappen.', no: 'Restaurant, butikker, coworking og familiefasiliteter vises som en del av det bredere konseptet, ikke den umiddelbare boligfasen.' },

  { find: '12 — Current Release', es: '12 — Fase Actual', fr: '12 — Phase Actuelle', de: '12 — Aktuelle Phase', ru: '12 — Текущая Очередь', ar: '12 — المرحلة الحالية', nl: '12 — Huidige Fase', pl: '12 — Aktualna Faza', sv: '12 — Nuvarande Fas', no: '12 — Nåværende Fase' },
  { find: 'Cancelada Park,<br>the details come next.', es: 'Cancelada Park,<br>los detalles vienen a continuación.', fr: 'Cancelada Park,<br>les détails arrivent ensuite.', de: 'Cancelada Park,<br>die Details folgen.', ru: 'Cancelada Park,<br>далее — детали.', ar: 'Cancelada Park،<br>والتفاصيل تأتي تاليًا.', nl: 'Cancelada Park,<br>de details volgen hierna.', pl: 'Cancelada Park,<br>szczegóły już wkrótce.', sv: 'Cancelada Park,<br>detaljerna kommer härnäst.', no: 'Cancelada Park,<br>detaljene følger straks.' },
  { find: 'Ask for the latest residence plans, availability, guide prices, payment terms and confirmed delivery information before choosing a home.', es: 'Solicite los planos actualizados, la disponibilidad, los precios orientativos, las condiciones de pago y la información de entrega confirmada antes de elegir una vivienda.', fr: 'Demandez les derniers plans, la disponibilité, les prix indicatifs, les conditions de paiement et les informations de livraison confirmées avant de choisir un logement.', de: 'Fordern Sie aktuelle Grundrisse, Verfügbarkeit, Richtpreise, Zahlungsbedingungen und bestätigte Übergabeinformationen an, bevor Sie sich für eine Wohnung entscheiden.', ru: 'Запросите актуальные планировки, наличие, ориентировочные цены, условия оплаты и подтверждённые сроки сдачи, прежде чем выбрать резиденцию.', ar: 'اطلب أحدث مخططات المساكن والتوافر والأسعار الاسترشادية وشروط الدفع ومعلومات التسليم المؤكدة قبل اختيار المسكن.', nl: 'Vraag naar de meest recente plattegronden, beschikbaarheid, richtprijzen, betalingsvoorwaarden en bevestigde opleveringsinformatie voordat u een woning kiest.', pl: 'Poproś o najnowsze plany rezydencji, dostępność, ceny orientacyjne, warunki płatności i potwierdzone informacje o terminie odbioru przed wyborem domu.', sv: 'Fråga efter de senaste bostadsplanerna, tillgänglighet, riktpriser, betalningsvillkor och bekräftad information om tillträde innan ni väljer bostad.', no: 'Be om de nyeste boligplanene, tilgjengelighet, veiledende priser, betalingsvilkår og bekreftet informasjon om overtakelse før du velger bolig.' },
];
