import { CARD_CHROME_ENTRIES } from './card_chrome_translations.mjs';

// Translations for developments.html's own hand-authored page copy,
// applied by build_developments_locales.mjs as literal find/replace over
// the rendered English page (same proven pattern as the homepage's
// HOMEPAGE_CONTENT_ENTRIES). Entries missing a locale keep English.
//
// data-filter attribute VALUES are matching keys used by
// liora-discovery.js against each card's data-tags -- they must stay
// English. Only visible label text between > < is translated.

// Filter-pill labels and card tag chips share one vocabulary. Place-name
// style tags (Golden Mile, Rio Real, Estepona, ...) intentionally have no
// entry: the site-wide convention keeps proper-noun area labels as-is.
export const TAG_LABELS = {
  'Sea View': { es: 'Vistas al Mar', fr: 'Vue Mer', de: 'Meerblick', ru: 'Вид на Море', ar: 'إطلالة على البحر', nl: 'Zeezicht', pl: 'Widok na morze', sv: 'Havsutsikt', no: 'Sjøutsikt'  },
  'Beachside': { es: 'Junto a la Playa', fr: 'Bord de Mer', de: 'Strandnähe', ru: 'У Пляжа', ar: 'بجوار الشاطئ', nl: 'Aan het Strand', pl: 'Przy plaży', sv: 'Vid stranden', no: 'Ved stranden'  },
  'Golf Living': { es: 'Vida de Golf', fr: 'Vie Golf', de: 'Golf-Wohnen', ru: 'Гольф-Резиденции', ar: 'حياة الغولف', nl: 'Golfleven', pl: 'Życie przy polu golfowym', sv: 'Golfboende', no: 'Golfliv'  },
  'Wellness Living': { es: 'Bienestar', fr: 'Bien-Être', de: 'Wellness-Wohnen', ru: 'Wellness-Образ Жизни', ar: 'حياة العافية', nl: 'Wellnesswonen', pl: 'Wellness', sv: 'Wellnessboende', no: 'Velværeliv'  },
  'Resort Lifestyle': { es: 'Estilo Resort', fr: 'Esprit Resort', de: 'Resort-Lebensstil', ru: 'Курортный Стиль Жизни', ar: 'نمط حياة المنتجعات', nl: 'Resortstijl', pl: 'Styl życia resortowego', sv: 'Resortliv', no: 'Resortstil'  },
  'Family-Oriented': { es: 'Ideal para Familias', fr: 'Familial', de: 'Familienfreundlich', ru: 'Для Семьи', ar: 'مناسب للعائلات', nl: 'Gezinsvriendelijk', pl: 'Przyjazne rodzinie', sv: 'Familjevänligt', no: 'Familievennlig'  },
  'Privacy &amp; Security': { es: 'Privacidad y Seguridad', fr: 'Intimité et Sécurité', de: 'Privatsphäre & Sicherheit', ru: 'Приватность и Безопасность', ar: 'الخصوصية والأمان', nl: 'Privacy en Veiligheid', pl: 'Prywatność i bezpieczeństwo', sv: 'Integritet och säkerhet', no: 'Privatliv og sikkerhet'  },
  'Walkable Lifestyle': { es: 'Todo a Pie', fr: 'Tout à Pied', de: 'Alles zu Fuß Erreichbar', ru: 'Всё в Шаговой Доступности', ar: 'كل شيء سيرًا على الأقدام', nl: 'Alles lopend bereikbaar', pl: 'Wszystko w zasięgu spaceru', sv: 'Allt på gångavstånd', no: 'Alt i gåavstand'  },
  'Lock-and-Leave': { es: 'Cierra y Vete', fr: 'Clé en Main', de: 'Abschließen & Verreisen', ru: 'Закрыл и Уехал', ar: 'أغلق وغادر', nl: 'Afsluiten en Vertrekken', pl: 'Zamknij i wyjedź', sv: 'Lås och res', no: 'Lås og reis'  },
  'Smart Home': { es: 'Hogar Inteligente', fr: 'Maison Connectée', de: 'Smart Home', ru: 'Умный Дом', ar: 'منزل ذكي', nl: 'Smart Home', pl: 'Inteligentny dom', sv: 'Smart hem', no: 'Smarthjem'  },
  'Sustainable Living': { es: 'Vida Sostenible', fr: 'Habitat Durable', de: 'Nachhaltiges Wohnen', ru: 'Экологичная Жизнь', ar: 'حياة مستدامة', nl: 'Duurzaam wonen', pl: 'Zrównoważone życie', sv: 'Hållbart boende', no: 'Bærekraftig liv'  },
  'Design-Led': { es: 'Diseño de Autor', fr: 'Design Signature', de: 'Designorientiert', ru: 'Дизайнерский Подход', ar: 'تصميم متميز', nl: 'Designgedreven', pl: 'Projekt autorski', sv: 'Designdrivet', no: 'Designdrevet'  },
  'Ultra Luxury': { es: 'Ultra Lujo', fr: 'Ultra Luxe', de: 'Ultra-Luxus', ru: 'Ультра-Люкс', ar: 'فخامة قصوى', nl: 'Ultraluxe', pl: 'Ultra luksus', sv: 'Ultralyx', no: 'Ultraluksus'  },
  'Boutique Community': { es: 'Comunidad Boutique', fr: 'Communauté Boutique', de: 'Boutique-Wohnanlage', ru: 'Бутик-Комьюнити', ar: 'مجتمع بوتيكي', nl: 'Boetiekgemeenschap', pl: 'Butikowa społeczność', sv: 'Boutiqueboende', no: 'Boutiquefellesskap'  },
  'Contemporary Mediterranean': { es: 'Mediterráneo Contemporáneo', fr: 'Méditerranéen Contemporain', de: 'Zeitgenössisch Mediterran', ru: 'Современный Средиземноморский', ar: 'متوسطي معاصر', nl: 'Eigentijds mediterraans', pl: 'Współczesny śródziemnomorski', sv: 'Modern medelhavsstil', no: 'Moderne middelhavsstil'  },
  'Minimalist Architecture': { es: 'Arquitectura Minimalista', fr: 'Architecture Minimaliste', de: 'Minimalistische Architektur', ru: 'Минималистичная Архитектура', ar: 'عمارة بسيطة', nl: 'Minimalistische architectuur', pl: 'Minimalistyczna architektura', sv: 'Minimalistisk arkitektur', no: 'Minimalistisk arkitektur'  },
  'Organic Design': { es: 'Diseño Orgánico', fr: 'Design Organique', de: 'Organisches Design', ru: 'Органичный Дизайн', ar: 'تصميم عضوي', nl: 'Organisch design', pl: 'Organiczny design', sv: 'Organisk design', no: 'Organisk design'  },
  'Panoramic Glass Design': { es: 'Diseño Acristalado Panorámico', fr: 'Design Vitré Panoramique', de: 'Panorama-Glasdesign', ru: 'Панорамное Остекление', ar: 'تصميم زجاجي بانورامي', nl: 'Panoramisch glasontwerp', pl: 'Panoramiczne przeszklenia', sv: 'Panoramisk glasdesign', no: 'Panoramisk glassdesign'  },
  'Low-Density Development': { es: 'Promoción de Baja Densidad', fr: 'Programme à Faible Densité', de: 'Bebauung mit Geringer Dichte', ru: 'Малоэтажная Застройка', ar: 'مشروع منخفض الكثافة', nl: 'Project met Lage Dichtheid', pl: 'Inwestycja o niskiej zabudowie', sv: 'Lågdensitetsprojekt', no: 'Prosjekt med lav tetthet'  },
  'Boutique Development': { es: 'Promoción Boutique', fr: 'Programme Boutique', de: 'Boutique-Projekt', ru: 'Бутик-Проект', ar: 'مشروع بوتيكي', nl: 'Boetiekproject', pl: 'Inwestycja butikowa', sv: 'Boutiqueprojekt', no: 'Boutiqueprosjekt'  },
  'Beachfront': { es: 'Primera Línea de Playa', fr: 'Front de Mer', de: 'Direkt am Strand', ru: 'Первая Линия', ar: 'واجهة بحرية', nl: 'Eerste lijn strand', pl: 'Pierwsza linia plaży', sv: 'Strandnära (första linjen)', no: 'Første linje til stranden'  },
  'Hillside Views': { es: 'Vistas desde la Ladera', fr: 'Vues sur les Collines', de: 'Hanglage mit Aussicht', ru: 'Вид с Холма', ar: 'إطلالات التلال', nl: 'Uitzicht vanaf de Heuvel', pl: 'Widoki ze wzgórza', sv: 'Utsikt från sluttningen', no: 'Utsikt fra åssiden'  },
  'Gated Community': { es: 'Urbanización Cerrada', fr: 'Résidence Fermée', de: 'Bewachte Wohnanlage', ru: 'Закрытая Резиденция', ar: 'مجمع مسور', nl: 'Beveiligde woonwijk', pl: 'Osiedle zamknięte', sv: 'Bevakat boende', no: 'Gjerdet boligområde'  },
  'Walkable to Amenities': { es: 'Servicios a Pie', fr: 'Commodités à Pied', de: 'Alles Fußläufig', ru: 'Инфраструктура Рядом', ar: 'خدمات قريبة سيرًا', nl: 'Voorzieningen lopend bereikbaar', pl: 'Udogodnienia w zasięgu spaceru', sv: 'Service på gångavstånd', no: 'Fasiliteter i gåavstand'  },
  'Primary Residence': { es: 'Vivienda Habitual', fr: 'Résidence Principale', de: 'Hauptwohnsitz', ru: 'Основное Жильё', ar: 'سكن رئيسي', nl: 'Hoofdverblijf', pl: 'Miejsce stałego zamieszkania', sv: 'Permanentbostad', no: 'Fast bolig'  },
  'Holiday Home': { es: 'Casa de Vacaciones', fr: 'Résidence de Vacances', de: 'Ferienhaus', ru: 'Дом для Отдыха', ar: 'منزل عطلات', nl: 'Vakantiewoning', pl: 'Dom wakacyjny', sv: 'Fritidshus', no: 'Feriebolig'  },
  'Investment Property': { es: 'Propiedad de Inversión', fr: 'Bien d’Investissement', de: 'Anlageimmobilie', ru: 'Инвестиционная Недвижимость', ar: 'عقار استثماري', nl: 'Investeringspand', pl: 'Nieruchomość inwestycyjna', sv: 'Investeringsfastighet', no: 'Investeringseiendom'  },
  'Rental Yield Potential': { es: 'Potencial de Rentabilidad', fr: 'Potentiel Locatif', de: 'Mietrendite-Potenzial', ru: 'Потенциал Арендной Доходности', ar: 'إمكانات عائد الإيجار', nl: 'Potentieel huurrendement', pl: 'Potencjał rentowności najmu', sv: 'Potentiell uthyrningsavkastning', no: 'Potensial for utleieavkastning'  },
  'Family Relocation': { es: 'Traslado en Familia', fr: 'Installation en Famille', de: 'Familienumzug', ru: 'Переезд с Семьёй', ar: 'انتقال عائلي', nl: 'Verhuizing met het Gezin', pl: 'Przeprowadzka z rodziną', sv: 'Familjeflytt', no: 'Flytting med familien'  },
  'International Buyer': { es: 'Comprador Internacional', fr: 'Acheteur International', de: 'Internationaler Käufer', ru: 'Международный Покупатель', ar: 'مشترٍ دولي', nl: 'Internationale koper', pl: 'Kupujący z zagranicy', sv: 'Internationell köpare', no: 'Internasjonal kjøper'  },
  'Second Home': { es: 'Segunda Residencia', fr: 'Résidence Secondaire', de: 'Zweitwohnsitz', ru: 'Второй Дом', ar: 'منزل ثانٍ', nl: 'Tweede woning', pl: 'Druga nieruchomość', sv: 'Andra bostad', no: 'Sekundærbolig'  },
  'Lifestyle Investment': { es: 'Inversión en Estilo de Vida', fr: 'Investissement Style de Vie', de: 'Lifestyle-Investment', ru: 'Инвестиция в Образ Жизни', ar: 'استثمار في نمط الحياة', nl: 'Investering in Levensstijl', pl: 'Inwestycja w styl życia', sv: 'Livsstilsinvestering', no: 'Livsstilsinvestering'  },
  'Long-Term Value': { es: 'Valor a Largo Plazo', fr: 'Valeur à Long Terme', de: 'Langfristiger Wert', ru: 'Долгосрочная Ценность', ar: 'قيمة طويلة الأمد', nl: 'Waarde op Lange Termijn', pl: 'Wartość długoterminowa', sv: 'Långsiktigt värde', no: 'Langsiktig verdi'  },
  'Low-Maintenance Ownership': { es: 'Mantenimiento Mínimo', fr: 'Entretien Minimal', de: 'Pflegeleichtes Eigentum', ru: 'Минимум Обслуживания', ar: 'ملكية سهلة الصيانة', nl: 'Onderhoudsarm eigendom', pl: 'Łatwe w utrzymaniu', sv: 'Underhållsfritt ägande', no: 'Vedlikeholdsfritt eierskap'  },
  // Card-chip-only vocabulary
  'Off-Plan': { es: 'Sobre Plano', fr: 'Sur Plan', de: 'Off-Plan', ru: 'На Этапе Строительства', ar: 'على المخطط', nl: 'Op plan', pl: 'Sprzedaż z planu', sv: 'Under projektering', no: 'Under prosjektering'  },
  'Completed': { es: 'Finalizado', fr: 'Terminé', de: 'Fertiggestellt', ru: 'Завершено', ar: 'مكتمل', nl: 'Voltooid', pl: 'Ukończone', sv: 'Färdigställd', no: 'Ferdigstilt'  },
  'Resort Amenities': { es: 'Servicios de Resort', fr: 'Prestations Resort', de: 'Resort-Ausstattung', ru: 'Курортная Инфраструктура', ar: 'مرافق المنتجع', nl: 'Resortvoorzieningen', pl: 'Udogodnienia resortowe', sv: 'Resortfaciliteter', no: 'Resortfasiliteter'  },
  'Resort access': { es: 'Acceso a resort', fr: 'Accès resort', de: 'Resort-Zugang', ru: 'Доступ к курорту', ar: 'وصول إلى المنتجع', nl: 'Toegang tot resort', pl: 'Dostęp do resortu', sv: 'Tillgång till resort', no: 'Tilgang til resort'  },
  'Large terraces': { es: 'Terrazas amplias', fr: 'Grandes terrasses', de: 'Große Terrassen', ru: 'Просторные террасы', ar: 'شرفات واسعة', nl: 'Grote terrassen', pl: 'Duże tarasy', sv: 'Stora terrasser', no: 'Store terrasser'  },
  'Private Rooftop Pool': { es: 'Piscina Privada en Azotea', fr: 'Piscine Privée sur le Toit', de: 'Privater Dachpool', ru: 'Частный Бассейн на Крыше', ar: 'مسبح خاص على السطح', nl: 'Privézwembad op het Dak', pl: 'Prywatny basen na dachu', sv: 'Privat takpool', no: 'Privat takbasseng'  },
  'Rooftop Pool': { es: 'Piscina en Azotea', fr: 'Piscine sur le Toit', de: 'Dachpool', ru: 'Бассейн на Крыше', ar: 'مسبح على السطح', nl: 'Zwembad op het Dak', pl: 'Basen na dachu', sv: 'Takpool', no: 'Takbasseng'  },
  'Walk to Beach': { es: 'Playa a Pie', fr: 'Plage à Pied', de: 'Strand zu Fuß', ru: 'Пляж Пешком', ar: 'الشاطئ سيرًا', nl: 'Lopend naar het Strand', pl: 'Plaża w zasięgu spaceru', sv: 'Gångavstånd till stranden', no: 'Gåavstand til stranden'  },
  'Smart Living': { es: 'Vida Inteligente', fr: 'Habitat Connecté', de: 'Smartes Wohnen', ru: 'Умные Технологии', ar: 'حياة ذكية', nl: 'Slim wonen', pl: 'Inteligentne życie', sv: 'Smart boende', no: 'Smart liv'  },
  'Sky bar': { es: 'Sky bar', fr: 'Sky bar', de: 'Sky-Bar', ru: 'Скай-бар', ar: 'سكاي بار', nl: 'Sky bar', pl: 'Sky bar', sv: 'Sky bar', no: 'Sky bar'  },
  'Golf simulator': { es: 'Simulador de golf', fr: 'Simulateur de golf', de: 'Golfsimulator', ru: 'Гольф-симулятор', ar: 'محاكي غولف', nl: 'Golfsimulator', pl: 'Symulator golfa', sv: 'Golfsimulator', no: 'Golfsimulator'  },
  'Co-Working': { es: 'Coworking', fr: 'Coworking', de: 'Co-Working', ru: 'Коворкинг', ar: 'مساحة عمل مشتركة', nl: 'Co-Working', pl: 'Co-working', sv: 'Co-Working', no: 'Co-Working'  },
  'Gym': { es: 'Gimnasio', fr: 'Salle de Sport', de: 'Fitnessstudio', ru: 'Тренажёрный Зал', ar: 'صالة رياضية', nl: 'Fitnessruimte', pl: 'Siłownia', sv: 'Gym', no: 'Treningssenter'  },
  'Indoor Spa': { es: 'Spa Interior', fr: 'Spa Intérieur', de: 'Indoor-Spa', ru: 'Крытый Спа', ar: 'سبا داخلي', nl: 'Binnenspa', pl: 'Spa wewnętrzne', sv: 'Inomhusspa', no: 'Innendørs spa'  },
  'Private Pool Penthouses': { es: 'Áticos con Piscina Privada', fr: 'Penthouses avec Piscine Privée', de: 'Penthäuser mit Privatpool', ru: 'Пентхаусы с Бассейном', ar: 'بنتهاوس بمسبح خاص', nl: 'Penthouses met Privézwembad', pl: 'Penthouse’y z prywatnym basenem', sv: 'Takvåningar med privat pool', no: 'Toppleiligheter med privat basseng'  },
  'Private Spa': { es: 'Spa Privado', fr: 'Spa Privé', de: 'Privates Spa', ru: 'Частный Спа', ar: 'سبا خاص', nl: 'Privéspa', pl: 'Prywatne spa', sv: 'Privat spa', no: 'Privat spa'  },
  'Cinema &amp; Coworking': { es: 'Cine y Coworking', fr: 'Cinéma et Coworking', de: 'Kino & Co-Working', ru: 'Кинозал и Коворкинг', ar: 'سينما ومساحة عمل', nl: 'Bioscoop en Coworking', pl: 'Kino i coworking', sv: 'Biograf och coworking', no: 'Kino og coworking'  },
  'Boutique Collection': { es: 'Colección Boutique', fr: 'Collection Boutique', de: 'Boutique-Kollektion', ru: 'Бутик-Коллекция', ar: 'مجموعة بوتيكية', nl: 'Boetiekcollectie', pl: 'Kolekcja butikowa', sv: 'Boutiquekollektion', no: 'Boutiquekolleksjon'  },
  'Private Pool': { es: 'Piscina Privada', fr: 'Piscine Privée', de: 'Privater Pool', ru: 'Частный Бассейн', ar: 'مسبح خاص', nl: 'Privézwembad', pl: 'Prywatny basen', sv: 'Privat pool', no: 'Privat basseng'  },
  'Entertaining': { es: 'Para Recibir', fr: 'Recevoir', de: 'Gastfreundschaft', ru: 'Для Приёмов', ar: 'الاستضافة', nl: 'Gastvrij ontvangen', pl: 'Przyjmowanie gości', sv: 'Umgänge', no: 'Selskapelighet'  },
  'Contemporary': { es: 'Contemporáneo', fr: 'Contemporain', de: 'Zeitgenössisch', ru: 'Современный Стиль', ar: 'معاصر', nl: 'Eigentijds', pl: 'Współczesny', sv: 'Modern', no: 'Moderne'  },
  'Double-Height Living': { es: 'Salón a Doble Altura', fr: 'Séjour Double Hauteur', de: 'Wohnen in Doppelhöhe', ru: 'Двусветная Гостиная', ar: 'معيشة مزدوجة الارتفاع', nl: 'Woonkamer met Dubbele Hoogte', pl: 'Salon o podwójnej wysokości', sv: 'Vardagsrum i dubbel höjd', no: 'Stue i dobbel høyde'  },
  'Rooftop Solarium': { es: 'Solárium en Azotea', fr: 'Solarium en Toiture', de: 'Dachsolarium', ru: 'Солярий на Крыше', ar: 'سطح شمسي', nl: 'Solarium op het Dak', pl: 'Solarium na dachu', sv: 'Solarium på taket', no: 'Solarium på taket'  },
  'Walk to Puerto Banús': { es: 'A Pie a Puerto Banús', fr: 'À Pied de Puerto Banús', de: 'Zu Fuß nach Puerto Banús', ru: 'Пешком до Пуэрто-Бануса', ar: 'سيرًا إلى بويرتو بانوس', nl: 'Lopend naar Puerto Banús', pl: 'Puerto Banús w zasięgu spaceru', sv: 'Gångavstånd till Puerto Banús', no: 'Gåavstand til Puerto Banús'  },
  'Insurance-Backed Payments': { es: 'Pagos Avalados por Seguro', fr: 'Paiements Assurés', de: 'Versicherte Zahlungen', ru: 'Платежи под Страховкой', ar: 'دفعات مضمونة بالتأمين', nl: 'Verzekerde betalingen', pl: 'Płatności zabezpieczone ubezpieczeniem', sv: 'Försäkrade betalningar', no: 'Forsikrede betalinger'  },
  'Staged Payment Plan': { es: 'Pago Escalonado', fr: 'Paiement Échelonné', de: 'Gestaffelter Zahlungsplan', ru: 'Поэтапная Оплата', ar: 'خطة دفع مرحلية', nl: 'Gefaseerd betalingsplan', pl: 'Płatności ratalne', sv: 'Etappvis betalningsplan', no: 'Trinnvis betalingsplan'  },
  'Lift': { es: 'Ascensor', fr: 'Ascenseur', de: 'Aufzug', ru: 'Лифт', ar: 'مصعد', nl: 'Lift', pl: 'Winda', sv: 'Hiss', no: 'Heis'  },
  'EV Charging': { es: 'Carga para Vehículo Eléctrico', fr: 'Recharge Véhicule Électrique', de: 'E-Auto-Ladestation', ru: 'Зарядка Электромобиля', ar: 'شاحن سيارات كهربائية', nl: 'Laadpunt voor Elektrische Auto’s', pl: 'Ładowanie aut elektrycznych', sv: 'Laddning för elbil', no: 'Lading for elbil'  },
  'Flex Living': { es: 'Flex Living', fr: 'Flex Living', de: 'Flex Living', ru: 'Гибкое Владение', ar: 'سكن مرن', nl: 'Flex Living', pl: 'Flex Living', sv: 'Flex Living', no: 'Flex Living'  }
};

const PAGE_ENTRIES_HEAD = [
  // Head
  { find: '<title>Costa del Sol New Developments | Nueva Living</title>', es: '<title>Obra Nueva en la Costa del Sol | Nueva Living</title>', fr: '<title>Programmes Neufs sur la Costa del Sol | Nueva Living</title>', de: '<title>Neubauprojekte an der Costa del Sol | Nueva Living</title>', ru: '<title>Новостройки на Коста-дель-Соль | Nueva Living</title>', ar: '<title>مشاريع جديدة في كوستا ديل سول | Nueva Living</title>', nl: '<title>Nieuwbouw aan de Costa del Sol | Nueva Living</title>', pl: '<title>Nowe inwestycje na Costa del Sol | Nueva Living</title>', sv: '<title>Nya bostadsprojekt på Costa del Sol | Nueva Living</title>', no: '<title>Nye boligprosjekter på Costa del Sol | Nueva Living</title>'  },
  { find: 'Explore new developments across the Costa del Sol, chosen for their design, location and everyday appeal.', es: 'Descubre promociones de obra nueva en toda la Costa del Sol, seleccionadas por su diseño, ubicación y atractivo para el día a día.', fr: 'Découvrez des programmes neufs sur toute la Costa del Sol, choisis pour leur design, leur emplacement et leur agrément au quotidien.', de: 'Entdecken Sie Neubauprojekte an der gesamten Costa del Sol, ausgewählt nach Design, Lage und Alltagstauglichkeit.', ru: 'Изучите новостройки по всему побережью Коста-дель-Соль, отобранные за дизайн, расположение и удобство для жизни.', ar: 'استكشف مشاريع جديدة في جميع أنحاء كوستا ديل سول، مختارة لتصميمها وموقعها وملاءمتها للحياة اليومية.', nl: 'Ontdek nieuwbouwprojecten langs de hele Costa del Sol, geselecteerd om hun design, ligging en alledaagse aantrekkingskracht.', pl: 'Odkryj nowe inwestycje na całym wybrzeżu Costa del Sol, wybrane ze względu na design, lokalizację i codzienny komfort.', sv: 'Upptäck nya bostadsprojekt längs hela Costa del Sol, utvalda för sin design, sitt läge och sin vardagliga charm.', no: 'Utforsk nye boligprosjekter langs hele Costa del Sol, utvalgt for design, beliggenhet og hverdagslig sjarm.'  },
  { find: '<meta property="og:title" content="Costa del Sol New Developments | Nueva Living">', es: '<meta property="og:title" content="Obra Nueva en la Costa del Sol | Nueva Living">', fr: '<meta property="og:title" content="Programmes Neufs sur la Costa del Sol | Nueva Living">', de: '<meta property="og:title" content="Neubauprojekte an der Costa del Sol | Nueva Living">', ru: '<meta property="og:title" content="Новостройки на Коста-дель-Соль | Nueva Living">', ar: '<meta property="og:title" content="مشاريع جديدة في كوستا ديل سول | Nueva Living">', nl: '<meta property="og:title" content="Nieuwbouw aan de Costa del Sol | Nueva Living">', pl: '<meta property="og:title" content="Nowe inwestycje na Costa del Sol | Nueva Living">', sv: '<meta property="og:title" content="Nya bostadsprojekt på Costa del Sol | Nueva Living">', no: '<meta property="og:title" content="Nye boligprosjekter på Costa del Sol | Nueva Living">'  },
  { find: '<meta name="twitter:title" content="Costa del Sol New Developments | Nueva Living">', es: '<meta name="twitter:title" content="Obra Nueva en la Costa del Sol | Nueva Living">', fr: '<meta name="twitter:title" content="Programmes Neufs sur la Costa del Sol | Nueva Living">', de: '<meta name="twitter:title" content="Neubauprojekte an der Costa del Sol | Nueva Living">', ru: '<meta name="twitter:title" content="Новостройки на Коста-дель-Соль | Nueva Living">', ar: '<meta name="twitter:title" content="مشاريع جديدة في كوستا ديل سول | Nueva Living">', nl: '<meta name="twitter:title" content="Nieuwbouw aan de Costa del Sol | Nueva Living">', pl: '<meta name="twitter:title" content="Nowe inwestycje na Costa del Sol | Nueva Living">', sv: '<meta name="twitter:title" content="Nya bostadsprojekt på Costa del Sol | Nueva Living">', no: '<meta name="twitter:title" content="Nye boligprosjekter på Costa del Sol | Nueva Living">'  },

  // Breadcrumb
  { find: '<li><a href="index.html">Home</a></li>', es: '<li><a href="index.html">Inicio</a></li>', fr: '<li><a href="index.html">Accueil</a></li>', de: '<li><a href="index.html">Startseite</a></li>', ru: '<li><a href="index.html">Главная</a></li>', ar: '<li><a href="index.html">الرئيسية</a></li>', nl: '<li><a href="index.html">Home</a></li>', pl: '<li><a href="index.html">Strona główna</a></li>', sv: '<li><a href="index.html">Hem</a></li>', no: '<li><a href="index.html">Hjem</a></li>'  },
  { find: '<li><span aria-current="page">Developments</span></li>', es: '<li><span aria-current="page">Promociones</span></li>', fr: '<li><span aria-current="page">Programmes</span></li>', de: '<li><span aria-current="page">Neubauprojekte</span></li>', ru: '<li><span aria-current="page">Новостройки</span></li>', ar: '<li><span aria-current="page">المشاريع</span></li>', nl: '<li><span aria-current="page">Nieuwbouwprojecten</span></li>', pl: '<li><span aria-current="page">Inwestycje</span></li>', sv: '<li><span aria-current="page">Bostadsprojekt</span></li>', no: '<li><span aria-current="page">Boligprosjekter</span></li>'  },

  // Hero
  { find: '<span class="kicker">Selected Developments</span>', es: '<span class="kicker">Promociones Seleccionadas</span>', fr: '<span class="kicker">Programmes Sélectionnés</span>', de: '<span class="kicker">Ausgewählte Neubauprojekte</span>', ru: '<span class="kicker">Избранные Новостройки</span>', ar: '<span class="kicker">مشاريع مختارة</span>', nl: '<span class="kicker">Geselecteerde Nieuwbouwprojecten</span>', pl: '<span class="kicker">Wybrane inwestycje</span>', sv: '<span class="kicker">Utvalda Bostadsprojekt</span>', no: '<span class="kicker">Utvalgte boligprosjekter</span>'  },
  { find: 'Luxury properties for sale on the <em>Costa del Sol</em>', es: 'Propiedades de lujo en venta en la <em>Costa del Sol</em>', fr: 'Propriétés de luxe à vendre sur la <em>Costa del Sol</em>', de: 'Luxusimmobilien zum Verkauf an der <em>Costa del Sol</em>', ru: 'Элитная недвижимость на продажу на <em>Коста-дель-Соль</em>', ar: 'عقارات فاخرة للبيع في <em>كوستا ديل سول</em>', nl: 'Luxe woningen te koop aan de <em>Costa del Sol</em>', pl: 'Luksusowe nieruchomości na sprzedaż na <em>Costa del Sol</em>', sv: 'Lyxbostäder till salu på <em>Costa del Sol</em>', no: 'Luksusboliger til salgs på <em>Costa del Sol</em>'  },
  { find: 'Find your ideal home on the Costa del Sol with our advanced property search. Browse a carefully selected collection of new developments and luxury residences, and filter by location, price, property type and more to discover the home that perfectly matches your lifestyle.', es: 'Encuentra tu vivienda ideal en la Costa del Sol con nuestro buscador avanzado. Explora una colección cuidadosamente seleccionada de obra nueva y residencias de lujo, y filtra por ubicación, precio, tipo de propiedad y más para descubrir el hogar que encaja perfectamente con tu estilo de vida.', fr: 'Trouvez votre logement idéal sur la Costa del Sol grâce à notre recherche avancée. Parcourez une collection soigneusement sélectionnée de programmes neufs et de résidences de luxe, et filtrez par emplacement, prix, type de bien et plus encore pour découvrir la maison qui correspond parfaitement à votre style de vie.', de: 'Finden Sie Ihr ideales Zuhause an der Costa del Sol mit unserer erweiterten Immobiliensuche. Durchstöbern Sie eine sorgfältig ausgewählte Kollektion von Neubauprojekten und Luxusresidenzen und filtern Sie nach Lage, Preis, Immobilientyp und mehr, um das Zuhause zu entdecken, das perfekt zu Ihrem Lebensstil passt.', ru: 'Найдите идеальный дом на Коста-дель-Соль с помощью нашего расширенного поиска. Просмотрите тщательно отобранную коллекцию новостроек и элитных резиденций и отфильтруйте по расположению, цене, типу недвижимости и другим параметрам, чтобы найти дом, идеально соответствующий вашему образу жизни.', ar: 'اعثر على منزلك المثالي في كوستا ديل سول من خلال بحثنا المتقدم عن العقارات. تصفح مجموعة مختارة بعناية من المشاريع الجديدة والمساكن الفاخرة، وقم بالتصفية حسب الموقع والسعر ونوع العقار والمزيد لاكتشاف المنزل الذي يناسب نمط حياتك تمامًا.', nl: 'Vind uw ideale woning aan de Costa del Sol met onze geavanceerde zoekfunctie. Blader door een zorgvuldig samengestelde collectie nieuwbouwprojecten en luxe residenties, en filter op locatie, prijs, woningtype en meer om de woning te ontdekken die perfect bij uw levensstijl past.', pl: 'Znajdź swój wymarzony dom na Costa del Sol dzięki naszej zaawansowanej wyszukiwarce nieruchomości. Przeglądaj starannie wyselekcjonowaną kolekcję nowych inwestycji i luksusowych rezydencji, filtruj według lokalizacji, ceny, rodzaju nieruchomości i innych kryteriów, aby znaleźć dom idealnie dopasowany do Państwa stylu życia.', sv: 'Hitta ditt drömboende på Costa del Sol med vår avancerade bostadssökning. Bläddra bland ett noggrant utvalt urval av nya bostadsprojekt och lyxresidenser, och filtrera efter läge, pris, bostadstyp och mer för att hitta hemmet som passar perfekt med din livsstil.', no: 'Finn din ideelle bolig på Costa del Sol med vårt avanserte boligsøk. Bla gjennom en nøye utvalgt samling av nye boligprosjekter og luksusresidenser, og filtrer etter beliggenhet, pris, boligtype og mer for å finne boligen som passer perfekt til din livsstil.'  },
  { find: 'aria-controls="devHeroLead">Read More</button>', es: 'aria-controls="devHeroLead">Leer Más</button>', fr: 'aria-controls="devHeroLead">Lire Plus</button>', de: 'aria-controls="devHeroLead">Mehr Lesen</button>', ru: 'aria-controls="devHeroLead">Читать Далее</button>', ar: 'aria-controls="devHeroLead">اقرأ المزيد</button>', nl: 'aria-controls="devHeroLead">Lees Meer</button>', pl: 'aria-controls="devHeroLead">Czytaj więcej</button>', sv: 'aria-controls="devHeroLead">Läs Mer</button>', no: 'aria-controls="devHeroLead">Les Mer</button>'  },
  { find: '>Explore Developments</a>', es: '>Ver Promociones</a>', fr: '>Découvrir les Programmes</a>', de: '>Neubauprojekte Entdecken</a>', ru: '>Смотреть Новостройки</a>', ar: '>استكشاف المشاريع</a>', nl: '>Bekijk Nieuwbouwprojecten</a>', pl: '>Zobacz inwestycje</a>', sv: '>Utforska Bostadsprojekt</a>', no: '>Utforsk boligprosjekter</a>'  },
  // Inline hero-lead toggle script literals
  { find: "heroLeadToggle.textContent = expanded ? 'Read Less' : 'Read More';", es: "heroLeadToggle.textContent = expanded ? 'Leer Menos' : 'Leer Más';", fr: "heroLeadToggle.textContent = expanded ? 'Lire Moins' : 'Lire Plus';", de: "heroLeadToggle.textContent = expanded ? 'Weniger Lesen' : 'Mehr Lesen';", ru: "heroLeadToggle.textContent = expanded ? 'Свернуть' : 'Читать Далее';", ar: "heroLeadToggle.textContent = expanded ? 'اقرأ أقل' : 'اقرأ المزيد';", nl: "heroLeadToggle.textContent = expanded ? 'Lees Minder' : 'Lees Meer';", pl: "heroLeadToggle.textContent = expanded ? 'Czytaj mniej' : 'Czytaj więcej';", sv: "heroLeadToggle.textContent = expanded ? 'Läs mindre' : 'Läs mer';", no: "heroLeadToggle.textContent = expanded ? 'Les Mindre' : 'Les Mer';"  },

  // View tabs
  { find: 'aria-label="Developments view"', es: 'aria-label="Vista de promociones"', fr: 'aria-label="Vue des programmes"', de: 'aria-label="Projektansicht"', ru: 'aria-label="Вид списка новостроек"', ar: 'aria-label="عرض المشاريع"', nl: 'aria-label="Weergave nieuwbouwprojecten"', pl: 'aria-label="Widok inwestycji"', sv: 'aria-label="Vy för bostadsprojekt"', no: 'aria-label="Visning av boligprosjekter"'  },
  { find: 'data-view-tab="current" role="tab" aria-selected="true">Current Developments</button>', es: 'data-view-tab="current" role="tab" aria-selected="true">Promociones Actuales</button>', fr: 'data-view-tab="current" role="tab" aria-selected="true">Programmes Actuels</button>', de: 'data-view-tab="current" role="tab" aria-selected="true">Aktuelle Projekte</button>', ru: 'data-view-tab="current" role="tab" aria-selected="true">Текущие Новостройки</button>', ar: 'data-view-tab="current" role="tab" aria-selected="true">المشاريع الحالية</button>', nl: 'data-view-tab="current" role="tab" aria-selected="true">Actuele Projecten</button>', pl: 'data-view-tab="current" role="tab" aria-selected="true">Aktualne inwestycje</button>', sv: 'data-view-tab="current" role="tab" aria-selected="true">Aktuella Projekt</button>', no: 'data-view-tab="current" role="tab" aria-selected="true">Aktuelle Prosjekter</button>'  },
  { find: 'data-view-tab="archived" role="tab" aria-selected="false">Earlier Sold Projects</button>', es: 'data-view-tab="archived" role="tab" aria-selected="false">Proyectos Ya Vendidos</button>', fr: 'data-view-tab="archived" role="tab" aria-selected="false">Projets Déjà Vendus</button>', de: 'data-view-tab="archived" role="tab" aria-selected="false">Bereits Verkaufte Projekte</button>', ru: 'data-view-tab="archived" role="tab" aria-selected="false">Ранее Проданные Проекты</button>', ar: 'data-view-tab="archived" role="tab" aria-selected="false">مشاريع بيعت سابقًا</button>', nl: 'data-view-tab="archived" role="tab" aria-selected="false">Eerder Verkochte Projecten</button>', pl: 'data-view-tab="archived" role="tab" aria-selected="false">Wcześniej sprzedane projekty</button>', sv: 'data-view-tab="archived" role="tab" aria-selected="false">Tidigare sålda projekt</button>', no: 'data-view-tab="archived" role="tab" aria-selected="false">Tidligere Solgte Prosjekter</button>'  },
  { find: 'aria-label="Development discovery filters"', es: 'aria-label="Filtros de búsqueda de promociones"', fr: 'aria-label="Filtres de recherche de programmes"', de: 'aria-label="Filter für die Projektsuche"', ru: 'aria-label="Фильтры поиска новостроек"', ar: 'aria-label="عوامل تصفية البحث عن المشاريع"', nl: 'aria-label="Zoekfilters voor nieuwbouwprojecten"', pl: 'aria-label="Filtry wyszukiwania inwestycji"', sv: 'aria-label="Sökfilter för bostadsprojekt"', no: 'aria-label="Søkefiltre for boligprosjekter"'  },

  // AI search
  { find: ">Describe the home you're looking for</label>", es: '>Describe la vivienda que buscas</label>', fr: '>Décrivez le bien que vous recherchez</label>', de: '>Beschreiben Sie das Zuhause, das Sie suchen</label>', ru: '>Опишите дом, который вы ищете</label>', ar: '>صف المنزل الذي تبحث عنه</label>', nl: '>Beschrijf de woning die u zoekt</label>', pl: '>Opisz dom, którego szukasz</label>', sv: '>Beskriv bostaden du letar efter</label>', no: '>Beskriv boligen du leter etter</label>'  },
  { find: 'placeholder="Use our AI assistant to find what you are looking for"', es: 'placeholder="Usa nuestro asistente de IA para encontrar lo que buscas"', fr: 'placeholder="Utilisez notre assistant IA pour trouver ce que vous cherchez"', de: 'placeholder="Nutzen Sie unseren KI-Assistenten, um zu finden, was Sie suchen"', ru: 'placeholder="Используйте нашего ИИ-ассистента, чтобы найти то, что вы ищете"', ar: 'placeholder="استخدم مساعد الذكاء الاصطناعي للعثور على ما تبحث عنه"', nl: 'placeholder="Gebruik onze AI-assistent om te vinden wat u zoekt"', pl: 'placeholder="Skorzystaj z naszego asystenta AI, aby znaleźć to, czego szukasz"', sv: 'placeholder="Använd vår AI-assistent för att hitta det du söker"', no: 'placeholder="Bruk vår AI-assistent for å finne det du leter etter"'  },
  { find: '<span data-ai-search-submit-label>Search</span>', es: '<span data-ai-search-submit-label>Buscar</span>', fr: '<span data-ai-search-submit-label>Rechercher</span>', de: '<span data-ai-search-submit-label>Suchen</span>', ru: '<span data-ai-search-submit-label>Найти</span>', ar: '<span data-ai-search-submit-label>بحث</span>', nl: '<span data-ai-search-submit-label>Zoeken</span>', pl: '<span data-ai-search-submit-label>Szukaj</span>', sv: '<span data-ai-search-submit-label>Sök</span>', no: '<span data-ai-search-submit-label>Søk</span>'  },
  { find: 'data-ai-search-example>Beachfront villa near Puerto Ban&uacute;s</button>', es: 'data-ai-search-example>Villa en primera línea cerca de Puerto Banús</button>', fr: 'data-ai-search-example>Villa en front de mer près de Puerto Banús</button>', de: 'data-ai-search-example>Strandvilla nahe Puerto Banús</button>', ru: 'data-ai-search-example>Вилла у моря рядом с Пуэрто-Банус</button>', ar: 'data-ai-search-example>فيلا على الشاطئ قرب بويرتو بانوس</button>', nl: 'data-ai-search-example>Strandvilla nabij Puerto Banús</button>', pl: 'data-ai-search-example>Willa przy plaży blisko Puerto Banús</button>', sv: 'data-ai-search-example>Strandvilla nära Puerto Banús</button>', no: 'data-ai-search-example>Strandvilla nær Puerto Banús</button>'  },
  { find: 'data-ai-search-example>Golf-front penthouse, 2 bedrooms</button>', es: 'data-ai-search-example>Ático frente al golf, 2 dormitorios</button>', fr: 'data-ai-search-example>Penthouse face au golf, 2 chambres</button>', de: 'data-ai-search-example>Penthouse am Golfplatz, 2 Schlafzimmer</button>', ru: 'data-ai-search-example>Пентхаус у гольф-поля, 2 спальни</button>', ar: 'data-ai-search-example>بنتهاوس مطل على الغولف، غرفتا نوم</button>', nl: 'data-ai-search-example>Penthouse aan de golfbaan, 2 slaapkamers</button>', pl: 'data-ai-search-example>Penthouse przy polu golfowym, 2 sypialnie</button>', sv: 'data-ai-search-example>Takvåning vid golfbanan, 2 sovrum</button>', no: 'data-ai-search-example>Toppleilighet ved golfbanen, 2 soverom</button>'  },
  { find: 'data-ai-search-example>Family home under &euro;1.5M, ready now</button>', es: 'data-ai-search-example>Vivienda familiar por menos de 1,5M€, lista para entrar</button>', fr: 'data-ai-search-example>Maison familiale sous 1,5M€, disponible maintenant</button>', de: 'data-ai-search-example>Familienhaus unter 1,5M€, sofort bezugsfertig</button>', ru: 'data-ai-search-example>Семейный дом до 1,5 млн €, готов к заселению</button>', ar: 'data-ai-search-example>منزل عائلي بأقل من 1.5 مليون يورو، جاهز الآن</button>', nl: 'data-ai-search-example>Gezinswoning onder €1,5M, direct beschikbaar</button>', pl: 'data-ai-search-example>Dom rodzinny poniżej 1,5 mln €, gotowy do zamieszkania</button>', sv: 'data-ai-search-example>Familjebostad under 1,5 miljoner €, inflyttningsklar nu</button>', no: 'data-ai-search-example>Familiebolig under 1,5 mill. €, klar nå</button>'  },
  { find: 'data-ai-search-category data-ai-search-example>&#127958;&#65039; Beach</button>', es: 'data-ai-search-category data-ai-search-example>&#127958;&#65039; Playa</button>', fr: 'data-ai-search-category data-ai-search-example>&#127958;&#65039; Plage</button>', de: 'data-ai-search-category data-ai-search-example>&#127958;&#65039; Strand</button>', ru: 'data-ai-search-category data-ai-search-example>&#127958;&#65039; Пляж</button>', ar: 'data-ai-search-category data-ai-search-example>&#127958;&#65039; شاطئ</button>', nl: 'data-ai-search-category data-ai-search-example>&#127958;&#65039; Strand</button>', pl: 'data-ai-search-category data-ai-search-example>&#127958;&#65039; Plaża</button>', sv: 'data-ai-search-category data-ai-search-example>&#127958;&#65039; Strand</button>', no: 'data-ai-search-category data-ai-search-example>&#127958;&#65039; Strand</button>'  },
  { find: 'data-ai-search-category data-ai-search-example>&#9971;&#65039; Golf</button>', es: 'data-ai-search-category data-ai-search-example>&#9971;&#65039; Golf</button>', fr: 'data-ai-search-category data-ai-search-example>&#9971;&#65039; Golf</button>', de: 'data-ai-search-category data-ai-search-example>&#9971;&#65039; Golf</button>', ru: 'data-ai-search-category data-ai-search-example>&#9971;&#65039; Гольф</button>', ar: 'data-ai-search-category data-ai-search-example>&#9971;&#65039; غولف</button>', nl: 'data-ai-search-category data-ai-search-example>&#9971;&#65039; Golf</button>', pl: 'data-ai-search-category data-ai-search-example>&#9971;&#65039; Golf</button>', sv: 'data-ai-search-category data-ai-search-example>&#9971;&#65039; Golf</button>', no: 'data-ai-search-category data-ai-search-example>&#9971;&#65039; Golf</button>'  },
  { find: 'data-ai-search-category data-ai-search-example>&#127961;&#65039; Family</button>', es: 'data-ai-search-category data-ai-search-example>&#127961;&#65039; Familia</button>', fr: 'data-ai-search-category data-ai-search-example>&#127961;&#65039; Famille</button>', de: 'data-ai-search-category data-ai-search-example>&#127961;&#65039; Familie</button>', ru: 'data-ai-search-category data-ai-search-example>&#127961;&#65039; Семья</button>', ar: 'data-ai-search-category data-ai-search-example>&#127961;&#65039; عائلة</button>', nl: 'data-ai-search-category data-ai-search-example>&#127961;&#65039; Familie</button>', pl: 'data-ai-search-category data-ai-search-example>&#127961;&#65039; Rodzina</button>', sv: 'data-ai-search-category data-ai-search-example>&#127961;&#65039; Familj</button>', no: 'data-ai-search-category data-ai-search-example>&#127961;&#65039; Familie</button>'  },
  { find: 'data-ai-search-category data-ai-search-example>&#128176; Investment</button>', es: 'data-ai-search-category data-ai-search-example>&#128176; Inversión</button>', fr: 'data-ai-search-category data-ai-search-example>&#128176; Investissement</button>', de: 'data-ai-search-category data-ai-search-example>&#128176; Investment</button>', ru: 'data-ai-search-category data-ai-search-example>&#128176; Инвестиции</button>', ar: 'data-ai-search-category data-ai-search-example>&#128176; استثمار</button>', nl: 'data-ai-search-category data-ai-search-example>&#128176; Investering</button>', pl: 'data-ai-search-category data-ai-search-example>&#128176; Inwestycja</button>', sv: 'data-ai-search-category data-ai-search-example>&#128176; Investering</button>', no: 'data-ai-search-category data-ai-search-example>&#128176; Investering</button>'  },

  // Primary filters
  { find: '<span>Location</span>', es: '<span>Ubicación</span>', fr: '<span>Emplacement</span>', de: '<span>Lage</span>', ru: '<span>Расположение</span>', ar: '<span>الموقع</span>', nl: '<span>Locatie</span>', pl: '<span>Lokalizacja</span>', sv: '<span>Läge</span>', no: '<span>Beliggenhet</span>'  },
  { find: '<option value="">All Locations</option>', es: '<option value="">Todas las Ubicaciones</option>', fr: '<option value="">Tous les Emplacements</option>', de: '<option value="">Alle Lagen</option>', ru: '<option value="">Все Районы</option>', ar: '<option value="">جميع المواقع</option>', nl: '<option value="">Alle Locaties</option>', pl: '<option value="">Wszystkie lokalizacje</option>', sv: '<option value="">Alla Lägen</option>', no: '<option value="">Alle Beliggenheter</option>'  },
  { find: '<span>Property Type</span>', es: '<span>Tipo de Propiedad</span>', fr: '<span>Type de Bien</span>', de: '<span>Immobilientyp</span>', ru: '<span>Тип Недвижимости</span>', ar: '<span>نوع العقار</span>', nl: '<span>Woningtype</span>', pl: '<span>Rodzaj nieruchomości</span>', sv: '<span>Bostadstyp</span>', no: '<span>Boligtype</span>'  },
  { find: '<option value="">All Types</option>', es: '<option value="">Todos los Tipos</option>', fr: '<option value="">Tous les Types</option>', de: '<option value="">Alle Typen</option>', ru: '<option value="">Все Типы</option>', ar: '<option value="">جميع الأنواع</option>', nl: '<option value="">Alle Typen</option>', pl: '<option value="">Wszystkie rodzaje</option>', sv: '<option value="">Alla Typer</option>', no: '<option value="">Alle Typer</option>'  },
  { find: '<option value="apartment">Apartment</option>', es: '<option value="apartment">Apartamento</option>', fr: '<option value="apartment">Appartement</option>', de: '<option value="apartment">Wohnung</option>', ru: '<option value="apartment">Апартаменты</option>', ar: '<option value="apartment">شقة</option>', nl: '<option value="apartment">Appartement</option>', pl: '<option value="apartment">Apartament</option>', sv: '<option value="apartment">Lägenhet</option>', no: '<option value="apartment">Leilighet</option>'  },
  { find: '<option value="penthouse">Penthouse</option>', es: '<option value="penthouse">Ático</option>', fr: '<option value="penthouse">Penthouse</option>', de: '<option value="penthouse">Penthouse</option>', ru: '<option value="penthouse">Пентхаус</option>', ar: '<option value="penthouse">بنتهاوس</option>', nl: '<option value="penthouse">Penthouse</option>', pl: '<option value="penthouse">Penthouse</option>', sv: '<option value="penthouse">Takvåning</option>', no: '<option value="penthouse">Toppleilighet</option>'  },
  { find: '<option value="villa">Villa</option>', es: '<option value="villa">Villa</option>', fr: '<option value="villa">Villa</option>', de: '<option value="villa">Villa</option>', ru: '<option value="villa">Вилла</option>', ar: '<option value="villa">فيلا</option>', nl: '<option value="villa">Villa</option>', pl: '<option value="villa">Willa</option>', sv: '<option value="villa">Villa</option>', no: '<option value="villa">Villa</option>'  },
  { find: '<option value="townhouse">Townhouse</option>', es: '<option value="townhouse">Adosado</option>', fr: '<option value="townhouse">Maison de Ville</option>', de: '<option value="townhouse">Reihenhaus</option>', ru: '<option value="townhouse">Таунхаус</option>', ar: '<option value="townhouse">تاون هاوس</option>', nl: '<option value="townhouse">Herenhuis</option>', pl: '<option value="townhouse">Dom szeregowy</option>', sv: '<option value="townhouse">Radhus</option>', no: '<option value="townhouse">Rekkehus</option>'  },
  { find: '<span>Status</span>', es: '<span>Estado</span>', fr: '<span>Statut</span>', de: '<span>Status</span>', ru: '<span>Статус</span>', ar: '<span>الحالة</span>', nl: '<span>Status</span>', pl: '<span>Status</span>', sv: '<span>Status</span>', no: '<span>Status</span>'  },
  { find: '<option value="">Any Status</option>', es: '<option value="">Cualquier Estado</option>', fr: '<option value="">Tout Statut</option>', de: '<option value="">Jeder Status</option>', ru: '<option value="">Любой Статус</option>', ar: '<option value="">أي حالة</option>', nl: '<option value="">Elke Status</option>', pl: '<option value="">Dowolny status</option>', sv: '<option value="">Alla Statusar</option>', no: '<option value="">Enhver Status</option>'  },
  { find: '<option value="off_plan">Off-Plan</option>', es: '<option value="off_plan">Sobre Plano</option>', fr: '<option value="off_plan">Sur Plan</option>', de: '<option value="off_plan">Off-Plan</option>', ru: '<option value="off_plan">На Этапе Строительства</option>', ar: '<option value="off_plan">على المخطط</option>', nl: '<option value="off_plan">Op plan</option>', pl: '<option value="off_plan">Sprzedaż z planu</option>', sv: '<option value="off_plan">Under Projektering</option>', no: '<option value="off_plan">Under Prosjektering</option>'  },
  { find: '<option value="under_construction">Under Construction</option>', es: '<option value="under_construction">En Construcción</option>', fr: '<option value="under_construction">En Construction</option>', de: '<option value="under_construction">Im Bau</option>', ru: '<option value="under_construction">Строится</option>', ar: '<option value="under_construction">قيد الإنشاء</option>', nl: '<option value="under_construction">In Aanbouw</option>', pl: '<option value="under_construction">W budowie</option>', sv: '<option value="under_construction">Under Uppförande</option>', no: '<option value="under_construction">Under Bygging</option>'  },
  { find: '<option value="completed">Completed</option>', es: '<option value="completed">Finalizado</option>', fr: '<option value="completed">Terminé</option>', de: '<option value="completed">Fertiggestellt</option>', ru: '<option value="completed">Завершено</option>', ar: '<option value="completed">مكتمل</option>', nl: '<option value="completed">Voltooid</option>', pl: '<option value="completed">Ukończone</option>', sv: '<option value="completed">Färdigställd</option>', no: '<option value="completed">Ferdigstilt</option>'  },
  { find: '<span>Move-in Timing</span>', es: '<span>Plazo de Entrada</span>', fr: '<span>Délai d’Emménagement</span>', de: '<span>Einzugstermin</span>', ru: '<span>Срок Заселения</span>', ar: '<span>موعد الانتقال</span>', nl: '<span>Opleverdatum</span>', pl: '<span>Termin odbioru</span>', sv: '<span>Inflyttningstid</span>', no: '<span>Innflyttingstidspunkt</span>'  },
  { find: '<option value="">Any Timing</option>', es: '<option value="">Cualquier Plazo</option>', fr: '<option value="">Tout Délai</option>', de: '<option value="">Jeder Zeitpunkt</option>', ru: '<option value="">Любой Срок</option>', ar: '<option value="">أي وقت</option>', nl: '<option value="">Elk Moment</option>', pl: '<option value="">Dowolny termin</option>', sv: '<option value="">Alla Tider</option>', no: '<option value="">Alle Tidspunkter</option>'  },
  { find: '<option value="ready">Ready Now</option>', es: '<option value="ready">Listo para Entrar</option>', fr: '<option value="ready">Disponible Maintenant</option>', de: '<option value="ready">Sofort Bezugsfertig</option>', ru: '<option value="ready">Готово Сейчас</option>', ar: '<option value="ready">جاهز الآن</option>', nl: '<option value="ready">Direct Beschikbaar</option>', pl: '<option value="ready">Gotowe do zamieszkania</option>', sv: '<option value="ready">Inflyttningsklar Nu</option>', no: '<option value="ready">Klar Nå</option>'  },
  { find: '<option value="1y">Within 1 Year</option>', es: '<option value="1y">En 1 Año</option>', fr: '<option value="1y">Sous 1 An</option>', de: '<option value="1y">Innerhalb 1 Jahres</option>', ru: '<option value="1y">В Течение 1 Года</option>', ar: '<option value="1y">خلال سنة واحدة</option>', nl: '<option value="1y">Binnen 1 Jaar</option>', pl: '<option value="1y">W ciągu 1 roku</option>', sv: '<option value="1y">Inom 1 År</option>', no: '<option value="1y">Innen 1 År</option>'  },
  { find: '<option value="2y">Within 2 Years</option>', es: '<option value="2y">En 2 Años</option>', fr: '<option value="2y">Sous 2 Ans</option>', de: '<option value="2y">Innerhalb von 2 Jahren</option>', ru: '<option value="2y">В Течение 2 Лет</option>', ar: '<option value="2y">خلال سنتين</option>', nl: '<option value="2y">Binnen 2 Jaar</option>', pl: '<option value="2y">W ciągu 2 lat</option>', sv: '<option value="2y">Inom 2 År</option>', no: '<option value="2y">Innen 2 År</option>'  },
  { find: '<option value="2y+">2+ Years</option>', es: '<option value="2y+">Más de 2 Años</option>', fr: '<option value="2y+">Plus de 2 Ans</option>', de: '<option value="2y+">Über 2 Jahre</option>', ru: '<option value="2y+">Более 2 Лет</option>', ar: '<option value="2y+">أكثر من سنتين</option>', nl: '<option value="2y+">2+ Jaar</option>', pl: '<option value="2y+">Ponad 2 lata</option>', sv: '<option value="2y+">2+ År</option>', no: '<option value="2y+">2+ År</option>'  },
  { find: '<span>Price Range<em class="range-readout" data-range-readout>Any price</em></span>', es: '<span>Rango de Precio<em class="range-readout" data-range-readout>Cualquier precio</em></span>', fr: '<span>Fourchette de Prix<em class="range-readout" data-range-readout>Tout prix</em></span>', de: '<span>Preisspanne<em class="range-readout" data-range-readout>Jeder Preis</em></span>', ru: '<span>Диапазон Цен<em class="range-readout" data-range-readout>Любая цена</em></span>', ar: '<span>نطاق السعر<em class="range-readout" data-range-readout>أي سعر</em></span>', nl: '<span>Prijsklasse<em class="range-readout" data-range-readout>Elke prijs</em></span>', pl: '<span>Zakres cen<em class="range-readout" data-range-readout>Dowolna cena</em></span>', sv: '<span>Prisintervall<em class="range-readout" data-range-readout>Alla priser</em></span>', no: '<span>Prisintervall<em class="range-readout" data-range-readout>Alle priser</em></span>'  },
  { find: 'aria-label="Minimum price"', es: 'aria-label="Precio mínimo"', fr: 'aria-label="Prix minimum"', de: 'aria-label="Mindestpreis"', ru: 'aria-label="Минимальная цена"', ar: 'aria-label="الحد الأدنى للسعر"', nl: 'aria-label="Minimumprijs"', pl: 'aria-label="Cena minimalna"', sv: 'aria-label="Minimipris"', no: 'aria-label="Minstepris"'  },
  { find: 'aria-label="Maximum price"', es: 'aria-label="Precio máximo"', fr: 'aria-label="Prix maximum"', de: 'aria-label="Höchstpreis"', ru: 'aria-label="Максимальная цена"', ar: 'aria-label="الحد الأقصى للسعر"', nl: 'aria-label="Maximumprijs"', pl: 'aria-label="Cena maksymalna"', sv: 'aria-label="Maxpris"', no: 'aria-label="Maksimalpris"'  },
  { find: '<span>Bedrooms<em class="range-readout" data-range-readout>Any</em></span>', es: '<span>Dormitorios<em class="range-readout" data-range-readout>Cualquiera</em></span>', fr: '<span>Chambres<em class="range-readout" data-range-readout>Toutes</em></span>', de: '<span>Schlafzimmer<em class="range-readout" data-range-readout>Beliebig</em></span>', ru: '<span>Спальни<em class="range-readout" data-range-readout>Любое число</em></span>', ar: '<span>غرف النوم<em class="range-readout" data-range-readout>أي عدد</em></span>', nl: '<span>Slaapkamers<em class="range-readout" data-range-readout>Elk aantal</em></span>', pl: '<span>Sypialnie<em class="range-readout" data-range-readout>Dowolna liczba</em></span>', sv: '<span>Sovrum<em class="range-readout" data-range-readout>Alla</em></span>', no: '<span>Soverom<em class="range-readout" data-range-readout>Alle</em></span>'  },
  { find: 'aria-label="Minimum bedrooms"', es: 'aria-label="Mínimo de dormitorios"', fr: 'aria-label="Nombre minimum de chambres"', de: 'aria-label="Minimale Schlafzimmeranzahl"', ru: 'aria-label="Минимум спален"', ar: 'aria-label="الحد الأدنى لغرف النوم"', nl: 'aria-label="Minimum aantal slaapkamers"', pl: 'aria-label="Minimalna liczba sypialni"', sv: 'aria-label="Minsta antal sovrum"', no: 'aria-label="Minste antall soverom"'  },
  { find: 'aria-label="Maximum bedrooms"', es: 'aria-label="Máximo de dormitorios"', fr: 'aria-label="Nombre maximum de chambres"', de: 'aria-label="Maximale Schlafzimmeranzahl"', ru: 'aria-label="Максимум спален"', ar: 'aria-label="الحد الأقصى لغرف النوم"', nl: 'aria-label="Maximum aantal slaapkamers"', pl: 'aria-label="Maksymalna liczba sypialni"', sv: 'aria-label="Högsta antal sovrum"', no: 'aria-label="Høyeste antall soverom"'  },
  { find: '>Reset Filters</button>', es: '>Restablecer Filtros</button>', fr: '>Réinitialiser les Filtres</button>', de: '>Filter Zurücksetzen</button>', ru: '>Сбросить Фильтры</button>', ar: '>إعادة تعيين الفلاتر</button>', nl: '>Filters Resetten</button>', pl: '>Resetuj filtry</button>', sv: '>Återställ Filter</button>', no: '>Tilbakestill filtre</button>'  },

  // Lifestyle panel
  { find: '<span class="lifestyle-star" aria-hidden="true">&#10022;</span> Filter by Lifestyle</span>', es: '<span class="lifestyle-star" aria-hidden="true">&#10022;</span> Filtrar por Estilo de Vida</span>', fr: '<span class="lifestyle-star" aria-hidden="true">&#10022;</span> Filtrer par Style de Vie</span>', de: '<span class="lifestyle-star" aria-hidden="true">&#10022;</span> Nach Lebensstil Filtern</span>', ru: '<span class="lifestyle-star" aria-hidden="true">&#10022;</span> Фильтр по Образу Жизни</span>', ar: '<span class="lifestyle-star" aria-hidden="true">&#10022;</span> تصفية حسب نمط الحياة</span>', nl: '<span class="lifestyle-star" aria-hidden="true">&#10022;</span> Filteren op Levensstijl</span>', pl: '<span class="lifestyle-star" aria-hidden="true">&#10022;</span> Filtruj wg stylu życia</span>', sv: '<span class="lifestyle-star" aria-hidden="true">&#10022;</span> Filtrera efter livsstil</span>', no: '<span class="lifestyle-star" aria-hidden="true">&#10022;</span> Filtrer etter Livsstil</span>'  },
  { find: 'aria-label="Lifestyle filter mode"', es: 'aria-label="Modo de filtro de estilo de vida"', fr: 'aria-label="Mode de filtre style de vie"', de: 'aria-label="Lifestyle-Filtermodus"', ru: 'aria-label="Режим фильтра по образу жизни"', ar: 'aria-label="وضع تصفية نمط الحياة"', nl: 'aria-label="Modus levensstijlfilter"', pl: 'aria-label="Tryb filtra stylu życia"', sv: 'aria-label="Filterläge för livsstil"', no: 'aria-label="Filtermodus for livsstil"'  },
  { find: 'data-mode="lifestyle" aria-selected="true">Lifestyle</button>', es: 'data-mode="lifestyle" aria-selected="true">Estilo de Vida</button>', fr: 'data-mode="lifestyle" aria-selected="true">Style de Vie</button>', de: 'data-mode="lifestyle" aria-selected="true">Lebensstil</button>', ru: 'data-mode="lifestyle" aria-selected="true">Образ Жизни</button>', ar: 'data-mode="lifestyle" aria-selected="true">نمط الحياة</button>', nl: 'data-mode="lifestyle" aria-selected="true">Levensstijl</button>', pl: 'data-mode="lifestyle" aria-selected="true">Styl życia</button>', sv: 'data-mode="lifestyle" aria-selected="true">Livsstil</button>', no: 'data-mode="lifestyle" aria-selected="true">Livsstil</button>'  },
  { find: 'data-mode="architecture" aria-selected="false">Architecture</button>', es: 'data-mode="architecture" aria-selected="false">Arquitectura</button>', fr: 'data-mode="architecture" aria-selected="false">Architecture</button>', de: 'data-mode="architecture" aria-selected="false">Architektur</button>', ru: 'data-mode="architecture" aria-selected="false">Архитектура</button>', ar: 'data-mode="architecture" aria-selected="false">العمارة</button>', nl: 'data-mode="architecture" aria-selected="false">Architectuur</button>', pl: 'data-mode="architecture" aria-selected="false">Architektura</button>', sv: 'data-mode="architecture" aria-selected="false">Arkitektur</button>', no: 'data-mode="architecture" aria-selected="false">Arkitektur</button>'  },
  { find: 'data-mode="location" aria-selected="false">Setting</button>', es: 'data-mode="location" aria-selected="false">Entorno</button>', fr: 'data-mode="location" aria-selected="false">Cadre</button>', de: 'data-mode="location" aria-selected="false">Umgebung</button>', ru: 'data-mode="location" aria-selected="false">Окружение</button>', ar: 'data-mode="location" aria-selected="false">المحيط</button>', nl: 'data-mode="location" aria-selected="false">Omgeving</button>', pl: 'data-mode="location" aria-selected="false">Otoczenie</button>', sv: 'data-mode="location" aria-selected="false">Omgivning</button>', no: 'data-mode="location" aria-selected="false">Omgivelser</button>'  },
  { find: 'data-mode="investment" aria-selected="false">Investment</button>', es: 'data-mode="investment" aria-selected="false">Inversión</button>', fr: 'data-mode="investment" aria-selected="false">Investissement</button>', de: 'data-mode="investment" aria-selected="false">Investment</button>', ru: 'data-mode="investment" aria-selected="false">Инвестиции</button>', ar: 'data-mode="investment" aria-selected="false">الاستثمار</button>', nl: 'data-mode="investment" aria-selected="false">Investering</button>', pl: 'data-mode="investment" aria-selected="false">Inwestycja</button>', sv: 'data-mode="investment" aria-selected="false">Investering</button>', no: 'data-mode="investment" aria-selected="false">Investering</button>'  },
  { find: '<span>No lifestyle filters selected</span>', es: '<span>Sin filtros de estilo de vida seleccionados</span>', fr: '<span>Aucun filtre de style de vie sélectionné</span>', de: '<span>Keine Lifestyle-Filter ausgewählt</span>', ru: '<span>Фильтры по образу жизни не выбраны</span>', ar: '<span>لم يتم اختيار فلاتر نمط الحياة</span>', nl: '<span>Geen levensstijlfilters geselecteerd</span>', pl: '<span>Nie wybrano filtrów stylu życia</span>', sv: '<span>Inga livsstilsfilter valda</span>', no: '<span>Ingen livsstilsfiltre valgt</span>'  },

  // Sort
  { find: '<span>Sort</span>', es: '<span>Ordenar</span>', fr: '<span>Trier</span>', de: '<span>Sortieren</span>', ru: '<span>Сортировка</span>', ar: '<span>ترتيب</span>', nl: '<span>Sorteren</span>', pl: '<span>Sortuj</span>', sv: '<span>Sortera</span>', no: '<span>Sorter</span>'  },
  { find: '<option value="curated">Recommended order</option>', es: '<option value="curated">Orden recomendado</option>', fr: '<option value="curated">Ordre recommandé</option>', de: '<option value="curated">Empfohlene Reihenfolge</option>', ru: '<option value="curated">Рекомендуемый порядок</option>', ar: '<option value="curated">الترتيب الموصى به</option>', nl: '<option value="curated">Aanbevolen volgorde</option>', pl: '<option value="curated">Kolejność polecana</option>', sv: '<option value="curated">Rekommenderad ordning</option>', no: '<option value="curated">Anbefalt rekkefølge</option>'  },
  { find: '<option value="newest">Newest release</option>', es: '<option value="newest">Lanzamiento más reciente</option>', fr: '<option value="newest">Lancement le plus récent</option>', de: '<option value="newest">Neueste Veröffentlichung</option>', ru: '<option value="newest">Сначала новые</option>', ar: '<option value="newest">الأحدث إصدارًا</option>', nl: '<option value="newest">Nieuwste release</option>', pl: '<option value="newest">Najnowsza premiera</option>', sv: '<option value="newest">Senaste lansering</option>', no: '<option value="newest">Nyeste lansering</option>'  },
  { find: '<option value="price-asc">Price: low to high</option>', es: '<option value="price-asc">Precio: de menor a mayor</option>', fr: '<option value="price-asc">Prix : croissant</option>', de: '<option value="price-asc">Preis: aufsteigend</option>', ru: '<option value="price-asc">Цена: по возрастанию</option>', ar: '<option value="price-asc">السعر: من الأقل إلى الأعلى</option>', nl: '<option value="price-asc">Prijs: laag naar hoog</option>', pl: '<option value="price-asc">Cena: rosnąco</option>', sv: '<option value="price-asc">Pris: lågt till högt</option>', no: '<option value="price-asc">Pris: lavt til høyt</option>'  },
  { find: '<option value="price-desc">Price: high to low</option>', es: '<option value="price-desc">Precio: de mayor a menor</option>', fr: '<option value="price-desc">Prix : décroissant</option>', de: '<option value="price-desc">Preis: absteigend</option>', ru: '<option value="price-desc">Цена: по убыванию</option>', ar: '<option value="price-desc">السعر: من الأعلى إلى الأقل</option>', nl: '<option value="price-desc">Prijs: hoog naar laag</option>', pl: '<option value="price-desc">Cena: malejąco</option>', sv: '<option value="price-desc">Pris: högt till lågt</option>', no: '<option value="price-desc">Pris: høyt til lavt</option>'  },
  { find: '<option value="completion">Completion soonest</option>', es: '<option value="completion">Entrega más próxima</option>', fr: '<option value="completion">Livraison la plus proche</option>', de: '<option value="completion">Frühestes Fertigstellungsdatum</option>', ru: '<option value="completion">Ближайшая сдача</option>', ar: '<option value="completion">الأقرب إنجازًا</option>', nl: '<option value="completion">Eerstvolgende oplevering</option>', pl: '<option value="completion">Najbliższy termin ukończenia</option>', sv: '<option value="completion">Snarast färdigställande</option>', no: '<option value="completion">Snarest ferdigstillelse</option>'  },

  // Empty state
  { find: '<span>No exact match found.</span>', es: '<span>No se encontró ninguna coincidencia exacta.</span>', fr: '<span>Aucune correspondance exacte trouvée.</span>', de: '<span>Keine genaue Übereinstimmung gefunden.</span>', ru: '<span>Точных совпадений не найдено.</span>', ar: '<span>لم يتم العثور على تطابق دقيق.</span>', nl: '<span>Geen exacte match gevonden.</span>', pl: '<span>Nie znaleziono dokładnego dopasowania.</span>', sv: '<span>Ingen exakt träff hittades.</span>', no: '<span>Ingen eksakt match funnet.</span>'  },
  { find: '<p>Try fewer filters, explore similar projects or tell us what you are looking for.</p>', es: '<p>Prueba con menos filtros, explora proyectos similares o cuéntanos qué buscas.</p>', fr: '<p>Essayez avec moins de filtres, explorez des projets similaires ou dites-nous ce que vous recherchez.</p>', de: '<p>Versuchen Sie es mit weniger Filtern, entdecken Sie ähnliche Projekte oder sagen Sie uns, wonach Sie suchen.</p>', ru: '<p>Попробуйте убрать часть фильтров, посмотрите похожие проекты или расскажите нам, что вы ищете.</p>', ar: '<p>جرّب عددًا أقل من الفلاتر، أو استكشف مشاريع مشابهة، أو أخبرنا بما تبحث عنه.</p>', nl: '<p>Probeer minder filters, bekijk vergelijkbare projecten of vertel ons wat u zoekt.</p>', pl: '<p>Spróbuj użyć mniej filtrów, przejrzyj podobne projekty lub powiedz nam, czego szukasz.</p>', sv: '<p>Prova med färre filter, utforska liknande projekt eller berätta vad du letar efter.</p>', no: '<p>Prøv færre filtre, utforsk lignende prosjekter eller fortell oss hva du leter etter.</p>'  },
  { find: '>Get a Personal Shortlist</a>', es: '>Solicita tu Lista Personalizada</a>', fr: '>Recevoir une Sélection Personnalisée</a>', de: '>Persönliche Auswahl Erhalten</a>', ru: '>Получить Персональную Подборку</a>', ar: '>احصل على قائمة مختارة شخصية</a>', nl: '>Vraag een Persoonlijke Selectie Aan</a>', pl: '>Otrzymaj osobistą listę ofert</a>', sv: '>Få en personlig urval</a>', no: '>Få en personlig utvalgsliste</a>'  },

  // Card meta labels + CTA (shared set lives in PROJECT_CARD_ENTRIES below;
  // merged into this page's entries at the bottom of this file)
];

// Project-card meta labels, meta values and CTA shared by every page that
// renders generated project cards (developments.html, segment pages).
export const PROJECT_CARD_ENTRIES = [
  ...CARD_CHROME_ENTRIES,
  { find: '<div><span>From</span><strong>', es: '<div><span>Desde</span><strong>', fr: '<div><span>À Partir de</span><strong>', de: '<div><span>Ab</span><strong>', ru: '<div><span>От</span><strong>', ar: '<div><span>ابتداءً من</span><strong>', nl: '<div><span>Vanaf</span><strong>', pl: '<div><span>Od</span><strong>', sv: '<div><span>Från</span><strong>', no: '<div><span>Fra</span><strong>'  },
  { find: '<div><span>Type</span><strong>', es: '<div><span>Tipo</span><strong>', fr: '<div><span>Type</span><strong>', de: '<div><span>Typ</span><strong>', ru: '<div><span>Тип</span><strong>', ar: '<div><span>النوع</span><strong>', nl: '<div><span>Type</span><strong>', pl: '<div><span>Rodzaj</span><strong>', sv: '<div><span>Typ</span><strong>', no: '<div><span>Type</span><strong>'  },
  { find: '<div><span>Status</span><strong>', es: '<div><span>Estado</span><strong>', fr: '<div><span>Statut</span><strong>', de: '<div><span>Status</span><strong>', ru: '<div><span>Статус</span><strong>', ar: '<div><span>الحالة</span><strong>', nl: '<div><span>Status</span><strong>', pl: '<div><span>Status</span><strong>', sv: '<div><span>Status</span><strong>', no: '<div><span>Status</span><strong>'  },
  { find: '<div><span>Delivery</span><strong>', es: '<div><span>Entrega</span><strong>', fr: '<div><span>Livraison</span><strong>', de: '<div><span>Übergabe</span><strong>', ru: '<div><span>Сдача</span><strong>', ar: '<div><span>التسليم</span><strong>', nl: '<div><span>Oplevering</span><strong>', pl: '<div><span>Termin odbioru</span><strong>', sv: '<div><span>Leverans</span><strong>', no: '<div><span>Levering</span><strong>'  },
  { find: '>Explore Project</a>', es: '>Explorar Proyecto</a>', fr: '>Découvrir le Projet</a>', de: '>Projekt Entdecken</a>', ru: '>Смотреть Проект</a>', ar: '>استكشاف المشروع</a>', nl: '>Bekijk Project</a>', pl: '>Zobacz projekt</a>', sv: '>Utforska Projekt</a>', no: '>Utforsk prosjekt</a>'  },
  { find: 'aria-label="Previous image"', es: 'aria-label="Imagen anterior"', fr: 'aria-label="Image précédente"', de: 'aria-label="Vorheriges Bild"', ru: 'aria-label="Предыдущее изображение"', ar: 'aria-label="الصورة السابقة"', nl: 'aria-label="Vorige afbeelding"', pl: 'aria-label="Poprzednie zdjęcie"', sv: 'aria-label="Föregående bild"', no: 'aria-label="Forrige bilde"'  },
  { find: 'aria-label="Next image"', es: 'aria-label="Imagen siguiente"', fr: 'aria-label="Image suivante"', de: 'aria-label="Nächstes Bild"', ru: 'aria-label="Следующее изображение"', ar: 'aria-label="الصورة التالية"', nl: 'aria-label="Volgende afbeelding"', pl: 'aria-label="Następne zdjęcie"', sv: 'aria-label="Nästa bild"', no: 'aria-label="Neste bilde"'  },

  // Card meta type values (mirrors the homepage's dictionary)
  { find: '<strong>Apartments, Penthouses &amp; Villas</strong>', es: '<strong>Apartamentos, Áticos y Villas</strong>', fr: '<strong>Appartements, Penthouses et Villas</strong>', de: '<strong>Wohnungen, Penthäuser & Villen</strong>', ru: '<strong>Апартаменты, Пентхаусы и Виллы</strong>', ar: '<strong>شقق وبنتهاوس وفلل</strong>', nl: '<strong>Appartementen, Penthouses & Villa’s</strong>', pl: '<strong>Apartamenty, penthouse’y i wille</strong>', sv: '<strong>Lägenheter, takvåningar och villor</strong>', no: '<strong>Leiligheter, toppleiligheter & villaer</strong>'  },
  { find: '<strong>Semi-Detached Houses</strong>', es: '<strong>Casas Adosadas</strong>', fr: '<strong>Maisons Jumelées</strong>', de: '<strong>Doppelhaushälften</strong>', ru: '<strong>Дома на Две Семьи</strong>', ar: '<strong>منازل شبه منفصلة</strong>', nl: '<strong>Twee-onder-een-kapwoningen</strong>', pl: '<strong>Domy bliźniacze</strong>', sv: '<strong>Parhus</strong>', no: '<strong>Tomannsboliger</strong>'  },
  { find: '<strong>Penthouses &amp; Villas</strong>', es: '<strong>Áticos y Villas</strong>', fr: '<strong>Penthouses et Villas</strong>', de: '<strong>Penthäuser & Villen</strong>', ru: '<strong>Пентхаусы и Виллы</strong>', ar: '<strong>بنتهاوس وفلل</strong>', nl: '<strong>Penthouses & Villa’s</strong>', pl: '<strong>Penthouse’y i wille</strong>', sv: '<strong>Takvåningar & Villor</strong>', no: '<strong>Toppleiligheter & villaer</strong>'  },
  { find: '<strong>Apartments &amp; Penthouses</strong>', es: '<strong>Apartamentos y Áticos</strong>', fr: '<strong>Appartements et Penthouses</strong>', de: '<strong>Wohnungen & Penthäuser</strong>', ru: '<strong>Апартаменты и Пентхаусы</strong>', ar: '<strong>شقق وبنتهاوس</strong>', nl: '<strong>Appartementen & Penthouses</strong>', pl: '<strong>Apartamenty i penthouse’y</strong>', sv: '<strong>Lägenheter & Takvåningar</strong>', no: '<strong>Leiligheter & toppleiligheter</strong>'  },
  { find: '<strong>1-4 Bedroom Homes</strong>', es: '<strong>Viviendas de 1 a 4 Dormitorios</strong>', fr: '<strong>Logements de 1 à 4 Chambres</strong>', de: '<strong>Wohnungen mit 1–4 Schlafzimmern</strong>', ru: '<strong>Дома с 1–4 Спальнями</strong>', ar: '<strong>مساكن من غرفة إلى 4 غرف نوم</strong>', nl: '<strong>Woningen met 1 tot 4 Slaapkamers</strong>', pl: '<strong>Domy z 1–4 sypialniami</strong>', sv: '<strong>Bostäder med 1–4 Sovrum</strong>', no: '<strong>Boliger med 1–4 soverom</strong>'  },
  { find: '<strong>Duplex Residences &amp; Penthouses</strong>', es: '<strong>Dúplex y Áticos</strong>', fr: '<strong>Duplex et Penthouses</strong>', de: '<strong>Duplex-Residenzen & Penthäuser</strong>', ru: '<strong>Дуплексы и Пентхаусы</strong>', ar: '<strong>دوبلكس وبنتهاوس</strong>', nl: '<strong>Duplexwoningen & Penthouses</strong>', pl: '<strong>Rezydencje dupleksowe i penthouse’y</strong>', sv: '<strong>Duplexbostäder & Takvåningar</strong>', no: '<strong>Dupleksboliger & toppleiligheter</strong>'  },
  { find: '<strong>Villas &amp; Apartments</strong>', es: '<strong>Villas y Apartamentos</strong>', fr: '<strong>Villas et Appartements</strong>', de: '<strong>Villen & Wohnungen</strong>', ru: '<strong>Виллы и Апартаменты</strong>', ar: '<strong>فلل وشقق</strong>', nl: '<strong>Villa’s & Appartementen</strong>', pl: '<strong>Wille i apartamenty</strong>', sv: '<strong>Villor & Lägenheter</strong>', no: '<strong>Villaer & leiligheter</strong>'  },
  { find: '<strong>Villas</strong>', es: '<strong>Villas</strong>', fr: '<strong>Villas</strong>', de: '<strong>Villen</strong>', ru: '<strong>Виллы</strong>', ar: '<strong>فلل</strong>', nl: '<strong>Villa’s</strong>', pl: '<strong>Wille</strong>', sv: '<strong>Villor</strong>', no: '<strong>Villaer</strong>'  },
  // Card meta status values
  { find: '<strong>Off-Plan</strong>', es: '<strong>Sobre Plano</strong>', fr: '<strong>Sur Plan</strong>', de: '<strong>Off-Plan</strong>', ru: '<strong>На Этапе Строительства</strong>', ar: '<strong>على المخطط</strong>', nl: '<strong>Op plan</strong>', pl: '<strong>Sprzedaż z planu</strong>', sv: '<strong>Under Projektering</strong>', no: '<strong>Under prosjektering</strong>'  },
  { find: '<strong>Off-plan</strong>', es: '<strong>Sobre plano</strong>', fr: '<strong>Sur plan</strong>', de: '<strong>Off-Plan</strong>', ru: '<strong>На этапе строительства</strong>', ar: '<strong>على المخطط</strong>', nl: '<strong>Op plan</strong>', pl: '<strong>Sprzedaż z planu</strong>', sv: '<strong>Under projektering</strong>', no: '<strong>Under prosjektering</strong>'  },
  { find: '<strong>Completed</strong>', es: '<strong>Finalizado</strong>', fr: '<strong>Terminé</strong>', de: '<strong>Fertiggestellt</strong>', ru: '<strong>Завершено</strong>', ar: '<strong>مكتمل</strong>', nl: '<strong>Voltooid</strong>', pl: '<strong>Ukończone</strong>', sv: '<strong>Färdigställd</strong>', no: '<strong>Ferdigstilt</strong>'  },
  { find: '<strong>Current release</strong>', es: '<strong>Fase actual</strong>', fr: '<strong>Phase actuelle</strong>', de: '<strong>Aktuelle Phase</strong>', ru: '<strong>Текущая очередь</strong>', ar: '<strong>المرحلة الحالية</strong>', nl: '<strong>Huidige fase</strong>', pl: '<strong>Aktualny etap</strong>', sv: '<strong>Aktuell fas</strong>', no: '<strong>Nåværende fase</strong>'  },
  { find: '<strong>Under construction</strong>', es: '<strong>En construcción</strong>', fr: '<strong>En construction</strong>', de: '<strong>Im Bau</strong>', ru: '<strong>В стадии строительства</strong>', ar: '<strong>قيد الإنشاء</strong>', nl: '<strong>In aanbouw</strong>', pl: '<strong>W budowie</strong>', sv: '<strong>Under uppförande</strong>', no: '<strong>Under bygging</strong>'  },
  { find: '<strong>Est. Q2 2029</strong>', es: '<strong>Est. T2 2029</strong>', fr: '<strong>Est. T2 2029</strong>', de: '<strong>Vsl. Q2 2029</strong>', ru: '<strong>Ориент. 2 кв. 2029</strong>', ar: '<strong>تقديريًا الربع الثاني 2029</strong>', nl: '<strong>Verw. Q2 2029</strong>', pl: '<strong>Szac. Q2 2029</strong>', sv: '<strong>Ber. Q2 2029</strong>', no: '<strong>Est. Q2 2029</strong>'  },
];

const PAGE_ENTRIES_TAIL = [
  // Archived section
  { find: '<span class="label">Track Record</span>', es: '<span class="label">Trayectoria</span>', fr: '<span class="label">Historique</span>', de: '<span class="label">Erfolgsbilanz</span>', ru: '<span class="label">Наш Опыт</span>', ar: '<span class="label">سجل الإنجازات</span>', nl: '<span class="label">Trackrecord</span>', pl: '<span class="label">Osiągnięcia</span>', sv: '<span class="label">Meritlista</span>', no: '<span class="label">Merittliste</span>'  },
  { find: '<h2 class="section-title">Earlier <em>sold projects</em></h2>', es: '<h2 class="section-title">Proyectos <em>ya vendidos</em></h2>', fr: '<h2 class="section-title">Projets <em>déjà vendus</em></h2>', de: '<h2 class="section-title">Bereits <em>verkaufte Projekte</em></h2>', ru: '<h2 class="section-title">Ранее <em>проданные проекты</em></h2>', ar: '<h2 class="section-title">مشاريع <em>بيعت سابقًا</em></h2>', nl: '<h2 class="section-title">Eerder <em>verkochte projecten</em></h2>', pl: '<h2 class="section-title">Wcześniej <em>sprzedane projekty</em></h2>', sv: '<h2 class="section-title">Tidigare <em>sålda projekt</em></h2>', no: '<h2 class="section-title">Tidligere <em>solgte prosjekter</em></h2>'  },
  { find: '<p class="body-copy">A look back at developments we have already sold out, kept here rather than removed so you can see our track record.</p>', es: '<p class="body-copy">Un repaso a las promociones que ya hemos vendido por completo, que mantenemos aquí en lugar de eliminarlas para que puedas ver nuestra trayectoria.</p>', fr: '<p class="body-copy">Un retour sur les programmes que nous avons déjà entièrement vendus, conservés ici plutôt que supprimés pour que vous puissiez voir notre historique.</p>', de: '<p class="body-copy">Ein Rückblick auf Projekte, die bereits vollständig verkauft sind — wir behalten sie hier, damit Sie unsere Erfolgsbilanz sehen können.</p>', ru: '<p class="body-copy">Обзор проектов, которые уже полностью распроданы, — мы сохраняем их здесь, чтобы вы могли оценить наш опыт.</p>', ar: '<p class="body-copy">نظرة على المشاريع التي بيعت بالكامل، نحتفظ بها هنا بدلًا من حذفها لتتمكن من الاطلاع على سجل إنجازاتنا.</p>', nl: '<p class="body-copy">Een overzicht van projecten die we al volledig hebben verkocht, hier bewaard in plaats van verwijderd zodat u ons trackrecord kunt zien.</p>', pl: '<p class="body-copy">Przegląd inwestycji, które już całkowicie sprzedaliśmy — zachowujemy je tutaj zamiast usuwać, aby mogli Państwo zobaczyć nasze osiągnięcia.</p>', sv: '<p class="body-copy">En tillbakablick på projekt som vi redan har sålt slut, sparade här istället för borttagna så att du kan se vår meritlista.</p>', no: '<p class="body-copy">Et tilbakeblikk på prosjekter vi allerede har solgt ut, bevart her i stedet for fjernet, slik at du kan se vår merittliste.</p>'  },
  { find: 'No earlier sold projects to show yet &mdash; check back soon.', es: 'Aún no hay proyectos vendidos que mostrar. Vuelve pronto.', fr: 'Aucun projet déjà vendu à afficher pour le moment — revenez bientôt.', de: 'Noch keine verkauften Projekte zu zeigen — schauen Sie bald wieder vorbei.', ru: 'Пока нет проданных проектов для показа — загляните позже.', ar: 'لا توجد مشاريع مباعة لعرضها بعد — عد قريبًا.', nl: 'Nog geen eerder verkochte projecten om te tonen — kom binnenkort terug.', pl: 'Brak jeszcze wcześniej sprzedanych projektów do wyświetlenia — sprawdź ponownie wkrótce.', sv: 'Inga tidigare sålda projekt att visa än — kom tillbaka snart.', no: 'Ingen tidligere solgte prosjekter å vise ennå — kom tilbake snart.'  },

  // Before-you-view band
  { find: '<span class="label">Before You View</span>', es: '<span class="label">Antes de la Visita</span>', fr: '<span class="label">Avant Votre Visite</span>', de: '<span class="label">Vor der Besichtigung</span>', ru: '<span class="label">Перед Просмотром</span>', ar: '<span class="label">قبل المعاينة</span>', nl: '<span class="label">Voor het Bezichtigen</span>', pl: '<span class="label">Przed oglądaniem</span>', sv: '<span class="label">Innan Visning</span>', no: '<span class="label">Før Visning</span>'  },
  { find: '<h2 class="section-title">What we check before <em>a viewing</em></h2>', es: '<h2 class="section-title">Qué comprobamos antes de <em>una visita</em></h2>', fr: '<h2 class="section-title">Ce que nous vérifions avant <em>une visite</em></h2>', de: '<h2 class="section-title">Was wir vor <em>einer Besichtigung</em> prüfen</h2>', ru: '<h2 class="section-title">Что мы проверяем перед <em>просмотром</em></h2>', ar: '<h2 class="section-title">ما نتحقق منه قبل <em>المعاينة</em></h2>', nl: '<h2 class="section-title">Wat we controleren voor <em>een bezichtiging</em></h2>', pl: '<h2 class="section-title">Co sprawdzamy przed <em>oglądaniem</em></h2>', sv: '<h2 class="section-title">Vad vi kontrollerar innan <em>en visning</em></h2>', no: '<h2 class="section-title">Hva vi sjekker før <em>en visning</em></h2>'  },
  { find: '<h3>Latest Prices &amp; Availability</h3>', es: '<h3>Precios y Disponibilidad Actualizados</h3>', fr: '<h3>Prix et Disponibilités à Jour</h3>', de: '<h3>Aktuelle Preise & Verfügbarkeit</h3>', ru: '<h3>Актуальные Цены и Наличие</h3>', ar: '<h3>أحدث الأسعار والتوافر</h3>', nl: '<h3>Actuele Prijzen & Beschikbaarheid</h3>', pl: '<h3>Aktualne ceny i dostępność</h3>', sv: '<h3>Senaste priser och tillgänglighet</h3>', no: '<h3>Siste priser & tilgjengelighet</h3>'  },
  { find: '<p>Which homes are available, their reservation status, current prices and expected delivery.</p>', es: '<p>Qué viviendas están disponibles, su estado de reserva, precios actuales y entrega prevista.</p>', fr: '<p>Quels logements sont disponibles, leur statut de réservation, les prix actuels et la livraison prévue.</p>', de: '<p>Welche Wohnungen verfügbar sind, ihr Reservierungsstatus, aktuelle Preise und die voraussichtliche Übergabe.</p>', ru: '<p>Какие объекты доступны, их статус резервирования, актуальные цены и ожидаемые сроки сдачи.</p>', ar: '<p>ما هي المساكن المتاحة، وحالة حجزها، والأسعار الحالية، وموعد التسليم المتوقع.</p>', nl: '<p>Welke woningen beschikbaar zijn, hun reserveringsstatus, actuele prijzen en verwachte oplevering.</p>', pl: '<p>Które domy są dostępne, ich status rezerwacji, aktualne ceny i przewidywany termin odbioru.</p>', sv: '<p>Vilka bostäder som är tillgängliga, deras bokningsstatus, aktuella priser och förväntad leverans.</p>', no: '<p>Hvilke boliger som er tilgjengelige, reservasjonsstatus, gjeldende priser og forventet levering.</p>'  },
  { find: '<h3>The Developer</h3>', es: '<h3>La Promotora</h3>', fr: '<h3>Le Promoteur</h3>', de: '<h3>Der Bauträger</h3>', ru: '<h3>Застройщик</h3>', ar: '<h3>المطور العقاري</h3>', nl: '<h3>De Ontwikkelaar</h3>', pl: '<h3>Deweloper</h3>', sv: '<h3>Byggherren</h3>', no: '<h3>Utbyggeren</h3>'  },
  { find: '<p>Previous projects, warranties, specifications and comparable developments nearby.</p>', es: '<p>Proyectos anteriores, garantías, especificaciones y promociones comparables en la zona.</p>', fr: '<p>Projets antérieurs, garanties, spécifications et programmes comparables à proximité.</p>', de: '<p>Frühere Projekte, Garantien, Ausstattungsmerkmale und vergleichbare Projekte in der Nähe.</p>', ru: '<p>Предыдущие проекты, гарантии, спецификации и сопоставимые новостройки поблизости.</p>', ar: '<p>المشاريع السابقة والضمانات والمواصفات والمشاريع المماثلة القريبة.</p>', nl: '<p>Eerdere projecten, garanties, specificaties en vergelijkbare nieuwbouwprojecten in de buurt.</p>', pl: '<p>Wcześniejsze projekty, gwarancje, specyfikacje i porównywalne inwestycje w okolicy.</p>', sv: '<p>Tidigare projekt, garantier, specifikationer och jämförbara bostadsprojekt i närheten.</p>', no: '<p>Tidligere prosjekter, garantier, spesifikasjoner og sammenlignbare boligprosjekter i nærheten.</p>'  },
  { find: '<h3>The Location</h3>', es: '<h3>La Ubicación</h3>', fr: '<h3>L’Emplacement</h3>', de: '<h3>Die Lage</h3>', ru: '<h3>Расположение</h3>', ar: '<h3>الموقع</h3>', nl: '<h3>De Locatie</h3>', pl: '<h3>Lokalizacja</h3>', sv: '<h3>Läget</h3>', no: '<h3>Beliggenheten</h3>'  },
  { find: '<p>Access, nearby services, rental demand, resale appeal and how the area fits your plans.</p>', es: '<p>Accesos, servicios cercanos, demanda de alquiler, atractivo de reventa y cómo encaja la zona con tus planes.</p>', fr: '<p>Accès, services à proximité, demande locative, attrait à la revente et adéquation du secteur avec vos projets.</p>', de: '<p>Anbindung, nahegelegene Dienstleistungen, Mietnachfrage, Wiederverkaufsattraktivität und wie die Lage zu Ihren Plänen passt.</p>', ru: '<p>Транспортная доступность, инфраструктура рядом, спрос на аренду, привлекательность при перепродаже и соответствие района вашим планам.</p>', ar: '<p>سهولة الوصول والخدمات القريبة والطلب على الإيجار وجاذبية إعادة البيع ومدى ملاءمة المنطقة لخططك.</p>', nl: '<p>Bereikbaarheid, nabijgelegen voorzieningen, huurvraag, aantrekkelijkheid bij doorverkoop en hoe de omgeving past bij uw plannen.</p>', pl: '<p>Dostęp, pobliskie usługi, popyt na wynajem, atrakcyjność przy odsprzedaży i to, jak okolica pasuje do Państwa planów.</p>', sv: '<p>Tillgänglighet, närliggande service, uthyrningsefterfrågan, attraktionskraft vid vidareförsäljning och hur området passar dina planer.</p>', no: '<p>Tilgang, nærliggende tjenester, utleieetterspørsel, attraktivitet ved videresalg og hvordan området passer til planene dine.</p>'  },

  // CTA band
  { find: '<h2 class="cta-title">Ask for the latest project list and documents.</h2>', es: '<h2 class="cta-title">Solicita la lista de proyectos y documentación actualizada.</h2>', fr: '<h2 class="cta-title">Demandez la liste des projets et les documents à jour.</h2>', de: '<h2 class="cta-title">Fordern Sie die aktuelle Projektliste und Unterlagen an.</h2>', ru: '<h2 class="cta-title">Запросите актуальный список проектов и документы.</h2>', ar: '<h2 class="cta-title">اطلب أحدث قائمة للمشاريع والمستندات.</h2>', nl: '<h2 class="cta-title">Vraag de meest recente projectlijst en documenten aan.</h2>', pl: '<h2 class="cta-title">Poproś o najnowszą listę projektów i dokumenty.</h2>', sv: '<h2 class="cta-title">Be om den senaste projektlistan och dokumenten.</h2>', no: '<h2 class="cta-title">Be om den nyeste prosjektlisten og dokumentene.</h2>'  },
  { find: '>Get Project Information</a>', es: '>Solicitar Información</a>', fr: '>Obtenir des Informations</a>', de: '>Projektinformationen Anfordern</a>', ru: '>Получить Информацию</a>', ar: '>الحصول على معلومات المشروع</a>', nl: '>Vraag Projectinformatie Aan</a>', pl: '>Poproś o informacje o projekcie</a>', sv: '>Få Projektinformation</a>', no: '>Få prosjektinformasjon</a>'  },

];

// Nav, mobile menu and footer chrome shared by every hand-authored static
// page (developments.html, compare.html, thank-you.html, 404.html) whose
// locale variants are produced by clone-and-replace rather than a
// locale-aware render function.
export const CHROME_ENTRIES = [
  // Nav / mobile menu
  { find: '>Buying Guides</a>', es: '>Guías de Compra</a>', fr: '>Guides d’Achat</a>', de: '>Kaufratgeber</a>', ru: '>Покупателям</a>', ar: '>أدلة الشراء</a>', nl: '>Koopgidsen</a>', pl: '>Przewodniki zakupowe</a>', sv: '>Köpguider</a>', no: '>Kjøpsguider</a>'  },
  { find: '>Why Nueva</a>', es: '>Por Qué Nueva</a>', fr: '>Pourquoi Nueva</a>', de: '>Warum Nueva</a>', ru: '>Почему Nueva</a>', ar: '>لماذا نويفا</a>', nl: '>Waarom Nueva</a>', pl: '>Dlaczego Nueva</a>', sv: '>Varför Nueva</a>', no: '>Hvorfor Nueva</a>'  },
  { find: '>Developments</a>', es: '>Promociones</a>', fr: '>Programmes</a>', de: '>Neubauprojekte</a>', ru: '>Новостройки</a>', ar: '>المشاريع</a>', nl: '>Nieuwbouwprojecten</a>', pl: '>Inwestycje</a>', sv: '>Bostadsprojekt</a>', no: '>Boligprosjekter</a>'  },
  { find: '>Areas</a>', es: '>Zonas</a>', fr: '>Secteurs</a>', de: '>Lagen</a>', ru: '>Районы</a>', ar: '>المناطق</a>', nl: '>Gebieden</a>', pl: '>Lokalizacje</a>', sv: '>Områden</a>', no: '>Områder</a>'  },
  { find: '>Advisory</a>', es: '>Asesoramiento</a>', fr: '>Conseil</a>', de: '>Beratung</a>', ru: '>Консультации</a>', ar: '>الاستشارات</a>', nl: '>Advies</a>', pl: '>Doradztwo</a>', sv: '>Rådgivning</a>', no: '>Rådgivning</a>'  },
  { find: '>Contact Us</a>', es: '>Contacto</a>', fr: '>Contact</a>', de: '>Kontakt</a>', ru: '>Контакты</a>', ar: '>اتصل بنا</a>', nl: '>Contact</a>', pl: '>Kontakt</a>', sv: '>Kontakta Oss</a>', no: '>Kontakt oss</a>'  },
  { find: 'aria-label="Nueva Living home"', es: 'aria-label="Inicio de Nueva Living"', fr: 'aria-label="Accueil Nueva Living"', de: 'aria-label="Nueva Living Startseite"', ru: 'aria-label="Главная Nueva Living"', ar: 'aria-label="الصفحة الرئيسية Nueva Living"', nl: 'aria-label="Nueva Living startpagina"', pl: 'aria-label="Strona główna Nueva Living"', sv: 'aria-label="Nueva Living startsida"', no: 'aria-label="Nueva Living hjemmeside"'  },
  { find: 'aria-label="Menu"', es: 'aria-label="Menú"', fr: 'aria-label="Menu"', de: 'aria-label="Menü"', ru: 'aria-label="Меню"', ar: 'aria-label="القائمة"', nl: 'aria-label="Menu"', pl: 'aria-label="Menu"', sv: 'aria-label="Meny"', no: 'aria-label="Meny"'  },

  // Footer
  { find: 'We help international buyers find and compare new-build and off-plan homes across the Costa del Sol.', es: 'Ayudamos a compradores internacionales a encontrar y comparar viviendas de obra nueva y sobre plano en toda la Costa del Sol.', fr: 'Nous aidons les acheteurs internationaux à trouver et comparer des logements neufs et sur plan sur toute la Costa del Sol.', de: 'Wir helfen internationalen Käufern, Neubau- und Off-Plan-Immobilien an der gesamten Costa del Sol zu finden und zu vergleichen.', ru: 'Мы помогаем международным покупателям находить и сравнивать новостройки и строящееся жильё по всему побережью Коста-дель-Соль.', ar: 'نساعد المشترين الدوليين في العثور على منازل جديدة وعلى المخطط ومقارنتها في جميع أنحاء كوستا ديل سول.', nl: 'Wij helpen internationale kopers bij het vinden en vergelijken van nieuwbouwwoningen en woningen op plan langs de hele Costa del Sol.', pl: 'Pomagamy zagranicznym nabywcom znaleźć i porównać nowe oraz sprzedawane z planu nieruchomości na całym wybrzeżu Costa del Sol.', sv: 'Vi hjälper internationella köpare att hitta och jämföra nyproducerade och projekterade bostäder längs hela Costa del Sol.', no: 'Vi hjelper internasjonale kjøpere med å finne og sammenligne nybygg og boliger under prosjektering langs hele Costa del Sol.'  },
  { find: '<div class="footer-col-title">Company</div>', es: '<div class="footer-col-title">Empresa</div>', fr: '<div class="footer-col-title">Société</div>', de: '<div class="footer-col-title">Unternehmen</div>', ru: '<div class="footer-col-title">Компания</div>', ar: '<div class="footer-col-title">الشركة</div>', nl: '<div class="footer-col-title">Bedrijf</div>', pl: '<div class="footer-col-title">Firma</div>', sv: '<div class="footer-col-title">Företag</div>', no: '<div class="footer-col-title">Selskap</div>'  },
  { find: '>Why Nueva Living</a>', es: '>Por Qué Nueva Living</a>', fr: '>Pourquoi Nueva Living</a>', de: '>Warum Nueva Living</a>', ru: '>Почему Nueva Living</a>', ar: '>لماذا Nueva Living</a>', nl: '>Waarom Nueva Living</a>', pl: '>Dlaczego Nueva Living</a>', sv: '>Varför Nueva Living</a>', no: '>Hvorfor Nueva Living</a>'  },
  { find: '>About</a>', es: '>Sobre Nosotros</a>', fr: '>À Propos</a>', de: '>Über Uns</a>', ru: '>О Нас</a>', ar: '>من نحن</a>', nl: '>Over Ons</a>', pl: '>O nas</a>', sv: '>Om Oss</a>', no: '>Om oss</a>'  },
  { find: '<div class="footer-col-title">Projects</div>', es: '<div class="footer-col-title">Proyectos</div>', fr: '<div class="footer-col-title">Projets</div>', de: '<div class="footer-col-title">Projekte</div>', ru: '<div class="footer-col-title">Проекты</div>', ar: '<div class="footer-col-title">المشاريع</div>', nl: '<div class="footer-col-title">Projecten</div>', pl: '<div class="footer-col-title">Projekty</div>', sv: '<div class="footer-col-title">Projekt</div>', no: '<div class="footer-col-title">Prosjekter</div>'  },
  { find: '>All Developments</a>', es: '>Todas las Promociones</a>', fr: '>Tous les Programmes</a>', de: '>Alle Neubauprojekte</a>', ru: '>Все Новостройки</a>', ar: '>جميع المشاريع</a>', nl: '>Alle Nieuwbouwprojecten</a>', pl: '>Wszystkie inwestycje</a>', sv: '>Alla Bostadsprojekt</a>', no: '>Alle boligprosjekter</a>'  },
  { find: '>Areas Overview</a>', es: '>Resumen de Zonas</a>', fr: '>Aperçu des Secteurs</a>', de: '>Überblick der Lagen</a>', ru: '>Обзор Районов</a>', ar: '>نظرة عامة على المناطق</a>', nl: '>Overzicht Gebieden</a>', pl: '>Przegląd lokalizacji</a>', sv: '>Områdesöversikt</a>', no: '>Områdeoversikt</a>'  },
  { find: '<div class="footer-col-title">Contact</div>', es: '<div class="footer-col-title">Contacto</div>', fr: '<div class="footer-col-title">Contact</div>', de: '<div class="footer-col-title">Kontakt</div>', ru: '<div class="footer-col-title">Контакты</div>', ar: '<div class="footer-col-title">التواصل</div>', nl: '<div class="footer-col-title">Contact</div>', pl: '<div class="footer-col-title">Kontakt</div>', sv: '<div class="footer-col-title">Kontakt</div>', no: '<div class="footer-col-title">Kontakt</div>'  },
  { find: '>Marbella, Spain</a>', es: '>Marbella, España</a>', fr: '>Marbella, Espagne</a>', de: '>Marbella, Spanien</a>', ru: '>Марбелья, Испания</a>', ar: '>ماربيا، إسبانيا</a>', nl: '>Marbella, Spanje</a>', pl: '>Marbella, Hiszpania</a>', sv: '>Marbella, Spanien</a>', no: '>Marbella, Spania</a>'  },
  { find: '<div class="footer-col-title" style="margin-top:24px;">Legal</div>', es: '<div class="footer-col-title" style="margin-top:24px;">Legal</div>', fr: '<div class="footer-col-title" style="margin-top:24px;">Mentions Légales</div>', de: '<div class="footer-col-title" style="margin-top:24px;">Rechtliches</div>', ru: '<div class="footer-col-title" style="margin-top:24px;">Правовая Информация</div>', ar: '<div class="footer-col-title" style="margin-top:24px;">الشؤون القانونية</div>', nl: '<div class="footer-col-title" style="margin-top:24px;">Juridisch</div>', pl: '<div class="footer-col-title" style="margin-top:24px;">Informacje prawne</div>', sv: '<div class="footer-col-title" style="margin-top:24px;">Juridiskt</div>', no: '<div class="footer-col-title" style="margin-top:24px;">Juridisk Informasjon</div>'  },
  { find: '>Privacy Policy</a>', es: '>Política de Privacidad</a>', fr: '>Politique de Confidentialité</a>', de: '>Datenschutzerklärung</a>', ru: '>Политика Конфиденциальности</a>', ar: '>سياسة الخصوصية</a>', nl: '>Privacybeleid</a>', pl: '>Polityka prywatności</a>', sv: '>Integritetspolicy</a>', no: '>Personvernerklæring</a>'  },
  { find: '>Legal Notice</a>', es: '>Aviso Legal</a>', fr: '>Mentions Légales</a>', de: '>Impressum</a>', ru: '>Юридическая Информация</a>', ar: '>إشعار قانوني</a>', nl: '>Juridische Mededeling</a>', pl: '>Nota prawna</a>', sv: '>Juridisk Information</a>', no: '>Juridisk merknad</a>'  },
  { find: '>Cookie Policy</a>', es: '>Política de Cookies</a>', fr: '>Politique de Cookies</a>', de: '>Cookie-Richtlinie</a>', ru: '>Политика Использования Cookie</a>', ar: '>سياسة ملفات تعريف الارتباط</a>', nl: '>Cookiebeleid</a>', pl: '>Polityka cookies</a>', sv: '>Cookiepolicy</a>', no: '>Retningslinjer for informasjonskapsler</a>'  },
  { find: 'Information presented on this website is for general marketing purposes only and does not constitute legal, financial or investment advice. Development details, prices and delivery dates are subject to change without notice.', es: 'La información presentada en este sitio web tiene únicamente fines comerciales generales y no constituye asesoramiento legal, financiero ni de inversión. Los detalles de las promociones, precios y fechas de entrega pueden cambiar sin previo aviso.', fr: 'Les informations présentées sur ce site le sont à des fins commerciales générales uniquement et ne constituent pas un conseil juridique, financier ou en investissement. Les détails des programmes, les prix et les dates de livraison peuvent être modifiés sans préavis.', de: 'Die auf dieser Website dargestellten Informationen dienen ausschließlich allgemeinen Marketingzwecken und stellen keine Rechts-, Finanz- oder Anlageberatung dar. Projektdetails, Preise und Übergabetermine können sich ohne Vorankündigung ändern.', ru: 'Информация, представленная на этом сайте, носит исключительно общий маркетинговый характер и не является юридической, финансовой или инвестиционной консультацией. Характеристики проектов, цены и сроки сдачи могут изменяться без предварительного уведомления.', ar: 'المعلومات المعروضة على هذا الموقع هي لأغراض تسويقية عامة فقط ولا تشكل استشارة قانونية أو مالية أو استثمارية. تفاصيل المشاريع والأسعار ومواعيد التسليم قابلة للتغيير دون إشعار مسبق.', nl: 'Informatie op deze website is uitsluitend bedoeld voor algemene marketingdoeleinden en vormt geen juridisch, financieel of beleggingsadvies. Projectdetails, prijzen en opleverdata kunnen zonder voorafgaande kennisgeving wijzigen.', pl: 'Informacje przedstawione na tej stronie służą wyłącznie ogólnym celom marketingowym i nie stanowią porady prawnej, finansowej ani inwestycyjnej. Szczegóły projektów, ceny i terminy odbioru mogą ulec zmianie bez uprzedzenia.', sv: 'Informationen på denna webbplats är endast avsedd för allmänna marknadsföringsändamål och utgör inte juridisk, finansiell eller investeringsrådgivning. Projektdetaljer, priser och leveransdatum kan ändras utan förvarning.', no: 'Informasjonen som presenteres på dette nettstedet er kun ment for generelle markedsføringsformål og utgjør ikke juridisk, finansiell eller investeringsrådgivning. Prosjektdetaljer, priser og leveringsdatoer kan endres uten forvarsel.'  },
  { find: 'aria-label="Contact Nueva Living on WhatsApp"', es: 'aria-label="Contactar con Nueva Living por WhatsApp"', fr: 'aria-label="Contacter Nueva Living sur WhatsApp"', de: 'aria-label="Nueva Living über WhatsApp kontaktieren"', ru: 'aria-label="Связаться с Nueva Living в WhatsApp"', ar: 'aria-label="التواصل مع Nueva Living عبر واتساب"', nl: 'aria-label="Contact opnemen met Nueva Living via WhatsApp"', pl: 'aria-label="Skontaktuj się z Nueva Living przez WhatsApp"', sv: 'aria-label="Kontakta Nueva Living via WhatsApp"', no: 'aria-label="Kontakt Nueva Living via WhatsApp"'  }
];

export const DEVELOPMENTS_PAGE_ENTRIES = [
  ...PAGE_ENTRIES_HEAD,
  ...PROJECT_CARD_ENTRIES,
  ...PAGE_ENTRIES_TAIL,
  ...CHROME_ENTRIES
];

// "Show image N of M" gallery-dot aria-labels, translated as templates
// (regex-applied by the build script since N/M vary per card).
export const SHOW_IMAGE_TEMPLATES = {
  es: 'Mostrar imagen {n} de {m}',
  fr: 'Afficher l’image {n} sur {m}',
  de: 'Bild {n} von {m} anzeigen',
  ru: 'Показать изображение {n} из {m}',
  ar: 'عرض الصورة {n} من {m}',
  nl: 'Afbeelding {n} van {m} weergeven',
  pl: 'Pokaż zdjęcie {n} z {m}',
  sv: 'Visa bild {n} av {m}',
  no: 'Vis bilde {n} av {m}'
};

// data-i18n-* runtime strings consumed by liora-discovery.js.
export const DISCOVERY_RUNTIME_STRINGS = {
  es: {
    countOne: '{count} promoción seleccionada',
    countMany: '{count} promociones seleccionadas',
    noFilters: 'Sin filtros de estilo de vida seleccionados',
    anyPrice: 'Cualquier precio',
    any: 'Cualquiera',
    searching: 'Buscando…',
    search: 'Buscar',
    aiMatching: 'Mostrando promociones que coinciden.',
    aiNoMatch: 'Ninguna promoción actual coincide con esa búsqueda.',
    aiError: 'La búsqueda con IA no está disponible ahora mismo. Prueba los filtros de abajo.'
  },
  fr: {
    countOne: '{count} programme sélectionné',
    countMany: '{count} programmes sélectionnés',
    noFilters: 'Aucun filtre de style de vie sélectionné',
    anyPrice: 'Tout prix',
    any: 'Toutes',
    searching: 'Recherche…',
    search: 'Rechercher',
    aiMatching: 'Affichage des programmes correspondants.',
    aiNoMatch: 'Aucun programme actuel ne correspond à cette recherche.',
    aiError: 'La recherche IA est indisponible pour le moment — essayez les filtres ci-dessous.'
  },
  de: {
    countOne: '{count} ausgewähltes Projekt',
    countMany: '{count} ausgewählte Projekte',
    noFilters: 'Keine Lifestyle-Filter ausgewählt',
    anyPrice: 'Jeder Preis',
    any: 'Beliebig',
    searching: 'Suche läuft…',
    search: 'Suchen',
    aiMatching: 'Passende Projekte werden angezeigt.',
    aiNoMatch: 'Kein aktuelles Projekt entspricht dieser Suche.',
    aiError: 'Die KI-Suche ist derzeit nicht verfügbar — nutzen Sie stattdessen die Filter unten.'
  },
  ru: {
    countOne: '{count} отобранный проект',
    countMany: 'Отобранных проектов: {count}',
    noFilters: 'Фильтры по образу жизни не выбраны',
    anyPrice: 'Любая цена',
    any: 'Любое число',
    searching: 'Идёт поиск…',
    search: 'Найти',
    aiMatching: 'Показаны подходящие новостройки.',
    aiNoMatch: 'Ни одна текущая новостройка не соответствует этому запросу.',
    aiError: 'ИИ-поиск сейчас недоступен — воспользуйтесь фильтрами ниже.'
  },
  ar: {
    countOne: 'مشروع مختار واحد',
    countMany: '{count} مشاريع مختارة',
    noFilters: 'لم يتم اختيار فلاتر نمط الحياة',
    anyPrice: 'أي سعر',
    any: 'أي عدد',
    searching: 'جارٍ البحث…',
    search: 'بحث',
    aiMatching: 'عرض المشاريع المطابقة.',
    aiNoMatch: 'لا يوجد مشروع حالي يطابق هذا البحث.',
    aiError: 'بحث الذكاء الاصطناعي غير متاح حاليًا — جرّب الفلاتر أدناه.'
  },
  nl: {
    countOne: '{count} geselecteerd project',
    countMany: '{count} geselecteerde projecten',
    noFilters: 'Geen levensstijlfilters geselecteerd',
    anyPrice: 'Elke prijs',
    any: 'Elk aantal',
    searching: 'Bezig met zoeken…',
    search: 'Zoeken',
    aiMatching: 'Overeenkomende projecten worden weergegeven.',
    aiNoMatch: 'Geen actueel project komt overeen met deze zoekopdracht.',
    aiError: 'AI-zoeken is momenteel niet beschikbaar — probeer de filters hieronder.'
  },
  pl: {
    countOne: '{count} wybrany projekt',
    countMany: '{count} wybranych projektów',
    noFilters: 'Nie wybrano filtrów stylu życia',
    anyPrice: 'Dowolna cena',
    any: 'Dowolna liczba',
    searching: 'Wyszukiwanie…',
    search: 'Szukaj',
    aiMatching: 'Wyświetlanie pasujących projektów.',
    aiNoMatch: 'Żaden aktualny projekt nie pasuje do tego wyszukiwania.',
    aiError: 'Wyszukiwanie AI jest obecnie niedostępne — skorzystaj z filtrów poniżej.'
  },
  sv: {
    countOne: '{count} valt projekt',
    countMany: '{count} valda projekt',
    noFilters: 'Inga livsstilsfilter valda',
    anyPrice: 'Alla priser',
    any: 'Alla',
    searching: 'Söker…',
    search: 'Sök',
    aiMatching: 'Visar matchande projekt.',
    aiNoMatch: 'Inget aktuellt projekt matchar den sökningen.',
    aiError: 'AI-sökningen är inte tillgänglig just nu — prova filtren nedan.'
  },
  no: {
    countOne: '{count} valgt prosjekt',
    countMany: '{count} valgte prosjekter',
    noFilters: 'Ingen livsstilsfiltre valgt',
    anyPrice: 'Alle priser',
    any: 'Alle',
    searching: 'Søker…',
    search: 'Søk',
    aiMatching: 'Viser samsvarende prosjekter.',
    aiNoMatch: 'Ingen nåværende prosjekter samsvarer med det søket.',
    aiError: 'AI-søk er ikke tilgjengelig akkurat nå — prøv filtrene nedenfor.'
  }
};
