// Editorial image alt text authored directly in the page-building scripts
// (homepage sections, area cards, guides/segment heroes, team photos,
// referrals). Unlike project media, these have no JSON overlay to hang a
// translation on, so they are literal alt="..." find/replace pairs.
//
// Shared by build_homepage_locales.mjs, build_footer_pages.mjs and
// build_segment_pages.mjs; each applies the ones its own pages contain.
export const EDITORIAL_ALT_ENTRIES = [
  // Area cards (homepage + areas.html)
  { find: 'alt="Marbella coastline at sunrise with La Concha mountain"', es: 'alt="Litoral de Marbella al amanecer con la montaña de La Concha"', fr: 'alt="Le littoral de Marbella au lever du soleil avec la montagne La Concha"', de: 'alt="Küste von Marbella bei Sonnenaufgang mit dem Berg La Concha"', ru: 'alt="Побережье Марбельи на рассвете с горой Ла-Конча"', ar: 'alt="ساحل ماربيا عند الشروق مع جبل لا كونتشا"' },
  { find: 'alt="Estepona old town street with white houses and flower pots"', es: 'alt="Calle del casco antiguo de Estepona con casas blancas y macetas de flores"', fr: 'alt="Rue de la vieille ville d’Estepona avec maisons blanches et pots de fleurs"', de: 'alt="Altstadtgasse von Estepona mit weißen Häusern und Blumentöpfen"', ru: 'alt="Улица старого города Эстепоны с белыми домами и цветочными горшками"', ar: 'alt="شارع في بلدة إستيبونا القديمة بمنازل بيضاء وأصص زهور"' },
  { find: 'alt="Benahavis mountain village and elevated hillside landscape"', es: 'alt="Pueblo de montaña de Benahavís y paisaje elevado de ladera"', fr: 'alt="Village de montagne de Benahavís et paysage de coteaux en hauteur"', de: 'alt="Bergdorf Benahavís und erhöhte Hanglandschaft"', ru: 'alt="Горная деревня Бенаавис и возвышенный ландшафт склонов"', ar: 'alt="قرية بيناهافيس الجبلية والمناظر الطبيعية المرتفعة"' },
  { find: 'alt="Puerto Banus marina and La Concha near Nueva Andalucia"', es: 'alt="Puerto deportivo de Puerto Banús y La Concha cerca de Nueva Andalucía"', fr: 'alt="La marina de Puerto Banús et La Concha près de Nueva Andalucía"', de: 'alt="Yachthafen Puerto Banús und La Concha nahe Nueva Andalucía"', ru: 'alt="Марина Пуэрто-Банус и Ла-Конча рядом с Нуэва-Андалусия"', ar: 'alt="مرسى بويرتو بانوس وجبل لا كونتشا قرب نويفا أندلوسيا"' },
  { find: 'alt="Fuengirola seafront sign with palms and Mediterranean water"', es: 'alt="Cartel del paseo marítimo de Fuengirola con palmeras y aguas del Mediterráneo"', fr: 'alt="Panneau du front de mer de Fuengirola avec palmiers et eaux méditerranéennes"', de: 'alt="Strandpromenaden-Schild von Fuengirola mit Palmen und Mittelmeerwasser"', ru: 'alt="Указатель на набережной Фуэнхиролы с пальмами и водами Средиземного моря"', ar: 'alt="لافتة كورنيش فوينخيرولا بأشجار النخيل ومياه البحر المتوسط"' },

  // Homepage editorial sections
  { find: 'alt="Luxury villa with infinity pool, Costa del Sol"', es: 'alt="Villa de lujo con piscina infinita, Costa del Sol"', fr: 'alt="Villa de luxe avec piscine à débordement, Costa del Sol"', de: 'alt="Luxusvilla mit Infinity-Pool, Costa del Sol"', ru: 'alt="Роскошная вилла с бассейном-инфинити, Коста-дель-Соль"', ar: 'alt="فيلا فاخرة بمسبح لامتناهٍ، كوستا ديل سول"' },
  { find: 'alt="New Costa del Sol residences with planted terraces, warm timber details and Mediterranean landscaping"', es: 'alt="Nuevas viviendas en la Costa del Sol con terrazas ajardinadas, detalles cálidos en madera y paisajismo mediterráneo"', fr: 'alt="Nouvelles résidences de la Costa del Sol avec terrasses végétalisées, détails chaleureux en bois et paysagisme méditerranéen"', de: 'alt="Neue Costa-del-Sol-Residenzen mit bepflanzten Terrassen, warmen Holzdetails und mediterraner Gartengestaltung"', ru: 'alt="Новые резиденции Коста-дель-Соль с озеленёнными террасами, тёплыми деревянными деталями и средиземноморским ландшафтом"', ar: 'alt="مساكن جديدة في كوستا ديل سول بتراسات مزروعة وتفاصيل خشبية دافئة وتنسيق حدائق متوسطي"' },
  { find: 'alt="Architectural plans and cost calculations being reviewed for a new development"', es: 'alt="Revisión de planos arquitectónicos y cálculos de costes de una nueva promoción"', fr: 'alt="Examen de plans d’architecte et de calculs de coûts pour un nouveau programme"', de: 'alt="Prüfung von Architekturplänen und Kostenberechnungen für ein neues Projekt"', ru: 'alt="Изучение архитектурных планов и расчёта стоимости нового проекта"', ar: 'alt="مراجعة المخططات المعمارية وحسابات التكلفة لمشروع جديد"' },
  { find: 'alt="Curated samples of timber, stone and engineered finishes selected for a new residence"', es: 'alt="Muestras seleccionadas de madera, piedra y acabados técnicos elegidas para una nueva vivienda"', fr: 'alt="Échantillons sélectionnés de bois, de pierre et de finitions techniques choisis pour une nouvelle résidence"', de: 'alt="Ausgewählte Muster aus Holz, Stein und technischen Oberflächen für eine neue Residenz"', ru: 'alt="Подобранные образцы дерева, камня и инженерных отделок для новой резиденции"', ar: 'alt="عينات مختارة من الخشب والحجر والتشطيبات الهندسية لمسكن جديد"' },
  { find: 'alt="Mediterranean sea-view terrace representing enduring lifestyle appeal"', es: 'alt="Terraza mediterránea con vistas al mar que refleja un atractivo duradero"', fr: 'alt="Terrasse méditerranéenne avec vue mer illustrant un attrait durable"', de: 'alt="Mediterrane Terrasse mit Meerblick als Ausdruck dauerhafter Wohnqualität"', ru: 'alt="Средиземноморская терраса с видом на море как символ непреходящей привлекательности"', ar: 'alt="تراس متوسطي بإطلالة بحرية يجسد جاذبية دائمة"' },
  { find: 'alt="Nueva Living advisor discussing a floorplan and preferred areas with prospective buyers"', es: 'alt="Asesor de Nueva Living comentando un plano y las zonas preferidas con posibles compradores"', fr: 'alt="Conseiller Nueva Living présentant un plan et les secteurs souhaités à de futurs acquéreurs"', de: 'alt="Nueva Living-Berater bespricht Grundriss und bevorzugte Lagen mit Kaufinteressenten"', ru: 'alt="Консультант Nueva Living обсуждает планировку и предпочитаемые районы с покупателями"', ar: 'alt="مستشار Nueva Living يناقش مخططًا والمناطق المفضلة مع مشترين محتملين"' },
  { find: 'alt="Architect reviewing plans and a scale model in a design studio"', es: 'alt="Arquitecto revisando planos y una maqueta en un estudio de diseño"', fr: 'alt="Architecte examinant des plans et une maquette dans un studio de design"', de: 'alt="Architekt prüft Pläne und ein Modell in einem Designstudio"', ru: 'alt="Архитектор изучает чертежи и макет в дизайн-студии"', ar: 'alt="مهندس معماري يراجع المخططات ونموذجًا مصغرًا في استوديو تصميم"' },
  { find: 'alt="Keys ready for handover inside a completed modern home"', es: 'alt="Llaves listas para la entrega en una vivienda moderna terminada"', fr: 'alt="Clés prêtes à être remises dans un logement moderne achevé"', de: 'alt="Schlüssel zur Übergabe in einem fertiggestellten modernen Zuhause"', ru: 'alt="Ключи, готовые к передаче, в завершённом современном доме"', ar: 'alt="مفاتيح جاهزة للتسليم داخل منزل عصري مكتمل"' },
  { find: 'alt="Buyer signing an agreement with professional guidance"', es: 'alt="Comprador firmando un acuerdo con asesoramiento profesional"', fr: 'alt="Acquéreur signant un contrat avec un accompagnement professionnel"', de: 'alt="Käufer unterzeichnet einen Vertrag mit professioneller Begleitung"', ru: 'alt="Покупатель подписывает договор при профессиональном сопровождении"', ar: 'alt="مشترٍ يوقّع اتفاقية بإرشاد مهني"' },

  // Guides / segment heroes
  { find: 'alt="Aerial dusk view of a new-build Costa del Sol residence and pool terrace"', es: 'alt="Vista aérea al atardecer de una vivienda de obra nueva en la Costa del Sol y su terraza con piscina"', fr: 'alt="Vue aérienne au crépuscule d’une résidence neuve de la Costa del Sol et de sa terrasse-piscine"', de: 'alt="Luftaufnahme einer Neubau-Residenz an der Costa del Sol mit Poolterrasse in der Dämmerung"', ru: 'alt="Вид с воздуха в сумерках на новую резиденцию Коста-дель-Соль с террасой у бассейна"', ar: 'alt="منظر جوي عند الغروب لمسكن جديد في كوستا ديل سول وتراس المسبح"' },
  { find: 'alt="Exterior view of a new-build apartment and penthouse development with a palm-lined pool terrace, Estepona"', es: 'alt="Vista exterior de una promoción de obra nueva de apartamentos y áticos con terraza de piscina bordeada de palmeras, Estepona"', fr: 'alt="Vue extérieure d’un programme neuf d’appartements et penthouses avec terrasse-piscine bordée de palmiers, Estepona"', de: 'alt="Außenansicht eines Neubauprojekts mit Wohnungen und Penthouses und palmengesäumter Poolterrasse, Estepona"', ru: 'alt="Внешний вид нового жилого комплекса с апартаментами и пентхаусами и террасой у бассейна в окружении пальм, Эстепона"', ar: 'alt="منظر خارجي لمشروع جديد من الشقق والبنتهاوس مع تراس مسبح تحيط به النخيل، إستيبونا"' },
  { find: 'alt="Aerial view of a new-build apartment and penthouse development framed by the Guadalmina golf course and the Mediterranean, Marbella"', es: 'alt="Vista aérea de una promoción de obra nueva de apartamentos y áticos enmarcada por el campo de golf de Guadalmina y el Mediterráneo, Marbella"', fr: 'alt="Vue aérienne d’un programme neuf d’appartements et penthouses encadré par le golf de Guadalmina et la Méditerranée, Marbella"', de: 'alt="Luftaufnahme eines Neubauprojekts mit Wohnungen und Penthouses, eingerahmt vom Golfplatz Guadalmina und dem Mittelmeer, Marbella"', ru: 'alt="Вид с воздуха на новый комплекс апартаментов и пентхаусов в обрамлении гольф-поля Guadalmina и Средиземного моря, Марбелья"', ar: 'alt="منظر جوي لمشروع جديد من الشقق والبنتهاوس يحيط به ملعب غولف Guadalmina والبحر المتوسط، ماربيا"' },

  // Team + referrals
  { find: 'alt="Sasan Raftari, founder of Nueva Living"', es: 'alt="Sasan Raftari, fundador de Nueva Living"', fr: 'alt="Sasan Raftari, fondateur de Nueva Living"', de: 'alt="Sasan Raftari, Gründer von Nueva Living"', ru: 'alt="Сасан Рафтари, основатель Nueva Living"', ar: 'alt="ساسان رفتاري، مؤسس Nueva Living"' },
  { find: 'alt="Sami Altun, co-founder of Nueva Living"', es: 'alt="Sami Altun, cofundador de Nueva Living"', fr: 'alt="Sami Altun, cofondateur de Nueva Living"', de: 'alt="Sami Altun, Mitgründer von Nueva Living"', ru: 'alt="Сами Алтун, соучредитель Nueva Living"', ar: 'alt="سامي ألتون، الشريك المؤسس لـ Nueva Living"' },
  { find: 'alt="Rooftop terrace lounge and dining area overlooking the Costa del Sol coastline"', es: 'alt="Salón y comedor en terraza de azotea con vistas al litoral de la Costa del Sol"', fr: 'alt="Salon et espace repas sur terrasse en toiture surplombant le littoral de la Costa del Sol"', de: 'alt="Dachterrassen-Lounge und Essbereich mit Blick auf die Küste der Costa del Sol"', ru: 'alt="Лаундж и обеденная зона на террасе крыши с видом на побережье Коста-дель-Соль"', ar: 'alt="صالة وتراس طعام على السطح يطلان على ساحل كوستا ديل سول"' },
  { find: 'alt="Night view of a Costa del Sol residence and palm-lined pool terrace"', es: 'alt="Vista nocturna de una vivienda en la Costa del Sol y su terraza de piscina bordeada de palmeras"', fr: 'alt="Vue nocturne d’une résidence de la Costa del Sol et de sa terrasse-piscine bordée de palmiers"', de: 'alt="Nachtansicht einer Costa-del-Sol-Residenz mit palmengesäumter Poolterrasse"', ru: 'alt="Ночной вид на резиденцию Коста-дель-Соль и террасу у бассейна в окружении пальм"', ar: 'alt="منظر ليلي لمسكن في كوستا ديل سول وتراس مسبح تحيط به النخيل"' }
];
