// Editorial image alt text authored directly in the page-building scripts
// (homepage sections, area cards, guides/segment heroes, team photos,
// referrals). Unlike project media, these have no JSON overlay to hang a
// translation on, so they are literal alt="..." find/replace pairs.
//
// Shared by build_homepage_locales.mjs, build_footer_pages.mjs and
// build_segment_pages.mjs; each applies the ones its own pages contain.
export const EDITORIAL_ALT_ENTRIES = [
  // Area cards (homepage + areas.html)
  { find: 'alt="Marbella coastline at sunrise with La Concha mountain"', es: 'alt="Litoral de Marbella al amanecer con la montaña de La Concha"', fr: 'alt="Le littoral de Marbella au lever du soleil avec la montagne La Concha"', de: 'alt="Küste von Marbella bei Sonnenaufgang mit dem Berg La Concha"', ru: 'alt="Побережье Марбельи на рассвете с горой Ла-Конча"', ar: 'alt="ساحل ماربيا عند الشروق مع جبل لا كونتشا"', nl: 'alt="Kustlijn van Marbella bij zonsopgang met de berg La Concha"', pl: 'alt="Wybrzeże Marbelli o wschodzie słońca z górą La Concha"', sv: 'alt="Marbellas kustlinje vid soluppgång med berget La Concha"', no: 'alt="Marbellas kystlinje ved soloppgang med fjellet La Concha"' },
  { find: 'alt="Estepona old town street with white houses and flower pots"', es: 'alt="Calle del casco antiguo de Estepona con casas blancas y macetas de flores"', fr: 'alt="Rue de la vieille ville d’Estepona avec maisons blanches et pots de fleurs"', de: 'alt="Altstadtgasse von Estepona mit weißen Häusern und Blumentöpfen"', ru: 'alt="Улица старого города Эстепоны с белыми домами и цветочными горшками"', ar: 'alt="شارع في بلدة إستيبونا القديمة بمنازل بيضاء وأصص زهور"', nl: 'alt="Straat in de oude binnenstad van Estepona met witte huizen en bloempotten"', pl: 'alt="Ulica starówki Estepony z białymi domami i donicami z kwiatami"', sv: 'alt="Gata i Esteponas gamla stad med vita hus och blomkrukor"', no: 'alt="Gate i Esteponas gamleby med hvite hus og blomsterpotter"' },
  { find: 'alt="Benahavis mountain village and elevated hillside landscape"', es: 'alt="Pueblo de montaña de Benahavís y paisaje elevado de ladera"', fr: 'alt="Village de montagne de Benahavís et paysage de coteaux en hauteur"', de: 'alt="Bergdorf Benahavís und erhöhte Hanglandschaft"', ru: 'alt="Горная деревня Бенаавис и возвышенный ландшафт склонов"', ar: 'alt="قرية بيناهافيس الجبلية والمناظر الطبيعية المرتفعة"', nl: 'alt="Bergdorp Benahavís en verhoogd heuvellandschap"', pl: 'alt="Górska wioska Benahavís i krajobraz wzgórz"', sv: 'alt="Bergbyn Benahavís och kuperat höjdlandskap"', no: 'alt="Fjelllandsbyen Benahavís og forhøyet ås-landskap"' },
  { find: 'alt="Puerto Banús marina and La Concha near Nueva Andalucia"', es: 'alt="Puerto deportivo de Puerto Banús y La Concha cerca de Nueva Andalucía"', fr: 'alt="La marina de Puerto Banús et La Concha près de Nueva Andalucía"', de: 'alt="Yachthafen Puerto Banús und La Concha nahe Nueva Andalucía"', ru: 'alt="Марина Пуэрто-Банус и Ла-Конча рядом с Нуэва-Андалусия"', ar: 'alt="مرسى بويرتو بانوس وجبل لا كونتشا قرب نويفا أندلوسيا"', nl: 'alt="Jachthaven Puerto Banús en La Concha bij Nueva Andalucía"', pl: 'alt="Marina Puerto Banús i La Concha w pobliżu Nueva Andalucía"', sv: 'alt="Marinan Puerto Banús och La Concha nära Nueva Andalucía"', no: 'alt="Marinaen Puerto Banús og La Concha nær Nueva Andalucía"' },
  { find: 'alt="Fuengirola seafront sign with palms and Mediterranean water"', es: 'alt="Cartel del paseo marítimo de Fuengirola con palmeras y aguas del Mediterráneo"', fr: 'alt="Panneau du front de mer de Fuengirola avec palmiers et eaux méditerranéennes"', de: 'alt="Strandpromenaden-Schild von Fuengirola mit Palmen und Mittelmeerwasser"', ru: 'alt="Указатель на набережной Фуэнхиролы с пальмами и водами Средиземного моря"', ar: 'alt="لافتة كورنيش فوينخيرولا بأشجار النخيل ومياه البحر المتوسط"', nl: 'alt="Bord aan de boulevard van Fuengirola met palmbomen en Middellandse Zee"', pl: 'alt="Znak na promenadzie w Fuengiroli z palmami i wodami Morza Śródziemnego"', sv: 'alt="Skylt vid Fuengirolas strandpromenad med palmer och Medelhavsvatten"', no: 'alt="Skilt ved Fuengirolas strandpromenade med palmer og Middelhavet"' },

  // Homepage editorial sections
  // Hero poster. The old one was a villa render; it is now a frame from the
  // background video, so the description follows the picture rather than the
  // brand. One alt covers both the desktop and mobile frame, and neither
  // location is confirmed, so it says what is in shot and nothing more.
  { find: 'alt="Aerial view of a beach lined with palms, with apartment buildings behind"', es: 'alt="Vista aérea de una playa bordeada de palmeras, con edificios de apartamentos al fondo"', fr: 'alt="Vue aérienne d’une plage bordée de palmiers, avec des immeubles en arrière-plan"', de: 'alt="Luftaufnahme eines von Palmen gesäumten Strandes, dahinter Wohngebäude"', ru: 'alt="Вид с воздуха на пляж с пальмами и жилыми домами позади"', ar: 'alt="منظر جوي لشاطئ تحفّه النخيل مع مبانٍ سكنية في الخلفية"', nl: 'alt="Luchtfoto van een strand omzoomd door palmen, met appartementengebouwen erachter"', pl: 'alt="Widok z lotu ptaka na plażę obsadzoną palmami, z budynkami mieszkalnymi w tle"', sv: 'alt="Flygbild över en strand kantad av palmer, med flerbostadshus bakom"', no: 'alt="Flyfoto av en strand kantet av palmer, med boligblokker bak"' },
  { find: 'alt="New Costa del Sol residences with planted terraces, warm timber details and Mediterranean landscaping"', es: 'alt="Nuevas viviendas en la Costa del Sol con terrazas ajardinadas, detalles cálidos en madera y paisajismo mediterráneo"', fr: 'alt="Nouvelles résidences de la Costa del Sol avec terrasses végétalisées, détails chaleureux en bois et paysagisme méditerranéen"', de: 'alt="Neue Costa-del-Sol-Residenzen mit bepflanzten Terrassen, warmen Holzdetails und mediterraner Gartengestaltung"', ru: 'alt="Новые резиденции Коста-дель-Соль с озеленёнными террасами, тёплыми деревянными деталями и средиземноморским ландшафтом"', ar: 'alt="مساكن جديدة في كوستا ديل سول بتراسات مزروعة وتفاصيل خشبية دافئة وتنسيق حدائق متوسطي"', nl: 'alt="Nieuwe woningen aan de Costa del Sol met beplante terrassen, warme houten details en mediterrane aanleg"', pl: 'alt="Nowe nieruchomości na Costa del Sol z zazielenionymi tarasami, ciepłymi drewnianymi detalami i śródziemnomorską zielenią"', sv: 'alt="Nya bostäder på Costa del Sol med planterade terrasser, varma trädetaljer och medelhavsinspirerad landskapsdesign"', no: 'alt="Nye boliger på Costa del Sol med beplantede terrasser, varme tredetaljer og middelhavspreget landskap"' },
  { find: 'alt="Architectural plans and cost calculations being reviewed for a new development"', es: 'alt="Revisión de planos arquitectónicos y cálculos de costes de una nueva promoción"', fr: 'alt="Examen de plans d’architecte et de calculs de coûts pour un nouveau programme"', de: 'alt="Prüfung von Architekturplänen und Kostenberechnungen für ein neues Projekt"', ru: 'alt="Изучение архитектурных планов и расчёта стоимости нового проекта"', ar: 'alt="مراجعة المخططات المعمارية وحسابات التكلفة لمشروع جديد"', nl: 'alt="Architectonische plannen en kostenberekeningen worden beoordeeld voor een nieuw project"', pl: 'alt="Przegląd planów architektonicznych i kalkulacji kosztów nowej inwestycji"', sv: 'alt="Arkitektritningar och kostnadsberäkningar granskas för ett nytt projekt"', no: 'alt="Arkitekttegninger og kostnadsberegninger gjennomgås for et nytt prosjekt"' },
  { find: 'alt="Curated samples of timber, stone and engineered finishes selected for a new residence"', es: 'alt="Muestras seleccionadas de madera, piedra y acabados técnicos elegidas para una nueva vivienda"', fr: 'alt="Échantillons sélectionnés de bois, de pierre et de finitions techniques choisis pour une nouvelle résidence"', de: 'alt="Ausgewählte Muster aus Holz, Stein und technischen Oberflächen für eine neue Residenz"', ru: 'alt="Подобранные образцы дерева, камня и инженерных отделок для новой резиденции"', ar: 'alt="عينات مختارة من الخشب والحجر والتشطيبات الهندسية لمسكن جديد"', nl: 'alt="Zorgvuldig samengestelde stalen van hout, steen en technische afwerkingen voor een nieuwe woning"', pl: 'alt="Starannie dobrane próbki drewna, kamienia i wykończeń technicznych wybrane dla nowej rezydencji"', sv: 'alt="Utvalda prover av trä, sten och tekniska ytskikt för en ny bostad"', no: 'alt="Utvalgte prøver av tre, stein og tekniske overflater for en ny bolig"' },
  { find: 'alt="Mediterranean sea-view terrace representing enduring lifestyle appeal"', es: 'alt="Terraza mediterránea con vistas al mar que refleja un atractivo duradero"', fr: 'alt="Terrasse méditerranéenne avec vue mer illustrant un attrait durable"', de: 'alt="Mediterrane Terrasse mit Meerblick als Ausdruck dauerhafter Wohnqualität"', ru: 'alt="Средиземноморская терраса с видом на море как символ непреходящей привлекательности"', ar: 'alt="تراس متوسطي بإطلالة بحرية يجسد جاذبية دائمة"', nl: 'alt="Mediterraans terras met zeezicht als symbool van blijvende levensstijl"', pl: 'alt="Śródziemnomorski taras z widokiem na morze symbolizujący trwały urok stylu życia"', sv: 'alt="Medelhavsterrass med havsutsikt som symboliserar bestående livsstilscharm"', no: 'alt="Middelhavsterrasse med sjøutsikt som representerer varig livsstilsappell"' },
  { find: 'alt="Nueva Living advisor discussing a floorplan and preferred areas with prospective buyers"', es: 'alt="Asesor de Nueva Living comentando un plano y las zonas preferidas con posibles compradores"', fr: 'alt="Conseiller Nueva Living présentant un plan et les secteurs souhaités à de futurs acquéreurs"', de: 'alt="Nueva Living-Berater bespricht Grundriss und bevorzugte Lagen mit Kaufinteressenten"', ru: 'alt="Консультант Nueva Living обсуждает планировку и предпочитаемые районы с покупателями"', ar: 'alt="مستشار Nueva Living يناقش مخططًا والمناطق المفضلة مع مشترين محتملين"', nl: 'alt="Nueva Living-adviseur bespreekt een plattegrond en voorkeursregio\'s met potentiële kopers"', pl: 'alt="Doradca Nueva Living omawia rzut mieszkania i preferowane okolice z potencjalnymi nabywcami"', sv: 'alt="Nueva Living-rådgivare diskuterar en planritning och önskade områden med potentiella köpare"', no: 'alt="Nueva Living-rådgiver diskuterer en plantegning og foretrukne områder med potensielle kjøpere"' },
  { find: 'alt="Architect reviewing plans and a scale model in a design studio"', es: 'alt="Arquitecto revisando planos y una maqueta en un estudio de diseño"', fr: 'alt="Architecte examinant des plans et une maquette dans un studio de design"', de: 'alt="Architekt prüft Pläne und ein Modell in einem Designstudio"', ru: 'alt="Архитектор изучает чертежи и макет в дизайн-студии"', ar: 'alt="مهندس معماري يراجع المخططات ونموذجًا مصغرًا في استوديو تصميم"', nl: 'alt="Architect bekijkt plannen en een schaalmodel in een ontwerpstudio"', pl: 'alt="Architekt przegląda plany i makietę w studiu projektowym"', sv: 'alt="Arkitekt granskar ritningar och en skalmodell i en designstudio"', no: 'alt="Arkitekt gjennomgår tegninger og en skala-modell i et designstudio"' },
  { find: 'alt="Keys ready for handover inside a completed modern home"', es: 'alt="Llaves listas para la entrega en una vivienda moderna terminada"', fr: 'alt="Clés prêtes à être remises dans un logement moderne achevé"', de: 'alt="Schlüssel zur Übergabe in einem fertiggestellten modernen Zuhause"', ru: 'alt="Ключи, готовые к передаче, в завершённом современном доме"', ar: 'alt="مفاتيح جاهزة للتسليم داخل منزل عصري مكتمل"', nl: 'alt="Sleutels klaar voor overdracht in een voltooide moderne woning"', pl: 'alt="Klucze gotowe do przekazania w ukończonym nowoczesnym domu"', sv: 'alt="Nycklar redo för överlämning i ett färdigställt modernt hem"', no: 'alt="Nøkler klare for overlevering i et ferdigstilt moderne hjem"' },
  { find: 'alt="Buyer signing an agreement with professional guidance"', es: 'alt="Comprador firmando un acuerdo con asesoramiento profesional"', fr: 'alt="Acquéreur signant un contrat avec un accompagnement professionnel"', de: 'alt="Käufer unterzeichnet einen Vertrag mit professioneller Begleitung"', ru: 'alt="Покупатель подписывает договор при профессиональном сопровождении"', ar: 'alt="مشترٍ يوقّع اتفاقية بإرشاد مهني"', nl: 'alt="Koper ondertekent een overeenkomst met professionele begeleiding"', pl: 'alt="Nabywca podpisujący umowę z profesjonalnym wsparciem"', sv: 'alt="Köpare undertecknar ett avtal med professionell vägledning"', no: 'alt="Kjøper signerer en avtale med profesjonell veiledning"' },

  // Guides / segment heroes
  { find: 'alt="Aerial dusk view of a new-build Costa del Sol residence and pool terrace"', es: 'alt="Vista aérea al atardecer de una vivienda de obra nueva en la Costa del Sol y su terraza con piscina"', fr: 'alt="Vue aérienne au crépuscule d’une résidence neuve de la Costa del Sol et de sa terrasse-piscine"', de: 'alt="Luftaufnahme einer Neubau-Residenz an der Costa del Sol mit Poolterrasse in der Dämmerung"', ru: 'alt="Вид с воздуха в сумерках на новую резиденцию Коста-дель-Соль с террасой у бассейна"', ar: 'alt="منظر جوي عند الغروب لمسكن جديد في كوستا ديل سول وتراس المسبح"', nl: 'alt="Luchtfoto in de schemering van een nieuwbouwwoning aan de Costa del Sol met zwembadterras"', pl: 'alt="Widok z lotu ptaka o zmierzchu na nową nieruchomość na Costa del Sol z tarasem przy basenie"', sv: 'alt="Flygvy i skymningen av en nyproducerad bostad på Costa del Sol med poolterrass"', no: 'alt="Luftfoto i skumringen av en nybygd bolig på Costa del Sol med bassengterrasse"' },
  { find: 'alt="Exterior view of a new-build apartment and penthouse development with a palm-lined pool terrace, Estepona"', es: 'alt="Vista exterior de una promoción de obra nueva de apartamentos y áticos con terraza de piscina bordeada de palmeras, Estepona"', fr: 'alt="Vue extérieure d’un programme neuf d’appartements et penthouses avec terrasse-piscine bordée de palmiers, Estepona"', de: 'alt="Außenansicht eines Neubauprojekts mit Wohnungen und Penthäusern und palmengesäumter Poolterrasse, Estepona"', ru: 'alt="Внешний вид нового жилого комплекса с апартаментами и пентхаусами и террасой у бассейна в окружении пальм, Эстепона"', ar: 'alt="منظر خارجي لمشروع جديد من الشقق والبنتهاوس مع تراس مسبح تحيط به النخيل، إستيبونا"', nl: 'alt="Buitenaanzicht van een nieuwbouwproject met appartementen en penthouses met een door palmbomen omzoomd zwembadterras, Estepona"', pl: 'alt="Widok zewnętrzny nowej inwestycji apartamentów i penthouse\'ów z tarasem przy basenie otoczonym palmami, Estepona"', sv: 'alt="Exteriörvy av ett nyproducerat lägenhets- och takvåningsprojekt med palmkantad poolterrass, Estepona"', no: 'alt="Eksteriørvisning av et nybygd leilighets- og toppleilighetsprosjekt med palmekledd bassengterrasse, Estepona"' },
  { find: 'alt="Aerial view of a new-build apartment and penthouse development framed by the Guadalmina golf course and the Mediterranean, Marbella"', es: 'alt="Vista aérea de una promoción de obra nueva de apartamentos y áticos enmarcada por el campo de golf de Guadalmina y el Mediterráneo, Marbella"', fr: 'alt="Vue aérienne d’un programme neuf d’appartements et penthouses encadré par le golf de Guadalmina et la Méditerranée, Marbella"', de: 'alt="Luftaufnahme eines Neubauprojekts mit Wohnungen und Penthäusern, eingerahmt vom Golfplatz Guadalmina und dem Mittelmeer, Marbella"', ru: 'alt="Вид с воздуха на новый комплекс апартаментов и пентхаусов в обрамлении гольф-поля Guadalmina и Средиземного моря, Марбелья"', ar: 'alt="منظر جوي لمشروع جديد من الشقق والبنتهاوس يحيط به ملعب غولف Guadalmina والبحر المتوسط، ماربيا"', nl: 'alt="Luchtfoto van een nieuwbouwproject met appartementen en penthouses omgeven door de golfbaan Guadalmina en de Middellandse Zee, Marbella"', pl: 'alt="Widok z lotu ptaka na nową inwestycję apartamentów i penthouse\'ów otoczoną polem golfowym Guadalmina i Morzem Śródziemnym, Marbella"', sv: 'alt="Flygvy av ett nyproducerat lägenhets- och takvåningsprojekt omgivet av golfbanan Guadalmina och Medelhavet, Marbella"', no: 'alt="Luftfoto av et nybygd leilighets- og toppleilighetsprosjekt omkranset av golfbanen Guadalmina og Middelhavet, Marbella"' },

  // Team + referrals
  { find: 'alt="Sasan Raftari, founder of Nueva Living"', es: 'alt="Sasan Raftari, fundador de Nueva Living"', fr: 'alt="Sasan Raftari, fondateur de Nueva Living"', de: 'alt="Sasan Raftari, Gründer von Nueva Living"', ru: 'alt="Сасан Рафтари, основатель Nueva Living"', ar: 'alt="ساسان رفتاري، مؤسس Nueva Living"', nl: 'alt="Sasan Raftari, oprichter van Nueva Living"', pl: 'alt="Sasan Raftari, założyciel Nueva Living"', sv: 'alt="Sasan Raftari, grundare av Nueva Living"', no: 'alt="Sasan Raftari, grunnlegger av Nueva Living"' },
  { find: 'alt="Sami Altun, co-founder of Nueva Living"', es: 'alt="Sami Altun, cofundador de Nueva Living"', fr: 'alt="Sami Altun, cofondateur de Nueva Living"', de: 'alt="Sami Altun, Mitgründer von Nueva Living"', ru: 'alt="Сами Алтун, соучредитель Nueva Living"', ar: 'alt="سامي ألتون، الشريك المؤسس لـ Nueva Living"', nl: 'alt="Sami Altun, medeoprichter van Nueva Living"', pl: 'alt="Sami Altun, współzałożyciel Nueva Living"', sv: 'alt="Sami Altun, medgrundare av Nueva Living"', no: 'alt="Sami Altun, medgrunnlegger av Nueva Living"' },
  { find: 'alt="Rooftop terrace lounge and dining area overlooking the Costa del Sol coastline"', es: 'alt="Salón y comedor en terraza de azotea con vistas al litoral de la Costa del Sol"', fr: 'alt="Salon et espace repas sur terrasse en toiture surplombant le littoral de la Costa del Sol"', de: 'alt="Dachterrassen-Lounge und Essbereich mit Blick auf die Küste der Costa del Sol"', ru: 'alt="Лаундж и обеденная зона на террасе крыши с видом на побережье Коста-дель-Соль"', ar: 'alt="صالة وتراس طعام على السطح يطلان على ساحل كوستا ديل سول"', nl: 'alt="Loungeterras op het dak en eetgedeelte met uitzicht op de kustlijn van de Costa del Sol"', pl: 'alt="Taras na dachu z częścią wypoczynkową i jadalną z widokiem na wybrzeże Costa del Sol"', sv: 'alt="Takterrasslounge och matplats med utsikt över Costa del Sols kustlinje"', no: 'alt="Takterrasse-lounge og spiseplass med utsikt over Costa del Sols kystlinje"' },
  { find: 'alt="Night view of a Costa del Sol residence and palm-lined pool terrace"', es: 'alt="Vista nocturna de una vivienda en la Costa del Sol y su terraza de piscina bordeada de palmeras"', fr: 'alt="Vue nocturne d’une résidence de la Costa del Sol et de sa terrasse-piscine bordée de palmiers"', de: 'alt="Nachtansicht einer Costa-del-Sol-Residenz mit palmengesäumter Poolterrasse"', ru: 'alt="Ночной вид на резиденцию Коста-дель-Соль и террасу у бассейна в окружении пальм"', ar: 'alt="منظر ليلي لمسكن في كوستا ديل سول وتراس مسبح تحيط به النخيل"', nl: 'alt="Nachtaanzicht van een woning aan de Costa del Sol met een door palmbomen omzoomd zwembadterras"', pl: 'alt="Nocny widok na nieruchomość na Costa del Sol z tarasem przy basenie otoczonym palmami"', sv: 'alt="Nattvy av en bostad på Costa del Sol med palmkantad poolterrass"', no: 'alt="Nattbilde av en bolig på Costa del Sol med palmekledd bassengterrasse"' },
  // Guide hub cards. Three of these were unreachable in any language but
  // English until the stale englishOnly flag came off the hub, so their alt
  // text had never needed translating.
  { find: 'alt="Buyer reviewing purchase contract documents with legal guidance"', es: 'alt="Comprador revisando la documentación del contrato de compra con asesoramiento jurídico"', fr: 'alt="Acheteur examinant les documents du contrat d’achat avec un conseil juridique"', de: 'alt="Käufer prüft die Unterlagen des Kaufvertrags mit rechtlicher Beratung"', ru: 'alt="Покупатель изучает документы договора купли-продажи с юридическим сопровождением"', ar: 'alt="مشترٍ يراجع مستندات عقد الشراء بمشورة قانونية"', nl: 'alt="Koper bekijkt de documenten van het koopcontract met juridisch advies"', pl: 'alt="Kupujący przegląda dokumenty umowy zakupu z pomocą prawną"', sv: 'alt="Köpare går igenom köpekontraktets handlingar med juridisk rådgivning"', no: 'alt="Kjøper gjennomgår dokumentene i kjøpekontrakten med juridisk bistand"' },
  { find: 'alt="Reviewing a development payment schedule and floorplans"', es: 'alt="Revisión del calendario de pagos de una promoción y de los planos"', fr: 'alt="Examen de l’échéancier de paiement d’un programme et des plans"', de: 'alt="Prüfung des Zahlungsplans eines Projekts und der Grundrisse"', ru: 'alt="Изучение графика платежей проекта и планировок"', ar: 'alt="مراجعة جدول دفعات المشروع والمخططات"', nl: 'alt="Beoordeling van het betaalschema van een project en de plattegronden"', pl: 'alt="Analiza harmonogramu płatności inwestycji i rzutów"', sv: 'alt="Genomgång av ett projekts betalningsplan och planritningar"', no: 'alt="Gjennomgang av et prosjekts betalingsplan og plantegninger"' },
  { find: 'alt="Handover inspection of a completed new-build residence"', es: 'alt="Inspección de entrega de una vivienda de obra nueva terminada"', fr: 'alt="Visite de livraison d’un logement neuf achevé"', de: 'alt="Übergabeinspektion einer fertiggestellten Neubauwohnung"', ru: 'alt="Приёмочный осмотр готового жилья в новостройке"', ar: 'alt="معاينة تسلّم وحدة سكنية جديدة مكتملة"', nl: 'alt="Opleveringsinspectie van een afgeronde nieuwbouwwoning"', pl: 'alt="Odbiór techniczny gotowego lokalu w nowej inwestycji"', sv: 'alt="Slutbesiktning av en färdigställd nyproducerad bostad"', no: 'alt="Overtakelsesbefaring av en ferdigstilt nybygd bolig"' },
  { find: 'alt="Buyer reviewing project documents remotely"', es: 'alt="Comprador revisando la documentación del proyecto a distancia"', fr: 'alt="Acheteur examinant à distance les documents du programme"', de: 'alt="Käufer prüft die Projektunterlagen aus der Ferne"', ru: 'alt="Покупатель изучает документы проекта удалённо"', ar: 'alt="مشترٍ يراجع مستندات المشروع عن بُعد"', nl: 'alt="Koper bekijkt de projectdocumenten op afstand"', pl: 'alt="Kupujący zdalnie przegląda dokumentację inwestycji"', sv: 'alt="Köpare går igenom projektets handlingar på distans"', no: 'alt="Kjøper gjennomgår prosjektdokumentene på avstand"' },
];
