// Group D: translated body prose for about.html, contact.html,
// privacy-policy.html, legal-notice.html and cookie-policy.html.
// See the comment above applyFooterPageTranslations() in
// build_footer_pages.mjs for how this is applied: literal find/replace
// over the already-rendered English HTML for a single page at a time.
//
// Ordering note: entries are deliberately ordered longest/most-specific
// first within each page group, and the few short, reused strings
// ("About", "Legal", "Contact Us") are placed at the very end of the
// file -- those short strings are substrings of several longer strings
// above them (e.g. "Legal" is contained in "Legal Notice" and "No Legal
// Or Financial Advice"), and since replacement runs in array order over
// an accumulating result, the longer/specific matches must be consumed
// first or the short generic entry would corrupt them mid-string. The
// two founder-role short labels ("Founder" / "Co-Founder") are matched
// together with their wrapping tags instead, since the bare words also
// appear inside a `data-context` attribute that must not be translated.
export const FOOTER_PAGE_ENTRIES_GROUP_D = [
  { find: "We focus on <em>new developments</em>", es: "Nos centramos en <em>la obra nueva</em>", fr: "Nous nous concentrons sur <em>le neuf</em>", de: "Wir konzentrieren uns auf <em>Neubauprojekte</em>", ru: "Мы специализируемся на <em>новостройках</em>", ar: "نركز على <em>المشاريع الجديدة</em>" },
  // ===== about.html =====
  { find: "About Nueva Living, a Costa del Sol new development advisory firm.", es: "Sobre Nueva Living, una firma de asesoría en obra nueva en la Costa del Sol.", fr: "À propos de Nueva Living, cabinet de conseil en programmes neufs sur la Costa del Sol.", de: "Über Nueva Living, eine Beratungsgesellschaft für Neubauprojekte an der Costa del Sol.", ru: "О компании Nueva Living — консультационном агентстве по новостройкам Коста-дель-Соль.", ar: "عن نويفا ليفينغ، شركة استشارات متخصصة في المشاريع العقارية الجديدة على ساحل كوستا ديل سول." },
  { find: "About Nueva Living", es: "Sobre Nueva Living", fr: "À propos de Nueva Living", de: "Über Nueva Living", ru: "О компании Nueva Living", ar: "عن نويفا ليفينغ" },
  { find: "Nueva Living was created for buyers who want straightforward help in the Costa del Sol new-build market.", es: "Nueva Living nació para compradores que buscan ayuda clara y directa en el mercado de obra nueva de la Costa del Sol.", fr: "Nueva Living a été créée pour les acheteurs qui souhaitent un accompagnement simple et direct sur le marché du neuf de la Costa del Sol.", de: "Nueva Living wurde für Käufer gegründet, die auf dem Neubaumarkt der Costa del Sol unkomplizierte, direkte Unterstützung suchen.", ru: "Nueva Living создана для покупателей, которым нужна прямая и понятная помощь на рынке новостроек Коста-дель-Соль.", ar: "تأسست نويفا ليفينغ لخدمة المشترين الراغبين في مساعدة واضحة ومباشرة في سوق المشاريع العقارية الجديدة على ساحل كوستا ديل سول." },
  { find: "New builds are <em>what we know</em>", es: "La obra nueva es <em>lo que dominamos</em>", fr: "Le neuf, <em>c'est notre spécialité</em>", de: "Neubauprojekte sind <em>unsere Kernkompetenz</em>", ru: "Новостройки — <em>наша специализация</em>", ar: "المشاريع الجديدة هي <em>مجال خبرتنا</em>" },
  { find: "Because we only work with new and off-plan homes, we know the developers, the projects and the questions buyers should ask.", es: "Como solo trabajamos con viviendas nuevas y sobre plano, conocemos a los promotores, los proyectos y las preguntas que todo comprador debería hacer.", fr: "Parce que nous ne travaillons qu'avec des biens neufs et en VEFA, nous connaissons les promoteurs, les programmes et les questions que tout acheteur devrait poser.", de: "Da wir uns ausschließlich auf Neubau- und Off-Plan-Immobilien konzentrieren, kennen wir die Bauträger, die Projekte und die Fragen, die Käufer stellen sollten.", ru: "Поскольку мы работаем исключительно с новостройками и объектами на этапе строительства, мы знаем застройщиков, проекты и вопросы, которые должен задать каждый покупатель.", ar: "بما أننا نعمل حصرًا مع المنازل الجديدة والمشاريع قيد الإنشاء، فإننا نعرف المطورين والمشاريع والأسئلة التي ينبغي على المشتري طرحها." },
  { find: "Our job is simple: show you what is available, explain what is good and help you leave the wrong options behind.", es: "Nuestra labor es sencilla: mostrarle lo disponible, explicarle qué es realmente bueno y ayudarle a descartar las opciones que no le convienen.", fr: "Notre mission est simple : vous montrer ce qui est disponible, vous expliquer ce qui est vraiment intéressant et vous aider à écarter les options qui ne vous conviennent pas.", de: "Unsere Aufgabe ist einfach: Wir zeigen Ihnen, was verfügbar ist, erklären, was wirklich gut ist, und helfen Ihnen, die falschen Optionen auszuschließen.", ru: "Наша задача проста: показать вам доступные варианты, объяснить, что действительно хорошо, и помочь отказаться от неподходящих вариантов.", ar: "مهمتنا بسيطة: نعرض لكم الخيارات المتاحة، ونوضح ما هو جيد بالفعل، ونساعدكم على استبعاد الخيارات غير المناسبة." },
  { find: "Sasan founded Nueva Living to make the search for a new home on the Costa del Sol clearer and more focused.", es: "Sasan fundó Nueva Living para que la búsqueda de una vivienda nueva en la Costa del Sol sea más clara y más enfocada.", fr: "Sasan a fondé Nueva Living pour rendre la recherche d'un bien neuf sur la Costa del Sol plus claire et plus ciblée.", de: "Sasan gründete Nueva Living, um die Suche nach einem Neubau an der Costa del Sol klarer und zielgerichteter zu gestalten.", ru: "Сасан основал Nueva Living, чтобы сделать поиск нового дома на Коста-дель-Соль более понятным и целенаправленным.", ar: "أسّس ساسان شركة نويفا ليفينغ لجعل البحث عن منزل جديد في كوستا ديل سول أكثر وضوحًا وتركيزًا." },
  { find: "Contact him directly to discuss your search, ask about a project or build a shortlist around what matters to you.", es: "Contacte con él directamente para hablar de su búsqueda, preguntar sobre un proyecto o elaborar una preselección centrada en lo que realmente le importa.", fr: "Contactez-le directement pour discuter de votre recherche, vous renseigner sur un programme ou établir une présélection autour de ce qui compte pour vous.", de: "Kontaktieren Sie ihn direkt, um Ihre Suche zu besprechen, sich über ein Projekt zu informieren oder eine Auswahlliste rund um Ihre Prioritäten zu erstellen.", ru: "Свяжитесь с ним напрямую, чтобы обсудить ваш поиск, узнать о проекте или составить короткий список объектов исходя из того, что важно именно вам.", ar: "تواصلوا معه مباشرة لمناقشة بحثكم، أو الاستفسار عن مشروع، أو إعداد قائمة مختصرة تراعي ما يهمكم." },
  { find: "<span>Email</span>", es: "<span>Correo electrónico</span>", fr: "<span>E-mail</span>", de: "<span>E-Mail</span>", ru: "<span>Эл. почта</span>", ar: "<span>البريد الإلكتروني</span>" },
  { find: "<span>Phone / WhatsApp</span>", es: "<span>Teléfono / WhatsApp</span>", fr: "<span>Téléphone / WhatsApp</span>", de: "<span>Telefon / WhatsApp</span>", ru: "<span>Телефон / WhatsApp</span>", ar: "<span>الهاتف / واتساب</span>" },
  { find: "Sami brings a background in business development and economics, with a practical focus on evaluating opportunities, structuring decisions and building long-term relationships.", es: "Sami aporta una trayectoria en desarrollo de negocio y economía, con un enfoque práctico en evaluar oportunidades, estructurar decisiones y construir relaciones a largo plazo.", fr: "Sami possède une expérience en développement commercial et en économie, avec une approche pragmatique de l'évaluation des opportunités, de la structuration des décisions et de la construction de relations durables.", de: "Sami bringt einen Hintergrund in Business Development und Wirtschaft mit und legt praktischen Wert auf die Bewertung von Chancen, die Strukturierung von Entscheidungen und den Aufbau langfristiger Beziehungen.", ru: "Сами имеет опыт в развитии бизнеса и экономике, с практическим подходом к оценке возможностей, структурированию решений и выстраиванию долгосрочных отношений.", ar: "يتمتع سامي بخلفية في تطوير الأعمال والاقتصاد، مع تركيز عملي على تقييم الفرص وهيكلة القرارات وبناء علاقات طويلة الأمد." },
  { find: "At Nueva Living, he connects commercial insight with each buyer's priorities, helping keep project selection and the purchasing process clear, considered and grounded.", es: "En Nueva Living, combina su visión comercial con las prioridades de cada comprador, ayudando a que la selección de proyectos y el proceso de compra sean claros, meditados y realistas.", fr: "Chez Nueva Living, il associe sa vision commerciale aux priorités de chaque acheteur, contribuant à garder la sélection des programmes et le processus d'achat clairs, réfléchis et réalistes.", de: "Bei Nueva Living verbindet er kaufmännisches Gespür mit den Prioritäten jedes Käufers und sorgt dafür, dass Projektauswahl und Kaufprozess klar, durchdacht und fundiert bleiben.", ru: "В Nueva Living он сочетает коммерческое чутьё с приоритетами каждого покупателя, помогая сделать выбор проекта и процесс покупки понятным, взвешенным и обоснованным.", ar: "في نويفا ليفينغ، يجمع سامي بين الرؤية التجارية وأولويات كل مشترٍ، مما يساعد على إبقاء اختيار المشروع وعملية الشراء واضحة ومدروسة وواقعية." },
  { find: "Developers We Work With", es: "Promotores con los que trabajamos", fr: "Promoteurs avec lesquels nous travaillons", de: "Bauträger, mit denen wir zusammenarbeiten", ru: "Застройщики, с которыми мы работаем", ar: "المطورون الذين نتعاون معهم" },
  { find: "Direct conversations and project access across the main Costa del Sol areas.", es: "Contacto directo y acceso a proyectos en las principales zonas de la Costa del Sol.", fr: "Contacts directs et accès aux programmes dans les principaux secteurs de la Costa del Sol.", de: "Direkter Kontakt und Projektzugang in den wichtigsten Gebieten der Costa del Sol.", ru: "Прямые контакты и доступ к проектам в основных районах Коста-дель-Соль.", ar: "تواصل مباشر وإمكانية الوصول إلى المشاريع في المناطق الرئيسية بكوستا ديل سول." },
  { find: "Areas We Cover", es: "Zonas que cubrimos", fr: "Secteurs couverts", de: "Von uns abgedeckte Gebiete", ru: "Районы, которые мы охватываем", ar: "المناطق التي نغطيها" },
  { find: "From Marbella and Benahavis to Estepona, Nueva Andalucia, Mijas and Fuengirola.", es: "Desde Marbella y Benahavís hasta Estepona, Nueva Andalucía, Mijas y Fuengirola.", fr: "De Marbella et Benahavís à Estepona, Nueva Andalucía, Mijas et Fuengirola.", de: "Von Marbella und Benahavís bis Estepona, Nueva Andalucía, Mijas und Fuengirola.", ru: "От Марбельи и Бенаависа до Эстепоны, Нуэва-Андалусии, Михаса и Фуэнхиролы.", ar: "من ماربيا وبيناهابيس إلى إستيبونا ونويفا أندلوسيا وميخاس وفوينخيرولا." },
  { find: "Focused on New Builds", es: "Centrados en la obra nueva", fr: "Focalisés sur le neuf", de: "Fokussiert auf Neubauten", ru: "В фокусе — новостройки", ar: "التركيز على المشاريع الجديدة" },
  { find: "One clear focus keeps our advice useful and up to date.", es: "Un enfoque claro mantiene nuestro asesoramiento útil y actualizado.", fr: "Un positionnement clair garde nos conseils utiles et à jour.", de: "Ein klarer Fokus hält unsere Beratung nützlich und aktuell.", ru: "Чёткий фокус делает наши рекомендации полезными и актуальными.", ar: "التركيز الواضح يجعل استشاراتنا مفيدة ومحدثة دائمًا." },
  { find: "What Matters to Us", es: "Lo que nos importa", fr: "Ce qui compte pour nous", de: "Was uns wichtig ist", ru: "Что для нас важно", ar: "ما يهمنا" },
  { find: "Access, privacy and <em>clear advice</em>", es: "Acceso, privacidad y <em>asesoramiento claro</em>", fr: "Accès, confidentialité et <em>conseils clairs</em>", de: "Zugang, Diskretion und <em>klare Beratung</em>", ru: "Доступ, конфиденциальность и <em>понятные рекомендации</em>", ar: "الوصول والخصوصية <em>واستشارات واضحة</em>" },
  { find: "Privacy", es: "Privacidad", fr: "Confidentialité", de: "Diskretion", ru: "Конфиденциальность", ar: "الخصوصية" },
  { find: "We handle your requirements carefully and only share details when needed for your request.", es: "Tratamos sus requisitos con cuidado y solo compartimos sus datos cuando es necesario para atender su solicitud.", fr: "Nous traitons vos besoins avec attention et ne partageons vos informations que lorsque cela est nécessaire pour votre demande.", de: "Wir behandeln Ihre Anforderungen sorgfältig und geben Ihre Daten nur weiter, wenn dies für Ihre Anfrage erforderlich ist.", ru: "Мы внимательно относимся к вашим пожеланиям и передаём данные третьим лицам только когда это необходимо для вашего запроса.", ar: "نتعامل مع متطلباتكم بعناية ولا نشارك بياناتكم إلا عند الضرورة لتلبية طلبكم." },
  { find: "Fewer, Better Options", es: "Menos opciones, pero mejores", fr: "Moins d'options, mais meilleures", de: "Weniger, aber bessere Optionen", ru: "Меньше вариантов — но лучше", ar: "خيارات أقل وأفضل" },
  { find: "We focus on the projects worth considering rather than sending you a long catalogue.", es: "Nos centramos en los proyectos que realmente merecen su atención, en lugar de enviarle un catálogo interminable.", fr: "Nous nous concentrons sur les programmes qui méritent votre attention, plutôt que de vous envoyer un long catalogue.", de: "Wir konzentrieren uns auf die Projekte, die es wert sind, statt Ihnen einen langen Katalog zu schicken.", ru: "Мы сосредоточены на проектах, которые действительно заслуживают внимания, а не присылаем длинный каталог.", ar: "نركز على المشاريع الجديرة بالاهتمام بدلاً من إرسال كتالوج طويل." },
  { find: "The Full Picture", es: "La imagen completa", fr: "Une vision complète", de: "Das Gesamtbild", ru: "Полная картина", ar: "الصورة الكاملة" },
  { find: "Every recommendation includes the area, developer, timing and what may support future value.", es: "Cada recomendación incluye la zona, el promotor, los plazos y los factores que pueden respaldar el valor futuro.", fr: "Chaque recommandation précise le secteur, le promoteur, le calendrier et les facteurs pouvant soutenir la valeur future.", de: "Jede Empfehlung umfasst die Lage, den Bauträger, den Zeitrahmen und mögliche Faktoren für die künftige Wertentwicklung.", ru: "Каждая рекомендация включает район, застройщика, сроки и факторы, которые могут повлиять на будущую стоимость.", ar: "تتضمن كل توصية المنطقة والمطور والجدول الزمني والعوامل التي قد تدعم القيمة المستقبلية." },
  { find: "Tell us what you are looking for and we will help with the next step.", es: "Cuéntenos qué está buscando y le ayudaremos con el siguiente paso.", fr: "Dites-nous ce que vous recherchez, nous vous aiderons pour la prochaine étape.", de: "Sagen Sie uns, wonach Sie suchen, und wir helfen Ihnen beim nächsten Schritt.", ru: "Расскажите нам, что вы ищете, и мы поможем со следующим шагом.", ar: "أخبرونا بما تبحثون عنه وسنساعدكم في الخطوة التالية." },

  // Founder role/label pairs -- matched with wrapping tags so the bare
  // words "Founder" / "Co-Founder" never touch the data-context
  // attribute value on the adjacent WhatsApp link (which must stay
  // untranslated).
  { find: "<p class=\"founder-role\">Co-Founder, Nueva Living</p>", es: "<p class=\"founder-role\">Cofundador, Nueva Living</p>", fr: "<p class=\"founder-role\">Cofondateur, Nueva Living</p>", de: "<p class=\"founder-role\">Mitgründer, Nueva Living</p>", ru: "<p class=\"founder-role\">Сооснователь, Nueva Living</p>", ar: "<p class=\"founder-role\">شريك مؤسس، نويفا ليفينغ</p>" },
  { find: "<p class=\"founder-role\">Founder, Nueva Living</p>", es: "<p class=\"founder-role\">Fundador, Nueva Living</p>", fr: "<p class=\"founder-role\">Fondateur, Nueva Living</p>", de: "<p class=\"founder-role\">Gründer, Nueva Living</p>", ru: "<p class=\"founder-role\">Основатель, Nueva Living</p>", ar: "<p class=\"founder-role\">المؤسس، نويفا ليفينغ</p>" },
  { find: "<span class=\"label\">Co-Founder</span>", es: "<span class=\"label\">Cofundador</span>", fr: "<span class=\"label\">Cofondateur</span>", de: "<span class=\"label\">Mitgründer</span>", ru: "<span class=\"label\">Сооснователь</span>", ar: "<span class=\"label\">شريك مؤسس</span>" },
  { find: "<span class=\"label\">Founder</span>", es: "<span class=\"label\">Fundador</span>", fr: "<span class=\"label\">Fondateur</span>", de: "<span class=\"label\">Gründer</span>", ru: "<span class=\"label\">Основатель</span>", ar: "<span class=\"label\">المؤسس</span>" },

  // ===== contact.html =====
  { find: "Tell Nueva Living what kind of new home you are looking for on the Costa del Sol.", es: "Cuéntele a Nueva Living qué tipo de vivienda nueva busca en la Costa del Sol.", fr: "Indiquez à Nueva Living le type de bien neuf que vous recherchez sur la Costa del Sol.", de: "Teilen Sie Nueva Living mit, welche Art von Neubau-Immobilie Sie an der Costa del Sol suchen.", ru: "Расскажите Nueva Living, какой новый дом на Коста-дель-Соль вы ищете.", ar: "أخبروا نويفا ليفينغ عن نوع المنزل الجديد الذي تبحثون عنه في كوستا ديل سول." },
  { find: "Contact Nueva Living", es: "Contacte con Nueva Living", fr: "Contacter Nueva Living", de: "Kontaktieren Sie Nueva Living", ru: "Связаться с Nueva Living", ar: "تواصلوا مع نويفا ليفينغ" },
  { find: "Tell us what you are <em>looking for</em>", es: "Cuéntenos lo que <em>está buscando</em>", fr: "Dites-nous ce que <em>vous recherchez</em>", de: "Sagen Sie uns, <em>wonach Sie suchen</em>", ru: "Расскажите нам, что <em>вы ищете</em>", ar: "أخبرونا <em>عمّا تبحثون عنه</em>" },
  { find: "Share a few details and we will come back with relevant projects, current availability and a clear next step.", es: "Compártanos algunos datos y le responderemos con proyectos relevantes, disponibilidad actual y un siguiente paso claro.", fr: "Partagez quelques informations et nous reviendrons vers vous avec des programmes pertinents, les disponibilités actuelles et une prochaine étape claire.", de: "Teilen Sie uns ein paar Details mit, und wir melden uns mit passenden Projekten, aktueller Verfügbarkeit und einem klaren nächsten Schritt.", ru: "Поделитесь с нами несколькими деталями, и мы предложим вам подходящие проекты, актуальную доступность и понятный следующий шаг.", ar: "شاركونا ببعض التفاصيل وسنعاود التواصل معكم بمشاريع مناسبة وتوافر حالي وخطوة تالية واضحة." },
  { find: "Your Search", es: "Su búsqueda", fr: "Votre recherche", de: "Ihre Suche", ru: "Ваш поиск", ar: "بحثكم" },
  { find: "Let us help you <em>narrow it down</em>", es: "Permítanos ayudarle a <em>concretar su búsqueda</em>", fr: "Laissez-nous vous aider à <em>affiner votre recherche</em>", de: "Lassen Sie uns helfen, <em>die Auswahl einzugrenzen</em>", ru: "Позвольте нам помочь <em>сузить круг поиска</em>", ar: "دعونا نساعدكم على <em>تحديد اختياركم بدقة</em>" },
  { find: "Tell us what matters to you. We will reply with the projects and information that best fit your search.", es: "Cuéntenos qué es importante para usted. Le responderemos con los proyectos y la información que mejor se ajusten a su búsqueda.", fr: "Dites-nous ce qui compte pour vous. Nous vous répondrons avec les programmes et les informations qui correspondent le mieux à votre recherche.", de: "Sagen Sie uns, worauf es Ihnen ankommt. Wir antworten mit den Projekten und Informationen, die am besten zu Ihrer Suche passen.", ru: "Расскажите, что для вас важно. Мы ответим проектами и информацией, которые лучше всего соответствуют вашему запросу.", ar: "أخبرونا بما يهمكم، وسنرد عليكم بالمشاريع والمعلومات الأنسب لبحثكم." },
  { find: "Visit Us", es: "Visítenos", fr: "Nous rendre visite", de: "Besuchen Sie uns", ru: "Посетите нас", ar: "زوروا مكتبنا" },
  { find: "First Name", es: "Nombre", fr: "Prénom", de: "Vorname", ru: "Имя", ar: "الاسم الأول" },
  { find: "Last Name", es: "Apellidos", fr: "Nom", de: "Nachname", ru: "Фамилия", ar: "اسم العائلة" },
  { find: "Email Address", es: "Correo electrónico", fr: "Adresse e-mail", de: "E-Mail-Adresse", ru: "Адрес электронной почты", ar: "البريد الإلكتروني" },
  { find: "Phone Number", es: "Número de teléfono", fr: "Numéro de téléphone", de: "Telefonnummer", ru: "Номер телефона", ar: "رقم الهاتف" },
  { find: "Preferred Area", es: "Zona preferida", fr: "Secteur préféré", de: "Bevorzugte Lage", ru: "Предпочитаемый район", ar: "المنطقة المفضلة" },
  { find: "Property Type", es: "Tipo de propiedad", fr: "Type de bien", de: "Immobilientyp", ru: "Тип недвижимости", ar: "نوع العقار" },
  { find: "Budget Range", es: "Rango de presupuesto", fr: "Budget", de: "Budgetrahmen", ru: "Диапазон бюджета", ar: "نطاق الميزانية" },
  { find: "How Will You Use It?", es: "¿Cómo la utilizará?", fr: "Quel usage en ferez-vous ?", de: "Wie werden Sie die Immobilie nutzen?", ru: "Как вы планируете использовать недвижимость?", ar: "كيف ستستخدمون العقار؟" },
  { find: "Message", es: "Mensaje", fr: "Message", de: "Nachricht", ru: "Сообщение", ar: "الرسالة" },
  { find: "I agree to be contacted and for my data to be stored.", es: "Acepto ser contactado/a y que mis datos sean almacenados.", fr: "J'accepte d'être contacté(e) et que mes données soient conservées.", de: "Ich stimme zu, kontaktiert zu werden und dass meine Daten gespeichert werden.", ru: "Я согласен(на) на получение обратной связи и на хранение моих данных.", ar: "أوافق على التواصل معي وعلى تخزين بياناتي." },
  { find: "I would also like to receive occasional project updates from Nueva Living.", es: "También me gustaría recibir novedades ocasionales de proyectos de Nueva Living.", fr: "Je souhaite également recevoir occasionnellement des actualités sur les programmes de Nueva Living.", de: "Ich möchte außerdem gelegentlich Projekt-Updates von Nueva Living erhalten.", ru: "Я также хотел(а) бы получать периодические новости о проектах от Nueva Living.", ar: "أرغب أيضًا في تلقي تحديثات دورية عن المشاريع من نويفا ليفينغ." },
  { find: "Send Enquiry", es: "Enviar consulta", fr: "Envoyer la demande", de: "Anfrage senden", ru: "Отправить запрос", ar: "إرسال الاستفسار" },

  // ===== privacy-policy.html =====
  { find: "Privacy Policy", es: "Política de Privacidad", fr: "Politique de confidentialité", de: "Datenschutzerklärung", ru: "Политика конфиденциальности", ar: "سياسة الخصوصية" },
  { find: "Privacy policy draft for Nueva Living.", es: "Borrador de la política de privacidad de Nueva Living.", fr: "Projet de politique de confidentialité de Nueva Living.", de: "Entwurf der Datenschutzerklärung von Nueva Living.", ru: "Проект политики конфиденциальности Nueva Living.", ar: "مسودة سياسة الخصوصية الخاصة بنويفا ليفينغ." },
  { find: "Privacy <em>Policy</em>", es: "Política de <em>Privacidad</em>", fr: "Politique de <em>confidentialité</em>", de: "Datenschutz<em>erklärung</em>", ru: "Политика <em>конфиденциальности</em>", ar: "سياسة <em>الخصوصية</em>" },
  { find: "How we collect, use and protect the information you share with us.", es: "Cómo recopilamos, utilizamos y protegemos la información que usted comparte con nosotros.", fr: "Comment nous collectons, utilisons et protégeons les informations que vous partagez avec nous.", de: "Wie wir die Informationen, die Sie mit uns teilen, erheben, verwenden und schützen.", ru: "Как мы собираем, используем и защищаем информацию, которую вы нам предоставляете.", ar: "كيفية جمعنا واستخدامنا وحمايتنا للمعلومات التي تشاركونها معنا." },
  { find: "Overview", es: "Resumen", fr: "Vue d'ensemble", de: "Überblick", ru: "Обзор", ar: "نظرة عامة" },
  { find: "LIORA LIVING SL. (NIF B88827472), operating under the Nueva Living brand, is responsible for personal information submitted through enquiry forms, email or direct communication.", es: "LIORA LIVING SL. (NIF B88827472), que opera bajo la marca Nueva Living, es responsable de la información personal enviada a través de formularios de consulta, correo electrónico o comunicación directa.", fr: "LIORA LIVING SL. (NIF B88827472), exploitant la marque Nueva Living, est responsable des informations personnelles transmises via les formulaires de contact, l'e-mail ou toute communication directe.", de: "LIORA LIVING SL. (NIF B88827472), die unter der Marke Nueva Living tätig ist, ist verantwortlich für personenbezogene Daten, die über Kontaktformulare, E-Mail oder direkte Kommunikation übermittelt werden.", ru: "Компания LIORA LIVING SL. (налоговый номер NIF B88827472), работающая под брендом Nueva Living, несёт ответственность за персональные данные, предоставленные через формы запросов, электронную почту или прямую связь.", ar: "شركة LIORA LIVING SL. (الرقم الضريبي NIF B88827472)، التي تعمل تحت علامة نويفا ليفينغ، هي المسؤولة عن المعلومات الشخصية المقدَّمة عبر نماذج الاستفسار أو البريد الإلكتروني أو التواصل المباشر." },
  { find: "Information We May Collect", es: "Información que podemos recopilar", fr: "Informations que nous pouvons collecter", de: "Informationen, die wir erheben können", ru: "Информация, которую мы можем собирать", ar: "المعلومات التي قد نجمعها" },
  { find: "Name, contact details, preferred area, budget range, purchase purpose and any details voluntarily included in a message. Website measurement may also collect page visits, temporary session identifiers, device and browser type, general interaction events, referral or campaign information and performance or error data. Analytics does not read or store the values entered into form fields.", es: "Nombre, datos de contacto, zona preferida, rango de presupuesto, finalidad de la compra y cualquier detalle incluido voluntariamente en un mensaje. La medición del sitio web también puede recopilar visitas a páginas, identificadores de sesión temporales, tipo de dispositivo y navegador, eventos generales de interacción, información de referencia o campaña, y datos de rendimiento o errores. El sistema de analítica no lee ni almacena los valores introducidos en los campos del formulario.", fr: "Nom, coordonnées, secteur préféré, budget, finalité de l'achat et tout détail volontairement inclus dans un message. La mesure d'audience du site peut également collecter les visites de pages, des identifiants de session temporaires, le type d'appareil et de navigateur, des événements d'interaction généraux, des informations de provenance ou de campagne, ainsi que des données de performance ou d'erreur. L'outil d'analyse ne lit ni ne stocke les valeurs saisies dans les champs du formulaire.", de: "Name, Kontaktdaten, bevorzugte Lage, Budgetrahmen, Kaufzweck und alle freiwillig in einer Nachricht angegebenen Details. Die Website-Messung kann außerdem Seitenaufrufe, temporäre Sitzungskennungen, Geräte- und Browsertyp, allgemeine Interaktionsereignisse, Verweis- oder Kampagneninformationen sowie Leistungs- oder Fehlerdaten erfassen. Die Analyse liest oder speichert keine in Formularfelder eingegebenen Werte.", ru: "Имя, контактные данные, предпочитаемый район, диапазон бюджета, цель покупки и любые сведения, добровольно указанные в сообщении. Измерение посещаемости сайта может также собирать данные о просмотренных страницах, временные идентификаторы сессии, тип устройства и браузера, общие события взаимодействия, информацию о источнике перехода или кампании, а также данные о производительности и ошибках. Аналитика не считывает и не сохраняет значения, введённые в поля формы.", ar: "الاسم، وبيانات التواصل، والمنطقة المفضلة، ونطاق الميزانية، والغرض من الشراء، وأي تفاصيل يتم تضمينها طوعًا في الرسالة. قد يقوم قياس الموقع الإلكتروني أيضًا بجمع زيارات الصفحات، ومعرّفات الجلسة المؤقتة، ونوع الجهاز والمتصفح، وأحداث التفاعل العامة، ومعلومات الإحالة أو الحملة، وبيانات الأداء أو الأخطاء. لا تقوم أداة التحليلات بقراءة أو تخزين القيم المدخلة في حقول النموذج." },
  { find: "How Information Is Used", es: "Cómo se utiliza la información", fr: "Comment les informations sont utilisées", de: "Wie Informationen verwendet werden", ru: "Как используется информация", ar: "كيفية استخدام المعلومات" },
  { find: "Information is used to respond to enquiries, prepare relevant project suggestions, coordinate viewings and maintain appropriate records of client communication. Aggregated website measurement is used to understand which pages and features are useful, identify technical problems and improve website performance.", es: "La información se utiliza para responder a las consultas, preparar propuestas de proyectos relevantes, coordinar visitas y mantener registros adecuados de la comunicación con el cliente. La medición agregada del sitio web se utiliza para entender qué páginas y funciones resultan útiles, identificar problemas técnicos y mejorar el rendimiento del sitio.", fr: "Les informations sont utilisées pour répondre aux demandes, préparer des suggestions de programmes pertinentes, organiser les visites et conserver un historique approprié des échanges avec le client. La mesure d'audience agrégée sert à comprendre quelles pages et fonctionnalités sont utiles, à identifier les problèmes techniques et à améliorer les performances du site.", de: "Informationen werden verwendet, um Anfragen zu beantworten, passende Projektvorschläge vorzubereiten, Besichtigungen zu koordinieren und angemessene Aufzeichnungen der Kundenkommunikation zu führen. Aggregierte Website-Messungen werden verwendet, um zu verstehen, welche Seiten und Funktionen nützlich sind, technische Probleme zu erkennen und die Website-Leistung zu verbessern.", ru: "Информация используется для ответа на запросы, подготовки релевантных предложений по проектам, координации просмотров и ведения соответствующих записей общения с клиентом. Агрегированные данные измерения сайта используются для понимания того, какие страницы и функции полезны, выявления технических проблем и повышения производительности сайта.", ar: "تُستخدم المعلومات للرد على الاستفسارات، وإعداد اقتراحات مشاريع مناسبة، وتنسيق المعاينات، والاحتفاظ بسجلات ملائمة للتواصل مع العميل. تُستخدم بيانات قياس الموقع المجمّعة لفهم الصفحات والميزات المفيدة، وتحديد المشكلات التقنية، وتحسين أداء الموقع." },
  { find: "Sharing", es: "Compartición de datos", fr: "Partage des données", de: "Weitergabe", ru: "Передача данных", ar: "مشاركة البيانات" },
  { find: "Enquiry details may be processed in Nueva Living's customer relationship management system and shared with developers, legal advisers or other service providers only where necessary for a requested enquiry, viewing, reservation or service step. Website measurement events may be processed by Nueva Living's CRM and hosting providers for analytics and technical operation.", es: "Los datos de las consultas pueden procesarse en el sistema de gestión de relaciones con clientes (CRM) de Nueva Living y compartirse con promotores, asesores legales u otros proveedores de servicios únicamente cuando sea necesario para atender una consulta, visita, reserva o trámite solicitado. Los eventos de medición del sitio web pueden ser procesados por los proveedores de CRM y hosting de Nueva Living con fines de analítica y funcionamiento técnico.", fr: "Les informations de contact peuvent être traitées dans le système de gestion de la relation client (CRM) de Nueva Living et partagées avec des promoteurs, conseillers juridiques ou autres prestataires uniquement lorsque cela est nécessaire pour une demande, une visite, une réservation ou une étape de service sollicitée. Les événements de mesure d'audience du site peuvent être traités par les prestataires CRM et d'hébergement de Nueva Living à des fins d'analyse et de fonctionnement technique.", de: "Anfragedaten können im CRM-System (Customer-Relationship-Management) von Nueva Living verarbeitet und mit Bauträgern, Rechtsberatern oder anderen Dienstleistern geteilt werden, jedoch nur, soweit dies für eine angeforderte Anfrage, Besichtigung, Reservierung oder Serviceleistung erforderlich ist. Website-Messereignisse können von den CRM- und Hosting-Anbietern von Nueva Living zu Analyse- und technischen Betriebszwecken verarbeitet werden.", ru: "Данные запроса могут обрабатываться в системе управления взаимоотношениями с клиентами (CRM) Nueva Living и передаваться застройщикам, юридическим консультантам или другим поставщикам услуг только в случаях, необходимых для выполнения запрошенного обращения, просмотра, резервирования или иного этапа обслуживания. События измерения сайта могут обрабатываться поставщиками CRM и хостинга Nueva Living в целях аналитики и технической эксплуатации.", ar: "يجوز معالجة تفاصيل الاستفسار ضمن نظام إدارة علاقات العملاء (CRM) الخاص بنويفا ليفينغ، ومشاركتها مع المطورين أو المستشارين القانونيين أو مزودي الخدمات الآخرين فقط عند الضرورة لتنفيذ استفسار أو معاينة أو حجز أو خطوة خدمة مطلوبة. يجوز معالجة بيانات قياس الموقع من قبل مزودي خدمات CRM والاستضافة الخاصين بنويفا ليفينغ لأغراض التحليل والتشغيل التقني." },
  { find: "Retention &amp; Rights", es: "Conservación y Derechos", fr: "Conservation et droits", de: "Aufbewahrung &amp; Rechte", ru: "Хранение данных и права", ar: "الاحتفاظ بالبيانات والحقوق" },
  { find: "Personal data should be retained only for as long as needed for the enquiry or client relationship. Visitors may request access, correction or deletion by contacting contact@nuevaliving.com.", es: "Los datos personales deben conservarse únicamente durante el tiempo necesario para la consulta o la relación con el cliente. Los visitantes pueden solicitar acceso, rectificación o supresión escribiendo a contact@nuevaliving.com.", fr: "Les données personnelles ne doivent être conservées que le temps nécessaire à la demande ou à la relation client. Les visiteurs peuvent demander l'accès, la rectification ou la suppression de leurs données en écrivant à contact@nuevaliving.com.", de: "Personenbezogene Daten sollten nur so lange aufbewahrt werden, wie es für die Anfrage oder die Kundenbeziehung erforderlich ist. Besucher können Zugang, Berichtigung oder Löschung beantragen, indem sie sich an contact@nuevaliving.com wenden.", ru: "Персональные данные должны храниться только в течение времени, необходимого для обработки запроса или поддержания отношений с клиентом. Посетители могут запросить доступ, исправление или удаление данных, обратившись по адресу contact@nuevaliving.com.", ar: "ينبغي الاحتفاظ بالبيانات الشخصية فقط للمدة اللازمة للاستفسار أو للعلاقة مع العميل. يمكن للزوار طلب الوصول إلى بياناتهم أو تصحيحها أو حذفها عبر التواصل على contact@nuevaliving.com." },

  // ===== legal-notice.html =====
  { find: "Legal Notice", es: "Aviso Legal", fr: "Mentions légales", de: "Rechtliche Hinweise", ru: "Правовое уведомление", ar: "الإشعار القانوني" },
  { find: "Legal notice draft for Nueva Living.", es: "Borrador del aviso legal de Nueva Living.", fr: "Projet de mentions légales de Nueva Living.", de: "Entwurf der rechtlichen Hinweise von Nueva Living.", ru: "Проект правового уведомления Nueva Living.", ar: "مسودة الإشعار القانوني لنويفا ليفينغ." },
  { find: "Legal <em>Notice</em>", es: "Aviso <em>Legal</em>", fr: "Mentions <em>légales</em>", de: "Rechtliche <em>Hinweise</em>", ru: "Правовое <em>уведомление</em>", ar: "الإشعار <em>القانوني</em>" },
  { find: "No Legal Or Financial Advice", es: "Sin asesoramiento legal ni financiero", fr: "Absence de conseil juridique ou financier", de: "Keine Rechts- oder Finanzberatung", ru: "Отсутствие юридической или финансовой консультации", ar: "لا تُقدَّم استشارة قانونية أو مالية" },
  { find: "Who operates this website, what the information is for and the terms that apply.", es: "Quién opera este sitio web, para qué sirve la información y qué términos son de aplicación.", fr: "Qui exploite ce site web, à quoi servent les informations et quelles conditions s'appliquent.", de: "Wer diese Website betreibt, wofür die Informationen bestimmt sind und welche Bedingungen gelten.", ru: "Кто управляет этим сайтом, для чего предназначена информация и какие условия применяются.", ar: "من يدير هذا الموقع، والغرض من المعلومات، والشروط المعمول بها." },
  { find: "Website Owner", es: "Titular del sitio web", fr: "Éditeur du site", de: "Betreiber der Website", ru: "Владелец сайта", ar: "مالك الموقع الإلكتروني" },
  { find: "This website is presented under the Nueva Living brand and operated by LIORA LIVING SL., Tax ID (NIF) B88827472.", es: "Este sitio web se presenta bajo la marca Nueva Living y está operado por LIORA LIVING SL., con NIF B88827472.", fr: "Ce site web est présenté sous la marque Nueva Living et exploité par LIORA LIVING SL., numéro d'identification fiscale (NIF) B88827472.", de: "Diese Website wird unter der Marke Nueva Living präsentiert und von LIORA LIVING SL. betrieben, Steuernummer (NIF) B88827472.", ru: "Данный веб-сайт представлен под брендом Nueva Living и управляется компанией LIORA LIVING SL., налоговый номер (NIF) B88827472.", ar: "يُقدَّم هذا الموقع الإلكتروني تحت علامة نويفا ليفينغ، وتديره شركة LIORA LIVING SL.، الرقم الضريبي (NIF) B88827472." },
  { find: "Purpose Of The Website", es: "Finalidad del sitio web", fr: "Objet du site web", de: "Zweck der Website", ru: "Назначение сайта", ar: "الغرض من الموقع الإلكتروني" },
  { find: "The site provides general marketing information about new-build and off-plan property opportunities across the Costa del Sol. Content is indicative and subject to change.", es: "El sitio ofrece información comercial general sobre oportunidades de vivienda nueva y sobre plano en toda la Costa del Sol. El contenido es orientativo y puede modificarse.", fr: "Le site fournit des informations commerciales générales sur les opportunités de biens neufs et en VEFA sur la Costa del Sol. Le contenu est donné à titre indicatif et peut être modifié.", de: "Die Website stellt allgemeine Marketinginformationen über Neubau- und Off-Plan-Immobilienangebote an der Costa del Sol bereit. Die Inhalte sind unverbindlich und können sich ändern.", ru: "Сайт предоставляет общую маркетинговую информацию о возможностях приобретения новостроек и объектов на стадии строительства на Коста-дель-Соль. Содержание носит ориентировочный характер и может быть изменено.", ar: "يقدّم الموقع معلومات تسويقية عامة عن الفرص العقارية للمشاريع الجديدة وقيد الإنشاء في جميع أنحاء كوستا ديل سول. المحتوى إرشادي وقابل للتغيير." },
  { find: "Information on this website does not constitute legal, financial, tax or investment advice. Buyers should seek independent professional advice before making any property decision.", es: "La información de este sitio web no constituye asesoramiento legal, financiero, fiscal ni de inversión. Los compradores deben buscar asesoramiento profesional independiente antes de tomar cualquier decisión sobre una propiedad.", fr: "Les informations figurant sur ce site web ne constituent pas un conseil juridique, financier, fiscal ou en investissement. Les acheteurs doivent obtenir un avis professionnel indépendant avant toute décision relative à un bien immobilier.", de: "Die Informationen auf dieser Website stellen keine Rechts-, Finanz-, Steuer- oder Anlageberatung dar. Käufer sollten vor jeder Immobilienentscheidung unabhängigen fachlichen Rat einholen.", ru: "Информация на данном сайте не является юридической, финансовой, налоговой или инвестиционной консультацией. Покупателям следует обращаться за независимой профессиональной консультацией перед принятием любого решения о приобретении недвижимости.", ar: "لا تشكّل المعلومات الواردة في هذا الموقع استشارة قانونية أو مالية أو ضريبية أو استثمارية. ينبغي على المشترين طلب استشارة مهنية مستقلة قبل اتخاذ أي قرار يتعلق بالعقار." },
  { find: "Property Information", es: "Información sobre las propiedades", fr: "Informations sur les biens", de: "Immobilieninformationen", ru: "Информация об объектах недвижимости", ar: "معلومات العقار" },
  { find: "Prices, availability, plans, delivery dates and specifications are provided for general orientation and may change without notice. Final details must be confirmed directly through official developer documentation.", es: "Los precios, la disponibilidad, los planos, las fechas de entrega y las especificaciones se ofrecen a título orientativo y pueden modificarse sin previo aviso. Los detalles definitivos deben confirmarse directamente a través de la documentación oficial del promotor.", fr: "Les prix, la disponibilité, les plans, les dates de livraison et les spécifications sont fournis à titre indicatif et peuvent être modifiés sans préavis. Les détails définitifs doivent être confirmés directement via la documentation officielle du promoteur.", de: "Preise, Verfügbarkeit, Pläne, Fertigstellungstermine und Spezifikationen dienen der allgemeinen Orientierung und können sich ohne Vorankündigung ändern. Endgültige Details müssen direkt anhand der offiziellen Unterlagen des Bauträgers bestätigt werden.", ru: "Цены, наличие, планировки, сроки сдачи и характеристики приведены для общей ориентации и могут быть изменены без предварительного уведомления. Окончательные детали должны подтверждаться непосредственно на основании официальной документации застройщика.", ar: "الأسعار والتوافر والمخططات ومواعيد التسليم والمواصفات مقدَّمة لأغراض التوجيه العام وقد تتغير دون إشعار مسبق. يجب تأكيد التفاصيل النهائية مباشرة من خلال الوثائق الرسمية الصادرة عن المطور." },
  { find: "Intellectual Property", es: "Propiedad intelectual", fr: "Propriété intellectuelle", de: "Geistiges Eigentum", ru: "Интеллектуальная собственность", ar: "الملكية الفكرية" },
  { find: "Branding, layout, written content and original materials on this website may not be copied or reused without permission. Third-party images remain subject to their respective rights.", es: "La marca, el diseño, los contenidos escritos y los materiales originales de este sitio web no pueden copiarse ni reutilizarse sin autorización. Las imágenes de terceros siguen sujetas a sus respectivos derechos.", fr: "L'identité visuelle, la mise en page, les contenus rédigés et les éléments originaux de ce site web ne peuvent être copiés ou réutilisés sans autorisation. Les images provenant de tiers restent soumises à leurs droits respectifs.", de: "Marke, Layout, Textinhalte und Originalmaterialien dieser Website dürfen ohne Genehmigung nicht kopiert oder weiterverwendet werden. Bilder Dritter unterliegen weiterhin den jeweiligen Rechten.", ru: "Фирменный стиль, оформление, текстовое содержание и оригинальные материалы данного сайта не могут копироваться или использоваться повторно без разрешения. Изображения третьих сторон остаются предметом соответствующих прав.", ar: "لا يجوز نسخ أو إعادة استخدام العلامة التجارية أو التصميم أو المحتوى المكتوب أو المواد الأصلية الخاصة بهذا الموقع دون إذن. تظل صور الأطراف الثالثة خاضعة لحقوقها الخاصة." },

  // ===== cookie-policy.html =====
  { find: "Cookie Policy", es: "Política de Cookies", fr: "Politique de cookies", de: "Cookie-Richtlinie", ru: "Политика использования файлов cookie", ar: "سياسة ملفات تعريف الارتباط" },
  { find: "Cookie policy draft for Nueva Living.", es: "Borrador de la política de cookies de Nueva Living.", fr: "Projet de politique de cookies de Nueva Living.", de: "Entwurf der Cookie-Richtlinie von Nueva Living.", ru: "Проект политики использования файлов cookie Nueva Living.", ar: "مسودة سياسة ملفات تعريف الارتباط الخاصة بنويفا ليفينغ." },
  { find: "Cookie <em>Policy</em>", es: "Política de <em>Cookies</em>", fr: "Politique de <em>cookies</em>", de: "Cookie-<em>Richtlinie</em>", ru: "Политика <em>cookie</em>", ar: "سياسة <em>ملفات تعريف الارتباط</em>" },
  { find: "What cookies and third-party tools may be used on this website.", es: "Qué cookies y herramientas de terceros pueden utilizarse en este sitio web.", fr: "Quels cookies et outils tiers peuvent être utilisés sur ce site web.", de: "Welche Cookies und Tools von Drittanbietern auf dieser Website verwendet werden können.", ru: "Какие файлы cookie и инструменты сторонних поставщиков могут использоваться на этом сайте.", ar: "ملفات تعريف الارتباط والأدوات الخارجية التي قد تُستخدم على هذا الموقع." },
  { find: "Current Setup", es: "Configuración actual", fr: "Configuration actuelle", de: "Aktuelle Einstellung", ru: "Текущая настройка", ar: "الإعداد الحالي" },
  { find: "This website does not use advertising cookies. It uses first-party browser storage to keep a temporary website-measurement session active for up to 30 minutes and to support features such as saved project shortlists.", es: "Este sitio web no utiliza cookies publicitarias. Utiliza almacenamiento de navegador propio (first-party) para mantener activa una sesión temporal de medición del sitio durante un máximo de 30 minutos y para funciones como las listas de proyectos guardados.", fr: "Ce site web n'utilise pas de cookies publicitaires. Il utilise un stockage de navigateur propriétaire (first-party) pour maintenir active une session temporaire de mesure d'audience pendant 30 minutes maximum et pour prendre en charge des fonctionnalités telles que les listes de programmes enregistrées.", de: "Diese Website verwendet keine Werbe-Cookies. Sie nutzt First-Party-Browserspeicher, um eine temporäre Website-Messsitzung für bis zu 30 Minuten aktiv zu halten und Funktionen wie gespeicherte Projektlisten zu unterstützen.", ru: "Данный сайт не использует рекламные файлы cookie. Он использует собственное хранилище браузера (first-party) для поддержания временной сессии измерения сайта в течение не более 30 минут и для функций, таких как сохранённые списки проектов.", ar: "لا يستخدم هذا الموقع ملفات تعريف ارتباط إعلانية. يستخدم تخزين المتصفح الخاص بالموقع (first-party) للحفاظ على جلسة قياس مؤقتة نشطة لمدة تصل إلى 30 دقيقة، ولدعم ميزات مثل قوائم المشاريع المحفوظة." },
  { find: "Essential Cookies", es: "Cookies esenciales", fr: "Cookies essentiels", de: "Essenzielle Cookies", ru: "Обязательные файлы cookie", ar: "ملفات تعريف الارتباط الأساسية" },
  { find: "Essential cookies or equivalent browser storage may be used to support basic website function, security, form handling or preference storage where required.", es: "Pueden utilizarse cookies esenciales o almacenamiento de navegador equivalente para dar soporte a las funciones básicas del sitio web, la seguridad, la gestión de formularios o el almacenamiento de preferencias cuando sea necesario.", fr: "Des cookies essentiels ou un stockage de navigateur équivalent peuvent être utilisés pour prendre en charge les fonctions de base du site web, la sécurité, le traitement des formulaires ou le stockage des préférences lorsque cela est nécessaire.", de: "Essenzielle Cookies oder gleichwertiger Browserspeicher können verwendet werden, um grundlegende Website-Funktionen, Sicherheit, Formularverarbeitung oder die Speicherung von Präferenzen zu unterstützen, sofern erforderlich.", ru: "Обязательные файлы cookie или эквивалентное хранилище браузера могут использоваться для поддержки базовых функций сайта, безопасности, обработки форм или хранения предпочтений, если это необходимо.", ar: "قد تُستخدم ملفات تعريف الارتباط الأساسية أو ما يعادلها من تخزين المتصفح لدعم الوظائف الأساسية للموقع، والأمان، ومعالجة النماذج، أو تخزين التفضيلات عند الحاجة." },
  { find: "Website Measurement", es: "Medición del sitio web", fr: "Mesure d'audience du site", de: "Website-Messung", ru: "Измерение посещаемости сайта", ar: "قياس الموقع الإلكتروني" },
  { find: "Website measurement records page visits, scroll milestones, general clicks, media interactions, form submission status, technical errors and performance metrics. It also records basic device, browser, referral and campaign information. It does not collect the values typed into form fields.", es: "La medición del sitio web registra las visitas a las páginas, los hitos de desplazamiento, los clics generales, las interacciones con contenido multimedia, el estado de envío de formularios, los errores técnicos y las métricas de rendimiento. También registra información básica sobre el dispositivo, el navegador, la referencia y la campaña. No recopila los valores escritos en los campos del formulario.", fr: "La mesure d'audience du site enregistre les visites de pages, les jalons de défilement, les clics généraux, les interactions avec les contenus multimédias, le statut d'envoi des formulaires, les erreurs techniques et les indicateurs de performance. Elle enregistre également des informations de base sur l'appareil, le navigateur, la provenance et la campagne. Elle ne collecte pas les valeurs saisies dans les champs du formulaire.", de: "Die Website-Messung erfasst Seitenaufrufe, Scroll-Meilensteine, allgemeine Klicks, Medieninteraktionen, den Status der Formularübermittlung, technische Fehler und Leistungskennzahlen. Sie erfasst außerdem grundlegende Geräte-, Browser-, Verweis- und Kampagneninformationen. Sie erfasst keine in Formularfelder eingegebenen Werte.", ru: "Измерение сайта фиксирует посещения страниц, этапы прокрутки, общие клики, взаимодействие с медиа, статус отправки форм, технические ошибки и показатели производительности. Также фиксируется базовая информация об устройстве, браузере, источнике перехода и кампании. Значения, введённые в поля формы, не собираются.", ar: "يسجّل قياس الموقع زيارات الصفحات، ومراحل التمرير، والنقرات العامة، والتفاعلات مع الوسائط، وحالة إرسال النماذج، والأخطاء التقنية، ومقاييس الأداء. كما يسجّل معلومات أساسية عن الجهاز والمتصفح والإحالة والحملة. ولا يجمع القيم المكتوبة في حقول النموذج." },
  { find: "Third-Party Services", es: "Servicios de terceros", fr: "Services tiers", de: "Dienste Dritter", ru: "Сторонние сервисы", ar: "خدمات الأطراف الثالثة" },
  { find: "The site may load maps, video embeds or form and CRM services from third-party providers. These providers may process technical data according to their own policies.", es: "El sitio puede cargar mapas, vídeos incrustados o servicios de formularios y CRM de proveedores externos. Estos proveedores pueden procesar datos técnicos conforme a sus propias políticas.", fr: "Le site peut charger des cartes, des vidéos intégrées ou des services de formulaires et de CRM provenant de prestataires tiers. Ces prestataires peuvent traiter des données techniques selon leurs propres politiques.", de: "Die Website kann Karten, eingebettete Videos oder Formular- und CRM-Dienste von Drittanbietern laden. Diese Anbieter können technische Daten gemäß ihren eigenen Richtlinien verarbeiten.", ru: "Сайт может загружать карты, встроенные видео или сервисы форм и CRM от сторонних поставщиков. Эти поставщики могут обрабатывать технические данные согласно своим собственным политикам.", ar: "قد يقوم الموقع بتحميل خرائط أو مقاطع فيديو مضمّنة أو خدمات نماذج وإدارة علاقات العملاء (CRM) من مزودين خارجيين. قد يقوم هؤلاء المزودون بمعالجة بيانات تقنية وفقًا لسياساتهم الخاصة." },
  { find: "Managing Preferences", es: "Gestión de preferencias", fr: "Gestion des préférences", de: "Einstellungen verwalten", ru: "Управление настройками", ar: "إدارة التفضيلات" },
  { find: "Visitors can remove website storage through browser settings and may contact contact@nuevaliving.com with a privacy request. Consent requirements for non-essential measurement should be reviewed for each market in which the website is offered.", es: "Los visitantes pueden eliminar el almacenamiento del sitio web a través de la configuración del navegador y pueden contactar con contact@nuevaliving.com para una solicitud relacionada con la privacidad. Los requisitos de consentimiento para la medición no esencial deben revisarse para cada mercado en el que se ofrezca el sitio web.", fr: "Les visiteurs peuvent supprimer le stockage du site via les paramètres de leur navigateur et peuvent contacter contact@nuevaliving.com pour toute demande relative à la confidentialité. Les exigences de consentement pour la mesure non essentielle doivent être examinées pour chaque marché dans lequel le site est proposé.", de: "Besucher können den Website-Speicher über die Browsereinstellungen entfernen und sich für eine Datenschutzanfrage an contact@nuevaliving.com wenden. Die Einwilligungsanforderungen für nicht wesentliche Messungen sollten für jeden Markt, in dem die Website angeboten wird, geprüft werden.", ru: "Посетители могут удалить хранилище сайта через настройки браузера и могут обратиться по адресу contact@nuevaliving.com с запросом, связанным с конфиденциальностью. Требования к согласию на необязательное измерение должны рассматриваться отдельно для каждого рынка, на котором предлагается сайт.", ar: "يمكن للزوار إزالة تخزين الموقع من خلال إعدادات المتصفح، ويمكنهم التواصل مع contact@nuevaliving.com لتقديم طلب متعلق بالخصوصية. ينبغي مراجعة متطلبات الموافقة على القياس غير الأساسي لكل سوق يُقدَّم فيه الموقع." },

  // ===== shared legalBody() boilerplate (used by all 3 legal pages) =====
  { find: "Important Information", es: "Información importante", fr: "Informations importantes", de: "Wichtige Informationen", ru: "Важная информация", ar: "معلومات مهمة" },
  { find: "This page explains the main terms in plain language. It should be reviewed by qualified legal counsel before any future material change.", es: "Esta página explica los términos principales en un lenguaje sencillo. Debe ser revisada por un asesor legal cualificado antes de cualquier cambio sustancial futuro.", fr: "Cette page explique les principaux termes en langage simple. Elle doit être revue par un conseiller juridique qualifié avant toute modification substantielle future.", de: "Diese Seite erläutert die wichtigsten Begriffe in verständlicher Sprache. Sie sollte vor jeder künftigen wesentlichen Änderung von einem qualifizierten Rechtsberater geprüft werden.", ru: "Эта страница разъясняет основные условия простым языком. Перед любым будущим существенным изменением её должен проверить квалифицированный юрист.", ar: "توضّح هذه الصفحة الشروط الرئيسية بلغة مبسطة. ينبغي مراجعتها من قبل مستشار قانوني مؤهل قبل إجراء أي تعديل جوهري مستقبلي." },
  { find: "Have a question about a project?", es: "¿Tiene alguna pregunta sobre un proyecto?", fr: "Une question sur un programme ?", de: "Haben Sie eine Frage zu einem Projekt?", ru: "Есть вопрос о проекте?", ar: "هل لديكم سؤال حول أحد المشاريع؟" },

  // ===== short, reused strings -- must stay last (see ordering note above) =====
  { find: "About", es: "Sobre Nosotros", fr: "À propos", de: "Über uns", ru: "О нас", ar: "من نحن" },
  { find: "Legal", es: "Legal", fr: "Mentions légales", de: "Rechtliches", ru: "Правовая информация", ar: "قانوني" },
  { find: "Contact Us", es: "Contáctenos", fr: "Contactez-nous", de: "Kontaktieren Sie uns", ru: "Свяжитесь с нами", ar: "تواصلوا معنا" },
];
