// Guide hub card titles and descriptions.
//
// Four of these cards carried a stale englishOnly flag and were hidden from
// every reader but the English one, so their copy had never needed
// translating. Removing the flag made them visible in all ten languages --
// still in English. This is the other half of that fix.
export const GUIDE_CARD_ENTRIES = [
  // Kort som var dolda bakom den inaktuella englishOnly-flaggan
  { find: 'Buying from Abroad', es: 'Comprar desde el extranjero', fr: 'Acheter depuis l’étranger', de: 'Kauf aus dem Ausland', ru: 'Покупка из-за рубежа', ar: 'الشراء من الخارج', nl: 'Kopen vanuit het buitenland', pl: 'Zakup z zagranicy', sv: 'Köpa från utlandet', no: 'Kjøpe fra utlandet' },
  { find: 'Bank Guarantees Explained', es: 'Las garantías bancarias, explicadas', fr: 'Les garanties bancaires expliquées', de: 'Bankbürgschaften erklärt', ru: 'Банковские гарантии простыми словами', ar: 'الضمانات المصرفية، بوضوح', nl: 'Bankgaranties uitgelegd', pl: 'Gwarancje bankowe wyjaśnione', sv: 'Bankgarantier förklarade', no: 'Bankgarantier forklart' },
  { find: 'Off-Plan Payment Schedules', es: 'Calendarios de pago sobre plano', fr: 'Échéanciers de paiement sur plan', de: 'Zahlungspläne beim Kauf vom Plan', ru: 'Графики платежей на стадии строительства', ar: 'جداول الدفع على المخطط', nl: 'Betaalschema’s bij kopen op plan', pl: 'Harmonogramy płatności na etapie budowy', sv: 'Betalningsplaner vid köp på ritning', no: 'Betalingsplaner ved kjøp på tegning' },
  { find: 'Warranties and Snagging', es: 'Garantías y repasos de entrega', fr: 'Garanties et réserves à la livraison', de: 'Gewährleistung und Mängelliste', ru: 'Гарантии и приёмка', ar: 'الضمانات وقائمة العيوب', nl: 'Garanties en opleverpunten', pl: 'Gwarancje i lista usterek', sv: 'Garantier och besiktning', no: 'Garantier og mangelliste' },
  { find: 'What a purchase actually needs you present for: when the NIE is required, what a power of attorney covers, and how the money reaches the developer.', es: 'Para qué hace falta estar presente de verdad: cuándo se necesita el NIE, qué cubre un poder notarial y cómo llega el dinero al promotor.', fr: 'Ce pour quoi votre présence est réellement nécessaire : quand le NIE est exigé, ce que couvre une procuration et comment l’argent parvient au promoteur.', de: 'Wofür Ihre Anwesenheit wirklich nötig ist: wann die NIE verlangt wird, was eine Vollmacht abdeckt und wie das Geld zum Bauträger gelangt.', ru: 'Для чего действительно нужно ваше присутствие: когда требуется NIE, что покрывает доверенность и как деньги доходят до застройщика.', ar: 'ما الذي يستدعي حضوركم فعلاً: متى يُطلب رقم NIE، وما الذي يغطيه التوكيل، وكيف يصل المال إلى المطوّر.', nl: 'Waarvoor uw aanwezigheid werkelijk nodig is: wanneer het NIE vereist is, wat een volmacht dekt en hoe het geld bij de ontwikkelaar komt.', pl: 'Do czego naprawdę potrzebna jest Państwa obecność: kiedy wymagany jest numer NIE, co obejmuje pełnomocnictwo i jak pieniądze trafiają do dewelopera.', sv: 'Vad ni faktiskt måste vara på plats för: när NIE krävs, vad en fullmakt täcker och hur pengarna når byggherren.', no: 'Hva dere faktisk må være til stede for: når NIE kreves, hva en fullmakt dekker, og hvordan pengene når utbyggeren.' },
  { find: 'What actually protects an off-plan deposit under Spanish law, and the point in the timeline at which the statutory guarantee has not started yet.', es: 'Qué protege realmente una entrega a cuenta sobre plano según la ley española, y el momento del proceso en que la garantía legal todavía no ha empezado.', fr: 'Ce qui protège réellement un acompte sur plan selon la loi espagnole, et le moment du parcours où la garantie légale n’a pas encore commencé.', de: 'Was eine Anzahlung beim Kauf vom Plan nach spanischem Recht tatsächlich schützt und der Punkt im Ablauf, an dem die gesetzliche Sicherung noch nicht greift.', ru: 'Что на самом деле защищает предоплату на стадии строительства по испанскому праву и момент, когда установленная законом гарантия ещё не действует.', ar: 'ما الذي يحمي فعلاً الدفعة المقدمة في الشراء على المخطط بموجب القانون الإسباني، واللحظة التي لا يكون فيها الضمان القانوني قد بدأ بعد.', nl: 'Wat een aanbetaling bij kopen op plan werkelijk beschermt volgens Spaans recht, en het moment in het traject waarop de wettelijke waarborg nog niet geldt.', pl: 'Co naprawdę chroni zaliczkę przy zakupie na etapie budowy według prawa hiszpańskiego i moment, w którym ustawowa gwarancja jeszcze nie obowiązuje.', sv: 'Vad som faktiskt skyddar en handpenning vid köp på ritning enligt spansk lag, och den punkt i förloppet där det lagstadgade skyddet ännu inte gäller.', no: 'Hva som faktisk beskytter et forskudd ved kjøp på tegning etter spansk lov, og punktet i forløpet der den lovbestemte garantien ennå ikke gjelder.' },
  { find: 'The staged payment structures the developers on this site have supplied in writing, from reservation through to the balance at deed.', es: 'Las estructuras de pago escalonado que los promotores de esta web han facilitado por escrito, desde la reserva hasta el resto en la escritura.', fr: 'Les échéanciers que les promoteurs présentés sur ce site ont fournis par écrit, de la réservation jusqu’au solde à l’acte.', de: 'Die gestaffelten Zahlungspläne, die die Bauträger auf dieser Website schriftlich vorgelegt haben — von der Reservierung bis zum Restbetrag bei der Beurkundung.', ru: 'Графики поэтапных платежей, которые застройщики с этого сайта предоставили в письменном виде — от бронирования до остатка при подписании купчей.', ar: 'هياكل الدفع على مراحل التي قدّمها مطوّرو هذا الموقع كتابةً، من الحجز حتى الرصيد عند التوثيق.', nl: 'De gefaseerde betaalstructuren die de ontwikkelaars op deze site schriftelijk hebben aangeleverd, van reservering tot het restant bij de akte.', pl: 'Struktury płatności etapowych, które deweloperzy z tej strony przekazali na piśmie — od rezerwacji po resztę przy akcie notarialnym.', sv: 'De betalningsplaner som byggherrarna på den här sajten lämnat skriftligt, från reservation till resten vid köpebrevet.', no: 'Betalingsplanene utbyggerne på dette nettstedet har levert skriftlig, fra reservasjon til resten ved skjøtet.' },
  { find: 'The ten, three and one-year guarantees on a Spanish new-build, who is liable under each, and why the handover inspection starts the clock.', es: 'Las garantías de diez, tres y un año en la obra nueva española, quién responde en cada una y por qué la inspección de entrega pone el reloj en marcha.', fr: 'Les garanties de dix, trois et un an sur un logement neuf en Espagne, qui répond de quoi, et pourquoi la visite de livraison déclenche les délais.', de: 'Die Zehn-, Drei- und Einjahresgarantie beim spanischen Neubau, wer jeweils haftet und warum die Übergabeprüfung die Fristen in Gang setzt.', ru: 'Десяти-, трёх- и однолетняя гарантии на испанскую новостройку, кто отвечает по каждой и почему приёмка запускает отсчёт.', ar: 'ضمانات العشر سنوات والثلاث والسنة على البناء الجديد في إسبانيا، ومن المسؤول عن كل منها، ولماذا تبدأ معاينة التسلّم العدّ.', nl: 'De tien-, drie- en eenjaarsgaranties op Spaanse nieuwbouw, wie waarvoor aansprakelijk is, en waarom de oplevering de termijnen laat lopen.', pl: 'Gwarancje dziesięcio-, trzy- i jednoroczna na hiszpański nowy lokal, kto odpowiada w każdej z nich i dlaczego odbiór uruchamia bieg terminów.', sv: 'Tio-, tre- och ettårsgarantierna på spansk nyproduktion, vem som ansvarar för vad, och varför slutbesiktningen startar fristerna.', no: 'Ti-, tre- og ettårsgarantiene på spansk nybygg, hvem som er ansvarlig for hva, og hvorfor overtakelsesbefaringen starter fristene.' },
];
