// Translations for project `images.{hero,architecture,lifestyle,privateViewing}.alt`.
// These are the four large section images on each property page. They are a
// separate field group from `media.items[].alt` (the gallery), and were the
// last untranslated strings in the project data.
//
// alt text is not visible to sighted users, but it is what screen-reader
// users hear and what image search indexes -- so it belongs in the reader's
// own language, not English.
//
// Shape: { <slug>: { <imageKey>: { es, fr, de, ru, ar } } }
export const IMAGE_ALTS = {
  'alisios-residences': {
    hero: { es: 'Vista aérea de Alisios Residences enmarcada por el campo de golf de Guadalmina y el Mediterráneo', fr: 'Vue aérienne d’Alisios Residences encadrée par le golf de Guadalmina et la Méditerranée', de: 'Luftaufnahme von Alisios Residences, eingerahmt vom Golfplatz Guadalmina und dem Mittelmeer', ru: 'Вид с воздуха на Alisios Residences в обрамлении гольф-поля Guadalmina и Средиземного моря', ar: 'منظر جوي لمشروع Alisios Residences يحيط به ملعب غولف Guadalmina والبحر المتوسط', nl: 'Luchtfoto van Alisios Residences, omlijst door de golfbaan van Guadalmina en de Middellandse Zee', pl: 'Widok z lotu ptaka na Alisios Residences w otoczeniu pola golfowego Guadalmina i Morza Śródziemnego', sv: 'Flygbild över Alisios Residences, inramad av golfbanan i Guadalmina och Medelhavet', no: 'Luftfoto av Alisios Residences, innrammet av golfbanen i Guadalmina og Middelhavet' },
    architecture: { es: 'Vista al atardecer de la fachada contemporánea, los balcones y los jardines de Alisios Residences', fr: 'Vue au crépuscule de la façade contemporaine, des balcons et des jardins paysagers d’Alisios Residences', de: 'Dämmerungsansicht der zeitgenössischen Fassade, Balkone und Gartenanlagen von Alisios Residences', ru: 'Вид в сумерках на современный фасад, балконы и ландшафтные сады Alisios Residences', ar: 'منظر عند الغروب للواجهة المعاصرة والشرفات والحدائق المنسقة في Alisios Residences', nl: 'Avondzicht op de eigentijdse gevel, balkons en tuinen van Alisios Residences', pl: 'Widok o zmierzchu na współczesną fasadę, balkony i ogrody Alisios Residences', sv: 'Vy i skymningen över den moderna fasaden, balkongerna och trädgårdarna på Alisios Residences', no: 'Kveldsutsikt over den moderne fasaden, balkongene og hagene til Alisios Residences' },
    lifestyle: { es: 'Salón en terraza de azotea con vistas al campo de golf y al mar a lo lejos', fr: 'Salon de terrasse sur le toit donnant sur le golf avec la mer au loin', de: 'Dachterrassen-Lounge mit Blick über den Golfplatz und das Meer in der Ferne', ru: 'Лаундж на террасе крыши с видом на гольф-поле и море вдали', ar: 'صالة على تراس السطح تطل على ملعب الغولف والبحر في البعيد', nl: 'Loungehoek op het dakterras met uitzicht op de golfbaan en de zee in de verte', pl: 'Strefa wypoczynkowa na tarasie na dachu z widokiem na pole golfowe i morze w oddali', sv: 'Loungeyta på takterrassen med utsikt över golfbanan och havet i fjärran', no: 'Loungeområde på takterrassen med utsikt over golfbanen og havet i det fjerne' },
    privateViewing: { es: 'Salón en terraza de azotea con vistas sobre Guadalmina hacia el mar', fr: 'Salon de terrasse sur le toit avec vue sur Guadalmina en direction de la mer', de: 'Dachterrassen-Lounge mit Blick über Guadalmina zum Meer', ru: 'Лаундж на террасе крыши с видом на Гуадальмину в сторону моря', ar: 'صالة على تراس السطح بإطلالة على Guadalmina باتجاه البحر', nl: 'Loungehoek op het dakterras met uitzicht over Guadalmina richting zee', pl: 'Strefa wypoczynkowa na tarasie na dachu z widokiem na Guadalminę w stronę morza', sv: 'Loungeyta på takterrassen med utsikt över Guadalmina mot havet', no: 'Loungeområde på takterrassen med utsikt over Guadalmina mot havet' }
  },
  'altos-de-marbella': {
    hero: { es: 'Vista aérea al atardecer de Altos de Marbella Residences y su terraza con piscina', fr: 'Vue aérienne au crépuscule d’Altos de Marbella Residences et de sa terrasse-piscine', de: 'Luftaufnahme von Altos de Marbella Residences und der Poolterrasse in der Dämmerung', ru: 'Вид с воздуха в сумерках на Altos de Marbella Residences и террасу с бассейном', ar: 'منظر جوي عند الغروب لمشروع Altos de Marbella Residences وتراس المسبح', nl: 'Luchtfoto bij zonsondergang van Altos de Marbella Residences en het zwembadterras', pl: 'Widok z lotu ptaka o zachodzie słońca na Altos de Marbella Residences i taras z basenem', sv: 'Flygbild i solnedgången över Altos de Marbella Residences och poolterrassen', no: 'Luftfoto i solnedgangen av Altos de Marbella Residences og bassengterrassen' },
    architecture: { es: 'Vivienda diáfana que conecta el salón, la terraza y la piscina privada', fr: 'Logement ouvert reliant le séjour, la terrasse et la piscine privée', de: 'Offene Wohnung, die Wohnbereich, Terrasse und Privatpool verbindet', ru: 'Резиденция открытой планировки, объединяющая гостиную, террасу и частный бассейн', ar: 'مسكن مفتوح يربط بين غرفة المعيشة والتراس والمسبح الخاص', nl: 'Open woning die de woonkamer, het terras en het privézwembad met elkaar verbindt', pl: 'Otwarta przestrzeń mieszkalna łącząca salon, taras i prywatny basen', sv: 'Öppet boende som förenar vardagsrummet, terrassen och den privata poolen', no: 'Åpen bolig som knytter sammen stuen, terrassen og det private bassenget' },
    lifestyle: { es: 'Terraza elevada y césped con vistas al litoral hacia Marbella', fr: 'Terrasse surélevée et pelouse dominant le littoral vers Marbella', de: 'Erhöhte Terrasse und Rasenfläche mit Blick auf die Küste Richtung Marbella', ru: 'Приподнятая терраса и газон с видом на побережье в сторону Марбельи', ar: 'تراس مرتفع ومساحة عشبية تطل على الساحل باتجاه ماربيا', nl: 'Verhoogd terras en gazon met uitzicht op de kustlijn richting Marbella', pl: 'Podniesiony taras i trawnik z widokiem na wybrzeże w kierunku Marbelli', sv: 'Upphöjd terrass och gräsmatta med utsikt över kustlinjen mot Marbella', no: 'Hevet terrasse og plen med utsikt over kystlinjen mot Marbella' },
    privateViewing: { es: 'Terraza con piscina privada al atardecer con vistas al litoral', fr: 'Terrasse avec piscine privée au coucher du soleil avec vue sur le littoral', de: 'Private Poolterrasse bei Sonnenuntergang mit Küstenblick', ru: 'Терраса с частным бассейном на закате с видом на побережье', ar: 'تراس بمسبح خاص عند الغروب بإطلالة ساحلية', nl: 'Terras met privézwembad bij zonsondergang met uitzicht op de kustlijn', pl: 'Taras z prywatnym basenem o zachodzie słońca z widokiem na wybrzeże', sv: 'Terrass med privat pool i solnedgången med utsikt över kustlinjen', no: 'Terrasse med privat basseng i solnedgangen med utsikt over kystlinjen' }
  },
  'cancelada-park': {
    hero: { es: 'Imagen aérea del promotor de Cancelada Park y su entorno residencial ajardinado', fr: 'Visuel aérien du promoteur de Cancelada Park et de son cadre résidentiel paysager', de: 'Luftbild-Visualisierung des Bauträgers von Cancelada Park und seiner begrünten Wohnanlage', ru: 'Аэровизуализация застройщика Cancelada Park и его озеленённого жилого окружения', ar: 'تصور جوي من المطور لمشروع Cancelada Park ومحيطه السكني المنسق', nl: 'Luchtbeeld van de ontwikkelaar van Cancelada Park en de aangelegde woonomgeving', pl: 'Wizualizacja dewelopera z lotu ptaka przedstawiająca Cancelada Park i jego zagospodarowane otoczenie mieszkalne', sv: 'Utvecklarens flygbild av Cancelada Park och den anlagda bostadsmiljön', no: 'Utviklerens luftbilde av Cancelada Park og det opparbeidede boligmiljøet' },
    architecture: { es: 'Imagen del promotor de la arquitectura de baja altura y las terrazas ajardinadas de Cancelada Park', fr: 'Visuel du promoteur de l’architecture basse et des terrasses paysagées de Cancelada Park', de: 'Bauträger-Visualisierung der niedriggeschossigen Architektur und begrünten Terrassen von Cancelada Park', ru: 'Визуализация застройщика: малоэтажная архитектура и озеленённые террасы Cancelada Park', ar: 'تصور من المطور للعمارة المنخفضة والتراسات المنسقة في Cancelada Park', nl: 'Beeld van de ontwikkelaar van de laagbouwarchitectuur en de begroeide terrassen van Cancelada Park', pl: 'Wizualizacja dewelopera przedstawiająca niską zabudowę i zazielenione tarasy Cancelada Park', sv: 'Utvecklarbild av lågbebyggelsen och de gröna terrasserna på Cancelada Park', no: 'Utviklerbilde av den lave arkitekturen og de grønne terrassene til Cancelada Park' },
    lifestyle: { es: 'Terraza con jardín privado y zona de estar detrás de una villa residencial', fr: 'Terrasse-jardin privée et salon à l’arrière d’une villa résidentielle', de: 'Private Gartenterrasse und Lounge hinter einer Wohnvilla', ru: 'Приватная садовая терраса и зона отдыха позади жилой виллы', ar: 'تراس بحديقة خاصة ومنطقة جلوس خلف فيلا سكنية', nl: 'Terras met privétuin en zitgedeelte achter een woonvilla', pl: 'Taras z prywatnym ogrodem i strefą wypoczynkową za willą mieszkalną', sv: 'Terrass med privat trädgård och sittyta bakom en bostadsvilla', no: 'Terrasse med privat hage og sittegruppe bak en boligvilla' },
    privateViewing: { es: 'Imagen nocturna del promotor de la piscina y las viviendas de Cancelada Park', fr: 'Visuel nocturne du promoteur de la piscine et des résidences de Cancelada Park', de: 'Abendliche Bauträger-Visualisierung von Pool und Residenzen in Cancelada Park', ru: 'Вечерняя визуализация застройщика: бассейн и резиденции Cancelada Park', ar: 'تصور مسائي من المطور للمسبح والمساكن في Cancelada Park', nl: 'Nachtbeeld van de ontwikkelaar van het zwembad en de woningen van Cancelada Park', pl: 'Nocna wizualizacja dewelopera przedstawiająca basen i domy w Cancelada Park', sv: 'Utvecklarens nattbild av poolen och bostäderna på Cancelada Park', no: 'Utviklerens nattbilde av bassenget og boligene i Cancelada Park' }
  },
  'elviria-hills-residences': {
    hero: { es: 'Edificio residencial contemporáneo curvo con terrazas ajardinadas en Elviria Hills Residences', fr: 'Bâtiment résidentiel contemporain aux formes courbes avec terrasses végétalisées à Elviria Hills Residences', de: 'Geschwungenes zeitgenössisches Wohngebäude mit bepflanzten Terrassen in Elviria Hills Residences', ru: 'Изогнутое современное жилое здание с озеленёнными террасами в Elviria Hills Residences', ar: 'مبنى سكني معاصر منحني بتراسات مزروعة في Elviria Hills Residences', nl: 'Golvend eigentijds woongebouw met begroeide terrassen bij Elviria Hills Residences', pl: 'Współczesny, łukowaty budynek mieszkalny z zazielenionymi tarasami w Elviria Hills Residences', sv: 'Böljande modernt bostadshus med gröna terrasser vid Elviria Hills Residences', no: 'Buet moderne boligbygg med grønne terrasser ved Elviria Hills Residences' },
    architecture: { es: 'Edificios residenciales escalonados en torno a la piscina comunitaria y los jardines', fr: 'Bâtiments résidentiels étagés autour de la piscine commune et des jardins paysagers', de: 'Terrassenförmig um den Gemeinschaftspool und die Gartenanlagen angeordnete Wohngebäude', ru: 'Жилые корпуса, террасами расположенные вокруг общего бассейна и садов', ar: 'مبانٍ سكنية متدرجة حول المسبح المشترك والحدائق المنسقة', nl: 'Trapsgewijs opgebouwde woongebouwen rond het gemeenschappelijke zwembad en de tuinen', pl: 'Tarasowo ułożone budynki mieszkalne wokół wspólnego basenu i ogrodów', sv: 'Terrasserade bostadshus kring den gemensamma poolen och trädgårdarna', no: 'Terrasserte boligbygg rundt fellesbassenget og hagene' },
    lifestyle: { es: 'Piscina de spa interior con sauna y zona de descanso', fr: 'Piscine de spa intérieure avec sauna et espace détente', de: 'Innen-Spa-Pool mit Sauna und Loungebereich', ru: 'Крытый спа-бассейн с сауной и зоной отдыха', ar: 'مسبح سبا داخلي مع ساونا ومنطقة استرخاء', nl: 'Binnenspabad met sauna en rustzone', pl: 'Wewnętrzny basen spa z sauną i strefą relaksu', sv: 'Inomhusspa med pool, bastu och avkopplingsyta', no: 'Innendørs spabasseng med badstue og hvileområde' },
    privateViewing: { es: 'Dormitorio del piso piloto con salida a la terraza y vistas al jardín', fr: 'Chambre de l’appartement témoin avec accès à la terrasse et vue sur le jardin', de: 'Schlafzimmer der Musterwohnung mit Terrassenzugang und Gartenblick', ru: 'Спальня шоу-апартаментов с выходом на террасу и видом на сад', ar: 'غرفة نوم الشقة النموذجية مع منفذ إلى التراس وإطلالة على الحديقة', nl: 'Slaapkamer van de modelwoning met toegang tot het terras en uitzicht op de tuin', pl: 'Sypialnia w mieszkaniu pokazowym z wyjściem na taras i widokiem na ogród', sv: 'Sovrum i visningslägenheten med utgång till terrassen och utsikt över trädgården', no: 'Soverom i visningsleiligheten med utgang til terrassen og utsikt over hagen' }
  },
  'golden-mile-duplex-residences': {
    hero: { es: 'Vivienda dúplex con jardín, piscina privada y exuberante vegetación', fr: 'Duplex avec jardin, piscine privée et végétation luxuriante', de: 'Garten-Duplex mit privatem Pool und üppiger Bepflanzung', ru: 'Дуплекс с садом, частным бассейном и пышной зеленью', ar: 'دوبلكس بحديقة ومسبح خاص ومساحات خضراء وارفة', nl: 'Duplexwoning met tuin, privézwembad en weelderig groen', pl: 'Dom typu duplex z ogrodem, prywatnym basenem i bujną zielenią', sv: 'Duplexbostad med trädgård, privat pool och frodig grönska', no: 'Duplexbolig med hage, privat basseng og frodig grønt' },
    architecture: { es: 'Piscina infinita en azotea con vistas al Mediterráneo al atardecer', fr: 'Piscine à débordement sur le toit surplombant la Méditerranée au crépuscule', de: 'Infinity-Dachpool mit Blick auf das Mittelmeer in der Dämmerung', ru: 'Бассейн-инфинити на крыше с видом на Средиземное море в сумерках', ar: 'مسبح لامتناهٍ على السطح يطل على البحر المتوسط عند الغروب', nl: 'Infinity pool op het dak met uitzicht op de Middellandse Zee bij zonsondergang', pl: 'Basen typu infinity na dachu z widokiem na Morze Śródziemne o zachodzie słońca', sv: 'Infinitypool på taket med utsikt över Medelhavet i solnedgången', no: 'Infinitybasseng på taket med utsikt over Middelhavet i solnedgangen' },
    lifestyle: { es: 'Piscina infinita en azotea al atardecer con vistas al mar', fr: 'Piscine à débordement sur le toit au crépuscule avec vue mer', de: 'Infinity-Dachpool in der Dämmerung mit Meerblick', ru: 'Бассейн-инфинити на крыше в сумерках с видом на море', ar: 'مسبح لامتناهٍ على السطح عند الغروب بإطلالة بحرية', nl: 'Infinity pool op het dak bij zonsondergang met zeezicht', pl: 'Basen typu infinity na dachu o zachodzie słońca z widokiem na morze', sv: 'Infinitypool på taket i solnedgången med havsutsikt', no: 'Infinitybasseng på taket i solnedgangen med sjøutsikt' },
    privateViewing: { es: 'Salón amueblado por un estudio de diseño con obra de arte protagonista', fr: 'Séjour meublé par un studio de design avec œuvre d’art maîtresse', de: 'Von einem Designstudio möbliertes Wohnzimmer mit markantem Kunstwerk', ru: 'Гостиная с дизайнерской меблировкой и акцентным произведением искусства', ar: 'غرفة معيشة مؤثثة بتصميم راقٍ مع عمل فني بارز', nl: 'Door een designstudio ingerichte woonkamer met een opvallend kunstwerk als blikvanger', pl: 'Salon urządzony przez studio designu z eksponowanym dziełem sztuki', sv: 'Vardagsrum inrett av en designstudio med ett framträdande konstverk', no: 'Stue innredet av et designstudio med et fremtredende kunstverk' }
  },
  'golf-valley-flex-residences': {
    hero: { es: 'Viviendas contemporáneas con piscinas privadas al atardecer', fr: 'Résidences contemporaines avec piscines privées au coucher du soleil', de: 'Zeitgenössische Residenzen mit privaten Pools bei Sonnenuntergang', ru: 'Современные резиденции с частными бассейнами на закате', ar: 'مساكن معاصرة بمسابح خاصة عند الغروب', nl: 'Eigentijdse woningen met privézwembaden bij zonsondergang', pl: 'Nowoczesne domy z prywatnymi basenami o zachodzie słońca', sv: 'Moderna bostäder med privata pooler i solnedgången', no: 'Moderne boliger med private basseng i solnedgangen' },
    architecture: { es: 'Vista frontal de las viviendas con piscinas privadas y jardines', fr: 'Vue frontale des résidences avec piscines privées et jardins', de: 'Frontansicht der Residenzen mit privaten Pools und Gärten', ru: 'Вид спереди на резиденции с частными бассейнами и садами', ar: 'منظر أمامي للمساكن بمسابح خاصة وحدائق', nl: 'Vooraanzicht van de woningen met privézwembaden en tuinen', pl: 'Widok z przodu na domy z prywatnymi basenami i ogrodami', sv: 'Vy framifrån över bostäderna med privata pooler och trädgårdar', no: 'Frontutsikt over boligene med private basseng og hager' },
    lifestyle: { es: 'Piscina de spa interior abierta a un patio ajardinado', fr: 'Piscine de spa intérieure ouvrant sur une cour paysagée', de: 'Innen-Spa-Pool mit Zugang zu einem begrünten Innenhof', ru: 'Крытый спа-бассейн с выходом в озеленённый внутренний двор', ar: 'مسبح سبا داخلي يطل على فناء منسق', nl: 'Binnenspabad met toegang tot een aangelegde patio', pl: 'Wewnętrzny basen spa otwarty na zagospodarowany patio', sv: 'Inomhusspa med pool som öppnar sig mot en anlagd innergård', no: 'Innendørs spabasseng som åpner seg mot en opparbeidet patio' },
    privateViewing: { es: 'Salón con vistas al mar a través de acristalamiento de suelo a techo', fr: 'Séjour avec vue mer à travers des baies vitrées toute hauteur', de: 'Wohnzimmer mit Meerblick durch raumhohe Verglasung', ru: 'Гостиная с видом на море через панорамное остекление', ar: 'غرفة معيشة بإطلالة بحرية عبر زجاج ممتد من الأرض حتى السقف', nl: 'Woonkamer met zeezicht door glaswanden van vloer tot plafond', pl: 'Salon z widokiem na morze przez przeszklenia od podłogi do sufitu', sv: 'Vardagsrum med havsutsikt genom golv-till-tak-fönster', no: 'Stue med sjøutsikt gjennom vindusfelt fra gulv til tak' }
  },
  'jardin-del-mar-residences': {
    hero: { es: 'Render exterior de Jardin del Mar Residences con terraza de piscina bordeada de palmeras', fr: 'Rendu extérieur de Jardin del Mar Residences avec terrasse-piscine bordée de palmiers', de: 'Außenvisualisierung von Jardin del Mar Residences mit palmengesäumter Poolterrasse', ru: 'Внешняя визуализация Jardin del Mar Residences с террасой у бассейна в окружении пальм', ar: 'تصور خارجي لمشروع Jardin del Mar Residences مع تراس مسبح تحيط به النخيل', nl: 'Exterieurrender van Jardin del Mar Residences met een door palmbomen omzoomd zwembadterras', pl: 'Wizualizacja zewnętrzna Jardin del Mar Residences z tarasem basenowym otoczonym palmami', sv: 'Exteriörrendering av Jardin del Mar Residences med en palmkantad poolterrass', no: 'Eksteriørrendering av Jardin del Mar Residences med en palmekledd bassengterrasse' },
    architecture: { es: 'Fachada del patio del edificio con pérgola y paseo ajardinado', fr: 'Façade sur cour du bâtiment avec pergola et allée paysagée', de: 'Innenhoffassade des Gebäudes mit Pergola und begrüntem Weg', ru: 'Фасад внутреннего двора здания с перголой и озеленённой дорожкой', ar: 'واجهة فناء المبنى مع بيرغولا وممشى منسق', nl: 'Patiogevel van het gebouw met pergola en aangelegde wandelpad', pl: 'Fasada patio budynku z pergolą i zagospodarowaną alejką', sv: 'Innergårdsfasad på byggnaden med pergola och anlagd gångväg', no: 'Patiofasaden til bygget med pergola og opparbeidet gangvei' },
    lifestyle: { es: 'Piscina de spa interior privada dentro del recinto cerrado', fr: 'Piscine de spa intérieure privée au sein de la résidence sécurisée', de: 'Privater Innen-Spa-Pool innerhalb der geschlossenen Anlage', ru: 'Частный крытый спа-бассейн на закрытой территории', ar: 'مسبح سبا داخلي خاص ضمن المجمع المسور', nl: 'Privé binnenspabad binnen het afgesloten complex', pl: 'Prywatny wewnętrzny basen spa na terenie zamkniętego kompleksu', sv: 'Privat inomhusspa med pool inom det inhägnade området', no: 'Privat innendørs spabasseng innenfor det inngjerdede anlegget' },
    privateViewing: { es: 'Salón del piso piloto con estantería separadora de ambientes y mobiliario en tonos neutros', fr: 'Séjour de l’appartement témoin avec étagère cloison et mobilier aux tons neutres', de: 'Wohnzimmer der Musterwohnung mit Raumteiler-Regal und Möbeln in Naturtönen', ru: 'Гостиная шоу-апартаментов со стеллажом-перегородкой и мебелью нейтральных тонов', ar: 'غرفة معيشة الشقة النموذجية مع رفوف فاصلة وأثاث بألوان محايدة', nl: 'Woonkamer van de modelwoning met een ruimteverdelende boekenkast en meubilair in neutrale tinten', pl: 'Salon w mieszkaniu pokazowym z regałem dzielącym przestrzeń i meblami w neutralnych odcieniach', sv: 'Vardagsrum i visningslägenheten med en rumsavdelande hylla och möbler i neutrala toner', no: 'Stue i visningsleiligheten med en romdelende reol og møbler i nøytrale toner' }
  },
  'los-olivos-residences': {
    hero: { es: 'Vista aérea de Los Olivos Residences en construcción en el Valle del Golf de Marbella, con el litoral al fondo', fr: 'Vue aérienne de Los Olivos Residences en construction dans la Golf Valley de Marbella, avec le littoral en arrière-plan', de: 'Luftaufnahme von Los Olivos Residences im Bau im Golf Valley von Marbella mit der Küste im Hintergrund', ru: 'Вид с воздуха на строящийся Los Olivos Residences в Гольф-Вэлли Марбельи с побережьем на заднем плане', ar: 'منظر جوي لمشروع Los Olivos Residences قيد الإنشاء في وادي الغولف بماربيا مع الساحل في الخلفية', nl: 'Luchtfoto van Los Olivos Residences in aanbouw in de Golf Valley van Marbella, met de kustlijn op de achtergrond', pl: 'Widok z lotu ptaka na budowę Los Olivos Residences w Golf Valley w Marbelli, z linią brzegową w tle', sv: 'Flygbild av Los Olivos Residences under uppförande i Marbellas Golf Valley, med kustlinjen i bakgrunden', no: 'Luftfoto av Los Olivos Residences under bygging i Golf Valley i Marbella, med kystlinjen i bakgrunnen' },
    architecture: { es: 'Terraza privada con zona de estar y vistas despejadas a la montaña', fr: 'Terrasse privée avec coin salon et vues dégagées sur la montagne', de: 'Private Terrasse mit Sitzbereich und freiem Bergblick', ru: 'Приватная терраса с зоной отдыха и открытым видом на горы', ar: 'تراس خاص مع منطقة جلوس وإطلالات جبلية مفتوحة', nl: 'Privéterras met zitgedeelte en vrij uitzicht op de bergen', pl: 'Prywatny taras ze strefą wypoczynkową i rozległym widokiem na góry', sv: 'Privat terrass med sittyta och fri utsikt över bergen', no: 'Privat terrasse med sittegruppe og fri utsikt til fjellet' },
    lifestyle: { es: 'Mesa de comedor en la terraza con vistas a la montaña de La Concha', fr: 'Table de repas en terrasse avec vue sur la montagne La Concha', de: 'Esstisch auf der Terrasse mit Blick auf den Berg La Concha', ru: 'Обеденный стол на террасе с видом на гору Ла-Конча', ar: 'طاولة طعام على التراس بإطلالة على جبل لا كونتشا', nl: 'Eettafel op het terras met uitzicht op de berg La Concha', pl: 'Stół jadalny na tarasie z widokiem na górę La Concha', sv: 'Matbord på terrassen med utsikt över berget La Concha', no: 'Spisebord på terrassen med utsikt til fjellet La Concha' },
    privateViewing: { es: 'Salón del piso piloto con panelado de madera y mobiliario en tonos neutros', fr: 'Séjour de l’appartement témoin avec mur média en bois et mobilier aux tons neutres', de: 'Wohnzimmer der Musterwohnung mit holzvertäfelter Medienwand und Möbeln in Naturtönen', ru: 'Гостиная шоу-апартаментов с деревянной ТВ-стеной и мебелью нейтральных тонов', ar: 'غرفة معيشة الشقة النموذجية بجدار خشبي وأثاث بألوان محايدة', nl: 'Woonkamer van de modelwoning met houten wandpanelen en meubilair in neutrale tinten', pl: 'Salon w mieszkaniu pokazowym z drewnianą boazerią i meblami w neutralnych odcieniach', sv: 'Vardagsrum i visningslägenheten med träpanelklädd vägg och möbler i neutrala toner', no: 'Stue i visningsleiligheten med trepanel og møbler i nøytrale toner' }
  },
  'marbella-west-garden-residences': {
    hero: { es: 'Patio ajardinado y piscina exterior de Marbella West Garden Residences', fr: 'Cour paysagée et piscine extérieure de Marbella West Garden Residences', de: 'Begrünter Innenhof und Außenpool von Marbella West Garden Residences', ru: 'Озеленённый внутренний двор и открытый бассейн Marbella West Garden Residences', ar: 'الفناء المنسق والمسبح الخارجي في Marbella West Garden Residences', nl: 'Aangelegde patio en buitenzwembad van Marbella West Garden Residences', pl: 'Zagospodarowane patio i basen zewnętrzny w Marbella West Garden Residences', sv: 'Anlagd innergård och utomhuspool på Marbella West Garden Residences', no: 'Opparbeidet patio og utendørsbasseng ved Marbella West Garden Residences' },
    architecture: { es: 'Terrazas curvas, piscinas privadas y vegetación mediterránea en Marbella West Garden Residences', fr: 'Terrasses courbes, piscines privées et végétation méditerranéenne à Marbella West Garden Residences', de: 'Geschwungene Terrassen, private Pools und mediterrane Bepflanzung in Marbella West Garden Residences', ru: 'Изогнутые террасы, частные бассейны и средиземноморское озеленение в Marbella West Garden Residences', ar: 'تراسات منحنية ومسابح خاصة ونباتات متوسطية في Marbella West Garden Residences', nl: 'Golvende terrassen, privézwembaden en mediterrane beplanting bij Marbella West Garden Residences', pl: 'Łukowate tarasy, prywatne baseny i śródziemnomorska roślinność w Marbella West Garden Residences', sv: 'Böljande terrasser, privata pooler och medelhavsvegetation på Marbella West Garden Residences', no: 'Buede terrasser, private basseng og middelhavsvegetasjon ved Marbella West Garden Residences' },
    lifestyle: { es: 'Plataforma de yoga en la azotea al atardecer con vistas a la montaña', fr: 'Plateforme de yoga sur le toit au coucher du soleil avec vue sur la montagne', de: 'Yoga-Deck auf dem Dach bei Sonnenuntergang mit Bergblick', ru: 'Площадка для йоги на крыше на закате с видом на горы', ar: 'منصة يوغا على السطح عند الغروب بإطلالة جبلية', nl: 'Yogaplatform op het dak bij zonsondergang met uitzicht op de bergen', pl: 'Platforma do jogi na dachu o zachodzie słońca z widokiem na góry', sv: 'Yogadäck på taket i solnedgången med bergsutsikt', no: 'Yogaplattform på taket i solnedgangen med utsikt til fjellet' },
    privateViewing: { es: 'Piscina de agua salada con vistas al mar en Marbella West Garden Residences', fr: 'Piscine d’eau salée avec vue mer à Marbella West Garden Residences', de: 'Salzwasserpool mit Meerblick in Marbella West Garden Residences', ru: 'Бассейн с солёной водой и видом на море в Marbella West Garden Residences', ar: 'مسبح بمياه مالحة بإطلالة بحرية في Marbella West Garden Residences', nl: 'Zoutwaterzwembad met zeezicht bij Marbella West Garden Residences', pl: 'Basen z wodą słoną z widokiem na morze w Marbella West Garden Residences', sv: 'Saltvattenpool med havsutsikt på Marbella West Garden Residences', no: 'Saltvannsbasseng med sjøutsikt ved Marbella West Garden Residences' }
  },
  'nueva-alcantara-residences': {
    hero: { es: 'Vista en esquina de un edificio residencial contemporáneo con locales a pie de calle y terrazas ajardinadas', fr: 'Vue d’angle d’un immeuble résidentiel contemporain avec commerces en rez-de-chaussée et terrasses végétalisées', de: 'Eckansicht eines zeitgenössischen Wohngebäudes mit Ladengeschäften im Erdgeschoss und bepflanzten Terrassen', ru: 'Угловой вид современного жилого здания с магазинами на первом этаже и озеленёнными террасами', ar: 'منظر زاوية لمبنى سكني معاصر مع محلات على مستوى الشارع وتراسات مزروعة', nl: 'Hoekaanzicht van een eigentijds woongebouw met winkels op straatniveau en begroeide terrassen', pl: 'Widok narożny współczesnego budynku mieszkalnego z lokalami na poziomie ulicy i zazielenionymi tarasami', sv: 'Hörnvy över ett modernt bostadshus med butikslokaler i gatuplan och gröna terrasser', no: 'Hjørneutsikt over et moderne boligbygg med butikklokaler i gateplan og grønne terrasser' },
    architecture: { es: 'Fachada posterior de las viviendas a lo largo de una calle peatonal ajardinada', fr: 'Façade arrière des résidences le long d’une rue piétonne paysagée', de: 'Rückfassade der Residenzen entlang einer begrünten Fußgängerstraße', ru: 'Задний фасад резиденций вдоль озеленённой пешеходной улицы', ar: 'الواجهة الخلفية للمساكن على امتداد شارع مشاة منسق', nl: 'Achtergevel van de woningen langs een aangelegde voetgangersstraat', pl: 'Tylna fasada budynków wzdłuż zagospodarowanej ulicy pieszej', sv: 'Bakre fasad på bostäderna längs en anlagd gågata', no: 'Bakre fasade på boligene langs en opparbeidet gågate' },
    lifestyle: { es: 'Piscina en azotea con vistas a la montaña', fr: 'Piscine sur le toit avec vue sur la montagne', de: 'Dachpool mit Bergblick', ru: 'Бассейн на крыше с видом на горы', ar: 'مسبح على السطح بإطلالة جبلية', nl: 'Dakzwembad met uitzicht op de bergen', pl: 'Basen na dachu z widokiem na góry', sv: 'Takpool med bergsutsikt', no: 'Takbasseng med utsikt til fjellet' },
    privateViewing: { es: 'Salón y comedor del piso piloto con luz natural', fr: 'Séjour et espace repas de l’appartement témoin baignés de lumière naturelle', de: 'Wohn- und Essbereich der Musterwohnung mit natürlichem Licht', ru: 'Гостиная-столовая шоу-апартаментов с естественным светом', ar: 'غرفة معيشة وطعام الشقة النموذجية بإضاءة طبيعية', nl: 'Woon- en eetkamer van de modelwoning met natuurlijk licht', pl: 'Salon i jadalnia w mieszkaniu pokazowym doświetlone naturalnym światłem', sv: 'Vardags- och matrum i visningslägenheten med naturligt ljus', no: 'Stue og spisestue i visningsleiligheten med naturlig lys' }
  },
  'nueva-andalucia-villa-collection': {
    hero: { es: 'Villa contemporánea con piscina infinita en cascada y exuberante vegetación', fr: 'Villa contemporaine avec piscine à débordement en cascade et végétation luxuriante', de: 'Zeitgenössische Villa mit kaskadierendem Infinity-Pool und üppiger Bepflanzung', ru: 'Современная вилла с каскадным бассейном-инфинити и пышной зеленью', ar: 'فيلا معاصرة بمسبح لامتناهٍ متدرج ومساحات خضراء وارفة', nl: 'Eigentijdse villa met een trapsgewijze infinity pool en weelderig groen', pl: 'Nowoczesna willa z kaskadowym basenem typu infinity i bujną zielenią', sv: 'Modern villa med kaskaderande infinitypool och frodig grönska', no: 'Moderne villa med kaskaderende infinitybasseng og frodig grønt' },
    architecture: { es: 'Piscina infinita en cascada a lo largo de las terrazas de la villa', fr: 'Piscine à débordement en cascade le long des terrasses de la villa', de: 'Kaskadierender Infinity-Pool entlang der Terrassen der Villa', ru: 'Каскадный бассейн-инфинити вдоль террас виллы', ar: 'مسبح لامتناهٍ متدرج على امتداد تراسات الفيلا', nl: 'Trapsgewijze infinity pool langs de terrassen van de villa', pl: 'Kaskadowy basen typu infinity wzdłuż tarasów willi', sv: 'Kaskaderande infinitypool längs villans terrasser', no: 'Kaskaderende infinitybasseng langs villaens terrasser' },
    lifestyle: { es: 'Salón hundido con brasero junto a la piscina al atardecer', fr: 'Salon encastré avec foyer au bord de la piscine au crépuscule', de: 'Abgesenkte Feuerstellen-Lounge neben dem Pool in der Dämmerung', ru: 'Утопленная лаундж-зона с очагом у бассейна в сумерках', ar: 'صالة غائرة مع موقد نار بجانب المسبح عند الغروب', nl: 'Verzonken loungehoek met vuurschaal naast het zwembad bij zonsondergang', pl: 'Zagłębiona strefa wypoczynkowa z paleniskiem obok basenu o zachodzie słońca', sv: 'Nedsänkt loungeyta med eldstad intill poolen i solnedgången', no: 'Nedsenket loungeområde med ildsted ved bassenget i solnedgangen' },
    privateViewing: { es: 'Salón hundido con brasero junto a la piscina al atardecer', fr: 'Salon encastré avec foyer au bord de la piscine au crépuscule', de: 'Abgesenkte Feuerstellen-Lounge neben dem Pool in der Dämmerung', ru: 'Утопленная лаундж-зона с очагом у бассейна в сумерках', ar: 'صالة غائرة مع موقد نار بجانب المسبح عند الغروب', nl: 'Verzonken loungehoek met vuurschaal naast het zwembad bij zonsondergang', pl: 'Zagłębiona strefa wypoczynkowa z paleniskiem obok basenu o zachodzie słońca', sv: 'Nedsänkt loungeyta med eldstad intill poolen i solnedgången', no: 'Nedsenket loungeområde med ildsted ved bassenget i solnedgangen' }
  },
  'rio-real-townhouses': {
    hero: { es: 'Casas pareadas contemporáneas con salones acristalados diáfanos y terrazas ajardinadas', fr: 'Maisons jumelées contemporaines avec séjours ouverts vitrés et terrasses paysagées', de: 'Zeitgenössische Doppelhaushälften mit offenen, verglasten Wohnbereichen und begrünten Terrassen', ru: 'Современные сдвоенные дома с панорамными гостиными и озеленёнными террасами', ar: 'منازل متلاصقة معاصرة بمساحات معيشة مفتوحة ومزججة وتراسات منسقة', nl: 'Eigentijdse geschakelde woningen met open, glazen woonkamers en begroeide terrassen', pl: 'Nowoczesne domy bliźniacze z otwartymi, przeszklonymi salonami i zazielenionymi tarasami', sv: 'Moderna parhus med öppna, glasade vardagsrum och gröna terrasser', no: 'Moderne tomannsboliger med åpne, glassinnrammede stuer og grønne terrasser' },
    architecture: { es: 'Vista aérea del conjunto terminado en una ladera sobre Marbella con el mar al fondo', fr: 'Vue aérienne de la résidence achevée sur une colline au-dessus de Marbella avec la mer au loin', de: 'Luftaufnahme der fertiggestellten Anlage an einem Hang oberhalb von Marbella mit dem Meer in der Ferne', ru: 'Вид с воздуха на завершённый комплекс на склоне над Марбельей с морем вдали', ar: 'منظر جوي للمشروع المكتمل على منحدر يعلو ماربيا مع البحر في البعيد', nl: 'Luchtfoto van het voltooide complex op een heuvelhelling boven Marbella met de zee op de achtergrond', pl: 'Widok z lotu ptaka na ukończony kompleks na zboczu nad Marbellą, z morzem w tle', sv: 'Flygbild av det färdigställda projektet på en sluttning ovanför Marbella med havet i bakgrunden', no: 'Luftfoto av det ferdigstilte anlegget i en skråning over Marbella med havet i bakgrunnen' },
    lifestyle: { es: 'Terraza-comedor en el solárium de la azotea con vistas despejadas al mar', fr: 'Terrasse-repas du solarium sur le toit avec vue mer dégagée', de: 'Essterrasse im Dachsolarium mit freiem Meerblick', ru: 'Обеденная терраса в солярии на крыше с открытым видом на море', ar: 'تراس طعام في السطح الشمسي بإطلالة بحرية مفتوحة', nl: 'Eetterras op het zonneterras op het dak met vrij zeezicht', pl: 'Taras jadalny na solarium na dachu z rozległym widokiem na morze', sv: 'Matterrass på soldäcket på taket med fri havsutsikt', no: 'Spiseterrasse på soldekket på taket med fri sjøutsikt' },
    privateViewing: { es: 'Salón de doble altura de la casa piloto con acristalamiento de suelo a techo hacia una terraza privada', fr: 'Séjour double hauteur de la maison témoin avec baies vitrées toute hauteur ouvrant sur une terrasse privée', de: 'Doppelhohes Wohnzimmer des Musterhauses mit raumhoher Verglasung zu einer privaten Terrasse', ru: 'Гостиная двойной высоты в доме-образце с панорамным остеклением на приватную террасу', ar: 'غرفة معيشة بارتفاع مزدوج في المنزل النموذجي مع زجاج ممتد يطل على تراس خاص', nl: 'Dubbelhoge woonkamer van de modelwoning met glaswanden van vloer tot plafond naar een privéterras', pl: 'Dwupoziomowy salon w domu pokazowym z przeszkleniami od podłogi do sufitu prowadzącymi na prywatny taras', sv: 'Dubbelhögt vardagsrum i visningshuset med golv-till-tak-fönster ut mot en privat terrass', no: 'Stue med dobbel takhøyde i visningshuset med vindusfelt fra gulv til tak ut mot en privat terrasse' }
  },
  'vega-verde-residences': {
    hero: { es: 'Imagen aérea del promotor de Vega Verde Residences y el Valle del Golf circundante al atardecer', fr: 'Visuel aérien du promoteur de Vega Verde Residences et de la Golf Valley environnante au coucher du soleil', de: 'Luftbild-Visualisierung des Bauträgers von Vega Verde Residences und dem umliegenden Golf Valley bei Sonnenuntergang', ru: 'Аэровизуализация застройщика Vega Verde Residences и окружающей Гольф-Вэлли на закате', ar: 'تصور جوي من المطور لمشروع Vega Verde Residences ووادي الغولف المحيط عند الغروب', nl: 'Luchtbeeld van de ontwikkelaar van Vega Verde Residences en de omliggende Golf Valley bij zonsondergang', pl: 'Wizualizacja dewelopera z lotu ptaka przedstawiająca Vega Verde Residences i otaczającą Golf Valley o zachodzie słońca', sv: 'Utvecklarens flygbild av Vega Verde Residences och den omgivande Golf Valley i solnedgången', no: 'Utviklerens luftbilde av Vega Verde Residences og det omkringliggende Golf Valley i solnedgangen' },
    architecture: { es: 'Imagen del promotor de la arquitectura contemporánea, la piscina y los jardines paisajísticos', fr: 'Visuel du promoteur de l’architecture contemporaine, de la piscine et des jardins paysagers', de: 'Bauträger-Visualisierung der zeitgenössischen Architektur, des Pools und der Landschaftsgärten', ru: 'Визуализация застройщика: современная архитектура, бассейн и ландшафтные сады', ar: 'تصور من المطور للعمارة المعاصرة والمسبح والحدائق المنسقة', nl: 'Beeld van de ontwikkelaar van de eigentijdse architectuur, het zwembad en de aangelegde tuinen', pl: 'Wizualizacja dewelopera przedstawiająca nowoczesną architekturę, basen i zaprojektowane ogrody', sv: 'Utvecklarbild av den moderna arkitekturen, poolen och de anlagda trädgårdarna', no: 'Utviklerbilde av den moderne arkitekturen, bassenget og de opparbeidede hagene' },
    lifestyle: { es: 'Piscina interior y zona de spa de estilo resort', fr: 'Piscine intérieure et espace spa de style resort', de: 'Innenpool und Spa-Bereich im Resort-Stil', ru: 'Крытый бассейн и спа-зона в курортном стиле', ar: 'مسبح داخلي ومنطقة سبا بأسلوب المنتجعات', nl: 'Binnenzwembad en spagedeelte in resortstijl', pl: 'Kryty basen i strefa spa w stylu kurortu', sv: 'Inomhuspool och spaavdelning i resortstil', no: 'Innendørsbasseng og spaavdeling i resortstil' },
    privateViewing: { es: 'Imagen del promotor de la terraza de una vivienda al atardecer', fr: 'Visuel du promoteur de la terrasse d’une résidence au coucher du soleil', de: 'Bauträger-Visualisierung der Terrasse einer Residenz bei Sonnenuntergang', ru: 'Визуализация застройщика: терраса резиденции на закате', ar: 'تصور من المطور لتراس المسكن عند الغروب', nl: 'Beeld van de ontwikkelaar van het terras van een woning bij zonsondergang', pl: 'Wizualizacja dewelopera przedstawiająca taras jednego z domów o zachodzie słońca', sv: 'Utvecklarbild av en bostads terrass i solnedgången', no: 'Utviklerbilde av terrassen til en bolig i solnedgangen' }
  }
};
