// Translations for project `images.{hero,architecture,lifestyle,privateViewing}.alt`.
// These are the four large section images on each property page. They are a
// separate field group from `media.items[].alt` (the gallery), and were the
// last untranslated strings in the project data.
//
// alt text is not visible to sighted users, but it is what screen-reader
// users hear and what image search indexes -- so it belongs in the reader's
// own language, not English.
//
// Shape: { <slug>: { <imageKey>: { es, fr, de, ru, ar } } }
export const IMAGE_ALTS = {
  'alisios-residences': {
    hero: { es: 'Vista aérea de Alisios Residences enmarcada por el campo de golf de Guadalmina y el Mediterráneo', fr: 'Vue aérienne d’Alisios Residences encadrée par le golf de Guadalmina et la Méditerranée', de: 'Luftaufnahme von Alisios Residences, eingerahmt vom Golfplatz Guadalmina und dem Mittelmeer', ru: 'Вид с воздуха на Alisios Residences в обрамлении гольф-поля Guadalmina и Средиземного моря', ar: 'منظر جوي لمشروع Alisios Residences يحيط به ملعب غولف Guadalmina والبحر المتوسط' },
    architecture: { es: 'Vista al atardecer de la fachada contemporánea, los balcones y los jardines de Alisios Residences', fr: 'Vue au crépuscule de la façade contemporaine, des balcons et des jardins paysagers d’Alisios Residences', de: 'Dämmerungsansicht der zeitgenössischen Fassade, Balkone und Gartenanlagen von Alisios Residences', ru: 'Вид в сумерках на современный фасад, балконы и ландшафтные сады Alisios Residences', ar: 'منظر عند الغروب للواجهة المعاصرة والشرفات والحدائق المنسقة في Alisios Residences' },
    lifestyle: { es: 'Salón en terraza de azotea con vistas al campo de golf y al mar a lo lejos', fr: 'Salon de terrasse sur le toit donnant sur le golf avec la mer au loin', de: 'Dachterrassen-Lounge mit Blick über den Golfplatz und das Meer in der Ferne', ru: 'Лаундж на террасе крыши с видом на гольф-поле и море вдали', ar: 'صالة على تراس السطح تطل على ملعب الغولف والبحر في البعيد' },
    privateViewing: { es: 'Salón en terraza de azotea con vistas sobre Guadalmina hacia el mar', fr: 'Salon de terrasse sur le toit avec vue sur Guadalmina en direction de la mer', de: 'Dachterrassen-Lounge mit Blick über Guadalmina zum Meer', ru: 'Лаундж на террасе крыши с видом на Гуадальмину в сторону моря', ar: 'صالة على تراس السطح بإطلالة على Guadalmina باتجاه البحر' }
  },
  'altos-de-marbella': {
    hero: { es: 'Vista aérea al atardecer de Altos de Marbella Residences y su terraza con piscina', fr: 'Vue aérienne au crépuscule d’Altos de Marbella Residences et de sa terrasse-piscine', de: 'Luftaufnahme von Altos de Marbella Residences und der Poolterrasse in der Dämmerung', ru: 'Вид с воздуха в сумерках на Altos de Marbella Residences и террасу с бассейном', ar: 'منظر جوي عند الغروب لمشروع Altos de Marbella Residences وتراس المسبح' },
    architecture: { es: 'Vivienda diáfana que conecta el salón, la terraza y la piscina privada', fr: 'Logement ouvert reliant le séjour, la terrasse et la piscine privée', de: 'Offene Wohnung, die Wohnbereich, Terrasse und Privatpool verbindet', ru: 'Резиденция открытой планировки, объединяющая гостиную, террасу и частный бассейн', ar: 'مسكن مفتوح يربط بين غرفة المعيشة والتراس والمسبح الخاص' },
    lifestyle: { es: 'Terraza elevada y césped con vistas al litoral hacia Marbella', fr: 'Terrasse surélevée et pelouse dominant le littoral vers Marbella', de: 'Erhöhte Terrasse und Rasenfläche mit Blick auf die Küste Richtung Marbella', ru: 'Приподнятая терраса и газон с видом на побережье в сторону Марбельи', ar: 'تراس مرتفع ومساحة عشبية تطل على الساحل باتجاه ماربيا' },
    privateViewing: { es: 'Terraza con piscina privada al atardecer con vistas al litoral', fr: 'Terrasse avec piscine privée au coucher du soleil avec vue sur le littoral', de: 'Private Poolterrasse bei Sonnenuntergang mit Küstenblick', ru: 'Терраса с частным бассейном на закате с видом на побережье', ar: 'تراس بمسبح خاص عند الغروب بإطلالة ساحلية' }
  },
  'cancelada-park': {
    hero: { es: 'Imagen aérea del promotor de Cancelada Park y su entorno residencial ajardinado', fr: 'Visuel aérien du promoteur de Cancelada Park et de son cadre résidentiel paysager', de: 'Luftbild-Visualisierung des Bauträgers von Cancelada Park und seiner begrünten Wohnanlage', ru: 'Аэровизуализация застройщика Cancelada Park и его озеленённого жилого окружения', ar: 'تصور جوي من المطور لمشروع Cancelada Park ومحيطه السكني المنسق' },
    architecture: { es: 'Imagen del promotor de la arquitectura de baja altura y las terrazas ajardinadas de Cancelada Park', fr: 'Visuel du promoteur de l’architecture basse et des terrasses paysagées de Cancelada Park', de: 'Bauträger-Visualisierung der niedriggeschossigen Architektur und begrünten Terrassen von Cancelada Park', ru: 'Визуализация застройщика: малоэтажная архитектура и озеленённые террасы Cancelada Park', ar: 'تصور من المطور للعمارة المنخفضة والتراسات المنسقة في Cancelada Park' },
    lifestyle: { es: 'Terraza con jardín privado y zona de estar detrás de una villa residencial', fr: 'Terrasse-jardin privée et salon à l’arrière d’une villa résidentielle', de: 'Private Gartenterrasse und Lounge hinter einer Wohnvilla', ru: 'Приватная садовая терраса и зона отдыха позади жилой виллы', ar: 'تراس بحديقة خاصة ومنطقة جلوس خلف فيلا سكنية' },
    privateViewing: { es: 'Imagen nocturna del promotor de la piscina y las viviendas de Cancelada Park', fr: 'Visuel nocturne du promoteur de la piscine et des résidences de Cancelada Park', de: 'Abendliche Bauträger-Visualisierung von Pool und Residenzen in Cancelada Park', ru: 'Вечерняя визуализация застройщика: бассейн и резиденции Cancelada Park', ar: 'تصور مسائي من المطور للمسبح والمساكن في Cancelada Park' }
  },
  'elviria-hills-residences': {
    hero: { es: 'Edificio residencial contemporáneo curvo con terrazas ajardinadas en Elviria Hills Residences', fr: 'Bâtiment résidentiel contemporain aux formes courbes avec terrasses végétalisées à Elviria Hills Residences', de: 'Geschwungenes zeitgenössisches Wohngebäude mit bepflanzten Terrassen in Elviria Hills Residences', ru: 'Изогнутое современное жилое здание с озеленёнными террасами в Elviria Hills Residences', ar: 'مبنى سكني معاصر منحني بتراسات مزروعة في Elviria Hills Residences' },
    architecture: { es: 'Edificios residenciales escalonados en torno a la piscina comunitaria y los jardines', fr: 'Bâtiments résidentiels étagés autour de la piscine commune et des jardins paysagers', de: 'Terrassenförmig um den Gemeinschaftspool und die Gartenanlagen angeordnete Wohngebäude', ru: 'Жилые корпуса, террасами расположенные вокруг общего бассейна и садов', ar: 'مبانٍ سكنية متدرجة حول المسبح المشترك والحدائق المنسقة' },
    lifestyle: { es: 'Piscina de spa interior con sauna y zona de descanso', fr: 'Piscine de spa intérieure avec sauna et espace détente', de: 'Innen-Spa-Pool mit Sauna und Loungebereich', ru: 'Крытый спа-бассейн с сауной и зоной отдыха', ar: 'مسبح سبا داخلي مع ساونا ومنطقة استرخاء' },
    privateViewing: { es: 'Dormitorio del piso piloto con salida a la terraza y vistas al jardín', fr: 'Chambre de l’appartement témoin avec accès à la terrasse et vue sur le jardin', de: 'Schlafzimmer der Musterwohnung mit Terrassenzugang und Gartenblick', ru: 'Спальня шоу-апартаментов с выходом на террасу и видом на сад', ar: 'غرفة نوم الشقة النموذجية مع منفذ إلى التراس وإطلالة على الحديقة' }
  },
  'golden-mile-duplex-residences': {
    hero: { es: 'Vivienda dúplex con jardín, piscina privada y exuberante vegetación', fr: 'Duplex avec jardin, piscine privée et végétation luxuriante', de: 'Garten-Duplex mit privatem Pool und üppiger Bepflanzung', ru: 'Дуплекс с садом, частным бассейном и пышной зеленью', ar: 'دوبلكس بحديقة ومسبح خاص ومساحات خضراء وارفة' },
    architecture: { es: 'Piscina infinita en azotea con vistas al Mediterráneo al atardecer', fr: 'Piscine à débordement sur le toit surplombant la Méditerranée au crépuscule', de: 'Infinity-Dachpool mit Blick auf das Mittelmeer in der Dämmerung', ru: 'Бассейн-инфинити на крыше с видом на Средиземное море в сумерках', ar: 'مسبح لامتناهٍ على السطح يطل على البحر المتوسط عند الغروب' },
    lifestyle: { es: 'Piscina infinita en azotea al atardecer con vistas al mar', fr: 'Piscine à débordement sur le toit au crépuscule avec vue mer', de: 'Infinity-Dachpool in der Dämmerung mit Meerblick', ru: 'Бассейн-инфинити на крыше в сумерках с видом на море', ar: 'مسبح لامتناهٍ على السطح عند الغروب بإطلالة بحرية' },
    privateViewing: { es: 'Salón amueblado por un estudio de diseño con obra de arte protagonista', fr: 'Séjour meublé par un studio de design avec œuvre d’art maîtresse', de: 'Von einem Designstudio möbliertes Wohnzimmer mit markantem Kunstwerk', ru: 'Гостиная с дизайнерской меблировкой и акцентным произведением искусства', ar: 'غرفة معيشة مؤثثة بتصميم راقٍ مع عمل فني بارز' }
  },
  'golf-valley-flex-residences': {
    hero: { es: 'Viviendas contemporáneas con piscinas privadas al atardecer', fr: 'Résidences contemporaines avec piscines privées au coucher du soleil', de: 'Zeitgenössische Residenzen mit privaten Pools bei Sonnenuntergang', ru: 'Современные резиденции с частными бассейнами на закате', ar: 'مساكن معاصرة بمسابح خاصة عند الغروب' },
    architecture: { es: 'Vista frontal de las viviendas con piscinas privadas y jardines', fr: 'Vue frontale des résidences avec piscines privées et jardins', de: 'Frontansicht der Residenzen mit privaten Pools und Gärten', ru: 'Вид спереди на резиденции с частными бассейнами и садами', ar: 'منظر أمامي للمساكن بمسابح خاصة وحدائق' },
    lifestyle: { es: 'Piscina de spa interior abierta a un patio ajardinado', fr: 'Piscine de spa intérieure ouvrant sur une cour paysagée', de: 'Innen-Spa-Pool mit Zugang zu einem begrünten Innenhof', ru: 'Крытый спа-бассейн с выходом в озеленённый внутренний двор', ar: 'مسبح سبا داخلي يطل على فناء منسق' },
    privateViewing: { es: 'Salón con vistas al mar a través de acristalamiento de suelo a techo', fr: 'Séjour avec vue mer à travers des baies vitrées toute hauteur', de: 'Wohnzimmer mit Meerblick durch raumhohe Verglasung', ru: 'Гостиная с видом на море через панорамное остекление', ar: 'غرفة معيشة بإطلالة بحرية عبر زجاج ممتد من الأرض حتى السقف' }
  },
  'jardin-del-mar-residences': {
    hero: { es: 'Render exterior de Jardin del Mar Residences con terraza de piscina bordeada de palmeras', fr: 'Rendu extérieur de Jardin del Mar Residences avec terrasse-piscine bordée de palmiers', de: 'Außenvisualisierung von Jardin del Mar Residences mit palmengesäumter Poolterrasse', ru: 'Внешняя визуализация Jardin del Mar Residences с террасой у бассейна в окружении пальм', ar: 'تصور خارجي لمشروع Jardin del Mar Residences مع تراس مسبح تحيط به النخيل' },
    architecture: { es: 'Fachada del patio del edificio con pérgola y paseo ajardinado', fr: 'Façade sur cour du bâtiment avec pergola et allée paysagée', de: 'Innenhoffassade des Gebäudes mit Pergola und begrüntem Weg', ru: 'Фасад внутреннего двора здания с перголой и озеленённой дорожкой', ar: 'واجهة فناء المبنى مع بيرغولا وممشى منسق' },
    lifestyle: { es: 'Piscina de spa interior privada dentro del recinto cerrado', fr: 'Piscine de spa intérieure privée au sein de la résidence sécurisée', de: 'Privater Innen-Spa-Pool innerhalb der geschlossenen Anlage', ru: 'Частный крытый спа-бассейн на закрытой территории', ar: 'مسبح سبا داخلي خاص ضمن المجمع المسور' },
    privateViewing: { es: 'Salón del piso piloto con estantería separadora de ambientes y mobiliario en tonos neutros', fr: 'Séjour de l’appartement témoin avec étagère cloison et mobilier aux tons neutres', de: 'Wohnzimmer der Musterwohnung mit Raumteiler-Regal und Möbeln in Naturtönen', ru: 'Гостиная шоу-апартаментов со стеллажом-перегородкой и мебелью нейтральных тонов', ar: 'غرفة معيشة الشقة النموذجية مع رفوف فاصلة وأثاث بألوان محايدة' }
  },
  'los-olivos-residences': {
    hero: { es: 'Vista aérea de Los Olivos Residences en construcción en el Valle del Golf de Marbella, con el litoral al fondo', fr: 'Vue aérienne de Los Olivos Residences en construction dans la Golf Valley de Marbella, avec le littoral en arrière-plan', de: 'Luftaufnahme von Los Olivos Residences im Bau im Golf Valley von Marbella mit der Küste im Hintergrund', ru: 'Вид с воздуха на строящийся Los Olivos Residences в Гольф-Вэлли Марбельи с побережьем на заднем плане', ar: 'منظر جوي لمشروع Los Olivos Residences قيد الإنشاء في وادي الغولف بماربيا مع الساحل في الخلفية' },
    architecture: { es: 'Terraza privada con zona de estar y vistas despejadas a la montaña', fr: 'Terrasse privée avec coin salon et vues dégagées sur la montagne', de: 'Private Terrasse mit Sitzbereich und freiem Bergblick', ru: 'Приватная терраса с зоной отдыха и открытым видом на горы', ar: 'تراس خاص مع منطقة جلوس وإطلالات جبلية مفتوحة' },
    lifestyle: { es: 'Mesa de comedor en la terraza con vistas a la montaña de La Concha', fr: 'Table de repas en terrasse avec vue sur la montagne La Concha', de: 'Esstisch auf der Terrasse mit Blick auf den Berg La Concha', ru: 'Обеденный стол на террасе с видом на гору Ла-Конча', ar: 'طاولة طعام على التراس بإطلالة على جبل لا كونتشا' },
    privateViewing: { es: 'Salón del piso piloto con panelado de madera y mobiliario en tonos neutros', fr: 'Séjour de l’appartement témoin avec mur média en bois et mobilier aux tons neutres', de: 'Wohnzimmer der Musterwohnung mit holzvertäfelter Medienwand und Möbeln in Naturtönen', ru: 'Гостиная шоу-апартаментов с деревянной ТВ-стеной и мебелью нейтральных тонов', ar: 'غرفة معيشة الشقة النموذجية بجدار خشبي وأثاث بألوان محايدة' }
  },
  'marbella-west-garden-residences': {
    hero: { es: 'Patio ajardinado y piscina exterior de Marbella West Garden Residences', fr: 'Cour paysagée et piscine extérieure de Marbella West Garden Residences', de: 'Begrünter Innenhof und Außenpool von Marbella West Garden Residences', ru: 'Озеленённый внутренний двор и открытый бассейн Marbella West Garden Residences', ar: 'الفناء المنسق والمسبح الخارجي في Marbella West Garden Residences' },
    architecture: { es: 'Terrazas curvas, piscinas privadas y vegetación mediterránea en Marbella West Garden Residences', fr: 'Terrasses courbes, piscines privées et végétation méditerranéenne à Marbella West Garden Residences', de: 'Geschwungene Terrassen, private Pools und mediterrane Bepflanzung in Marbella West Garden Residences', ru: 'Изогнутые террасы, частные бассейны и средиземноморское озеленение в Marbella West Garden Residences', ar: 'تراسات منحنية ومسابح خاصة ونباتات متوسطية في Marbella West Garden Residences' },
    lifestyle: { es: 'Plataforma de yoga en la azotea al atardecer con vistas a la montaña', fr: 'Plateforme de yoga sur le toit au coucher du soleil avec vue sur la montagne', de: 'Yoga-Deck auf dem Dach bei Sonnenuntergang mit Bergblick', ru: 'Площадка для йоги на крыше на закате с видом на горы', ar: 'منصة يوغا على السطح عند الغروب بإطلالة جبلية' },
    privateViewing: { es: 'Piscina de agua salada con vistas al mar en Marbella West Garden Residences', fr: 'Piscine d’eau salée avec vue mer à Marbella West Garden Residences', de: 'Salzwasserpool mit Meerblick in Marbella West Garden Residences', ru: 'Бассейн с солёной водой и видом на море в Marbella West Garden Residences', ar: 'مسبح بمياه مالحة بإطلالة بحرية في Marbella West Garden Residences' }
  },
  'nueva-alcantara-residences': {
    hero: { es: 'Vista en esquina de un edificio residencial contemporáneo con locales a pie de calle y terrazas ajardinadas', fr: 'Vue d’angle d’un immeuble résidentiel contemporain avec commerces en rez-de-chaussée et terrasses végétalisées', de: 'Eckansicht eines zeitgenössischen Wohngebäudes mit Ladengeschäften im Erdgeschoss und bepflanzten Terrassen', ru: 'Угловой вид современного жилого здания с магазинами на первом этаже и озеленёнными террасами', ar: 'منظر زاوية لمبنى سكني معاصر مع محلات على مستوى الشارع وتراسات مزروعة' },
    architecture: { es: 'Fachada posterior de las viviendas a lo largo de una calle peatonal ajardinada', fr: 'Façade arrière des résidences le long d’une rue piétonne paysagée', de: 'Rückfassade der Residenzen entlang einer begrünten Fußgängerstraße', ru: 'Задний фасад резиденций вдоль озеленённой пешеходной улицы', ar: 'الواجهة الخلفية للمساكن على امتداد شارع مشاة منسق' },
    lifestyle: { es: 'Piscina en azotea con vistas a la montaña', fr: 'Piscine sur le toit avec vue sur la montagne', de: 'Dachpool mit Bergblick', ru: 'Бассейн на крыше с видом на горы', ar: 'مسبح على السطح بإطلالة جبلية' },
    privateViewing: { es: 'Salón y comedor del piso piloto con luz natural', fr: 'Séjour et espace repas de l’appartement témoin baignés de lumière naturelle', de: 'Wohn- und Essbereich der Musterwohnung mit natürlichem Licht', ru: 'Гостиная-столовая шоу-апартаментов с естественным светом', ar: 'غرفة معيشة وطعام الشقة النموذجية بإضاءة طبيعية' }
  },
  'nueva-andalucia-villa-collection': {
    hero: { es: 'Villa contemporánea con piscina infinita en cascada y exuberante vegetación', fr: 'Villa contemporaine avec piscine à débordement en cascade et végétation luxuriante', de: 'Zeitgenössische Villa mit kaskadierendem Infinity-Pool und üppiger Bepflanzung', ru: 'Современная вилла с каскадным бассейном-инфинити и пышной зеленью', ar: 'فيلا معاصرة بمسبح لامتناهٍ متدرج ومساحات خضراء وارفة' },
    architecture: { es: 'Piscina infinita en cascada a lo largo de las terrazas de la villa', fr: 'Piscine à débordement en cascade le long des terrasses de la villa', de: 'Kaskadierender Infinity-Pool entlang der Terrassen der Villa', ru: 'Каскадный бассейн-инфинити вдоль террас виллы', ar: 'مسبح لامتناهٍ متدرج على امتداد تراسات الفيلا' },
    lifestyle: { es: 'Salón hundido con brasero junto a la piscina al atardecer', fr: 'Salon encastré avec foyer au bord de la piscine au crépuscule', de: 'Abgesenkte Feuerstellen-Lounge neben dem Pool in der Dämmerung', ru: 'Утопленная лаундж-зона с очагом у бассейна в сумерках', ar: 'صالة غائرة مع موقد نار بجانب المسبح عند الغروب' },
    privateViewing: { es: 'Salón hundido con brasero junto a la piscina al atardecer', fr: 'Salon encastré avec foyer au bord de la piscine au crépuscule', de: 'Abgesenkte Feuerstellen-Lounge neben dem Pool in der Dämmerung', ru: 'Утопленная лаундж-зона с очагом у бассейна в сумерках', ar: 'صالة غائرة مع موقد نار بجانب المسبح عند الغروب' }
  },
  'rio-real-townhouses': {
    hero: { es: 'Casas pareadas contemporáneas con salones acristalados diáfanos y terrazas ajardinadas', fr: 'Maisons jumelées contemporaines avec séjours ouverts vitrés et terrasses paysagées', de: 'Zeitgenössische Doppelhaushälften mit offenen, verglasten Wohnbereichen und begrünten Terrassen', ru: 'Современные сдвоенные дома с панорамными гостиными и озеленёнными террасами', ar: 'منازل متلاصقة معاصرة بمساحات معيشة مفتوحة ومزججة وتراسات منسقة' },
    architecture: { es: 'Vista aérea del conjunto terminado en una ladera sobre Marbella con el mar al fondo', fr: 'Vue aérienne de la résidence achevée sur une colline au-dessus de Marbella avec la mer au loin', de: 'Luftaufnahme der fertiggestellten Anlage an einem Hang oberhalb von Marbella mit dem Meer in der Ferne', ru: 'Вид с воздуха на завершённый комплекс на склоне над Марбельей с морем вдали', ar: 'منظر جوي للمشروع المكتمل على منحدر يعلو ماربيا مع البحر في البعيد' },
    lifestyle: { es: 'Terraza-comedor en el solárium de la azotea con vistas despejadas al mar', fr: 'Terrasse-repas du solarium sur le toit avec vue mer dégagée', de: 'Essterrasse im Dachsolarium mit freiem Meerblick', ru: 'Обеденная терраса в солярии на крыше с открытым видом на море', ar: 'تراس طعام في السطح الشمسي بإطلالة بحرية مفتوحة' },
    privateViewing: { es: 'Salón de doble altura de la casa piloto con acristalamiento de suelo a techo hacia una terraza privada', fr: 'Séjour double hauteur de la maison témoin avec baies vitrées toute hauteur ouvrant sur une terrasse privée', de: 'Doppelhohes Wohnzimmer des Musterhauses mit raumhoher Verglasung zu einer privaten Terrasse', ru: 'Гостиная двойной высоты в доме-образце с панорамным остеклением на приватную террасу', ar: 'غرفة معيشة بارتفاع مزدوج في المنزل النموذجي مع زجاج ممتد يطل على تراس خاص' }
  },
  'vega-verde-residences': {
    hero: { es: 'Imagen aérea del promotor de Vega Verde Residences y el Valle del Golf circundante al atardecer', fr: 'Visuel aérien du promoteur de Vega Verde Residences et de la Golf Valley environnante au coucher du soleil', de: 'Luftbild-Visualisierung des Bauträgers von Vega Verde Residences und dem umliegenden Golf Valley bei Sonnenuntergang', ru: 'Аэровизуализация застройщика Vega Verde Residences и окружающей Гольф-Вэлли на закате', ar: 'تصور جوي من المطور لمشروع Vega Verde Residences ووادي الغولف المحيط عند الغروب' },
    architecture: { es: 'Imagen del promotor de la arquitectura contemporánea, la piscina y los jardines paisajísticos', fr: 'Visuel du promoteur de l’architecture contemporaine, de la piscine et des jardins paysagers', de: 'Bauträger-Visualisierung der zeitgenössischen Architektur, des Pools und der Landschaftsgärten', ru: 'Визуализация застройщика: современная архитектура, бассейн и ландшафтные сады', ar: 'تصور من المطور للعمارة المعاصرة والمسبح والحدائق المنسقة' },
    lifestyle: { es: 'Piscina interior y zona de spa de estilo resort', fr: 'Piscine intérieure et espace spa de style resort', de: 'Innenpool und Spa-Bereich im Resort-Stil', ru: 'Крытый бассейн и спа-зона в курортном стиле', ar: 'مسبح داخلي ومنطقة سبا بأسلوب المنتجعات' },
    privateViewing: { es: 'Imagen del promotor de la terraza de una vivienda al atardecer', fr: 'Visuel du promoteur de la terrasse d’une résidence au coucher du soleil', de: 'Bauträger-Visualisierung der Terrasse einer Residenz bei Sonnenuntergang', ru: 'Визуализация застройщика: терраса резиденции на закате', ar: 'تصور من المطور لتراس المسكن عند الغروب' }
  }
};
