// Body translations for the three hand-authored static pages that fall
// outside every render-based build pass: compare.html, thank-you.html and
// 404.html. Applied by build_static_page_locales.mjs as literal
// find/replace (longest-first), on top of the shared CHROME_ENTRIES from
// developments_page_translations.mjs.

export const THANK_YOU_ENTRIES = [
  { find: '<title>Enquiry Received | Nueva Living</title>', es: '<title>Consulta Recibida | Nueva Living</title>', fr: '<title>Demande Reçue | Nueva Living</title>', de: '<title>Anfrage Erhalten | Nueva Living</title>', ru: '<title>Запрос Получен | Nueva Living</title>', ar: '<title>تم استلام الطلب | Nueva Living</title>', nl: '<title>Aanvraag Ontvangen | Nueva Living</title>', pl: '<title>Zapytanie Otrzymane | Nueva Living</title>', sv: '<title>Förfrågan Mottagen | Nueva Living</title>', no: '<title>Forespørsel Mottatt | Nueva Living</title>' },
  { find: 'Thank you for contacting Nueva Living. Your private new-development request has been received.', es: 'Gracias por contactar con Nueva Living. Hemos recibido su solicitud privada sobre obra nueva.', fr: 'Merci d’avoir contacté Nueva Living. Votre demande privée concernant les programmes neufs a bien été reçue.', de: 'Vielen Dank für Ihre Kontaktaufnahme mit Nueva Living. Ihre private Neubau-Anfrage ist eingegangen.', ru: 'Благодарим за обращение в Nueva Living. Ваш запрос о новостройках получен.', ar: 'شكرًا لتواصلك مع Nueva Living. لقد استلمنا طلبك الخاص بالمشاريع الجديدة.', nl: 'Bedankt voor uw bericht aan Nueva Living. Uw persoonlijke aanvraag over nieuwbouw is ontvangen.', pl: 'Dziękujemy za kontakt z Nueva Living. Państwa prywatne zapytanie dotyczące nowej inwestycji zostało otrzymane.', sv: 'Tack för att ni kontaktat Nueva Living. Er privata förfrågan om nyproduktion har tagits emot.', no: 'Takk for at du kontaktet Nueva Living. Din private forespørsel om nybygg er mottatt.' },
  { find: '<meta property="og:title" content="Enquiry Received | Nueva Living">', es: '<meta property="og:title" content="Consulta Recibida | Nueva Living">', fr: '<meta property="og:title" content="Demande Reçue | Nueva Living">', de: '<meta property="og:title" content="Anfrage Erhalten | Nueva Living">', ru: '<meta property="og:title" content="Запрос Получен | Nueva Living">', ar: '<meta property="og:title" content="تم استلام الطلب | Nueva Living">', nl: '<meta property="og:title" content="Aanvraag Ontvangen | Nueva Living">', pl: '<meta property="og:title" content="Zapytanie Otrzymane | Nueva Living">', sv: '<meta property="og:title" content="Förfrågan Mottagen | Nueva Living">', no: '<meta property="og:title" content="Forespørsel Mottatt | Nueva Living">' },
  { find: 'Your private Nueva Living request has been received.', es: 'Hemos recibido su solicitud privada de Nueva Living.', fr: 'Votre demande privée Nueva Living a bien été reçue.', de: 'Ihre private Nueva Living-Anfrage ist eingegangen.', ru: 'Ваш личный запрос в Nueva Living получен.', ar: 'تم استلام طلبك الخاص لدى Nueva Living.', nl: 'Uw persoonlijke aanvraag bij Nueva Living is ontvangen.', pl: 'Państwa prywatne zapytanie do Nueva Living zostało otrzymane.', sv: 'Er privata förfrågan hos Nueva Living har tagits emot.', no: 'Din private forespørsel til Nueva Living er mottatt.' },
  { find: '<li><span aria-current="page">Enquiry Received</span></li>', es: '<li><span aria-current="page">Consulta Recibida</span></li>', fr: '<li><span aria-current="page">Demande Reçue</span></li>', de: '<li><span aria-current="page">Anfrage Erhalten</span></li>', ru: '<li><span aria-current="page">Запрос Получен</span></li>', ar: '<li><span aria-current="page">تم استلام الطلب</span></li>', nl: '<li><span aria-current="page">Aanvraag Ontvangen</span></li>', pl: '<li><span aria-current="page">Zapytanie Otrzymane</span></li>', sv: '<li><span aria-current="page">Förfrågan Mottagen</span></li>', no: '<li><span aria-current="page">Forespørsel Mottatt</span></li>' },
  { find: '<span class="kicker">Enquiry Received</span>', es: '<span class="kicker">Consulta Recibida</span>', fr: '<span class="kicker">Demande Reçue</span>', de: '<span class="kicker">Anfrage Erhalten</span>', ru: '<span class="kicker">Запрос Получен</span>', ar: '<span class="kicker">تم استلام الطلب</span>', nl: '<span class="kicker">Aanvraag Ontvangen</span>', pl: '<span class="kicker">Zapytanie Otrzymane</span>', sv: '<span class="kicker">Förfrågan Mottagen</span>', no: '<span class="kicker">Forespørsel Mottatt</span>' },
  { find: 'Thanks, we have your <em>enquiry</em>', es: 'Gracias, hemos recibido su <em>consulta</em>', fr: 'Merci, nous avons bien reçu votre <em>demande</em>', de: 'Danke, Ihre <em>Anfrage</em> ist bei uns', ru: 'Спасибо, ваш <em>запрос</em> у нас', ar: 'شكرًا، لقد استلمنا <em>طلبك</em>', nl: 'Bedankt, we hebben uw <em>aanvraag</em> ontvangen', pl: 'Dziękujemy, otrzymaliśmy Państwa <em>zapytanie</em>', sv: 'Tack, vi har er <em>förfrågan</em>', no: 'Takk, vi har mottatt din <em>forespørsel</em>' },
  { find: 'We will review what you sent and get back to you with the right project information, current availability or a clear next step.', es: 'Revisaremos lo que nos ha enviado y le responderemos con la información adecuada del proyecto, la disponibilidad actual o el siguiente paso a seguir.', fr: 'Nous examinerons votre demande et reviendrons vers vous avec les informations pertinentes sur le projet, la disponibilité actuelle ou une prochaine étape claire.', de: 'Wir prüfen Ihre Angaben und melden uns mit den passenden Projektinformationen, der aktuellen Verfügbarkeit oder einem klaren nächsten Schritt.', ru: 'Мы изучим ваш запрос и вернёмся к вам с нужной информацией о проекте, актуальным наличием или понятным следующим шагом.', ar: 'سنراجع ما أرسلته وسنعود إليك بمعلومات المشروع المناسبة أو التوافر الحالي أو خطوة تالية واضحة.', nl: 'We bekijken wat u heeft gestuurd en nemen contact met u op met de juiste projectinformatie, actuele beschikbaarheid of een duidelijke volgende stap.', pl: 'Przeanalizujemy przesłane informacje i skontaktujemy się z odpowiednimi danymi o projekcie, aktualną dostępnością lub jasnym kolejnym krokiem.', sv: 'Vi går igenom det ni skickat och återkommer med rätt projektinformation, aktuell tillgänglighet eller ett tydligt nästa steg.', no: 'Vi går gjennom det du har sendt inn og gir deg tilbakemelding med riktig prosjektinformasjon, aktuell tilgjengelighet eller et klart neste steg.' },
  // The heading was an h3 when this row was written and is an h2 now, which
  // silently stopped the match. The tag is not part of the sentence, so it is
  // no longer part of the key. Title Case was wrong in every language but German.
  { find: 'What Happens Next', es: 'Qué pasa ahora', fr: 'Et maintenant ?', de: 'Wie es weitergeht', ru: 'Что дальше', ar: 'ماذا يحدث الآن', nl: 'Wat gebeurt er nu', pl: 'Co dzieje się dalej', sv: 'Vad händer nu', no: 'Hva skjer videre' },
  { find: '<p>We check your enquiry against current availability, your preferred areas and the information you asked for.</p>', es: '<p>Contrastamos su consulta con la disponibilidad actual, sus zonas preferidas y la información que solicitaste.</p>', fr: '<p>Nous comparons votre demande à la disponibilité actuelle, à vos secteurs préférés et aux informations demandées.</p>', de: '<p>Wir gleichen Ihre Anfrage mit der aktuellen Verfügbarkeit, Ihren bevorzugten Lagen und den gewünschten Informationen ab.</p>', ru: '<p>Мы сверяем ваш запрос с актуальным наличием, предпочитаемыми районами и запрошенной информацией.</p>', ar: '<p>نراجع طلبك مقارنةً بالتوافر الحالي والمناطق المفضلة لديك والمعلومات التي طلبتها.</p>', nl: '<p>We vergelijken uw aanvraag met de actuele beschikbaarheid, uw voorkeursregio\'s en de gevraagde informatie.</p>', pl: '<p>Sprawdzamy Państwa zapytanie w odniesieniu do aktualnej dostępności, preferowanych lokalizacji i informacji, o które Państwo prosili.</p>', sv: '<p>Vi jämför er förfrågan med aktuell tillgänglighet, era föredragna områden och den information ni efterfrågat.</p>', no: '<p>Vi sjekker forespørselen din opp mot aktuell tilgjengelighet, dine foretrukne områder og informasjonen du ba om.</p>' },
  { find: '<h3>A Personal Reply</h3>', es: '<h3>Una Respuesta Personal</h3>', fr: '<h3>Une Réponse Personnalisée</h3>', de: '<h3>Eine Persönliche Antwort</h3>', ru: '<h3>Персональный Ответ</h3>', ar: '<h3>رد شخصي</h3>', nl: '<h3>Een Persoonlijk Antwoord</h3>', pl: '<h3>Osobista Odpowiedź</h3>', sv: '<h3>Ett Personligt Svar</h3>', no: '<h3>Et Personlig Svar</h3>' },
  { find: '<p>We will send the relevant project information or contact you to talk through the options.</p>', es: '<p>Le enviaremos la información relevante del proyecto o le contactaremos para comentar las opciones.</p>', fr: '<p>Nous vous enverrons les informations pertinentes sur le projet ou vous contacterons pour discuter des options.</p>', de: '<p>Wir senden Ihnen die relevanten Projektinformationen oder kontaktieren Sie, um die Optionen zu besprechen.</p>', ru: '<p>Мы отправим актуальную информацию о проекте или свяжемся с вами, чтобы обсудить варианты.</p>', ar: '<p>سنرسل لك معلومات المشروع ذات الصلة أو نتواصل معك لمناقشة الخيارات.</p>', nl: '<p>We sturen u de relevante projectinformatie of nemen contact met u op om de opties te bespreken.</p>', pl: '<p>Wyślemy odpowiednie informacje o projekcie lub skontaktujemy się, aby omówić dostępne opcje.</p>', sv: '<p>Vi skickar den relevanta projektinformationen eller kontaktar er för att gå igenom alternativen.</p>', no: '<p>Vi sender relevant prosjektinformasjon eller kontakter deg for å gå gjennom alternativene.</p>' },
  { find: '<h3>Need Faster Contact?</h3>', es: '<h3>¿Necesita una Respuesta más Rápida?</h3>', fr: '<h3>Besoin d’un Contact plus Rapide ?</h3>', de: '<h3>Schnelleren Kontakt Gewünscht?</h3>', ru: '<h3>Нужен Быстрый Контакт?</h3>', ar: '<h3>هل تحتاج إلى تواصل أسرع؟</h3>', nl: '<h3>Snel Contact Nodig?</h3>', pl: '<h3>Potrzebują Państwo szybszego kontaktu?</h3>', sv: '<h3>Behöver ni Snabbare Kontakt?</h3>', no: '<h3>Trenger du Raskere Kontakt?</h3>' },
  { find: '>Message us on WhatsApp</a>', es: '>Escríbenos por WhatsApp</a>', fr: '>Écrivez-nous sur WhatsApp</a>', de: '>Schreiben Sie uns auf WhatsApp</a>', ru: '>Напишите нам в WhatsApp</a>', ar: '>راسلنا عبر واتساب</a>', nl: '>Stuur ons een bericht via WhatsApp</a>', pl: '>Napisz do nas na WhatsApp</a>', sv: '>Skicka meddelande på WhatsApp</a>', no: '>Send oss melding på WhatsApp</a>' },
  { find: '<h2 class="cta-title">Keep exploring new developments.</h2>', es: '<h2 class="cta-title">Sigue explorando la obra nueva.</h2>', fr: '<h2 class="cta-title">Continuez à explorer les programmes neufs.</h2>', de: '<h2 class="cta-title">Entdecken Sie weitere Neubauprojekte.</h2>', ru: '<h2 class="cta-title">Продолжайте знакомиться с новостройками.</h2>', ar: '<h2 class="cta-title">واصل استكشاف المشاريع الجديدة.</h2>', nl: '<h2 class="cta-title">Blijf nieuwbouwprojecten ontdekken.</h2>', pl: '<h2 class="cta-title">Kontynuuj przeglądanie nowych inwestycji.</h2>', sv: '<h2 class="cta-title">Fortsätt utforska nya projekt.</h2>', no: '<h2 class="cta-title">Fortsett å utforske nye boligprosjekter.</h2>' },
  { find: '>View Developments</a>', es: '>Ver Promociones</a>', fr: '>Voir les Programmes</a>', de: '>Neubauprojekte Ansehen</a>', ru: '>Смотреть Новостройки</a>', ar: '>عرض المشاريع</a>', nl: '>Bekijk Nieuwbouwprojecten</a>', pl: '>Zobacz Inwestycje</a>', sv: '>Se Projekt</a>', no: '>Se Boligprosjekter</a>' },
];

export const COMPARE_ENTRIES = [
  { find: '<title>Compare Your Shortlist | Nueva Living</title>', es: '<title>Compara su Lista | Nueva Living</title>', fr: '<title>Comparez Votre Sélection | Nueva Living</title>', de: '<title>Ihre Auswahl Vergleichen | Nueva Living</title>', ru: '<title>Сравните Вашу Подборку | Nueva Living</title>', ar: '<title>قارن قائمتك المختارة | Nueva Living</title>', nl: '<title>Vergelijk Uw Lijst | Nueva Living</title>', pl: '<title>Porównaj Swoją Listę | Nueva Living</title>', sv: '<title>Jämför Er Lista | Nueva Living</title>', no: '<title>Sammenlign Din Liste | Nueva Living</title>' },
  { find: 'Compare the Costa del Sol developments you have saved to your shortlist, side by side.', es: 'Compara lado a lado las promociones de la Costa del Sol que ha guardado en su lista.', fr: 'Comparez côte à côte les programmes de la Costa del Sol que vous avez enregistrés dans votre sélection.', de: 'Vergleichen Sie die von Ihnen gespeicherten Costa-del-Sol-Projekte direkt nebeneinander.', ru: 'Сравните сохранённые вами новостройки Коста-дель-Соль бок о бок.', ar: 'قارن مشاريع كوستا ديل سول التي حفظتها في قائمتك جنبًا إلى جنب.', nl: 'Vergelijk de Costa del Sol-projecten die u aan uw lijst heeft toegevoegd, naast elkaar.', pl: 'Porównaj obok siebie inwestycje na Costa del Sol, które zapisali Państwo na swojej liście.', sv: 'Jämför de Costa del Sol-projekt ni sparat i er lista, sida vid sida.', no: 'Sammenlign Costa del Sol-prosjektene du har lagret på listen din, side om side.' },
  { find: '<li><a href="index.html">Home</a></li>', es: '<li><a href="index.html">Inicio</a></li>', fr: '<li><a href="index.html">Accueil</a></li>', de: '<li><a href="index.html">Startseite</a></li>', ru: '<li><a href="index.html">Главная</a></li>', ar: '<li><a href="index.html">الرئيسية</a></li>', nl: '<li><a href="index.html">Home</a></li>', pl: '<li><a href="index.html">Strona główna</a></li>', sv: '<li><a href="index.html">Hem</a></li>', no: '<li><a href="index.html">Hjem</a></li>' },
  { find: '<li><a href="developments.html">Developments</a></li>', es: '<li><a href="developments.html">Promociones</a></li>', fr: '<li><a href="developments.html">Programmes immobiliers</a></li>', de: '<li><a href="developments.html">Neubauprojekte</a></li>', ru: '<li><a href="developments.html">Новостройки</a></li>', ar: '<li><a href="developments.html">المشاريع</a></li>', nl: '<li><a href="developments.html">Nieuwbouwprojecten</a></li>', pl: '<li><a href="developments.html">Inwestycje</a></li>', sv: '<li><a href="developments.html">Nybyggnadsprojekt</a></li>', no: '<li><a href="developments.html">Nybyggprosjekter</a></li>' },
  { find: '<li><span aria-current="page">Compare</span></li>', es: '<li><span aria-current="page">Comparar</span></li>', fr: '<li><span aria-current="page">Comparer</span></li>', de: '<li><span aria-current="page">Vergleichen</span></li>', ru: '<li><span aria-current="page">Сравнение</span></li>', ar: '<li><span aria-current="page">مقارنة</span></li>', nl: '<li><span aria-current="page">Vergelijken</span></li>', pl: '<li><span aria-current="page">Porównaj</span></li>', sv: '<li><span aria-current="page">Jämför</span></li>', no: '<li><span aria-current="page">Sammenlign</span></li>' },
  { find: '<span class="kicker">Your Shortlist</span>', es: '<span class="kicker">Su Lista</span>', fr: '<span class="kicker">Votre Sélection</span>', de: '<span class="kicker">Ihre Auswahl</span>', ru: '<span class="kicker">Ваша Подборка</span>', ar: '<span class="kicker">قائمتك المختارة</span>', nl: '<span class="kicker">Uw Lijst</span>', pl: '<span class="kicker">Państwa Lista</span>', sv: '<span class="kicker">Er Lista</span>', no: '<span class="kicker">Din Liste</span>' },
  { find: 'Compare your <em>saved developments</em>', es: 'Compara sus <em>promociones guardadas</em>', fr: 'Comparez vos <em>programmes enregistrés</em>', de: 'Vergleichen Sie Ihre <em>gespeicherten Projekte</em>', ru: 'Сравните <em>сохранённые новостройки</em>', ar: 'قارن <em>مشاريعك المحفوظة</em>', nl: 'Vergelijk uw <em>opgeslagen projecten</em>', pl: 'Porównaj swoje <em>zapisane inwestycje</em>', sv: 'Jämför era <em>sparade projekt</em>', no: 'Sammenlign dine <em>lagrede prosjekter</em>' },
  { find: 'A side-by-side look at the projects you have saved, so you can weigh price, size and amenities without switching between pages.', es: 'Una vista comparativa de los proyectos que ha guardado, para valorar precio, tamaño y servicios sin cambiar de página.', fr: 'Une vue côte à côte des projets que vous avez enregistrés, pour comparer prix, surfaces et prestations sans changer de page.', de: 'Ein direkter Vergleich der von Ihnen gespeicherten Projekte, damit Sie Preis, Größe und Ausstattung abwägen können, ohne zwischen Seiten zu wechseln.', ru: 'Сравнение сохранённых проектов бок о бок: цена, площадь и инфраструктура — без переключения между страницами.', ar: 'نظرة جنبًا إلى جنب على المشاريع التي حفظتها، لتوازن بين السعر والمساحة والمرافق دون التنقل بين الصفحات.', nl: 'Een overzicht naast elkaar van de projecten die u heeft opgeslagen, zodat u prijs, grootte en voorzieningen kunt afwegen zonder tussen pagina\'s te wisselen.', pl: 'Zestawienie obok siebie zapisanych przez Państwa projektów, dzięki czemu mogą Państwo porównać cenę, powierzchnię i udogodnienia bez przełączania się między stronami.', sv: 'En jämförelse sida vid sida av de projekt ni sparat, så att ni kan väga pris, storlek och bekvämligheter utan att växla mellan sidor.', no: 'En sammenligning side om side av prosjektene du har lagret, slik at du kan veie pris, størrelse og fasiliteter uten å bytte mellom sider.' },
  { find: '<p class="body-copy">Loading your shortlist...</p>', es: '<p class="body-copy">Cargando su lista...</p>', fr: '<p class="body-copy">Chargement de votre sélection...</p>', de: '<p class="body-copy">Ihre Auswahl wird geladen...</p>', ru: '<p class="body-copy">Загружаем вашу подборку...</p>', ar: '<p class="body-copy">جارٍ تحميل قائمتك...</p>', nl: '<p class="body-copy">Uw lijst wordt geladen...</p>', pl: '<p class="body-copy">Ładowanie Państwa listy...</p>', sv: '<p class="body-copy">Laddar er lista...</p>', no: '<p class="body-copy">Laster listen din...</p>' },
];

export const NOT_FOUND_ENTRIES = [
  { find: '<title>Page Not Found | Nueva Living</title>', es: '<title>Página No Encontrada | Nueva Living</title>', fr: '<title>Page Introuvable | Nueva Living</title>', de: '<title>Seite Nicht Gefunden | Nueva Living</title>', ru: '<title>Страница Не Найдена | Nueva Living</title>', ar: '<title>الصفحة غير موجودة | Nueva Living</title>', nl: '<title>Pagina Niet Gevonden | Nueva Living</title>', pl: '<title>Strona Nie Znaleziona | Nueva Living</title>', sv: '<title>Sidan Hittades Inte | Nueva Living</title>', no: '<title>Siden ble ikke Funnet | Nueva Living</title>' },
  { find: 'The requested Nueva Living page could not be found.', es: 'No se ha podido encontrar la página de Nueva Living solicitada.', fr: 'La page Nueva Living demandée est introuvable.', de: 'Die angeforderte Nueva Living-Seite wurde nicht gefunden.', ru: 'Запрошенная страница Nueva Living не найдена.', ar: 'تعذر العثور على صفحة Nueva Living المطلوبة.', nl: 'De gevraagde Nueva Living-pagina kon niet worden gevonden.', pl: 'Nie można było znaleźć żądanej strony Nueva Living.', sv: 'Den begärda Nueva Living-sidan kunde inte hittas.', no: 'Den forespurte Nueva Living-siden ble ikke funnet.' },
  { find: '<meta property="og:title" content="Page Not Found | Nueva Living">', es: '<meta property="og:title" content="Página No Encontrada | Nueva Living">', fr: '<meta property="og:title" content="Page Introuvable | Nueva Living">', de: '<meta property="og:title" content="Seite Nicht Gefunden | Nueva Living">', ru: '<meta property="og:title" content="Страница Не Найдена | Nueva Living">', ar: '<meta property="og:title" content="الصفحة غير موجودة | Nueva Living">', nl: '<meta property="og:title" content="Pagina Niet Gevonden | Nueva Living">', pl: '<meta property="og:title" content="Strona Nie Znaleziona | Nueva Living">', sv: '<meta property="og:title" content="Sidan Hittades Inte | Nueva Living">', no: '<meta property="og:title" content="Siden ble ikke Funnet | Nueva Living">' },
  { find: 'This page is no longer <em>available</em>', es: 'Esta página ya no está <em>disponible</em>', fr: 'Cette page n’est plus <em>disponible</em>', de: 'Diese Seite ist nicht mehr <em>verfügbar</em>', ru: 'Эта страница больше <em>недоступна</em>', ar: 'هذه الصفحة لم تعد <em>متاحة</em>', nl: 'Deze pagina is niet langer <em>beschikbaar</em>', pl: 'Ta strona nie jest już <em>dostępna</em>', sv: 'Den här sidan är inte längre <em>tillgänglig</em>', no: 'Denne siden er ikke lenger <em>tilgjengelig</em>' },
  { find: 'The project or page you are looking for may have moved. Browse our current developments or contact us and we will help you find it.', es: 'El proyecto o la página que busca puede haberse movido. Explore nuestras promociones actuales o contáctenos y le ayudaremos a encontrarlo.', fr: 'Le projet ou la page que vous recherchez a peut-être été déplacé. Parcourez nos programmes actuels ou contactez-nous et nous vous aiderons à le retrouver.', de: 'Das gesuchte Projekt oder die Seite wurde möglicherweise verschoben. Durchstöbern Sie unsere aktuellen Projekte oder kontaktieren Sie uns — wir helfen Ihnen weiter.', ru: 'Проект или страница, которую вы ищете, возможно, была перемещена. Посмотрите наши текущие новостройки или свяжитесь с нами — мы поможем её найти.', ar: 'ربما تم نقل المشروع أو الصفحة التي تبحث عنها. تصفح مشاريعنا الحالية أو تواصل معنا وسنساعدك في العثور عليها.', nl: 'Het project of de pagina die u zoekt is mogelijk verplaatst. Blader door onze huidige nieuwbouwprojecten of neem contact met ons op en we helpen u verder.', pl: 'Projekt lub strona, której Państwo szukają, mogły zostać przeniesione. Prosimy przejrzeć nasze aktualne inwestycje lub skontaktować się z nami, a pomożemy ją znaleźć.', sv: 'Projektet eller sidan ni letar efter kan ha flyttats. Bläddra bland våra aktuella projekt eller kontakta oss så hjälper vi er att hitta den.', no: 'Prosjektet eller siden du leter etter, kan ha blitt flyttet. Bla gjennom våre nåværende boligprosjekter eller kontakt oss, så hjelper vi deg å finne den.' },
  { find: '<h2 class="cta-title">Return to the current Nueva Living collection.</h2>', es: '<h2 class="cta-title">Vuelve a la colección actual de Nueva Living.</h2>', fr: '<h2 class="cta-title">Revenez à la collection actuelle de Nueva Living.</h2>', de: '<h2 class="cta-title">Zurück zur aktuellen Nueva Living-Kollektion.</h2>', ru: '<h2 class="cta-title">Вернитесь к актуальной коллекции Nueva Living.</h2>', ar: '<h2 class="cta-title">عد إلى مجموعة Nueva Living الحالية.</h2>', nl: '<h2 class="cta-title">Ga terug naar de huidige Nueva Living-collectie.</h2>', pl: '<h2 class="cta-title">Wróć do aktualnej kolekcji Nueva Living.</h2>', sv: '<h2 class="cta-title">Återgå till Nueva Livings aktuella kollektion.</h2>', no: '<h2 class="cta-title">Gå tilbake til Nueva Livings gjeldende samling.</h2>' },
  { find: '>View Developments</a>', es: '>Ver Promociones</a>', fr: '>Voir les Programmes</a>', de: '>Neubauprojekte Ansehen</a>', ru: '>Смотреть Новостройки</a>', ar: '>عرض المشاريع</a>', nl: '>Bekijk Nieuwbouwprojecten</a>', pl: '>Zobacz Inwestycje</a>', sv: '>Se Projekt</a>', no: '>Se Boligprosjekter</a>' },
];

// data-i18n JSON blob for liora-compare.js's runtime strings.
export const COMPARE_RUNTIME_STRINGS = {
  es: {
    onRequest: 'A consultar', priceFrom: 'Desde {price}', bedroomsRange: '{min}-{max} dormitorios', bedroomsOne: '{n} dormitorios', toBeConfirmed: 'Por confirmar', dateLocale: 'es-ES',
    browse: 'Ver Promociones', rowPrice: 'Precio', rowBedrooms: 'Dormitorios', rowPropertyTypes: 'Tipos de propiedad', rowStatus: 'Estado', rowDelivery: 'Entrega', rowTotalUnits: 'Viviendas totales', rowAvailableUnits: 'Viviendas disponibles', rowArea: 'Zona', rowAmenities: 'Servicios',
    statusMap: { off_plan: 'Sobre plano', under_construction: 'En construcción', completed: 'Finalizado' },
    typeMap: { apartment: 'Apartamento', penthouse: 'Ático', villa: 'Villa', townhouse: 'Adosado', duplex: 'Dúplex' },
    note: 'Los precios, la disponibilidad y las fechas de entrega son orientativos y Nueva Living los reconfirma antes de cualquier reserva.',
    emptyNotSaved: 'Aún no has guardado ninguna promoción. Guarda un proyecto desde su página o tarjeta para compararlo aquí.',
    emptyNotFound: 'No hemos podido encontrar tus promociones guardadas. Puede que se hayan actualizado; prueba a navegar de nuevo.',
    emptyError: 'Los datos de comparación no están disponibles ahora mismo. Inténtalo de nuevo en breve.'
  },
  fr: {
    onRequest: 'Sur demande', priceFrom: 'À partir de {price}', bedroomsRange: '{min}-{max} chambres', bedroomsOne: '{n} chambres', toBeConfirmed: 'À confirmer', dateLocale: 'fr-FR',
    browse: 'Voir les Programmes', rowPrice: 'Prix', rowBedrooms: 'Chambres', rowPropertyTypes: 'Types de bien', rowStatus: 'Statut', rowDelivery: 'Livraison', rowTotalUnits: 'Logements au total', rowAvailableUnits: 'Logements disponibles', rowArea: 'Secteur', rowAmenities: 'Prestations',
    statusMap: { off_plan: 'Sur plan', under_construction: 'En construction', completed: 'Terminé' },
    typeMap: { apartment: 'Appartement', penthouse: 'Penthouse', villa: 'Villa', townhouse: 'Maison de ville', duplex: 'Duplex' },
    note: 'Les prix, la disponibilité et les dates de livraison sont indicatifs et reconfirmés par Nueva Living avant toute réservation.',
    emptyNotSaved: 'Vous n’avez encore enregistré aucun programme. Enregistrez un projet depuis sa page ou sa fiche pour le comparer ici.',
    emptyNotFound: 'Nous n’avons pas retrouvé vos programmes enregistrés. Ils ont peut-être été mis à jour — essayez de naviguer à nouveau.',
    emptyError: 'Les données de comparaison sont indisponibles pour le moment. Veuillez réessayer sous peu.'
  },
  de: {
    onRequest: 'Auf Anfrage', priceFrom: 'Ab {price}', bedroomsRange: '{min}-{max} Schlafzimmer', bedroomsOne: '{n} Schlafzimmer', toBeConfirmed: 'Wird bestätigt', dateLocale: 'de-DE',
    browse: 'Neubauprojekte Ansehen', rowPrice: 'Preis', rowBedrooms: 'Schlafzimmer', rowPropertyTypes: 'Immobilientypen', rowStatus: 'Status', rowDelivery: 'Übergabe', rowTotalUnits: 'Einheiten gesamt', rowAvailableUnits: 'Verfügbare Einheiten', rowArea: 'Lage', rowAmenities: 'Ausstattung',
    statusMap: { off_plan: 'Off-Plan', under_construction: 'Im Bau', completed: 'Fertiggestellt' },
    typeMap: { apartment: 'Wohnung', penthouse: 'Penthouse', villa: 'Villa', townhouse: 'Reihenhaus', duplex: 'Duplex' },
    note: 'Preise, Verfügbarkeit und Übergabetermine sind Richtwerte und werden von Nueva Living vor jeder Reservierung erneut bestätigt.',
    emptyNotSaved: 'Sie haben noch keine Projekte gespeichert. Speichern Sie ein Projekt über seine Seite oder Karte, um es hier zu vergleichen.',
    emptyNotFound: 'Wir konnten Ihre gespeicherten Projekte nicht finden. Sie wurden möglicherweise aktualisiert — versuchen Sie es erneut.',
    emptyError: 'Die Vergleichsdaten sind derzeit nicht verfügbar. Bitte versuchen Sie es in Kürze erneut.'
  },
  ru: {
    onRequest: 'По запросу', priceFrom: 'От {price}', bedroomsRange: '{min}-{max} спален', bedroomsOne: 'Спален: {n}', toBeConfirmed: 'Уточняется', dateLocale: 'ru-RU',
    browse: 'Смотреть Новостройки', rowPrice: 'Цена', rowBedrooms: 'Спальни', rowPropertyTypes: 'Типы недвижимости', rowStatus: 'Статус', rowDelivery: 'Сдача', rowTotalUnits: 'Всего резиденций', rowAvailableUnits: 'Доступно резиденций', rowArea: 'Район', rowAmenities: 'Инфраструктура',
    statusMap: { off_plan: 'На этапе строительства', under_construction: 'Строится', completed: 'Завершено' },
    typeMap: { apartment: 'Апартаменты', penthouse: 'Пентхаус', villa: 'Вилла', townhouse: 'Таунхаус', duplex: 'Дуплекс' },
    note: 'Цены, наличие и сроки сдачи являются ориентировочными и подтверждаются Nueva Living перед любым бронированием.',
    emptyNotSaved: 'Вы ещё не сохранили ни одной новостройки. Сохраните проект на его странице или карточке, чтобы сравнить его здесь.',
    emptyNotFound: 'Мы не нашли сохранённые вами проекты. Возможно, они были обновлены — попробуйте выбрать заново.',
    emptyError: 'Данные для сравнения сейчас недоступны. Пожалуйста, попробуйте чуть позже.'
  },
  ar: {
    onRequest: 'عند الطلب', priceFrom: 'ابتداءً من {price}', bedroomsRange: '{min}-{max} غرف نوم', bedroomsOne: '{n} غرف نوم', toBeConfirmed: 'قيد التأكيد', dateLocale: 'ar',
    browse: 'تصفح المشاريع', rowPrice: 'السعر', rowBedrooms: 'غرف النوم', rowPropertyTypes: 'أنواع العقارات', rowStatus: 'الحالة', rowDelivery: 'التسليم', rowTotalUnits: 'إجمالي الوحدات', rowAvailableUnits: 'الوحدات المتاحة', rowArea: 'المنطقة', rowAmenities: 'المرافق',
    statusMap: { off_plan: 'على المخطط', under_construction: 'قيد الإنشاء', completed: 'مكتمل' },
    typeMap: { apartment: 'شقة', penthouse: 'بنتهاوس', villa: 'فيلا', townhouse: 'تاون هاوس', duplex: 'دوبلكس' },
    note: 'الأسعار والتوافر ومواعيد التسليم إرشادية وتعيد Nueva Living تأكيدها قبل أي حجز.',
    emptyNotSaved: 'لم تحفظ أي مشاريع بعد. احفظ مشروعًا من صفحته أو بطاقته لمقارنته هنا.',
    emptyNotFound: 'لم نتمكن من العثور على مشاريعك المحفوظة. ربما تم تحديثها — جرّب التصفح من جديد.',
    emptyError: 'بيانات المقارنة غير متاحة حاليًا. يرجى المحاولة مرة أخرى قريبًا.'
  },
  nl: {
    onRequest: 'Op aanvraag', priceFrom: 'Vanaf {price}', bedroomsRange: '{min}-{max} slaapkamers', bedroomsOne: '{n} slaapkamers', toBeConfirmed: 'Nog te bevestigen', dateLocale: 'nl-NL',
    browse: 'Bekijk Nieuwbouwprojecten', rowPrice: 'Prijs', rowBedrooms: 'Slaapkamers', rowPropertyTypes: 'Woningtypes', rowStatus: 'Status', rowDelivery: 'Oplevering', rowTotalUnits: 'Totaal aantal woningen', rowAvailableUnits: 'Beschikbare woningen', rowArea: 'Gebied', rowAmenities: 'Voorzieningen',
    statusMap: { off_plan: 'In voorverkoop', under_construction: 'In aanbouw', completed: 'Opgeleverd' },
    typeMap: { apartment: 'Appartement', penthouse: 'Penthouse', villa: 'Villa', townhouse: 'Rijwoning', duplex: 'Duplex' },
    note: 'Prijzen, beschikbaarheid en opleverdata zijn indicatief en worden door Nueva Living bevestigd vóór elke reservering.',
    emptyNotSaved: 'U heeft nog geen project opgeslagen. Sla een project op via de pagina of kaart ervan om het hier te vergelijken.',
    emptyNotFound: 'We konden uw opgeslagen projecten niet vinden. Mogelijk zijn ze bijgewerkt; probeer opnieuw te bladeren.',
    emptyError: 'De vergelijkingsgegevens zijn op dit moment niet beschikbaar. Probeer het straks opnieuw.'
  },
  pl: {
    onRequest: 'Na zapytanie', priceFrom: 'Od {price}', bedroomsRange: '{min}-{max} sypialnie', bedroomsOne: '{n} sypialnie', toBeConfirmed: 'Do potwierdzenia', dateLocale: 'pl-PL',
    browse: 'Zobacz Inwestycje', rowPrice: 'Cena', rowBedrooms: 'Sypialnie', rowPropertyTypes: 'Rodzaje nieruchomości', rowStatus: 'Status', rowDelivery: 'Termin oddania', rowTotalUnits: 'Łączna liczba lokali', rowAvailableUnits: 'Dostępne lokale', rowArea: 'Lokalizacja', rowAmenities: 'Udogodnienia',
    statusMap: { off_plan: 'W przedsprzedaży', under_construction: 'W budowie', completed: 'Ukończone' },
    typeMap: { apartment: 'Apartament', penthouse: 'Penthouse', villa: 'Willa', townhouse: 'Dom szeregowy', duplex: 'Duplex' },
    note: 'Ceny, dostępność i terminy oddania mają charakter orientacyjny i są potwierdzane przez Nueva Living przed dokonaniem rezerwacji.',
    emptyNotSaved: 'Nie zapisałeś/aś jeszcze żadnej inwestycji. Zapisz projekt na jego stronie lub karcie, aby porównać go tutaj.',
    emptyNotFound: 'Nie udało się odnaleźć Twoich zapisanych inwestycji. Mogły zostać zaktualizowane — spróbuj przejrzeć je ponownie.',
    emptyError: 'Dane porównawcze są obecnie niedostępne. Spróbuj ponownie za chwilę.'
  },
  sv: {
    onRequest: 'På förfrågan', priceFrom: 'Från {price}', bedroomsRange: '{min}-{max} sovrum', bedroomsOne: '{n} sovrum', toBeConfirmed: 'Bekräftas senare', dateLocale: 'sv-SE',
    browse: 'Se Projekt', rowPrice: 'Pris', rowBedrooms: 'Sovrum', rowPropertyTypes: 'Bostadstyper', rowStatus: 'Status', rowDelivery: 'Tillträde', rowTotalUnits: 'Antal bostäder totalt', rowAvailableUnits: 'Tillgängliga bostäder', rowArea: 'Område', rowAmenities: 'Bekvämligheter',
    statusMap: { off_plan: 'Förhandsbokning', under_construction: 'Under uppförande', completed: 'Färdigställt' },
    typeMap: { apartment: 'Lägenhet', penthouse: 'Takvåning', villa: 'Villa', townhouse: 'Radhus', duplex: 'Duplex' },
    note: 'Priser, tillgänglighet och tillträdesdatum är vägledande och bekräftas av Nueva Living innan bokning.',
    emptyNotSaved: 'Du har inte sparat något projekt än. Spara ett projekt från dess sida eller kort för att jämföra det här.',
    emptyNotFound: 'Vi kunde inte hitta dina sparade projekt. De kan ha uppdaterats — försök bläddra igen.',
    emptyError: 'Jämförelsedata är inte tillgängliga just nu. Försök igen inom kort.'
  },
  no: {
    onRequest: 'På forespørsel', priceFrom: 'Fra {price}', bedroomsRange: '{min}-{max} soverom', bedroomsOne: '{n} soverom', toBeConfirmed: 'Bekreftes senere', dateLocale: 'nb-NO',
    browse: 'Se Boligprosjekter', rowPrice: 'Pris', rowBedrooms: 'Soverom', rowPropertyTypes: 'Boligtyper', rowStatus: 'Status', rowDelivery: 'Overlevering', rowTotalUnits: 'Totalt antall boliger', rowAvailableUnits: 'Tilgjengelige boliger', rowArea: 'Område', rowAmenities: 'Fasiliteter',
    statusMap: { off_plan: 'Under planlegging', under_construction: 'Under bygging', completed: 'Ferdigstilt' },
    typeMap: { apartment: 'Leilighet', penthouse: 'Takleilighet', villa: 'Villa', townhouse: 'Rekkehus', duplex: 'Duplex' },
    note: 'Priser, tilgjengelighet og overleveringsdatoer er veiledende og bekreftes av Nueva Living før eventuell reservasjon.',
    emptyNotSaved: 'Du har ikke lagret noen prosjekter ennå. Lagre et prosjekt fra siden eller kortet for å sammenligne det her.',
    emptyNotFound: 'Vi fant ikke de lagrede prosjektene dine. De kan ha blitt oppdatert — prøv å bla på nytt.',
    emptyError: 'Sammenligningsdataene er ikke tilgjengelige akkurat nå. Prøv igjen om litt.'
  }
};
