// Availability-table `unit.floor` values. These are a small, closed set of
// data strings (~30 distinct values across all 13 projects), so they are
// translated by exact match rather than parsed. Anything not listed here
// passes through unchanged -- including values already authored in Spanish
// in the source data ("Bloque 3"), which are left exactly as the developer
// supplied them.
export const UNIT_FLOORS = {
  '4th Floor': { es: '4.ª planta', fr: '4e étage', de: '4. Obergeschoss', ru: '5-й этаж', ar: 'الطابق الرابع', nl: '4e verdieping', pl: '4. piętro', sv: '4:e våningen', no: '5. etasje' },
  'Basement, Ground & First Floor': { es: 'Sótano, planta baja y primera planta', fr: 'Sous-sol, rez-de-chaussée et premier étage', de: 'Untergeschoss, Erdgeschoss und erstes Obergeschoss', ru: 'Цокольный, первый и второй этажи', ar: 'الطابق السفلي والأرضي والأول', nl: 'Kelder, begane grond en eerste verdieping', pl: 'Piwnica, parter i pierwsze piętro', sv: 'Källare, bottenvåning och första våningen', no: 'Kjeller, første og andre etasje' },
  'Block 1 (Palm Tree)': { es: 'Bloque 1 (Palmera)', fr: 'Bloc 1 (Palmier)', de: 'Block 1 (Palme)', ru: 'Корпус 1 (Пальма)', ar: 'المبنى 1 (النخلة)', nl: 'Blok 1 (Palmboom)', pl: 'Blok 1 (Palma)', sv: 'Hus 1 (Palm)', no: 'Blokk 1 (Palme)' },
  'Block 2 (Olive Tree)': { es: 'Bloque 2 (Olivo)', fr: 'Bloc 2 (Olivier)', de: 'Block 2 (Olivenbaum)', ru: 'Корпус 2 (Олива)', ar: 'المبنى 2 (شجرة الزيتون)', nl: 'Blok 2 (Olijfboom)', pl: 'Blok 2 (Oliwka)', sv: 'Hus 2 (Olivträd)', no: 'Blokk 2 (Oliventre)' },
  'Block 1, Ground Floor': { es: 'Bloque 1, planta baja', fr: 'Bloc 1, rez-de-chaussée', de: 'Block 1, Erdgeschoss', ru: 'Корпус 1, первый этаж', ar: 'المبنى 1، الطابق الأرضي', nl: 'Blok 1, begane grond', pl: 'Blok 1, parter', sv: 'Hus 1, bottenvåning', no: 'Blokk 1, første etasje' },
  'Block 2, Ground Floor': { es: 'Bloque 2, planta baja', fr: 'Bloc 2, rez-de-chaussée', de: 'Block 2, Erdgeschoss', ru: 'Корпус 2, первый этаж', ar: 'المبنى 2، الطابق الأرضي', nl: 'Blok 2, begane grond', pl: 'Blok 2, parter', sv: 'Hus 2, bottenvåning', no: 'Blokk 2, første etasje' },
  'Block 5, Ground Floor': { es: 'Bloque 5, planta baja', fr: 'Bloc 5, rez-de-chaussée', de: 'Block 5, Erdgeschoss', ru: 'Корпус 5, первый этаж', ar: 'المبنى 5، الطابق الأرضي', nl: 'Blok 5, begane grond', pl: 'Blok 5, parter', sv: 'Hus 5, bottenvåning', no: 'Blokk 5, første etasje' },
  'Block 6, Ground Floor': { es: 'Bloque 6, planta baja', fr: 'Bloc 6, rez-de-chaussée', de: 'Block 6, Erdgeschoss', ru: 'Корпус 6, первый этаж', ar: 'المبنى 6، الطابق الأرضي', nl: 'Blok 6, begane grond', pl: 'Blok 6, parter', sv: 'Hus 6, bottenvåning', no: 'Blokk 6, første etasje' },
  'Block 2, First Floor': { es: 'Bloque 2, primera planta', fr: 'Bloc 2, premier étage', de: 'Block 2, erstes Obergeschoss', ru: 'Корпус 2, второй этаж', ar: 'المبنى 2، الطابق الأول', nl: 'Blok 2, eerste verdieping', pl: 'Blok 2, pierwsze piętro', sv: 'Hus 2, första våningen', no: 'Blokk 2, andre etasje' },
  'Block 5, First Floor': { es: 'Bloque 5, primera planta', fr: 'Bloc 5, premier étage', de: 'Block 5, erstes Obergeschoss', ru: 'Корпус 5, второй этаж', ar: 'المبنى 5، الطابق الأول', nl: 'Blok 5, eerste verdieping', pl: 'Blok 5, pierwsze piętro', sv: 'Hus 5, första våningen', no: 'Blokk 5, andre etasje' },
  'Block 6, First Floor': { es: 'Bloque 6, primera planta', fr: 'Bloc 6, premier étage', de: 'Block 6, erstes Obergeschoss', ru: 'Корпус 6, второй этаж', ar: 'المبنى 6، الطابق الأول', nl: 'Blok 6, eerste verdieping', pl: 'Blok 6, pierwsze piętro', sv: 'Hus 6, första våningen', no: 'Blokk 6, andre etasje' },
  'Block 1, First Floor Duplex': { es: 'Bloque 1, dúplex en primera planta', fr: 'Bloc 1, duplex au premier étage', de: 'Block 1, Duplex im ersten Obergeschoss', ru: 'Корпус 1, дуплекс на втором этаже', ar: 'المبنى 1، دوبلكس في الطابق الأول', nl: 'Blok 1, duplex op eerste verdieping', pl: 'Blok 1, duplex na pierwszym piętrze', sv: 'Hus 1, duplex på första våningen', no: 'Blokk 1, duplex i andre etasje' },
  'Block 1, Penthouse Duplex': { es: 'Bloque 1, ático dúplex', fr: 'Bloc 1, penthouse duplex', de: 'Block 1, Duplex-Penthouse', ru: 'Корпус 1, двухуровневый пентхаус', ar: 'المبنى 1، بنتهاوس دوبلكس', nl: 'Blok 1, duplex penthouse', pl: 'Blok 1, penthouse duplex', sv: 'Hus 1, duplex-takvåning', no: 'Blokk 1, duplex-toppleilighet' },
  'Block 3, Penthouse Duplex': { es: 'Bloque 3, ático dúplex', fr: 'Bloc 3, penthouse duplex', de: 'Block 3, Duplex-Penthouse', ru: 'Корпус 3, двухуровневый пентхаус', ar: 'المبنى 3، بنتهاوس دوبلكس', nl: 'Blok 3, duplex penthouse', pl: 'Blok 3, penthouse duplex', sv: 'Hus 3, duplex-takvåning', no: 'Blokk 3, duplex-toppleilighet' },
  'Block 5, Penthouse Duplex': { es: 'Bloque 5, ático dúplex', fr: 'Bloc 5, penthouse duplex', de: 'Block 5, Duplex-Penthouse', ru: 'Корпус 5, двухуровневый пентхаус', ar: 'المبنى 5، بنتهاوس دوبلكس', nl: 'Blok 5, duplex penthouse', pl: 'Blok 5, penthouse duplex', sv: 'Hus 5, duplex-takvåning', no: 'Blokk 5, duplex-toppleilighet' },
  'Block 6, Penthouse Duplex': { es: 'Bloque 6, ático dúplex', fr: 'Bloc 6, penthouse duplex', de: 'Block 6, Duplex-Penthouse', ru: 'Корпус 6, двухуровневый пентхаус', ar: 'المبنى 6، بنتهاوس دوبلكس', nl: 'Blok 6, duplex penthouse', pl: 'Blok 6, penthouse duplex', sv: 'Hus 6, duplex-takvåning', no: 'Blokk 6, duplex-toppleilighet' },
  'Skyline Duplex Penthouse': { es: 'Ático dúplex Skyline', fr: 'Penthouse duplex Skyline', de: 'Skyline-Duplex-Penthouse', ru: 'Двухуровневый пентхаус Skyline', ar: 'بنتهاوس دوبلكس Skyline', nl: 'Skyline duplex penthouse', pl: 'Penthouse duplex Skyline', sv: 'Skyline duplex-takvåning', no: 'Skyline duplex-toppleilighet' },
  'Garden-Level Duplex': { es: 'Dúplex a nivel de jardín', fr: 'Duplex de plain-pied sur jardin', de: 'Duplex auf Gartenebene', ru: 'Дуплекс на садовом уровне', ar: 'دوبلكس بمستوى الحديقة', nl: 'Duplex op tuinniveau', pl: 'Duplex na poziomie ogrodu', sv: 'Duplex i trädgårdsnivå', no: 'Duplex på hagenivå' }
};
